import { useMemo } from "react";
import type { SavedMapAsset } from "../types";
import { hasCanonicalHomeServiceException } from "../../Project/workspace/canonicalHomeStatus";

type AreaLevel = "L0" | "L1" | "L2" | "L3";

type UseLayerCountsArgs = {
  visibleProjectAreas: SavedMapAsset[];
  visibleProjectAssets: SavedMapAsset[];
  visibleOpenreachAssets: SavedMapAsset[];
};

function normaliseAreaLevel(value: unknown): AreaLevel {
  const level = String(value || "L0").toUpperCase();

  if (level === "L1" || level === "L2" || level === "L3") {
    return level;
  }

  return "L0";
}

function isProjectAreaAsset(asset: SavedMapAsset) {
  const item = asset as any;
  const assetType = String(item.assetType ?? "").toLowerCase();
  const jointType = String(item.jointType ?? "").toLowerCase();
  const geometryType = String(
    item.geometryType ?? item.geometry?.type ?? "",
  ).toLowerCase();

  return (
    geometryType === "polygon" &&
    (assetType === "area" ||
      assetType === "polygon" ||
      assetType === "project-area" ||
      jointType.includes("polygon area"))
  );
}

export function useLayerCounts({
  visibleProjectAreas,
  visibleProjectAssets,
  visibleOpenreachAssets,
}: UseLayerCountsArgs) {
  return useMemo(() => {
    const norm = (value: unknown) => String(value ?? "").toLowerCase();

    const textForAsset = (asset: SavedMapAsset) => {
      const item = asset as any;
      return [
        item.assetType,
        item.type,
        item.jointType,
        item.cableType,
        item.name,
        item.label,
        item.category,
        item.source,
        item.referenceSubtype,
        item.homeType,
        item.dpType,
        item.closureType,
      ]
        .map(norm)
        .join(" ");
    };

    const hasPointGeometry = (asset: SavedMapAsset) => {
      const item = asset as any;
      return (
        asset.geometry?.type === "Point" ||
        (typeof item.lat === "number" && typeof item.lng === "number")
      );
    };

    const hasLineGeometry = (asset: SavedMapAsset) =>
      asset.geometry?.type === "LineString";

    const isLineCable = (asset: SavedMapAsset) => {
      const text = textForAsset(asset);
      return hasLineGeometry(asset) || text.includes("cable");
    };

    const isDuct = (asset: SavedMapAsset) => {
      const item = asset as any;
      return (
        norm(item.assetType) === "duct" ||
        norm(item.jointType) === "duct"
      );
    };

    const isDrop = (asset: SavedMapAsset) => {
      const item = asset as any;
      const text = textForAsset(asset);
      return (
        isLineCable(asset) &&
        (text.includes("drop") ||
          text.includes("home drop") ||
          text.includes("home-drop") ||
          item.isDropCable === true ||
          item.isHomeDrop === true ||
          item.generatedDrop === true ||
          item.autoGeneratedDrop === true ||
          item.dropCable === true ||
          Boolean(item.homeId || item.connectedHomeId || item.toHomeId || item.fromHomeId))
      );
    };

    const isDp = (asset: SavedMapAsset) => {
      if (!hasPointGeometry(asset) || isDrop(asset)) return false;
      const text = textForAsset(asset);
      return (
        text.includes("distribution-point") ||
        text.includes("distribution point") ||
        text.includes("dp") ||
        text.includes("cbt") ||
        text.includes("afn") ||
        text.includes("mdu")
      );
    };

    const isHome = (asset: SavedMapAsset) => {
      const item = asset as any;
      if (!hasPointGeometry(asset) || isLineCable(asset) || isDrop(asset) || isDp(asset)) {
        return false;
      }

      const text = textForAsset(asset);
      return Boolean(
        item.uprn ||
          item.UPRN ||
          item.properties?.UPRN ||
          item.properties?.uprn ||
          item.homeId ||
          text.includes("home") ||
          text.includes("premise") ||
          text.includes("property") ||
          text.includes("sdu") ||
          text.includes("flat"),
      );
    };

    const isJoint = (asset: SavedMapAsset) => {
      if (!hasPointGeometry(asset) || isDp(asset)) return false;
      const text = textForAsset(asset);
      return (
        text.includes("joint") ||
        text.includes("cmj") ||
        text.includes("midj") ||
        text.includes("lmj") ||
        text.includes("mmj")
      );
    };

    const isDataCentre = (asset: SavedMapAsset) => {
      if (!hasPointGeometry(asset)) return false;
      const text = textForAsset(asset);
      return (
        norm((asset as any).assetType) === "data-centre" ||
        text.includes("data centre") ||
        text.includes("data center") ||
        text.includes("datacentre") ||
        text.includes("datacenter")
      );
    };

    const isJointSubtype = (asset: SavedMapAsset, token: string) =>
      isJoint(asset) && textForAsset(asset).includes(token);

    const isUndergroundDp = (asset: SavedMapAsset) => {
      const text = textForAsset(asset);
      const item = asset as any;
      const installText = [
        item.installMethod,
        item.routeType,
        item.dpDetails?.installMethod,
        item.dpDetails?.mounting,
        item.dpDetails?.locationType,
        item.dpDetails?.networkType,
        item.properties?.installMethod,
        item.properties?.routeType,
      ]
        .map(norm)
        .join(" ");

      return (
        installText.includes("underground") ||
        installText.includes("ug") ||
        installText.includes("duct") ||
        text.includes(" underground") ||
        text.includes(" ug ") ||
        text.includes("-ug") ||
        text.includes("ug-")
      );
    };

    const isOverheadDp = (asset: SavedMapAsset) => {
      if (!isDp(asset)) return false;
      const text = textForAsset(asset);
      const item = asset as any;
      const installText = [
        item.installMethod,
        item.routeType,
        item.dpDetails?.installMethod,
        item.dpDetails?.mounting,
        item.dpDetails?.locationType,
        item.properties?.installMethod,
        item.properties?.routeType,
      ]
        .map(norm)
        .join(" ");

      if (isUndergroundDp(asset)) return false;
      if (installText.includes("oh") || installText.includes("overhead") || text.includes(" overhead")) return true;
      return true;
    };

    const isPole = (asset: SavedMapAsset) =>
      hasPointGeometry(asset) && textForAsset(asset).includes("pole");

    const isChamber = (asset: SavedMapAsset) => {
      const text = textForAsset(asset);
      return hasPointGeometry(asset) && (text.includes("chamber") || text.includes("manhole"));
    };

    const isStreetCab = (asset: SavedMapAsset) => {
      const text = textForAsset(asset);
      return text.includes("street cab") || text.includes("streetcab") || text.includes("cabinet");
    };

    const homeKey = (asset: SavedMapAsset) => {
      const item = asset as any;
      const raw =
        item.uprn ||
        item.UPRN ||
        item.properties?.UPRN ||
        item.properties?.uprn ||
        item.homeId ||
        item.address ||
        item.label ||
        item.name ||
        item.id;

      if (raw) return String(raw).trim().toLowerCase();

      if (asset.geometry?.type === "Point") {
        const [lat, lng] = asset.geometry.coordinates as [number, number];
        return `${Number(lat).toFixed(7)},${Number(lng).toFixed(7)}`;
      }

      return "";
    };

    const isDropLinkedToHome = (drop: SavedMapAsset, home: SavedMapAsset) => {
      if (!isDrop(drop)) return false;
      const dropItem = drop as any;
      const homeItem = home as any;
      const homeKeys = [
        home.id,
        homeItem.uprn,
        homeItem.UPRN,
        homeItem.properties?.UPRN,
        homeItem.properties?.uprn,
        homeItem.homeId,
      ]
        .map((value) => String(value || "").trim())
        .filter(Boolean);

      const dropKeys = [
        dropItem.fromAssetId,
        dropItem.toAssetId,
        dropItem.homeId,
        dropItem.connectedHomeId,
        dropItem.toHomeId,
        dropItem.fromHomeId,
        dropItem.uprn,
        dropItem.UPRN,
      ].map((value) => String(value || "").trim());

      return homeKeys.some((key) => dropKeys.includes(key));
    };

    const getHomeStatusForLayer = (home: SavedMapAsset): "unconnected" | "connected" | "live" => {
      const item = home as any;
      const status = String(
        item.customerStatus ||
          item.homeStatus ||
          item.status ||
          item.buildStatus ||
          item.serviceStatus ||
          item.connectionStatus ||
          item.properties?.status ||
          "",
      )
        .trim()
        .toLowerCase()
        .replace(/\s+/g, "_")
        .replace(/-/g, "_");

      if (status === "live") return "live";

      const metadataConnection = String(item.connection || item.properties?.connection || "").toLowerCase();
      if (item.connectedDpId || item.properties?.connectedDpId || item.connectedDP || item.dpId || metadataConnection === "connected") {
        return "connected";
      }

      const drop = visibleProjectAssets.find((asset) => isDropLinkedToHome(asset, home));
      if (!drop) return "unconnected";

      const dropStatus = String((drop as any).customerStatus || (drop as any).homeStatus || (drop as any).status || "")
        .trim()
        .toLowerCase()
        .replace(/\s+/g, "_")
        .replace(/-/g, "_");

      return dropStatus === "live" ? "live" : "connected";
    };

    const homesByKey = new Map<string, SavedMapAsset>();
    visibleProjectAssets.filter(isHome).forEach((asset) => {
      const key = homeKey(asset);
      if (key && !homesByKey.has(key)) homesByKey.set(key, asset);
    });

    const canonicalHomes = Array.from(homesByKey.values());
    const connectedHomes = canonicalHomes.filter((home) => getHomeStatusForLayer(home) === "connected");
    const unconnectedHomes = canonicalHomes.filter((home) => getHomeStatusForLayer(home) === "unconnected");
    const liveHomes = canonicalHomes.filter((home) => getHomeStatusForLayer(home) === "live");
    const notLiveHomes = canonicalHomes.filter((home) => {
      const status = getHomeStatusForLayer(home);
      return status === "unconnected" || hasCanonicalHomeServiceException(home);
    });

    const designDucts = visibleProjectAssets.filter(isDuct);
    const designCables = visibleProjectAssets.filter((asset) => isLineCable(asset) && !isDuct(asset) && !isDrop(asset));
    const dropCables = visibleProjectAssets.filter(isDrop);
    const projectAreaAssets = visibleProjectAreas.filter(isProjectAreaAsset);
    const openreachDucts = visibleOpenreachAssets.filter((asset) => asset.geometry?.type === "LineString");
    const openreachPoles = visibleOpenreachAssets.filter((asset) => textForAsset(asset).includes("pole"));
    const openreachChambers = visibleOpenreachAssets.filter((asset) => {
      const text = textForAsset(asset);
      return text.includes("chamber") || text.includes("manhole") || text.includes("joint chamber");
    });
    const suggestedPoles = visibleOpenreachAssets.filter((asset) => {
      const text = textForAsset(asset);
      return text.includes("suggested") && text.includes("pole");
    });
    const suggestedChambers = visibleOpenreachAssets.filter((asset) => {
      const text = textForAsset(asset);
      return text.includes("suggested") && (text.includes("chamber") || text.includes("manhole"));
    });
    const suggestedDucts = visibleOpenreachAssets.filter((asset) => {
      const text = textForAsset(asset);
      return asset.geometry?.type === "LineString" && text.includes("suggested");
    });

    return {
      areas: projectAreaAssets.length,
      l0: projectAreaAssets.filter((asset) => normaliseAreaLevel((asset as any).areaLevel) === "L0").length,
      l1: projectAreaAssets.filter((asset) => normaliseAreaLevel((asset as any).areaLevel) === "L1").length,
      l2: projectAreaAssets.filter((asset) => normaliseAreaLevel((asset as any).areaLevel) === "L2").length,
      l3: projectAreaAssets.filter((asset) => normaliseAreaLevel((asset as any).areaLevel) === "L3").length,
      agJoints: visibleProjectAssets.filter(isJoint).length,
      cmjJoints: visibleProjectAssets.filter((asset) => isJointSubtype(asset, "cmj")).length,
      midjJoints: visibleProjectAssets.filter((asset) => isJointSubtype(asset, "midj")).length,
      mmjJoints: visibleProjectAssets.filter((asset) => isJointSubtype(asset, "mmj")).length,
      lmjJoints: visibleProjectAssets.filter((asset) => isJointSubtype(asset, "lmj")).length,
      streetCabs: visibleProjectAssets.filter(isStreetCab).length,
      dataCentres: visibleProjectAssets.filter(isDataCentre).length,
      poles: visibleProjectAssets.filter(isPole).length,
      newPoles: visibleProjectAssets.filter((asset) => {
        const text = textForAsset(asset);
        return isPole(asset) && (text.includes("new pole") || text.includes("np ") || text.includes("np:") || text.includes("np-"));
      }).length,
      orPoles: openreachPoles.length,
      suggestedPoles: suggestedPoles.length,
      chambers: visibleProjectAssets.filter(isChamber).length,
      orChambers: openreachChambers.length,
      suggestedChambers: suggestedChambers.length,
      homes: homesByKey.size,
      homesConnected: connectedHomes.length,
      homesUnconnected: unconnectedHomes.length,
      homesLive: liveHomes.length,
      homesNotLive: notLiveHomes.length,
      ducts: designDucts.length,
      cables: designCables.length,
      feeders: designCables.filter((asset) => textForAsset(asset).includes("feeder")).length,
      links: designCables.filter((asset) => textForAsset(asset).includes("link")).length,
      dropCables: dropCables.length,
      ulw96: designCables.filter((asset) => textForAsset(asset).includes("96")).length,
      ulw48: designCables.filter((asset) => textForAsset(asset).includes("48")).length,
      ulw36: designCables.filter((asset) => textForAsset(asset).includes("36")).length,
      ulw24: designCables.filter((asset) => textForAsset(asset).includes("24")).length,
      ulw12: designCables.filter((asset) => textForAsset(asset).includes("12")).length,
      orDucts: openreachDucts.length,
      suggestedDucts: suggestedDucts.length,
      distributionPoints: visibleProjectAssets.filter(isDp).length,
      ohDpJoints: visibleProjectAssets.filter((asset) => isDp(asset) && isOverheadDp(asset)).length,
      ugDpJoints: visibleProjectAssets.filter((asset) => isDp(asset) && isUndergroundDp(asset)).length,
    };
  }, [visibleProjectAreas, visibleProjectAssets, visibleOpenreachAssets]);
}
