import React, { useEffect, useMemo, useState } from "react";
import WorkspaceMap, { type WorkspaceLayerVisibility } from "./WorkspaceMap";
import type { OpenreachLayerVisibility } from "../map/OpenreachOverlayLayer";
import AssetIntelligencePanel from "./AssetIntelligencePanel";
import WorkspaceTabContent from "./workspace/WorkspaceTabContent";
import type { SavedMapAsset } from "../map/types";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../../firebase";
import { auditAreaAssets, type AuditIssue } from "../../services/areaAudit";
import {
  buildNetworkGraph,
  findDisconnectedAssets,
} from "../../services/networkGraph";

// =====================================================
// FILE: ProjectWorkspace.tsx
// PURPOSE: Dedicated project workspace shell for Alistra GIS.
//          This is the first UI migration away from one overloaded
//          map sidebar into a project-specific operations screen.
// PHASE 7 UI: Cleaner operational workspace layout, wider map,
//             compact header, cleaner KPI flow. No storage/topology
//             or cable logic changed in this file.
// =====================================================

type WorkspaceOperationPanel =
  | "none"
  | "projectDetails"
  | "rfsBreakdown"
  | "issues"
  | "topology"
  | "qa"
  | "trace"
  | "addAsset"
  | "report";

type WorkspaceTab =
  | "overview"
  | "topology"
  | "qa"
  | "build"
  | "maintenance"
  | "assets"
  | "fibre"
  | "reports"
  | "settings";

type ProjectWorkspaceStats = {
  homesPassed: number;
  homesConnected: number;
  rfsPercent: number;
  issueCount: number;
  topologyLinks: number;
  splicePoints: number;
  areaM2?: number;
  joints: number;
  dps: number;
  streetCabs: number;
  poles: number;
  chambers: number;
  cables: number;
  dropCables?: number;
  designCables?: number;
  routeLengthMeters: number;
  unmatchedCableIds?: number;
  fibreTrayRows?: number;
  mappedJoints?: number;
};

type ProjectWorkspaceProps = {
  projectName: string;
  status?: string;
  stats: ProjectWorkspaceStats;
  onBackToMap: () => void;
  onOpenTrace?: () => void;
  onOpenQA?: () => void;
  onOpenFibreTopology?: () => void;
  onOpenJointEditor?: (asset: SavedMapAsset) => void;
  onExport?: () => void;
  projectArea?: SavedMapAsset | null;
  projectAssets?: SavedMapAsset[];
  projectAreas?: SavedMapAsset[];
  activeProjectId?: string | null;
  onSelectProject?: (projectId: string) => void;
};

const tabs: { id: WorkspaceTab; label: string }[] = [
  { id: "overview", label: "Overview" },
  { id: "topology", label: "Topology" },
  { id: "qa", label: "QA" },
  { id: "build", label: "Build" },
  { id: "maintenance", label: "Maintenance" },
  { id: "assets", label: "Assets" },
  { id: "fibre", label: "Fibre" },
  { id: "reports", label: "Reports" },
];

const defaultWorkspaceLayers: WorkspaceLayerVisibility = {
  projectBoundary: true,
  areas: true,
  cables: true,
  dropCables: true,
  joints: true,
  dps: true,
  poles: true,
  chambers: true,
  streetCabs: true,
  homes: true,
  other: true,
};

const workspaceLayerOptions: {
  key: keyof WorkspaceLayerVisibility;
  label: string;
}[] = [
  { key: "projectBoundary", label: "Project Boundary" },
  { key: "areas", label: "Areas" },
  { key: "cables", label: "Cables" },
  { key: "dropCables", label: "Home Drop Cables" },
  { key: "joints", label: "Joints" },
  { key: "dps", label: "DPs / CBTs / AFNs" },
  { key: "poles", label: "Poles" },
  { key: "chambers", label: "Chambers" },
  { key: "streetCabs", label: "Street Cabs" },
  { key: "homes", label: "Homes" },
  { key: "other", label: "Other Assets" },
];

const defaultOpenreachLayers: OpenreachLayerVisibility = {
  ducts: true,
  trenches: true,
  spans: true,
  chambers: true,
  poles: true,
  labels: false,
};

const openreachLayerOptions: {
  key: keyof OpenreachLayerVisibility;
  label: string;
}[] = [
  { key: "ducts", label: "OR Ducts / Routes" },
  { key: "trenches", label: "OR Trenches" },
  { key: "spans", label: "OR Overhead Spans" },
  { key: "chambers", label: "OR Chambers" },
  { key: "poles", label: "OR Poles" },
  { key: "labels", label: "OR Route Labels" },
];

function isHomeDropCableAsset(
  asset: SavedMapAsset | null | undefined,
): boolean {
  if (!asset) return false;
  const item = asset as any;

  const text = [
    item.assetType,
    item.type,
    item.cableType,
    item.name,
    item.label,
    item.category,
    item.kind,
    item.installType,
    item.source,
    item.generatedBy,
  ]
    .map((value) => String(value ?? "").toLowerCase())
    .join(" ");

  return (
    text.includes("drop") ||
    text.includes("home-drop") ||
    text.includes("home drop") ||
    text.includes("drop-cable") ||
    text.includes("drop cable") ||
    item.isDropCable === true ||
    item.isHomeDrop === true ||
    item.generatedDrop === true ||
    item.autoGeneratedDrop === true ||
    item.dropCable === true ||
    Boolean(item.homeId || item.uprn || item.connectedHomeId)
  );
}

function isDesignCableAsset(asset: SavedMapAsset | null | undefined): boolean {
  if (!asset) return false;
  const item = asset as any;
  const type = String(item.assetType || item.type || "").toLowerCase();
  const hasLineGeometry = asset.geometry?.type === "LineString";
  const looksLikeCable = hasLineGeometry || type.includes("cable");
  return looksLikeCable && !isHomeDropCableAsset(asset);
}

function isWorkspaceDistributionPointAsset(
  asset: SavedMapAsset | null | undefined,
): boolean {
  if (!asset || isHomeDropCableAsset(asset)) return false;
  const item = asset as any;
  const typeText = [
    item.assetType,
    item.type,
    item.jointType,
    item.dpType,
    item.distributionPointType,
    item.closureType,
    item.name,
  ]
    .map((value) => String(value ?? "").toLowerCase())
    .join(" ");

  const hasPointGeometry =
    asset.geometry?.type === "Point" ||
    (typeof item.lat === "number" && typeof item.lng === "number");

  if (!hasPointGeometry) return false;

  return (
    typeText.includes("distribution-point") ||
    typeText.includes("distribution point") ||
    typeText.includes("dp") ||
    typeText.includes("cbt") ||
    typeText.includes("afn")
  );
}

function getProjectAreaLabel(area: SavedMapAsset | null | undefined): string {
  const item = area as any;
  return String(item?.name || item?.label || item?.projectName || item?.id || "Selected project");
}

function assetMatchKey(value: unknown): string {
  return String(value ?? "")
    .trim()
    .toLowerCase();
}

function getAssetIdentityKeys(
  asset: SavedMapAsset | null | undefined,
): string[] {
  if (!asset) return [];
  const item = asset as any;
  return [
    item.id,
    item.assetId,
    item.name,
    item.jointName,
    item.label,
    item.cableId,
    item.cableName,
  ]
    .map(assetMatchKey)
    .filter(Boolean);
}

function resolveFullProjectAsset(
  selectedAsset: SavedMapAsset | null,
  projectAssets: SavedMapAsset[],
): SavedMapAsset | null {
  if (!selectedAsset) return null;

  const selectedKeys = new Set(getAssetIdentityKeys(selectedAsset));

  const exactMatch = projectAssets.find((candidate) =>
    getAssetIdentityKeys(candidate).some((key) => selectedKeys.has(key)),
  );

  if (!exactMatch) return selectedAsset;

  return {
    ...selectedAsset,
    ...exactMatch,
    geometry: exactMatch.geometry || selectedAsset.geometry,
  } as SavedMapAsset;
}

function getWorkspaceAssetTitle(
  asset: SavedMapAsset | null | undefined,
): string {
  const item = (asset || {}) as any;
  return String(
    item.name ||
      item.jointName ||
      item.label ||
      item.cableId ||
      item.assetId ||
      item.id ||
      "Unnamed asset",
  );
}

function getWorkspaceAssetType(
  asset: SavedMapAsset | null | undefined,
): string {
  const item = (asset || {}) as any;
  return String(
    item.assetType || item.type || item.jointType || item.cableType || "Asset",
  );
}

function assetSearchText(asset: SavedMapAsset): string {
  const item = asset as any;
  return [
    item.id,
    item.assetId,
    item.name,
    item.jointName,
    item.label,
    item.cableId,
    item.cableName,
    item.assetType,
    item.type,
    item.jointType,
    item.cableType,
    item.address,
    item.uprn,
    item.status,
  ]
    .map((value) => String(value ?? "").toLowerCase())
    .join(" ");
}


type MappingRowsByAssetId = Record<string, any[][]>;

type MappingChunkDoc = {
  rowsJson?: string;
  rows?: any[];
  chunkIndex?: number;
};

function safeParseRowsJson(value: unknown): any[] {
  if (typeof value !== "string") return [];
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

async function loadWorkspaceJointMappingRows(jointId: string): Promise<any[][]> {
  const chunksRef = collection(
    db,
    "businesses",
    "fibre-gis-v2",
    "jointMappings",
    jointId,
    "chunks",
  );

  const snapshot = await getDocs(chunksRef);

  return snapshot.docs
    .map((chunkDoc) => {
      const data = chunkDoc.data() as MappingChunkDoc;
      let rows: any[] = [];

      if (typeof data.rowsJson === "string") {
        rows = safeParseRowsJson(data.rowsJson);
      }

      if (!rows.length && Array.isArray(data.rows)) {
        rows = data.rows.map((row: any) =>
          Array.isArray(row) ? row : Array.isArray(row?.values) ? row.values : row,
        );
      }

      return {
        id: chunkDoc.id,
        index:
          typeof data.chunkIndex === "number"
            ? data.chunkIndex
            : Number(String(chunkDoc.id).replace("chunk_", "")),
        rows: Array.isArray(rows) ? rows : [],
      };
    })
    .sort((a, b) => a.index - b.index || a.id.localeCompare(b.id))
    .flatMap((chunk) => chunk.rows)
    .filter((row) => Array.isArray(row));
}

function normaliseCableReference(value: unknown): string {
  return String(value ?? "")
    .trim()
    .toLowerCase()
    .replace(/[\s_/-]+/g, "");
}

function rowText(row: any[]): string {
  return row.map((value) => String(value ?? "")).join(" ");
}

function fibreNumberFromRow(row: any[], fallbackIndex: number): string {
  const direct = row?.[1];
  const parsed = Number(direct);
  if (Number.isFinite(parsed) && parsed > 0) return String(parsed);
  return `row-${fallbackIndex}`;
}

function cableAliases(asset: SavedMapAsset): string[] {
  const item = asset as any;
  const rawValues = [item.name, item.cableId, item.cableName, item.id]
    .map((value) => String(value ?? "").trim())
    .filter(Boolean);

  const aliases = new Set<string>();

  rawValues.forEach((raw) => {
    const normalised = normaliseCableReference(raw);
    if (normalised.length >= 3) aliases.add(normalised);

    const shortCableMatches = raw.match(/(?:\d+f)?(?:ulw|lc|fc|link|feeder|spine|drop)\d{1,4}/gi);
    shortCableMatches?.forEach((match) => {
      const next = normaliseCableReference(match);
      if (next.length >= 3) aliases.add(next);
    });
  });

  return Array.from(aliases);
}

function calculateUsedFibresFromMappings(cable: SavedMapAsset, rowsByAssetId: MappingRowsByAssetId): number | null {
  const aliases = cableAliases(cable);
  if (!aliases.length) return null;

  const matchedFibres = new Set<string>();

  Object.entries(rowsByAssetId).forEach(([jointId, rows]) => {
    rows.forEach((row, rowIndex) => {
      const normalisedText = normaliseCableReference(rowText(row));
      if (!aliases.some((alias) => normalisedText.includes(alias))) return;
      matchedFibres.add(`${jointId}:${fibreNumberFromRow(row, rowIndex)}`);
    });
  });

  return matchedFibres.size || null;
}

function enrichProjectAssetsWithMappings(
  assets: SavedMapAsset[],
  rowsByAssetId: MappingRowsByAssetId,
): SavedMapAsset[] {
  if (!Object.keys(rowsByAssetId).length) return assets;

  const withJointRows = assets.map((asset) => {
    const rows = rowsByAssetId[asset.id];
    if (!rows?.length) return asset;

    return {
      ...(asset as any),
      mappingRows: rows,
      mappingRowsCount: rows.length,
      mappingRowsSummary: {
        ...((asset as any).mappingRowsSummary || {}),
        rowCount: rows.length,
      },
    } as SavedMapAsset;
  });

  return withJointRows.map((asset) => {
    const item = asset as any;
    const assetType = String(item.assetType || item.type || "").toLowerCase();
    const isCable = assetType.includes("cable") || asset.geometry?.type === "LineString";
    if (!isCable) return asset;

    const usedFibres = calculateUsedFibresFromMappings(asset, rowsByAssetId);
    if (usedFibres === null) return asset;

    return {
      ...item,
      usedFibres,
      fibresUsed: usedFibres,
      usedCoreCount: usedFibres,
    } as SavedMapAsset;
  });
}

function formatNumber(value: number | undefined) {
  return (value ?? 0).toLocaleString("en-GB");
}

function formatDistance(meters: number | undefined) {
  const value = meters ?? 0;
  if (value >= 1000) return `${(value / 1000).toFixed(2)} km`;
  return `${Math.round(value)} m`;
}

function StatCard({
  label,
  value,
  tone = "default",
}: {
  label: string;
  value: React.ReactNode;
  tone?: "default" | "good" | "warn" | "bad";
}) {
  const toneColour =
    tone === "good"
      ? "#4ade80"
      : tone === "warn"
        ? "#fbbf24"
        : tone === "bad"
          ? "#fb7185"
          : "#e5e7eb";
  return (
    <div style={metricCard}>
      <div style={metricLabel}>{label}</div>
      <div style={{ ...metricValue, color: toneColour }}>{value}</div>
    </div>
  );
}

export default function ProjectWorkspace({
  projectName,
  status = "Build Phase",
  stats,
  onBackToMap,
  onOpenTrace,
  onOpenQA,
  onOpenFibreTopology,
  onOpenJointEditor,
  onExport,
  projectArea = null,
  projectAssets = [],
  projectAreas = [],
  activeProjectId = null,
  onSelectProject,
}: ProjectWorkspaceProps) {
  const [openreachLayers, setOpenreachLayers] =
    React.useState<OpenreachLayerVisibility>(defaultOpenreachLayers);

  const [selectedWorkspaceAsset, setSelectedWorkspaceAsset] =
    useState<SavedMapAsset | null>(null);
  const [searchTerm, setSearchTerm] = useState("");
  const [searchFocused, setSearchFocused] = useState(false);
  const [activeTab, setActiveTab] = useState<WorkspaceTab>("overview");
  const [mappingRowsByAssetId, setMappingRowsByAssetId] =
    useState<MappingRowsByAssetId>({});

  const mappingAssetKey = useMemo(
    () =>
      projectAssets
        .filter((asset) => Boolean((asset as any).mappingRowsRef || (asset as any).mappingRowsCount))
        .map((asset) => `${asset.id}:${(asset as any).mappingRowsCount || 0}:${(asset as any).updatedAt || ""}`)
        .sort()
        .join("|"),
    [projectAssets],
  );

  useEffect(() => {
    let cancelled = false;

    const assetsWithSharedMappings = projectAssets.filter((asset) =>
      Boolean((asset as any).mappingRowsRef || (asset as any).mappingRowsCount),
    );

    if (!assetsWithSharedMappings.length) {
      setMappingRowsByAssetId({});
      return;
    }

    Promise.all(
      assetsWithSharedMappings.map(async (asset) => {
        try {
          const rows = await loadWorkspaceJointMappingRows(asset.id);
          return [asset.id, rows] as const;
        } catch (err) {
          console.error(`Failed to load workspace mapping rows for ${asset.name || asset.id}`, err);
          return [asset.id, []] as const;
        }
      }),
    ).then((entries) => {
      if (cancelled) return;
      setMappingRowsByAssetId(Object.fromEntries(entries));
    });

    return () => {
      cancelled = true;
    };
  }, [mappingAssetKey, projectAssets]);

  const workspaceAssets = useMemo(
    () => enrichProjectAssetsWithMappings(projectAssets, mappingRowsByAssetId),
    [projectAssets, mappingRowsByAssetId],
  );

  const fullSelectedWorkspaceAsset = useMemo(
    () => resolveFullProjectAsset(selectedWorkspaceAsset, workspaceAssets),
    [selectedWorkspaceAsset, workspaceAssets],
  );
  const [layerMenuOpen, setLayerMenuOpen] = useState(false);
  const [visibleLayers, setVisibleLayers] = useState<WorkspaceLayerVisibility>(
    defaultWorkspaceLayers,
  );
  const [activeOperationPanel, setActiveOperationPanel] =
    useState<WorkspaceOperationPanel>("none");

  const auditIssues = useMemo(
    () => auditAreaAssets(workspaceAssets),
    [workspaceAssets],
  );
  const networkGraph = useMemo(
    () => buildNetworkGraph(workspaceAssets),
    [workspaceAssets],
  );
  const disconnectedAssets = useMemo(
    () => findDisconnectedAssets(networkGraph),
    [networkGraph],
  );

  const searchResults = useMemo(() => {
    const query = searchTerm.trim().toLowerCase();
    if (query.length < 2) return [];

    return workspaceAssets
      .filter((asset) => assetSearchText(asset).includes(query))
      .slice(0, 12);
  }, [workspaceAssets, searchTerm]);

  const selectedTraceRows = useMemo(() => {
    if (!fullSelectedWorkspaceAsset)
      return [] as {
        id: string;
        title: string;
        type: string;
        asset: SavedMapAsset | any;
      }[];

    const selectedKeys = new Set(
      getAssetIdentityKeys(fullSelectedWorkspaceAsset),
    );
    const selectedNode = Array.from(networkGraph.nodes.values()).find((node) =>
      getAssetIdentityKeys(node.asset).some((key) => selectedKeys.has(key)),
    );
    const selectedEdge = Array.from(networkGraph.edges.values()).find((edge) =>
      getAssetIdentityKeys(edge.asset).some((key) => selectedKeys.has(key)),
    );

    const rows: {
      id: string;
      title: string;
      type: string;
      asset: SavedMapAsset | any;
    }[] = [];

    if (selectedNode) {
      selectedNode.connectedTo.forEach((edgeId) => {
        const edge = networkGraph.edges.get(edgeId);
        if (!edge) return;
        rows.push({
          id: edge.id,
          title: getWorkspaceAssetTitle(edge.asset),
          type: `Connected cable / route`,
          asset: edge.asset,
        });
      });
    }

    if (selectedEdge) {
      Array.from(networkGraph.nodes.values())
        .filter((node) => node.connectedTo.includes(selectedEdge.id))
        .forEach((node) => {
          rows.push({
            id: node.id,
            title: getWorkspaceAssetTitle(node.asset),
            type: `Connected ${getWorkspaceAssetType(node.asset)}`,
            asset: node.asset,
          });
        });
    }

    return rows;
  }, [fullSelectedWorkspaceAsset, networkGraph]);

  const designCableCount = useMemo(
    () => workspaceAssets.filter(isDesignCableAsset).length,
    [workspaceAssets],
  );

  const dropCableCount = useMemo(
    () => workspaceAssets.filter(isHomeDropCableAsset).length,
    [workspaceAssets],
  );

  const dpClosureCount = useMemo(
    () => workspaceAssets.filter(isWorkspaceDistributionPointAsset).length,
    [workspaceAssets],
  );

  const displayStats = useMemo(
    () => ({
      ...stats,
      dps: dpClosureCount,
      cables: designCableCount,
      designCables: designCableCount,
      dropCables: dropCableCount,
    }),
    [stats, dpClosureCount, designCableCount, dropCableCount],
  );

  const issueBuckets = useMemo(
    () => ({
      high: auditIssues.filter((issue) => issue.severity === "high"),
      medium: auditIssues.filter((issue) => issue.severity === "medium"),
      low: auditIssues.filter((issue) => issue.severity === "low"),
    }),
    [auditIssues],
  );

  const openOperationPanel = (
    panel: WorkspaceOperationPanel,
    tab?: WorkspaceTab,
  ) => {
    if (tab) setActiveTab(tab);
    setActiveOperationPanel(panel);
  };

  const handleSearchSelect = (asset: SavedMapAsset) => {
    setSelectedWorkspaceAsset(asset);
    setSearchTerm(getWorkspaceAssetTitle(asset));
    setSearchFocused(false);
    setActiveOperationPanel("trace");
    setActiveTab("topology");
  };

  const openInternalTraceTool = () => {
    setActiveTab("topology");
    setActiveOperationPanel("trace");
  };

  const handleGenerateReport = () => {
    const reportLines = [
      `Alistra GIS Project Report`,
      `Project: ${projectName}`,
      `Status: ${status}`,
      ``,
      `Homes passed: ${displayStats.homesPassed}`,
      `Homes connected: ${displayStats.homesConnected}`,
      `RFS progress: ${displayStats.rfsPercent}%`,
      `Route length: ${formatDistance(displayStats.routeLengthMeters)}`,
      ``,
      `Assets`,
      `Joints: ${displayStats.joints}`,
      `DPs: ${displayStats.dps}`,
      `Street cabs: ${displayStats.streetCabs}`,
      `Poles: ${displayStats.poles}`,
      `Chambers: ${displayStats.chambers}`,
      `Design cables: ${displayStats.designCables ?? displayStats.cables}`,
      `Drop cables: ${displayStats.dropCables ?? 0}`,
      ``,
      `Topology`,
      `Graph nodes: ${networkGraph.nodes.size}`,
      `Graph links: ${networkGraph.edges.size}`,
      `Disconnected assets: ${disconnectedAssets.length}`,
      `Unmatched cable IDs: ${displayStats.unmatchedCableIds ?? 0}`,
      ``,
      `QA`,
      `High issues: ${issueBuckets.high.length}`,
      `Medium issues: ${issueBuckets.medium.length}`,
      `Low issues: ${issueBuckets.low.length}`,
      `Total issues: ${auditIssues.length}`,
    ];

    const blob = new Blob([reportLines.join("\n")], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${projectName.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-project-report.txt`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
    openOperationPanel("report", "reports");
  };

  const issueTone = displayStats.issueCount > 0 ? "bad" : "good";
  const rfsTone =
    displayStats.rfsPercent >= 80
      ? "good"
      : displayStats.rfsPercent >= 50
        ? "warn"
        : "bad";

  const assetTiles = useMemo(
    () => [
      ["Joint Boxes", displayStats.joints],
      ["DPs / CBTs / AFNs", displayStats.dps],
      ["Drop Cables", displayStats.dropCables ?? 0],
      ["Design Cables", displayStats.designCables ?? displayStats.cables],
      ["Street Cabs", displayStats.streetCabs],
      ["Poles", displayStats.poles],
      ["Chambers", displayStats.chambers],
    ],
    [displayStats],
  );

  const enabledWorkspaceLayerCount = workspaceLayerOptions.filter(
    (item) => visibleLayers[item.key],
  ).length;
  const enabledOpenreachLayerCount = openreachLayerOptions.filter(
    (item) => openreachLayers[item.key],
  ).length;
  const enabledLayerCount =
    enabledWorkspaceLayerCount + enabledOpenreachLayerCount;

  const toggleLayer = (key: keyof WorkspaceLayerVisibility) => {
    setVisibleLayers((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  const toggleOpenreachLayer = (key: keyof OpenreachLayerVisibility) => {
    setOpenreachLayers((prev) => ({
      ...prev,
      [key]: !prev[key],
    }));
  };

  const showAllLayers = () => {
    setVisibleLayers(defaultWorkspaceLayers);
    setOpenreachLayers(defaultOpenreachLayers);
  };

  const hideAllLayers = () => {
    setVisibleLayers({
      ...defaultWorkspaceLayers,
      projectBoundary: true,
      areas: false,
      cables: false,
      dropCables: false,
      joints: false,
      dps: false,
      poles: false,
      chambers: false,
      streetCabs: false,
      homes: false,
      other: false,
    });
    setOpenreachLayers({
      ducts: false,
      trenches: false,
      spans: false,
      chambers: false,
      poles: false,
      labels: false,
    });
  };

  const showOnlyOpenreachLayers = () => {
    setVisibleLayers({
      ...defaultWorkspaceLayers,
      projectBoundary: false,
      areas: false,
      cables: false,
      dropCables: false,
      joints: false,
      dps: false,
      poles: false,
      chambers: false,
      streetCabs: false,
      homes: false,
      other: false,
    });
    setOpenreachLayers(defaultOpenreachLayers);
  };

  return (
    <div style={workspaceRoot}>
      {/* =====================================================
          PROJECT TOP HEADER
      ===================================================== */}
      <header style={topHeader}>
        <div style={{ minWidth: 260 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <h1 style={projectTitle}>{projectName}</h1>
            <span style={statusPill}>{status}</span>
          </div>
          <div style={projectSubtitle}>Project Workspace</div>
          {projectAreas.length > 1 ? (
            <select
              value={activeProjectId || projectArea?.id || ""}
              onChange={(event) => {
                const nextProjectId = event.target.value;
                if (!nextProjectId) return;
                setSelectedWorkspaceAsset(null);
                setActiveOperationPanel("none");
                onSelectProject?.(nextProjectId);
              }}
              style={projectSwitcherSelect}
              title="Switch project area"
            >
              {projectAreas.map((area) => (
                <option key={area.id} value={area.id}>
                  {getProjectAreaLabel(area)}
                </option>
              ))}
            </select>
          ) : null}
        </div>

        <div style={topMetrics}>
          <StatCard
            label="RFS Progress"
            value={`${displayStats.rfsPercent}%`}
            tone={rfsTone}
          />
          <StatCard
            label="Homes Passed"
            value={formatNumber(displayStats.homesPassed)}
          />
          <StatCard
            label="Connected"
            value={formatNumber(displayStats.homesConnected)}
          />
          <StatCard
            label="Issues"
            value={formatNumber(displayStats.issueCount)}
            tone={issueTone}
          />
          <StatCard
            label="Topology Links"
            value={formatNumber(displayStats.topologyLinks)}
          />
          <StatCard
            label="Drop Cables"
            value={formatNumber(displayStats.dropCables ?? 0)}
          />
          <StatCard
            label="Splice Points"
            value={formatNumber(displayStats.splicePoints)}
          />
        </div>

        <div style={{ display: "flex", gap: 8 }}>
          <button type="button" style={smallButton} onClick={onExport}>
            Export
          </button>
          <button type="button" style={smallButton} onClick={onBackToMap}>
            Back To Map
          </button>
        </div>
      </header>

      {/* =====================================================
          WORKSPACE TAB BAR
      ===================================================== */}
      <nav style={tabBar}>
        {tabs.map((tab) => (
          <button
            key={tab.id}
            type="button"
            onClick={() => setActiveTab(tab.id)}
            style={activeTab === tab.id ? activeTabButton : tabButton}
          >
            {tab.label}
          </button>
        ))}
      </nav>

      <div style={workspaceBody}>
        {/* =====================================================
            LEFT WORKFLOW NAV
        ===================================================== */}
        <aside style={leftRail}>
          <div style={brandBlock}>
            <div style={brandIcon}>⌁</div>
            <div>
              <div style={{ fontWeight: 800 }}>Network</div>
              <div style={{ fontWeight: 800 }}>Operations</div>
            </div>
          </div>

          <SideGroup
            title="NETWORK OPERATIONS"
            items={[
              ["Topology", () => openOperationPanel("topology", "topology")],
              ["QA Status", () => openOperationPanel("qa", "qa")],
              [
                "Fibre Tray Topology",
                () => {
                  setActiveTab("fibre");
                  onOpenFibreTopology?.();
                },
              ],
              ["Disconnected Assets", () => openOperationPanel("qa", "qa")],
              ["Over Capacity", () => openOperationPanel("issues", "qa")],
            ]}
          />

          <SideGroup
            title="PROJECT MANAGEMENT"
            items={[
              [
                "Build Progress",
                () => openOperationPanel("rfsBreakdown", "build"),
              ],
              [
                "Maintenance",
                () => openOperationPanel("issues", "maintenance"),
              ],
              ["Assets", () => openOperationPanel("projectDetails", "assets")],
              ["Reports", () => openOperationPanel("report", "reports")],
            ]}
          />

          <div style={{ marginTop: "auto" }}>
            <button type="button" style={railButton} onClick={onBackToMap}>
              ← Back to global map
            </button>
          </div>
        </aside>

        {/* =====================================================
            MAIN DASHBOARD CONTENT
        ===================================================== */}
        <main style={contentGrid}>
          <section style={mapPanel}>
            <div style={mapToolbar}>
              <div style={searchWrap}>
                <input
                  type="search"
                  value={searchTerm}
                  onChange={(event) => setSearchTerm(event.target.value)}
                  onFocus={() => setSearchFocused(true)}
                  onKeyDown={(event) => {
                    if (event.key === "Enter" && searchResults[0]) {
                      handleSearchSelect(searchResults[0]);
                    }
                    if (event.key === "Escape") {
                      setSearchFocused(false);
                    }
                  }}
                  placeholder="Search address, asset, cable..."
                  style={searchInput}
                />
                {searchFocused && searchResults.length > 0 && (
                  <div style={searchResultsPanel}>
                    {searchResults.map((asset) => (
                      <button
                        key={String(
                          (asset as any).id ||
                            (asset as any).assetId ||
                            getWorkspaceAssetTitle(asset),
                        )}
                        type="button"
                        style={searchResultButton}
                        onMouseDown={(event) => {
                          event.preventDefault();
                          handleSearchSelect(asset);
                        }}
                      >
                        <strong>{getWorkspaceAssetTitle(asset)}</strong>
                        <span>{getWorkspaceAssetType(asset)}</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
              <div style={layerMenuWrap}>
                <button
                  type="button"
                  style={layerButton}
                  onClick={() => setLayerMenuOpen((open) => !open)}
                >
                  Layers ({enabledLayerCount}) ▾
                </button>

                {layerMenuOpen && (
                  <div style={layerMenu}>
                    <div style={layerMenuHeader}>Workspace Layers</div>
                    {workspaceLayerOptions.map((layer) => (
                      <label key={layer.key} style={layerRow}>
                        <input
                          type="checkbox"
                          checked={visibleLayers[layer.key]}
                          onChange={() => toggleLayer(layer.key)}
                        />
                        <span>{layer.label}</span>
                      </label>
                    ))}

                    <div style={layerMenuDivider} />
                    <div style={layerMenuHeader}>Openreach / PIA Layers</div>
                    {openreachLayerOptions.map((layer) => (
                      <label key={layer.key} style={layerRow}>
                        <input
                          type="checkbox"
                          checked={openreachLayers[layer.key]}
                          onChange={() => toggleOpenreachLayer(layer.key)}
                        />
                        <span>{layer.label}</span>
                      </label>
                    ))}

                    <div style={layerMenuActions}>
                      <button
                        type="button"
                        style={miniLayerButton}
                        onClick={showAllLayers}
                      >
                        Show all
                      </button>
                      <button
                        type="button"
                        style={miniLayerButton}
                        onClick={hideAllLayers}
                      >
                        Boundary only
                      </button>
                    </div>
                    <button
                      type="button"
                      style={fullWidthMiniLayerButton}
                      onClick={showOnlyOpenreachLayers}
                    >
                      Openreach / PIA only
                    </button>
                  </div>
                )}
              </div>
            </div>
            <div style={mapLiveWrap}>
              <WorkspaceMap
                openreachLayers={openreachLayers}
                projectName={projectName}
                projectArea={projectArea}
                assets={workspaceAssets}
                selectedAssetId={
                  fullSelectedWorkspaceAsset?.id ??
                  selectedWorkspaceAsset?.id ??
                  null
                }
                showCableDistances
                visibleLayers={visibleLayers}
                onAssetSelect={setSelectedWorkspaceAsset}
              />

              <div style={mapAssetInspector}>
                <div
                  style={{
                    color: "#93c5fd",
                    fontSize: 11,
                    fontWeight: 900,
                    letterSpacing: 0.4,
                  }}
                >
                  SELECTED ASSET
                </div>
                <div style={{ marginTop: 5, fontWeight: 900 }}>
                  {fullSelectedWorkspaceAsset
                    ? String(
                        (fullSelectedWorkspaceAsset as any).name ||
                          (fullSelectedWorkspaceAsset as any).jointName ||
                          fullSelectedWorkspaceAsset.id,
                      )
                    : "Click an asset"}
                </div>
                <div style={{ marginTop: 3, color: "#cbd5e1", fontSize: 12 }}>
                  {fullSelectedWorkspaceAsset
                    ? String(
                        (fullSelectedWorkspaceAsset as any).assetType ||
                          (fullSelectedWorkspaceAsset as any).jointType ||
                          "Asset",
                      )
                    : "Cable, DP, joint, pole, chamber or area"}
                </div>
              </div>
            </div>
          </section>

          {fullSelectedWorkspaceAsset ? (
            <section style={intelligenceDock}>
              <AssetIntelligencePanel
                asset={fullSelectedWorkspaceAsset}
                projectName={projectName}
                projectAssets={workspaceAssets}
                onClose={() => setSelectedWorkspaceAsset(null)}
                onOpenTopology={onOpenFibreTopology}
                onOpenQA={onOpenQA}
                onSelectAsset={setSelectedWorkspaceAsset}
                onZoomAsset={setSelectedWorkspaceAsset}
                onOpenJointEditor={onOpenJointEditor}
              />
            </section>
          ) : (
            <WorkspaceTabContent
              activeTab={activeTab}
              projectName={projectName}
              status={status}
              stats={displayStats}
              projectAssets={workspaceAssets}
              projectArea={projectArea}
              auditIssues={auditIssues}
              disconnectedAssets={disconnectedAssets}
              networkGraph={networkGraph}
              onOpenPanel={(panel, tab) =>
                openOperationPanel(
                  panel as WorkspaceOperationPanel,
                  (tab || activeTab) as WorkspaceTab,
                )
              }
              onOpenTrace={openInternalTraceTool}
              onOpenQA={onOpenQA}
              onOpenFibreTopology={onOpenFibreTopology}
              onExport={onExport}
              onBackToMap={onBackToMap}
            />
          )}

          {activeOperationPanel !== "none" && (
            <section style={operationDrawer}>
              <div style={operationDrawerHeader}>
                <div>
                  <div style={operationKicker}>OPERATION PANEL</div>
                  <h3 style={operationTitle}>
                    {activeOperationPanel === "projectDetails" &&
                      "Project Details"}
                    {activeOperationPanel === "rfsBreakdown" && "RFS Breakdown"}
                    {activeOperationPanel === "issues" && "Area Issues"}
                    {activeOperationPanel === "topology" && "Topology"}
                    {activeOperationPanel === "qa" && "QA Validation"}
                    {activeOperationPanel === "trace" && "Trace Fibre Route"}
                    {activeOperationPanel === "addAsset" && "Add New Asset"}
                    {activeOperationPanel === "report" && "Project Report"}
                  </h3>
                </div>
                <button
                  type="button"
                  style={closePanelButton}
                  onClick={() => setActiveOperationPanel("none")}
                >
                  ×
                </button>
              </div>

              {activeOperationPanel === "projectDetails" && (
                <div style={operationGrid}>
                  <InfoRow label="Project" value={projectName} />
                  <InfoRow label="Status" value={status} highlight />
                  <InfoRow
                    label="Homes"
                    value={`${formatNumber(displayStats.homesConnected)} / ${formatNumber(displayStats.homesPassed)}`}
                  />
                  <InfoRow
                    label="Route Length"
                    value={formatDistance(displayStats.routeLengthMeters)}
                  />
                  <InfoRow
                    label="Total Assets"
                    value={formatNumber(workspaceAssets.length)}
                  />
                  <InfoRow
                    label="Project Area"
                    value={
                      projectArea
                        ? String(
                            (projectArea as any).name ||
                              (projectArea as any).label ||
                              projectArea.id,
                          )
                        : "Not selected"
                    }
                  />
                </div>
              )}

              {activeOperationPanel === "rfsBreakdown" && (
                <div style={operationGrid}>
                  <InfoRow
                    label="RFS Progress"
                    value={`${displayStats.rfsPercent}%`}
                    highlight={displayStats.rfsPercent >= 80}
                  />
                  <InfoRow
                    label="Homes Passed"
                    value={formatNumber(displayStats.homesPassed)}
                  />
                  <InfoRow
                    label="Homes Connected"
                    value={formatNumber(displayStats.homesConnected)}
                  />
                  <InfoRow
                    label="Homes Remaining"
                    value={formatNumber(
                      Math.max(
                        0,
                        displayStats.homesPassed - displayStats.homesConnected,
                      ),
                    )}
                  />
                  <InfoRow label="Build Status" value={status} />
                </div>
              )}

              {(activeOperationPanel === "issues" ||
                activeOperationPanel === "qa") && (
                <div style={operationStack}>
                  <div style={issueGrid}>
                    <IssueCard
                      label="High"
                      value={issueBuckets.high.length}
                      tone="#7f1d1d"
                    />
                    <IssueCard
                      label="Medium"
                      value={issueBuckets.medium.length}
                      tone="#78350f"
                    />
                    <IssueCard
                      label="Low"
                      value={issueBuckets.low.length}
                      tone="#1e3a8a"
                    />
                  </div>
                  <div style={operationList}>
                    {auditIssues.length === 0 ? (
                      <div style={emptyPanel}>
                        No QA issues found for this project area.
                      </div>
                    ) : (
                      auditIssues
                        .slice(0, 12)
                        .map((issue: AuditIssue, index: number) => (
                          <div
                            key={`${issue.assetId}-${issue.issue}-${index}`}
                            style={operationListItem}
                          >
                            <strong>
                              {issue.severity.toUpperCase()} — {issue.category}
                            </strong>
                            <span>
                              {issue.assetName ||
                                issue.assetId ||
                                "Unknown asset"}
                            </span>
                            <small>{issue.issue}</small>
                          </div>
                        ))
                    )}
                  </div>
                </div>
              )}

              {activeOperationPanel === "topology" && (
                <div style={operationGrid}>
                  <InfoRow
                    label="Graph Nodes"
                    value={formatNumber(networkGraph.nodes.size)}
                  />
                  <InfoRow
                    label="Graph Links"
                    value={formatNumber(networkGraph.edges.size)}
                  />
                  <InfoRow
                    label="Mapped Joints"
                    value={formatNumber(
                      stats.mappedJoints ?? displayStats.joints,
                    )}
                  />
                  <InfoRow
                    label="Route Links"
                    value={formatNumber(displayStats.topologyLinks)}
                  />
                  <InfoRow
                    label="Disconnected Assets"
                    value={formatNumber(disconnectedAssets.length)}
                  />
                  <InfoRow
                    label="Unmatched Cable IDs"
                    value={formatNumber(displayStats.unmatchedCableIds ?? 0)}
                  />
                  <button
                    type="button"
                    style={wideButton}
                    onClick={onOpenFibreTopology}
                  >
                    Open Fibre Tray Topology
                  </button>
                </div>
              )}

              {activeOperationPanel === "trace" && (
                <div style={operationStack}>
                  {fullSelectedWorkspaceAsset ? (
                    <>
                      <div style={traceSelectedCard}>
                        <div style={operationKicker}>TRACE SELECTED</div>
                        <strong>
                          {getWorkspaceAssetTitle(fullSelectedWorkspaceAsset)}
                        </strong>
                        <span>
                          {getWorkspaceAssetType(fullSelectedWorkspaceAsset)}
                        </span>
                      </div>

                      <div style={operationList}>
                        {selectedTraceRows.length === 0 ? (
                          <div style={emptyPanel}>
                            No connected graph links found for this asset yet.
                            Check the cable endpoint snapping or select a cable
                            that touches this asset.
                          </div>
                        ) : (
                          selectedTraceRows.map((row) => (
                            <button
                              key={row.id}
                              type="button"
                              style={traceResultButton}
                              onClick={() =>
                                setSelectedWorkspaceAsset(
                                  row.asset as SavedMapAsset,
                                )
                              }
                            >
                              <strong>{row.title}</strong>
                              <span>{row.type}</span>
                            </button>
                          ))
                        )}
                      </div>
                    </>
                  ) : (
                    <div style={emptyPanel}>
                      Select a cable, joint, DP, pole, chamber or street cabinet
                      on the workspace map. The trace links will show here
                      without leaving this workspace.
                    </div>
                  )}
                </div>
              )}

              {activeOperationPanel === "addAsset" && (
                <div style={operationStack}>
                  <div style={emptyPanel}>
                    Asset creation still lives on the main map so the existing
                    right-click creation, snapping, cable drawing and save logic
                    stays protected.
                  </div>
                  <button
                    type="button"
                    style={wideButton}
                    onClick={onBackToMap}
                  >
                    Back To Map To Add Asset
                  </button>
                </div>
              )}

              {activeOperationPanel === "report" && (
                <div style={operationStack}>
                  <div style={emptyPanel}>
                    Project report is ready. Use Generate Report to download a
                    current text report, or Export Project Data for the existing
                    export workflow.
                  </div>
                  <button
                    type="button"
                    style={wideButton}
                    onClick={handleGenerateReport}
                  >
                    Download Report
                  </button>
                  <button type="button" style={wideButton} onClick={onExport}>
                    Export Project Data
                  </button>
                </div>
              )}
            </section>
          )}
        </main>
      </div>
    </div>
  );
}

function SideGroup({
  title,
  items,
}: {
  title: string;
  items: [string, () => void][];
}) {
  return (
    <div style={sideGroup}>
      <div style={sideGroupTitle}>{title}</div>
      {items.map(([label, onClick]) => (
        <button key={label} type="button" style={railButton} onClick={onClick}>
          {label}
        </button>
      ))}
    </div>
  );
}

function InfoRow({
  label,
  value,
  highlight = false,
}: {
  label: string;
  value: React.ReactNode;
  highlight?: boolean;
}) {
  return (
    <div style={infoRow}>
      <span style={{ color: "#cbd5e1" }}>{label}</span>
      <strong style={{ color: highlight ? "#4ade80" : "#f8fafc" }}>
        {value}
      </strong>
    </div>
  );
}

function IssueCard({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone: string;
}) {
  return (
    <div style={{ ...issueCard, background: tone }}>
      <div style={{ fontSize: 12, opacity: 0.9 }}>{label}</div>
      <div style={{ fontSize: 28, fontWeight: 900 }}>{value}</div>
    </div>
  );
}

const operationDrawer: React.CSSProperties = {
  gridColumn: "1 / -1",
  background: "#0f1b2d",
  border: "1px solid rgba(96, 165, 250, 0.35)",
  borderRadius: 12,
  padding: 16,
};

const operationDrawerHeader: React.CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "flex-start",
  gap: 16,
  marginBottom: 14,
};

const operationKicker: React.CSSProperties = {
  color: "#93c5fd",
  fontSize: 11,
  fontWeight: 900,
  letterSpacing: 0.5,
};

const operationTitle: React.CSSProperties = {
  margin: "3px 0 0",
  fontSize: 20,
};

const closePanelButton: React.CSSProperties = {
  background: "#132640",
  color: "#e5e7eb",
  border: "1px solid rgba(148, 163, 184, 0.25)",
  borderRadius: 8,
  cursor: "pointer",
  fontWeight: 700,
  width: 34,
  height: 34,
  padding: 0,
  fontSize: 22,
  lineHeight: "22px",
};

const operationGrid: React.CSSProperties = {
  display: "grid",
  gridTemplateColumns: "repeat(2, minmax(220px, 1fr))",
  gap: 10,
};

const operationStack: React.CSSProperties = {
  display: "grid",
  gap: 12,
};

const operationList: React.CSSProperties = {
  display: "grid",
  gap: 8,
  maxHeight: 320,
  overflow: "auto",
};

const operationListItem: React.CSSProperties = {
  display: "grid",
  gap: 4,
  background: "#111827",
  border: "1px solid rgba(148, 163, 184, 0.16)",
  borderRadius: 10,
  padding: 12,
  color: "#e5e7eb",
};

const emptyPanel: React.CSSProperties = {
  background: "#111827",
  border: "1px solid rgba(148, 163, 184, 0.16)",
  borderRadius: 10,
  padding: 14,
  color: "#cbd5e1",
};

const workspaceRoot: React.CSSProperties = {
  position: "absolute",
  inset: 0,
  zIndex: 5000,
  background:
    "radial-gradient(circle at top left, rgba(37, 99, 235, 0.16), transparent 32%), #07111f",
  color: "#f8fafc",
  display: "flex",
  flexDirection: "column",
  fontFamily:
    "Inter, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
};

const topHeader: React.CSSProperties = {
  minHeight: 112,
  display: "grid",
  gridTemplateColumns: "minmax(270px, 0.75fr) minmax(620px, 2.2fr) auto",
  alignItems: "center",
  gap: 16,
  padding: "14px 18px 14px 24px",
  borderBottom: "1px solid rgba(148, 163, 184, 0.18)",
  background: "linear-gradient(180deg, #0f1b2d 0%, #0a1424 100%)",
};

const projectTitle: React.CSSProperties = {
  margin: 0,
  fontSize: 28,
  lineHeight: 1.05,
  fontWeight: 950,
  letterSpacing: "-0.03em",
};
const projectSubtitle: React.CSSProperties = {
  marginTop: 6,
  color: "#94a3b8",
  fontSize: 14,
};

const projectSwitcherSelect: React.CSSProperties = {
  marginTop: 10,
  width: "100%",
  maxWidth: 260,
  background: "#020617",
  color: "#e5e7eb",
  border: "1px solid #334155",
  borderRadius: 10,
  padding: "9px 11px",
  fontWeight: 850,
  outline: "none",
  boxShadow: "inset 0 1px 0 rgba(255,255,255,0.04)",
};
const statusPill: React.CSSProperties = {
  background: "rgba(34,197,94,0.18)",
  color: "#86efac",
  border: "1px solid rgba(34,197,94,0.25)",
  borderRadius: 7,
  padding: "5px 9px",
  fontSize: 12,
  fontWeight: 800,
};
const topMetrics: React.CSSProperties = {
  display: "grid",
  gridTemplateColumns: "repeat(7, minmax(112px, 1fr))",
  gap: 10,
  alignItems: "stretch",
};
const metricCard: React.CSSProperties = {
  background: "linear-gradient(180deg, rgba(15, 23, 42, 0.90), rgba(15, 23, 42, 0.68))",
  border: "1px solid rgba(148, 163, 184, 0.16)",
  borderRadius: 12,
  padding: "11px 13px",
  minHeight: 66,
  boxShadow: "0 10px 24px rgba(0,0,0,0.18)",
};
const metricLabel: React.CSSProperties = {
  color: "#cbd5e1",
  fontSize: 11,
  marginBottom: 5,
};
const metricValue: React.CSSProperties = {
  fontSize: 23,
  fontWeight: 950,
  lineHeight: 1.05,
};
const smallButton: React.CSSProperties = {
  background: "#132640",
  color: "#e5e7eb",
  border: "1px solid rgba(148, 163, 184, 0.25)",
  borderRadius: 8,
  padding: "9px 12px",
  cursor: "pointer",
  fontWeight: 700,
};
const tabBar: React.CSSProperties = {
  minHeight: 50,
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "0 18px 0 176px",
  borderBottom: "1px solid rgba(148, 163, 184, 0.13)",
  background: "rgba(11, 22, 38, 0.96)",
};
const tabButton: React.CSSProperties = {
  background: "transparent",
  color: "#cbd5e1",
  border: "none",
  borderRadius: 8,
  padding: "10px 16px",
  cursor: "pointer",
  fontWeight: 700,
};
const activeTabButton: React.CSSProperties = {
  ...tabButton,
  background: "rgba(37, 99, 235, 0.22)",
  color: "#93c5fd",
  boxShadow: "inset 0 -2px 0 #3b82f6",
};
const workspaceBody: React.CSSProperties = {
  flex: 1,
  display: "grid",
  gridTemplateColumns: "176px 1fr",
  minHeight: 0,
};
const leftRail: React.CSSProperties = {
  background: "linear-gradient(180deg, #07111f 0%, #050b14 100%)",
  borderRight: "1px solid rgba(148, 163, 184, 0.16)",
  padding: "16px 12px",
  display: "flex",
  flexDirection: "column",
  gap: 18,
};
const brandBlock: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 10,
  marginBottom: 20,
};
const brandIcon: React.CSSProperties = {
  width: 34,
  height: 34,
  borderRadius: 10,
  background: "#2563eb",
  display: "grid",
  placeItems: "center",
  fontSize: 22,
  fontWeight: 900,
};
const sideGroup: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: 6,
};
const sideGroupTitle: React.CSSProperties = {
  color: "#94a3b8",
  fontSize: 11,
  fontWeight: 900,
  letterSpacing: 0.5,
  margin: "8px 0",
};
const railButton: React.CSSProperties = {
  textAlign: "left",
  background: "transparent",
  color: "#cbd5e1",
  border: "none",
  borderRadius: 8,
  padding: "9px 10px",
  cursor: "pointer",
  fontWeight: 650,
};
const contentGrid: React.CSSProperties = {
  padding: 16,
  overflow: "auto",
  display: "grid",
  gridTemplateColumns:
    "minmax(760px, 2.15fr) minmax(310px, 0.75fr) minmax(310px, 0.75fr)",
  gridAutoRows: "min-content",
  gap: 16,
  alignItems: "start",
};
const mapPanel: React.CSSProperties = {
  gridRow: "span 2",
  background: "linear-gradient(180deg, #0f1b2d 0%, #0b1626 100%)",
  border: "1px solid rgba(148, 163, 184, 0.18)",
  borderRadius: 14,
  padding: 14,
  boxShadow: "0 18px 44px rgba(0,0,0,0.18)",
};
const mapToolbar: React.CSSProperties = {
  display: "flex",
  gap: 10,
  marginBottom: 10,
};
const searchWrap: React.CSSProperties = { flex: 1, position: "relative" };
const searchInput: React.CSSProperties = {
  width: "100%",
  background: "#111827",
  border: "1px solid rgba(148, 163, 184, 0.2)",
  borderRadius: 8,
  color: "#e5e7eb",
  padding: "10px 12px",
  outline: "none",
};
const searchResultsPanel: React.CSSProperties = {
  position: "absolute",
  left: 0,
  right: 0,
  top: 44,
  zIndex: 1400,
  background: "rgba(2, 6, 23, 0.97)",
  border: "1px solid rgba(96, 165, 250, 0.35)",
  borderRadius: 10,
  padding: 8,
  boxShadow: "0 18px 45px rgba(0,0,0,0.45)",
};
const searchResultButton: React.CSSProperties = {
  width: "100%",
  display: "flex",
  justifyContent: "space-between",
  gap: 12,
  textAlign: "left",
  background: "transparent",
  color: "#e5e7eb",
  border: "none",
  borderRadius: 8,
  padding: "9px 10px",
  cursor: "pointer",
};
const layerButton: React.CSSProperties = { ...smallButton, minWidth: 130 };
const layerMenuWrap: React.CSSProperties = { position: "relative" };
const layerMenu: React.CSSProperties = {
  position: "absolute",
  right: 0,
  top: 44,
  zIndex: 1200,
  width: 260,
  maxHeight: 520,
  overflowY: "auto",
  background: "rgba(2, 6, 23, 0.96)",
  border: "1px solid rgba(148, 163, 184, 0.28)",
  borderRadius: 10,
  padding: 12,
  boxShadow: "0 16px 45px rgba(0,0,0,0.45)",
};
const layerMenuHeader: React.CSSProperties = {
  color: "#93c5fd",
  fontSize: 12,
  fontWeight: 900,
  letterSpacing: 0.4,
  marginBottom: 8,
};
const layerRow: React.CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: 8,
  padding: "6px 0",
  color: "#e5e7eb",
  fontSize: 13,
  fontWeight: 700,
};
const layerMenuDivider: React.CSSProperties = {
  height: 1,
  background: "rgba(148, 163, 184, 0.18)",
  margin: "10px 0",
};
const layerMenuActions: React.CSSProperties = {
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gap: 8,
  marginTop: 10,
};
const miniLayerButton: React.CSSProperties = {
  ...smallButton,
  padding: "7px 8px",
  fontSize: 12,
  background: "#111827",
};
const fullWidthMiniLayerButton: React.CSSProperties = {
  ...miniLayerButton,
  width: "100%",
  marginTop: 8,
};
const mapLiveWrap: React.CSSProperties = {
  position: "relative",
  height: 548,
  borderRadius: 12,
  overflow: "hidden",
  border: "1px solid rgba(148, 163, 184, 0.22)",
  background: "#020617",
  boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.02)",
};
const mapAssetInspector: React.CSSProperties = {
  position: "absolute",
  right: 14,
  top: 14,
  zIndex: 800,
  minWidth: 190,
  maxWidth: 260,
  background: "rgba(2, 6, 23, 0.86)",
  border: "1px solid rgba(148, 163, 184, 0.28)",
  borderRadius: 10,
  padding: 12,
  color: "#f8fafc",
  boxShadow: "0 12px 35px rgba(0,0,0,0.35)",
};
const areaBoundary: React.CSSProperties = {
  position: "absolute",
  left: "7%",
  right: "7%",
  top: "16%",
  bottom: "18%",
  border: "4px solid #22c55e",
  transform: "skew(-8deg)",
  background: "rgba(34,197,94,0.08)",
};
const mockNetworkLineOne: React.CSSProperties = {
  position: "absolute",
  left: "15%",
  right: "13%",
  top: "48%",
  height: 4,
  background: "#60a5fa",
  transform: "rotate(-4deg)",
  boxShadow: "0 0 0 2px rgba(96,165,250,0.2)",
};
const mockNetworkLineTwo: React.CSSProperties = {
  position: "absolute",
  left: "22%",
  width: "55%",
  top: "62%",
  height: 4,
  background: "#facc15",
  transform: "rotate(15deg)",
};
const mockNetworkLineThree: React.CSSProperties = {
  position: "absolute",
  left: "45%",
  width: "35%",
  top: "35%",
  height: 4,
  background: "#a78bfa",
  transform: "rotate(64deg)",
};
const mapLabel: React.CSSProperties = {
  position: "absolute",
  left: "46%",
  top: "46%",
  fontWeight: 900,
  textShadow: "0 2px 4px #000",
};
const mapControls: React.CSSProperties = {
  position: "absolute",
  left: 12,
  top: 12,
  background: "rgba(15,23,42,0.9)",
  borderRadius: 8,
  padding: "8px 13px",
  lineHeight: 1.8,
  fontWeight: 900,
};
const legendButton: React.CSSProperties = {
  position: "absolute",
  left: 16,
  bottom: 16,
  ...smallButton,
};
const threeDButton: React.CSSProperties = {
  position: "absolute",
  right: 16,
  bottom: 16,
  ...smallButton,
};
const intelligenceDock: React.CSSProperties = {
  gridColumn: "span 2",
  gridRow: "span 4",
  background: "linear-gradient(180deg, #0f1b2d 0%, #0b1626 100%)",
  border: "1px solid rgba(148, 163, 184, 0.18)",
  borderRadius: 14,
  overflow: "hidden",
  minHeight: 620,
  boxShadow: "0 18px 44px rgba(0,0,0,0.18)",
};
const summaryPanel: React.CSSProperties = {
  background: "linear-gradient(180deg, #0f1b2d 0%, #0b1626 100%)",
  border: "1px solid rgba(148, 163, 184, 0.18)",
  borderRadius: 14,
  padding: 16,
  minHeight: 170,
  boxShadow: "0 12px 30px rgba(0,0,0,0.14)",
};
const widePanel: React.CSSProperties = {
  ...summaryPanel,
  gridColumn: "span 1",
};
const panelTitle: React.CSSProperties = { margin: "0 0 14px", fontSize: 18 };
const infoRow: React.CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  gap: 12,
  padding: "7px 0",
  fontSize: 13,
};
const wideButton: React.CSSProperties = {
  ...smallButton,
  width: "100%",
  marginTop: 14,
  background: "#1e3a5f",
};
const donutWrap: React.CSSProperties = {
  height: 120,
  display: "grid",
  placeItems: "center",
};
const donut: React.CSSProperties = {
  width: 94,
  height: 94,
  borderRadius: "50%",
  border: "16px solid #34d399",
  display: "grid",
  placeItems: "center",
  fontWeight: 900,
  fontSize: 25,
};
const issueGrid: React.CSSProperties = {
  display: "grid",
  gridTemplateColumns: "repeat(3, 1fr)",
  gap: 8,
};
const issueCard: React.CSSProperties = {
  borderRadius: 8,
  padding: 12,
  minHeight: 68,
  display: "flex",
  flexDirection: "column",
  justifyContent: "space-between",
};
const assetGrid: React.CSSProperties = {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
  gap: 10,
};
const assetTile: React.CSSProperties = {
  background: "rgba(17, 24, 39, 0.92)",
  border: "1px solid rgba(148, 163, 184, 0.16)",
  borderRadius: 12,
  padding: 13,
  minHeight: 74,
};
const quickActions: React.CSSProperties = {
  display: "grid",
  gridTemplateColumns: "repeat(5, 1fr)",
  gap: 10,
};
const quickAction: React.CSSProperties = {
  ...smallButton,
  minHeight: 54,
  background: "#111827",
};

const traceSelectedCard: React.CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: 5,
  background: "rgba(15, 23, 42, 0.85)",
  border: "1px solid rgba(96, 165, 250, 0.35)",
  borderRadius: 10,
  padding: 12,
};
const traceResultButton: React.CSSProperties = {
  width: "100%",
  display: "flex",
  flexDirection: "column",
  gap: 4,
  textAlign: "left",
  background: "#111827",
  color: "#e5e7eb",
  border: "1px solid rgba(148, 163, 184, 0.16)",
  borderRadius: 9,
  padding: 12,
  cursor: "pointer",
};
