// =====================================================
// FILE: src/services/network/cableUsageEngine.ts
// PURPOSE: Central read-only cable utilisation engine for Phase 8C.
//          Supports downstream propagation from DP routing while keeping
//          legacy/joint mapping behaviour as a safe compatibility fallback.
// =====================================================

import type { GraphEdge, NetworkGraph } from "../networkGraph";
import { getCableUsedFibres } from "../../components/map/cableUsage";
import type {
  CableUsageState,
  DpRoutingState,
  NetworkAsset,
  PropagatedCableFibreState,
} from "./types";

function text(value: unknown): string {
  return String(value ?? "").trim();
}

function normalise(value: unknown): string {
  return text(value).toLowerCase();
}

function parseCapacity(...values: unknown[]): number {
  const joined = values.map(text).join(" ");
  const match = joined.match(/(288|144|96|48|36|24|12)\s*F?/i);
  if (match) return Number(match[1]);
  const numeric = values.map((value) => Number(value)).find((value) => Number.isFinite(value) && value > 0);
  return numeric ?? 0;
}

function uniqueSorted(values: unknown[]): number[] {
  return Array.from(
    new Set(values.map((value) => Number(value)).filter((value) => Number.isFinite(value) && value > 0)),
  ).sort((a, b) => a - b);
}

function isDropCable(asset: NetworkAsset): boolean {
  const item = asset as any;
  const haystack = [item.assetType, item.type, item.cableType, item.name, item.label, item.generatedBy]
    .map(normalise)
    .join(" ");
  return (
    haystack.includes("drop") ||
    item.isDropCable === true ||
    item.isHomeDrop === true ||
    item.generatedDrop === true ||
    item.autoGeneratedDrop === true ||
    Boolean(item.homeId || item.connectedHomeId || item.toHomeId || item.fromHomeId)
  );
}

function routeFibresForCable(cableId: string, dpStates: Record<string, DpRoutingState>) {
  const relatedStates = Object.values(dpStates).filter(
    (state) => state.throughCableId === cableId || state.downstreamCableId === cableId,
  );

  return {
    passthroughFibres: uniqueSorted(relatedStates.flatMap((state) => state.passthroughFibres)),
    consumedFibres: uniqueSorted(relatedStates.flatMap((state) => state.consumedFibres)),
    spareFibres: uniqueSorted(relatedStates.flatMap((state) => state.spareFibres)),
    inputFibres: uniqueSorted(relatedStates.flatMap((state) => state.inputFibres)),
  };
}

function makeSequential(count: number, capacity: number): number[] {
  const safeCount = Math.max(0, Math.round(count));
  const upper = capacity > 0 ? Math.min(capacity, safeCount) : safeCount;
  return Array.from({ length: upper }, (_, index) => index + 1);
}

function fullFibreSet(capacity: number): number[] {
  return capacity > 0 ? Array.from({ length: capacity }, (_, index) => index + 1) : [];
}

export function buildCableUsageState(args: {
  cable: NetworkAsset;
  allAssets: NetworkAsset[];
  edge?: GraphEdge;
  dpStates?: Record<string, DpRoutingState>;
  propagatedCableFibres?: Record<string, PropagatedCableFibreState>;
}): CableUsageState {
  const { cable, allAssets, edge, dpStates = {}, propagatedCableFibres = {} } = args;
  const item = cable as any;
  const assetId = text(item.id || item.assetId || item.cableId || item.name);
  const capacity = parseCapacity(item.fibreCount, item.fiberCount, item.coreCount, item.size);
  const dropCable = isDropCable(cable);
  const routed = routeFibresForCable(assetId, dpStates);
  const propagated = propagatedCableFibres[assetId];
  const propagatedUsedNumbers = propagated?.usedFibreNumbers || [];
  const legacyUsed = getCableUsedFibres(cable, allAssets);
  const routedUsedNumbers = uniqueSorted([...routed.inputFibres, ...routed.consumedFibres, ...routed.passthroughFibres]);
  const routedUsedCount = routedUsedNumbers.length;
  const propagatedUsedCount = propagatedUsedNumbers.length;
  const usedFibres = dropCable ? 1 : Math.max(legacyUsed, routedUsedCount, propagatedUsedCount);
  const usedFibreNumbers = propagatedUsedCount > 0
    ? propagatedUsedNumbers
    : routedUsedCount > 0
      ? routedUsedNumbers
      : makeSequential(usedFibres, capacity);
  const propagatedSpareFibres = propagated?.spareFibres || [];
  const spareFibres = propagatedSpareFibres.length > 0
    ? propagatedSpareFibres
    : routed.spareFibres.length > 0
      ? routed.spareFibres
      : fullFibreSet(capacity).filter((fibre) => !usedFibreNumbers.includes(fibre));
  const warnings: string[] = [];

  if (capacity > 0 && usedFibres > capacity) warnings.push("Cable used fibre count exceeds cable capacity.");
  if (!dropCable && capacity === 0) warnings.push("Cable capacity could not be detected.");
  if (propagated?.warnings?.length) warnings.push(...propagated.warnings);

  const source = propagatedUsedCount > 0
    ? propagated?.inferredDownstream
      ? "downstream-propagation-inferred"
      : "downstream-propagation-engine"
    : routedUsedCount > 0
      ? "dp-routing-engine"
      : dropCable
        ? "network-state-drop-cable"
        : legacyUsed > 0
          ? "network-state-cable-usage"
          : edge?.connectedNodeIds?.length
            ? "network-state-graph"
            : "network-state";

  return {
    assetId,
    assetName: text(item.name || item.label || item.cableId || item.id || "Cable"),
    cableType: text(item.cableType || item.type || item.assetType || "Cable"),
    capacity,
    usedFibres: capacity > 0 ? Math.min(capacity, usedFibres) : usedFibres,
    usedFibreNumbers,
    passthroughFibres: uniqueSorted([
      ...routed.passthroughFibres,
      ...(propagated?.passthroughFibres || []),
    ]),
    consumedFibres: uniqueSorted([
      ...routed.consumedFibres,
      ...(propagated?.consumedFibres || []),
    ]),
    spareFibres,
    utilisationPercent: capacity > 0 ? Math.round((Math.min(capacity, usedFibres) / capacity) * 100) : 0,
    isDropCable: dropCable,
    source,
    connectedNodeIds: edge?.connectedNodeIds || [],
    warnings: Array.from(new Set(warnings)),
  };
}

export function isCableLikeAsset(asset: NetworkAsset): boolean {
  const item = asset as any;
  const haystack = [item.assetType, item.type, item.jointType, item.cableType, item.name, item.label]
    .map(normalise)
    .join(" ");
  return item.geometry?.type === "LineString" || haystack.includes("cable") || haystack.includes("drop");
}

export function buildCableUsageStates(args: {
  assets: NetworkAsset[];
  graph: NetworkGraph;
  dpStates?: Record<string, DpRoutingState>;
  propagatedCableFibres?: Record<string, PropagatedCableFibreState>;
}): Record<string, CableUsageState> {
  const { assets, graph, dpStates = {}, propagatedCableFibres = {} } = args;
  return assets.filter(isCableLikeAsset).reduce<Record<string, CableUsageState>>((states, cable) => {
    const id = text((cable as any).id || (cable as any).assetId || (cable as any).cableId || (cable as any).name);
    if (!id) return states;
    states[id] = buildCableUsageState({
      cable,
      allAssets: assets,
      edge: graph.edges.get(id),
      dpStates,
      propagatedCableFibres,
    });
    return states;
  }, {});
}
