// =====================================================
// FILE: src/services/network/fibrePropagation.ts
// PURPOSE: Read-only downstream fibre propagation engine.
//          It turns DP routing intent into propagated cable state
//          without persisting computed values back to Firestore.
// =====================================================

import type { GraphEdge, NetworkGraph } from "../networkGraph";
import type {
  CableUsageState,
  DpRoutingState,
  FibrePropagationHop,
  FibrePropagationState,
  PropagatedCableFibreState,
} from "./types";

function uniqueSorted(values: unknown[]): number[] {
  return Array.from(
    new Set(
      values
        .map((value) => Number(value))
        .filter((value) => Number.isFinite(value) && value > 0),
    ),
  ).sort((a, b) => a - b);
}

function assetTypeFromClosure(closureType: string): string {
  if (closureType.includes("AFN")) return "AFN";
  if (closureType.includes("MDU")) return "MDU";
  if (closureType.includes("CBT")) return "CBT";
  return "Distribution Point";
}

function isDropCableEdge(edge: GraphEdge | undefined): boolean {
  if (!edge) return false;
  const item = edge.asset as any;
  const text = [
    edge.kind,
    item?.assetType,
    item?.type,
    item?.cableType,
    item?.name,
    item?.label,
    item?.generatedBy,
  ]
    .map((value) => String(value ?? "").toLowerCase())
    .join(" ");

  return (
    edge.kind === "drop" ||
    text.includes("drop") ||
    item?.isDropCable === true ||
    item?.isHomeDrop === true ||
    item?.generatedDrop === true ||
    item?.autoGeneratedDrop === true ||
    Boolean(item?.homeId || item?.connectedHomeId || item?.toHomeId || item?.fromHomeId)
  );
}

function ensureCableState(
  cableMap: Record<string, PropagatedCableFibreState>,
  cableId: string,
): PropagatedCableFibreState {
  if (!cableMap[cableId]) {
    cableMap[cableId] = {
      cableId,
      incomingFibres: [],
      consumedFibres: [],
      passthroughFibres: [],
      spareFibres: [],
      usedFibreNumbers: [],
      sourceDpIds: [],
      sourceDpNames: [],
      inferredDownstream: false,
      warnings: [],
    };
  }

  return cableMap[cableId];
}

function pushUniqueText(values: string[], value: string | undefined) {
  const cleaned = String(value || "").trim();
  if (cleaned && !values.includes(cleaned)) values.push(cleaned);
}

function mergeCableFibres(
  target: PropagatedCableFibreState,
  patch: Partial<PropagatedCableFibreState>,
) {
  target.incomingFibres = uniqueSorted([
    ...target.incomingFibres,
    ...(patch.incomingFibres || []),
  ]);
  target.consumedFibres = uniqueSorted([
    ...target.consumedFibres,
    ...(patch.consumedFibres || []),
  ]);
  target.passthroughFibres = uniqueSorted([
    ...target.passthroughFibres,
    ...(patch.passthroughFibres || []),
  ]);
  target.spareFibres = uniqueSorted([
    ...target.spareFibres,
    ...(patch.spareFibres || []),
  ]);
  target.usedFibreNumbers = uniqueSorted([
    ...target.usedFibreNumbers,
    ...target.incomingFibres,
    ...target.consumedFibres,
    ...target.passthroughFibres,
    ...(patch.usedFibreNumbers || []),
  ]);
  target.warnings = Array.from(new Set([...target.warnings, ...(patch.warnings || [])]));
  target.inferredDownstream = target.inferredDownstream || Boolean(patch.inferredDownstream);
}

function getCandidateDownstreamCables(args: {
  graph?: NetworkGraph;
  dpId: string;
  throughCableId?: string;
}): string[] {
  const { graph, dpId, throughCableId } = args;
  if (!graph) return [];

  const node = graph.nodes.get(dpId);
  if (!node) return [];

  return node.connectedTo.filter((edgeId) => {
    if (!edgeId || edgeId === throughCableId) return false;
    const edge = graph.edges.get(edgeId);
    if (!edge || isDropCableEdge(edge)) return false;
    return true;
  });
}

function resolveDownstreamCableId(args: {
  graph?: NetworkGraph;
  state: DpRoutingState;
}): { cableId?: string; inferred: boolean; warnings: string[] } {
  const { graph, state } = args;
  if (state.downstreamCableId) {
    return { cableId: state.downstreamCableId, inferred: false, warnings: [] };
  }

  const candidates = getCandidateDownstreamCables({
    graph,
    dpId: state.assetId,
    throughCableId: state.throughCableId,
  });

  if (candidates.length === 1) {
    return { cableId: candidates[0], inferred: true, warnings: [] };
  }

  if (state.passthroughFibres.length > 0 && candidates.length > 1) {
    return {
      inferred: false,
      warnings: [
        `Passthrough fibres exist but downstream cable is ambiguous (${candidates.length} possible cables). Select a downstream cable in DP Operations.`,
      ],
    };
  }

  return { inferred: false, warnings: [] };
}

function buildPropagatedCableFibres(args: {
  graph?: NetworkGraph;
  dpStates: Record<string, DpRoutingState>;
}): Record<string, PropagatedCableFibreState> {
  const { graph, dpStates } = args;
  const cableMap: Record<string, PropagatedCableFibreState> = {};

  Object.values(dpStates).forEach((state) => {
    const dpWarnings: string[] = [];

    if (state.throughCableId) {
      const throughCable = ensureCableState(cableMap, state.throughCableId);
      pushUniqueText(throughCable.sourceDpIds, state.assetId);
      pushUniqueText(throughCable.sourceDpNames, state.assetName);
      mergeCableFibres(throughCable, {
        incomingFibres: state.inputFibres,
        consumedFibres: state.consumedFibres,
        passthroughFibres: state.passthroughFibres,
        spareFibres: state.spareFibres,
        usedFibreNumbers: uniqueSorted([
          ...state.inputFibres,
          ...state.consumedFibres,
          ...state.passthroughFibres,
        ]),
      });
    }

    const downstream = resolveDownstreamCableId({ graph, state });
    dpWarnings.push(...downstream.warnings);

    if (downstream.cableId && state.passthroughFibres.length > 0) {
      const downstreamCable = ensureCableState(cableMap, downstream.cableId);
      pushUniqueText(downstreamCable.sourceDpIds, state.assetId);
      pushUniqueText(downstreamCable.sourceDpNames, state.assetName);
      mergeCableFibres(downstreamCable, {
        incomingFibres: state.passthroughFibres,
        passthroughFibres: state.passthroughFibres,
        usedFibreNumbers: state.passthroughFibres,
        inferredDownstream: downstream.inferred,
      });
    }

    if (dpWarnings.length && state.throughCableId) {
      const throughCable = ensureCableState(cableMap, state.throughCableId);
      mergeCableFibres(throughCable, { warnings: dpWarnings });
    }
  });

  return cableMap;
}

export function buildFibrePropagationState(args: {
  cableStates: Record<string, CableUsageState>;
  dpStates: Record<string, DpRoutingState>;
  graph?: NetworkGraph;
}): FibrePropagationState {
  const { cableStates, dpStates, graph } = args;
  const warnings: string[] = [];
  const propagatedCableFibres = buildPropagatedCableFibres({ graph, dpStates });

  const hops: FibrePropagationHop[] = Object.values(dpStates).map((state) => {
    const notes: string[] = [];
    const downstream = resolveDownstreamCableId({ graph, state });

    if (state.throughCableId && !cableStates[state.throughCableId]) {
      notes.push("Through cable is referenced but not present in computed cable state.");
    }

    if (downstream.cableId && !cableStates[downstream.cableId]) {
      notes.push("Downstream cable is referenced/inferred but not present in computed cable state.");
    }

    if (downstream.inferred) {
      notes.push(`Downstream cable inferred from topology: ${downstream.cableId}`);
    }

    notes.push(...downstream.warnings);
    notes.push(...state.warnings);
    warnings.push(...notes.map((note) => `${state.assetName}: ${note}`));

    return {
      assetId: state.assetId,
      assetName: state.assetName,
      assetType: assetTypeFromClosure(state.closureType),
      cableId: state.throughCableId,
      incomingFibres: state.inputFibres,
      consumedFibres: state.consumedFibres,
      passthroughFibres: state.passthroughFibres,
      spareFibres: state.spareFibres,
      notes,
    };
  });

  Object.values(cableStates).forEach((cableState) => {
    warnings.push(...cableState.warnings.map((warning) => `${cableState.assetName}: ${warning}`));
  });

  Object.values(propagatedCableFibres).forEach((cableState) => {
    warnings.push(...cableState.warnings.map((warning) => `${cableState.cableId}: ${warning}`));
  });

  return {
    cableStates,
    dpStates,
    propagatedCableFibres,
    hops,
    warnings: Array.from(new Set(warnings)),
  };
}
