// =====================================================
// FILE: src/services/network/networkState.ts
// PURPOSE: Single read-only computed network state for Phase 8C.
//          Storage remains the existing asset records/chunks; this file
//          computes operational state in memory only.
// =====================================================

import type {
  DpRoutingState,
  JointToDpFibreMatchState,
  JointCableOccupancyState,
  NetworkAsset,
  NetworkState,
  NetworkStateSummary,
} from "./types";
import { buildTopologyGraphState } from "./topologyGraph";
import { buildDpRoutingStates } from "./dpRoutingEngine";
import { buildCableUsageStates } from "./cableUsageEngine";
import { buildFibrePropagationState } from "./fibrePropagation";
import { buildJointToDpFibreMatchState } from "./jointToDpFibreMatcher";


function isReferenceInfrastructureAsset(asset: any): boolean {
  const haystack = [
    asset?.source,
    asset?.assetType,
    asset?.type,
    asset?.jointType,
    asset?.cableType,
    asset?.routeType,
    asset?.name,
    asset?.label,
    asset?.piaRef,
    asset?.piaKind,
    asset?.importedProperties?.Name,
    asset?.importedProperties?.name,
    asset?.importedProperties?.Description,
    asset?.importedProperties?.description,
  ]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();

  return (
    asset?.readOnly === true ||
    asset?.isReferenceAsset === true ||
    haystack.includes("openreach") ||
    haystack.includes("pia overlay") ||
    haystack.includes("pia route") ||
    haystack.includes("osp:") ||
    haystack.includes("pol:") ||
    haystack.includes("mp:") ||
    haystack.includes("jc:") ||
    haystack.includes("ch:") ||
    haystack.includes("chamber:") ||
    haystack.includes("missing pole")
  );
}

function uniqueSorted(values: unknown[]): number[] {
  return Array.from(
    new Set(
      values
        .map((value) => Number(value))
        .filter((value) => Number.isFinite(value) && value > 0),
    ),
  ).sort((a, b) => a - b);
}

function normaliseCableRef(value: unknown): string {
  return String(value ?? "")
    .trim()
    .toUpperCase()
    .replace(/[–—]/g, "-")
    .replace(/_/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}


function normaliseAssetRef(value: unknown): string {
  return String(value ?? "")
    .trim()
    .toUpperCase()
    .replace(/[–—]/g, "-")
    .replace(/[^A-Z0-9]/g, "");
}

function refsMatch(left: unknown, right: unknown): boolean {
  const a = normaliseAssetRef(left);
  const b = normaliseAssetRef(right);
  if (!a || !b) return false;
  return a === b || a.includes(b) || b.includes(a);
}

function getAssetName(asset: any): string {
  return String(
    asset?.name ||
      asset?.jointName ||
      asset?.label ||
      asset?.assetId ||
      asset?.id ||
      "",
  ).trim();
}

function getAssetIdentityKeys(asset: any): string[] {
  return [
    asset?.id,
    asset?.assetId,
    asset?.name,
    asset?.jointName,
    asset?.label,
    asset?.dpId,
  ]
    .map((value) => String(value ?? "").trim())
    .filter(Boolean);
}

function getHomeUniqueKey(asset: any): string {
  const raw =
    asset?.uprn ||
    asset?.UPRN ||
    asset?.properties?.UPRN ||
    asset?.properties?.uprn ||
    asset?.homeId ||
    asset?.connectedHomeId ||
    asset?.toHomeId ||
    asset?.id ||
    asset?.assetId ||
    asset?.name ||
    asset?.label;

  return normaliseAssetRef(raw);
}

function isDropCableAsset(asset: any): boolean {
  const text = [
    asset?.assetType,
    asset?.type,
    asset?.cableType,
    asset?.name,
    asset?.label,
    asset?.generatedBy,
  ]
    .map((value) => String(value ?? "").toLowerCase())
    .join(" ");

  return (
    asset?.geometry?.type === "LineString" &&
    (text.includes("drop") ||
      asset?.isDropCable === true ||
      asset?.isHomeDrop === true ||
      asset?.generatedDrop === true ||
      asset?.autoGeneratedDrop === true ||
      Boolean(asset?.homeId || asset?.connectedHomeId || asset?.toHomeId || asset?.fromHomeId))
  );
}

function isHomeAsset(asset: any): boolean {
  if (!asset || asset?.geometry?.type === "LineString" || isDropCableAsset(asset)) return false;

  const text = [
    asset?.assetType,
    asset?.type,
    asset?.homeType,
    asset?.name,
    asset?.label,
    asset?.category,
  ]
    .map((value) => String(value ?? "").toLowerCase())
    .join(" ");

  return (
    text.includes("home") ||
    text.includes("premise") ||
    text.includes("property") ||
    text.includes("sdu") ||
    text.includes("mdu") ||
    text.includes("flat") ||
    Boolean(asset?.uprn || asset?.UPRN || asset?.properties?.UPRN || asset?.properties?.uprn || asset?.homeId)
  );
}

function assetReferencesDp(asset: any, dpKeys: string[]): boolean {
  const candidates = [
    asset?.dpId,
    asset?.connectedDpId,
    asset?.assignedDpId,
    asset?.servingDpId,
    asset?.distributionPointId,
    asset?.parentDpId,
    asset?.fromDpId,
    asset?.toDpId,
    asset?.dpName,
    asset?.connectedDpName,
    asset?.assignedDpName,
    asset?.servingDpName,
    asset?.distributionPointName,
    asset?.splitterBox,
    asset?.splitterBoxName,
    asset?.sbName,
    asset?.properties?.dpId,
    asset?.properties?.connectedDpId,
    asset?.properties?.assignedDpId,
    asset?.properties?.servingDpId,
    asset?.properties?.distributionPointId,
    asset?.properties?.dpName,
    asset?.properties?.connectedDpName,
    asset?.properties?.assignedDpName,
    asset?.properties?.servingDpName,
    asset?.properties?.splitterBox,
    asset?.properties?.splitterBoxName,
    asset?.properties?.sbName,
  ].filter(Boolean);

  return candidates.some((candidate) => dpKeys.some((key) => refsMatch(candidate, key)));
}

function dropReferencesDp(drop: any, dpKeys: string[]): boolean {
  if (!isDropCableAsset(drop)) return false;

  const candidates = [
    drop?.fromAssetId,
    drop?.fromAssetName,
    drop?.fromDpId,
    drop?.fromDpName,
    drop?.dpId,
    drop?.dpName,
    drop?.connectedDpId,
    drop?.connectedDpName,
    drop?.parentDpId,
    drop?.parentDpName,
    drop?.sourceDpId,
    drop?.sourceDpName,
    drop?.name,
    drop?.label,
    drop?.properties?.fromAssetId,
    drop?.properties?.fromAssetName,
    drop?.properties?.fromDpId,
    drop?.properties?.fromDpName,
    drop?.properties?.dpId,
    drop?.properties?.dpName,
    drop?.properties?.connectedDpId,
    drop?.properties?.connectedDpName,
  ].filter(Boolean);

  return candidates.some((candidate) => dpKeys.some((key) => refsMatch(candidate, key)));
}

function getHomeKeyFromDrop(drop: any): string {
  const raw =
    drop?.homeId ||
    drop?.connectedHomeId ||
    drop?.toHomeId ||
    drop?.toAssetId ||
    drop?.uprn ||
    drop?.UPRN ||
    drop?.properties?.homeId ||
    drop?.properties?.connectedHomeId ||
    drop?.properties?.toHomeId ||
    drop?.properties?.toAssetId ||
    drop?.properties?.UPRN ||
    drop?.properties?.uprn ||
    drop?.name ||
    drop?.label ||
    drop?.id;

  return normaliseAssetRef(raw);
}

function getConnectedHomeCountForDp(args: {
  dpId: string;
  state: DpRoutingState;
  assets: NetworkAsset[];
}): number {
  const { dpId, state, assets } = args;
  const dpKeys = Array.from(
    new Set([dpId, state.assetId, state.assetName].map((value) => String(value ?? "").trim()).filter(Boolean)),
  );

  const homeKeys = new Set<string>();

  assets.forEach((asset: any) => {
    if (isHomeAsset(asset) && assetReferencesDp(asset, dpKeys)) {
      const key = getHomeUniqueKey(asset);
      if (key) homeKeys.add(key);
    }
  });

  // If homes do not carry a DP reference, generated drop cables usually do.
  // Count unique UPRNs/home IDs from drops as a fallback, but never allow
  // duplicate stale drop records to inflate the served-home count.
  assets.forEach((asset: any) => {
    if (dropReferencesDp(asset, dpKeys)) {
      const key = getHomeKeyFromDrop(asset);
      if (key) homeKeys.add(key);
    }
  });

  return homeKeys.size;
}

function requiredAfnSplitterFibreCount(connectedHomes: number, jointFibres: number[]): number {
  if (connectedHomes <= 0) return 0;
  if (!jointFibres.length) return 0;
  return Math.min(jointFibres.length, Math.max(1, Math.ceil(connectedHomes / 8)));
}

function getOccupancyForMatch(args: {
  match: NonNullable<JointToDpFibreMatchState["assignmentsByDpId"][string]>;
  jointToDpMatches: JointToDpFibreMatchState;
}): JointCableOccupancyState | null {
  const { match, jointToDpMatches } = args;
  const occupancies = Object.values(jointToDpMatches.cableOccupancyByCable || {});
  if (!occupancies.length) return null;

  const matchRefs = new Set(
    [...(match.sourceCableRefs || []), ...(match.targetCableRefs || [])]
      .map(normaliseCableRef)
      .filter(Boolean),
  );

  const candidates = occupancies.filter((occupancy) => {
    if (!occupancy.allocationsByDpId?.[match.dpId]) return false;
    if (!matchRefs.size) return true;
    return matchRefs.has(normaliseCableRef(occupancy.cableKey)) ||
      matchRefs.has(normaliseCableRef(occupancy.cableName));
  });

  return (
    candidates.sort(
      (a, b) =>
        b.highestAllocatedFibre - a.highestAllocatedFibre ||
        b.allocatedFibres.length - a.allocatedFibres.length,
    )[0] || null
  );
}

function buildSummary(state: Omit<NetworkState, "summary" | "warnings" | "generatedAt">): NetworkStateSummary {
  const cableStates = Object.values(state.cableStates);
  const dpStates = Object.values(state.dpStates);
  const disconnected = state.nodes.filter((node) => node.connectedTo.length === 0).length;

  return {
    nodes: state.nodes.length,
    edges: state.edges.length,
    dps: dpStates.length,
    cables: cableStates.filter((cable) => !cable.isDropCable).length,
    dropCables: cableStates.filter((cable) => cable.isDropCable).length,
    disconnected,
    usedFibres: cableStates.reduce((sum, cable) => sum + cable.usedFibres, 0),
    spareFibres: cableStates.reduce((sum, cable) => sum + cable.spareFibres.length, 0),
    passthroughFibres: dpStates.reduce((sum, dp) => sum + dp.passthroughFibres.length, 0),
    warnings: state.propagation.warnings.length + state.jointToDpMatches.warnings.length,
  };
}

function enrichDpStatesWithJointMatches(args: {
  dpStates: Record<string, DpRoutingState>;
  jointToDpMatches: JointToDpFibreMatchState;
  assets: NetworkAsset[];
}): Record<string, DpRoutingState> {
  const { dpStates, jointToDpMatches, assets } = args;

  return Object.entries(dpStates).reduce<Record<string, DpRoutingState>>((nextStates, [dpId, state]) => {
    const match = jointToDpMatches.assignmentsByDpId[dpId];
    const connectedHomes = getConnectedHomeCountForDp({ dpId, state, assets });

    if (!match || match.fibres.length === 0) {
      nextStates[dpId] = {
        ...state,
        connectedHomes,
        requiredSplitterFibres: state.closureType.includes("AFN")
          ? Math.max(0, Math.ceil(connectedHomes / 8))
          : undefined,
      };
      return nextStates;
    }

    // Joint rows are the source of truth for DP input fibres after the user
    // renames DPs to their SB IDs. Existing splitter/direct/passthrough intent
    // is preserved, but empty/cleared allocations now inherit the joint fibres.
    const jointFibres = uniqueSorted(match.fibres);
    const occupancy = getOccupancyForMatch({ match, jointToDpMatches });

    // IMPORTANT:
    // occupancy.allocatedFibres is the whole cable/run allocation, so on a
    // parent 144F run it can contain fibres for SB01, SB02, SB03, etc. Do not
    // feed that whole list into one DP/SB state or every child SB inherits the
    // parent cable usage and appears as 144F/135 used.
    // Use only this DP/SB's local allocation, falling back to the matched fibres.
    const localAllocation = occupancy?.allocationsByDpId?.[match.dpId];
    const jointAllocatedFibresOnCable = uniqueSorted(
      localAllocation?.fibres?.length ? localAllocation.fibres : jointFibres,
    );
    const localMinFibre = jointFibres.length ? Math.min(...jointFibres) : null;
    const localMaxFibre = jointFibres.length ? Math.max(...jointFibres) : null;
    const highestJointAllocatedFibre = jointAllocatedFibresOnCable.length
      ? Math.max(...jointAllocatedFibresOnCable)
      : 0;
    const jointPassthroughFibres = localMinFibre !== null
      ? jointAllocatedFibresOnCable.filter((fibre) => fibre < localMinFibre)
      : [];
    const jointAllocatedElsewhereFibres = localMaxFibre !== null
      ? jointAllocatedFibresOnCable.filter(
          (fibre) => fibre > localMaxFibre && !jointFibres.includes(fibre),
        )
      : [];
    const nextInputFibres = jointFibres;
    const isAfn = state.closureType.includes("AFN");
    const isMdu = state.closureType.includes("MDU");
    const isCbt = state.closureType.includes("CBT");

    // Joint/SB matched fibres are the source of truth for the incoming feed.
    // IMPORTANT: an AFN/SB must NOT treat every matched fibre as a splitter input.
    // A 1:8 splitter input fibre serves up to 8 homes. Any extra matched fibres
    // are passthrough/branch fibres for downstream SBs or 12F shoot-off cables.
    const requiredSplitterFibres = isAfn
      ? requiredAfnSplitterFibreCount(connectedHomes, jointFibres)
      : undefined;

    const autoSplitterFibres = isAfn
      ? jointFibres.slice(0, requiredSplitterFibres || 0)
      : state.splitterFibres;

    const autoPassthroughFibres = isAfn
      ? jointFibres.slice(requiredSplitterFibres || 0)
      : [];

    const nextSplitterFibres = isAfn
      ? autoSplitterFibres
      : state.splitterFibres.length > 0
        ? state.splitterFibres
        : state.splitterFibres;

    const nextDirectFibres = state.directFibres.length > 0
      ? state.directFibres
      : isCbt || isMdu
        ? jointFibres
        : state.directFibres;

    const nextPassthroughFibres = isAfn
      ? uniqueSorted(autoPassthroughFibres)
      : uniqueSorted([
          ...state.passthroughFibres,
          ...autoPassthroughFibres,
        ]);

    const nextConsumedFibres = uniqueSorted([...nextSplitterFibres, ...nextDirectFibres]);
    const nextUsedFibres = uniqueSorted([
      ...nextInputFibres,
      ...nextConsumedFibres,
      ...nextPassthroughFibres,
    ]);

    const nextCapacity = isAfn
      ? nextSplitterFibres.length * 8
      : state.capacity;

    nextStates[dpId] = {
      ...state,
      capacity: nextCapacity,
      connectedHomes,
      requiredSplitterFibres,
      inputFibres: nextInputFibres,
      splitterFibres: nextSplitterFibres,
      directFibres: nextDirectFibres,
      passthroughFibres: nextPassthroughFibres,
      consumedFibres: nextConsumedFibres,
      usedFibres: nextUsedFibres,
      jointMatchedFibres: jointFibres,
      jointPassthroughFibres: uniqueSorted([...jointPassthroughFibres, ...autoPassthroughFibres]),
      jointAllocatedElsewhereFibres,
      jointTrueSpareFibres: [],
      jointHighestAllocatedFibre: highestJointAllocatedFibre,
      jointCableKey: occupancy?.cableKey,
      jointCableName: occupancy?.cableName,
      jointCableOccupancy: occupancy || undefined,
      jointMatchSource: match.source,
      jointMatch: match,
      warnings: Array.from(
        new Set([
          ...state.warnings,
          ...match.warnings,
        ]),
      ),
    };

    return nextStates;
  }, {});
}

export function buildNetworkState(assets: NetworkAsset[] = []): NetworkState {
  const operationalAssets = (assets || []).filter((asset) => !isReferenceInfrastructureAsset(asset));

  const topology = buildTopologyGraphState(operationalAssets);
  const baseDpStates = buildDpRoutingStates(operationalAssets);
  const jointToDpMatches = buildJointToDpFibreMatchState(operationalAssets);
  const dpStates = enrichDpStatesWithJointMatches({
    dpStates: baseDpStates,
    jointToDpMatches,
    assets: operationalAssets,
  });

  // First pass: build cable state from saved records + direct DP routing.
  // This gives propagation enough cable metadata to validate references.
  const baseCableStates = buildCableUsageStates({
    assets: operationalAssets,
    graph: topology.graph,
    dpStates,
  });

  // Propagation pass: calculate what fibres continue downstream from each DP.
  const basePropagation = buildFibrePropagationState({
    cableStates: baseCableStates,
    dpStates,
    graph: topology.graph,
  });

  // Final pass: feed propagated cable fibres back into cable utilisation.
  const cableStates = buildCableUsageStates({
    assets: operationalAssets,
    graph: topology.graph,
    dpStates,
    propagatedCableFibres: basePropagation.propagatedCableFibres,
  });

  const propagation = buildFibrePropagationState({
    cableStates,
    dpStates,
    graph: topology.graph,
  });

  const baseState: Omit<NetworkState, "summary" | "warnings" | "generatedAt"> = {
    assets: operationalAssets,
    graph: topology.graph,
    nodes: topology.nodes,
    edges: topology.edges,
    dpStates,
    cableStates,
    propagation,
    jointToDpMatches,
  };

  const warnings = Array.from(new Set([...propagation.warnings, ...jointToDpMatches.warnings]));

  return {
    ...baseState,
    summary: buildSummary(baseState),
    warnings,
    generatedAt: new Date().toISOString(),
  };
}
