import type { SavedMapAsset } from "../components/map/types";

type Point = { lat: number; lng: number };

export type DpThroughCableResolution = {
  cable: SavedMapAsset | null;
  source: "saved" | "saved-parent" | "branch-parent" | "nearest" | "none";
  branchCable: SavedMapAsset | null;
};

export function text(value: unknown): string {
  return String(value ?? "").trim();
}

export function normaliseRef(value: unknown): string {
  return text(value)
    .toUpperCase()
    .replace(/[–—]/g, "-")
    .replace(/[^A-Z0-9]/g, "");
}

export function refsMatch(a: unknown, b: unknown): boolean {
  const left = normaliseRef(a);
  const right = normaliseRef(b);
  if (!left || !right) return false;
  return left === right || left.includes(right) || right.includes(left);
}

export function uniqueSortedNumbers(values: unknown[]): number[] {
  return Array.from(
    new Set(
      values
        .map((value) => Number(value))
        .filter((value) => Number.isFinite(value) && value > 0),
    ),
  ).sort((a, b) => a - b);
}

export function removeUndefinedDeep<T>(value: T): T {
  if (Array.isArray(value)) {
    return value.map((entry) => removeUndefinedDeep(entry)) as T;
  }

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>)
        .filter(([, entry]) => entry !== undefined)
        .map(([key, entry]) => [key, removeUndefinedDeep(entry)]),
    ) as T;
  }

  return value;
}

export function getAssetTitle(asset: SavedMapAsset | null | undefined): string {
  const item = asset as any;
  return text(
    item?.name ||
      item?.jointName ||
      item?.label ||
      item?.assetId ||
      item?.cableId ||
      item?.cableName ||
      item?.id ||
      "Asset",
  );
}

export function getCableFibreCount(asset: SavedMapAsset | null | undefined): number {
  const item = asset as any;
  if (!item) return 0;

  const haystack = [
    item.fibreCount,
    item.fiberCount,
    item.coreCount,
    item.size,
    item.cableSize,
    item.name,
    item.cableId,
    item.cableName,
    item.label,
  ]
    .map(text)
    .filter(Boolean)
    .join(" ");

  const match = haystack.match(/(?:^|[^0-9])(288|144|96|48|36|24|12)\s*F?(?:[^0-9]|$)/i);
  return match ? Number(match[1]) : 0;
}

export function getCableDisplaySize(asset: SavedMapAsset | null | undefined): string {
  const count = getCableFibreCount(asset);
  return count > 0 ? `${count}F` : "Unknown size";
}

export function getAssetPoint(asset: SavedMapAsset | null | undefined): Point | null {
  const item = asset as any;
  if (!item) return null;

  if (typeof item.lat === "number" && typeof item.lng === "number") {
    return { lat: item.lat, lng: item.lng };
  }

  const coords = item.geometry?.coordinates;
  if (item.geometry?.type === "Point" && Array.isArray(coords)) {
    const lat = Number(coords[0]);
    const lng = Number(coords[1]);
    if (Number.isFinite(lat) && Number.isFinite(lng)) return { lat, lng };
  }

  return null;
}

export function getCableLinePoints(asset: SavedMapAsset | null | undefined): Point[] {
  const coords = (asset as any)?.geometry?.coordinates;
  if ((asset as any)?.geometry?.type !== "LineString" || !Array.isArray(coords)) return [];

  return coords
    .map((coord: any) => ({ lat: Number(coord?.[0]), lng: Number(coord?.[1]) }))
    .filter((point: Point) => Number.isFinite(point.lat) && Number.isFinite(point.lng));
}

export function distanceMeters(a: Point, b: Point): number {
  const radius = 6371000;
  const toRad = (value: number) => (value * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * radius * Math.asin(Math.sqrt(h));
}

export function isDropCableAsset(asset: SavedMapAsset | null | undefined): boolean {
  if (!asset) return false;
  const item = asset as any;
  const haystack = [
    item.assetType,
    item.type,
    item.cableType,
    item.name,
    item.label,
    item.generatedBy,
  ]
    .map((value) => text(value).toLowerCase())
    .join(" ");

  return Boolean(
    asset.geometry?.type === "LineString" &&
      (haystack.includes("drop") ||
        item.isDropCable === true ||
        item.isHomeDrop === true ||
        item.generatedDrop === true ||
        item.autoGeneratedDrop === true ||
        item.dropCable === true ||
        item.homeId ||
        item.connectedHomeId ||
        item.toHomeId ||
        item.fromHomeId),
  );
}

export function isSupportingCableAsset(asset: SavedMapAsset | null | undefined): boolean {
  if (!asset) return false;
  if (asset.geometry?.type !== "LineString") return false;
  if (isDropCableAsset(asset)) return false;

  const item = asset as any;
  const haystack = [
    item.source,
    item.assetType,
    item.type,
    item.cableType,
    item.routeType,
    item.jointType,
    item.name,
    item.label,
    item.cableId,
    item.notes,
    item.importedProperties?.Name,
    item.importedProperties?.name,
    item.importedProperties?.Description,
    item.importedProperties?.description,
  ]
    .map((value) => text(value).toLowerCase())
    .join(" ");

  if (item.readOnly === true || item.isReferenceAsset === true) return false;
  if (
    haystack.includes("openreach") ||
    haystack.includes("pia") ||
    haystack.includes("osp:") ||
    haystack.includes("pol:") ||
    haystack.includes("mp:") ||
    haystack.includes("jc:") ||
    haystack.includes("ch:") ||
    haystack.includes("missing duct") ||
    haystack.includes("suggested duct")
  ) {
    return false;
  }

  return (
    haystack.includes("cable") ||
    haystack.includes("ulw") ||
    haystack.includes("feeder") ||
    haystack.includes("link") ||
    haystack.includes("distribution") ||
    haystack.includes("spine") ||
    getCableFibreCount(asset) > 0
  );
}

export function findCableByReference(
  allAssets: SavedMapAsset[],
  reference: unknown,
): SavedMapAsset | null {
  if (!text(reference) || text(reference) === "No through cable selected") return null;

  return (
    allAssets.find((candidate: any) =>
      isSupportingCableAsset(candidate) &&
      [
        candidate.id,
        candidate.assetId,
        candidate.name,
        candidate.cableId,
        candidate.cableName,
        candidate.label,
      ]
        .filter(Boolean)
        .some((ref) => refsMatch(ref, reference)),
    ) || null
  );
}

export function findParentCableForBranchCable(
  branchCable: SavedMapAsset | null | undefined,
  allAssets: SavedMapAsset[],
): SavedMapAsset | null {
  const item = branchCable as any;
  if (!branchCable) return null;

  const parentRefs = [
    item.parentCableId,
    item.parentCableName,
    item.parentCable,
    item.upstreamCableId,
    item.upstreamCableName,
    item.sourceCableId,
    item.sourceCableName,
  ].filter(Boolean);

  for (const ref of parentRefs) {
    const parent = findCableByReference(allAssets, ref);
    if (parent && parent.id !== branchCable.id) return parent;
  }

  return null;
}

export function cableEndpointDistanceToPoint(
  cable: SavedMapAsset | null | undefined,
  point: Point | null,
): number {
  if (!cable || !point) return Number.POSITIVE_INFINITY;
  const line = getCableLinePoints(cable);
  if (line.length < 2) return Number.POSITIVE_INFINITY;
  return Math.min(distanceMeters(point, line[0]), distanceMeters(point, line[line.length - 1]));
}

function findBranchParentThroughCableForDp(
  dp: SavedMapAsset | null | undefined,
  allAssets: SavedMapAsset[],
): { parent: SavedMapAsset | null; branch: SavedMapAsset | null } {
  const point = getAssetPoint(dp);
  if (!dp || !point) return { parent: null, branch: null };

  const nearbyBranchCables = allAssets
    .filter(isSupportingCableAsset)
    .map((candidate) => ({
      candidate,
      endpointDistance: cableEndpointDistanceToPoint(candidate, point),
      fibreCount: getCableFibreCount(candidate),
      parentCable: findParentCableForBranchCable(candidate, allAssets),
    }))
    .filter((entry) => entry.parentCable && entry.endpointDistance <= 35)
    .sort((a, b) => {
      const aIsSmallBranch = a.fibreCount > 0 && a.fibreCount <= 24 ? 0 : 1;
      const bIsSmallBranch = b.fibreCount > 0 && b.fibreCount <= 24 ? 0 : 1;
      return aIsSmallBranch - bIsSmallBranch || a.endpointDistance - b.endpointDistance;
    });

  const match = nearbyBranchCables[0];
  return { parent: match?.parentCable || null, branch: match?.candidate || null };
}

function findNearestThroughCableForDp(
  dp: SavedMapAsset | null | undefined,
  allAssets: SavedMapAsset[],
): SavedMapAsset | null {
  const point = getAssetPoint(dp);
  if (!dp || !point) return null;

  const candidates = allAssets
    .filter(isSupportingCableAsset)
    .map((candidate) => ({
      candidate,
      endpointDistance: cableEndpointDistanceToPoint(candidate, point),
      fibreCount: getCableFibreCount(candidate),
    }))
    .filter((entry) => entry.endpointDistance <= 28)
    .sort((a, b) => b.fibreCount - a.fibreCount || a.endpointDistance - b.endpointDistance);

  return candidates[0]?.candidate || null;
}

export function resolveDpThroughCable(
  dp: SavedMapAsset | null | undefined,
  allAssets: SavedMapAsset[] = [],
  savedCableReference?: unknown,
): DpThroughCableResolution {
  if (!dp) return { cable: null, source: "none", branchCable: null };

  const item = dp as any;
  const details = item.dpDetails || item.properties?.dpDetails || {};
  const afn = details.afnDetails || item.afnDetails || {};
  const mdu = details.mduDetails || item.mduDetails || {};
  const savedRef = text(
    savedCableReference ||
      afn.throughCableId ||
      afn.supportingCableId ||
      afn.cableId ||
      mdu.throughCableId ||
      details.throughCableId ||
      item.throughCableId ||
      item.parentCableId ||
      item.feedCableId,
  );

  const savedCable = findCableByReference(allAssets, savedRef);
  if (savedCable) {
    const savedParent = findParentCableForBranchCable(savedCable, allAssets);
    if (savedParent && getCableFibreCount(savedCable) <= 24) {
      return { cable: savedParent, source: "saved-parent", branchCable: savedCable };
    }
    return { cable: savedCable, source: "saved", branchCable: null };
  }

  const branch = findBranchParentThroughCableForDp(dp, allAssets);
  if (branch.parent) {
    return { cable: branch.parent, source: "branch-parent", branchCable: branch.branch };
  }

  const nearest = findNearestThroughCableForDp(dp, allAssets);
  if (nearest) return { cable: nearest, source: "nearest", branchCable: null };

  return { cable: null, source: "none", branchCable: null };
}

export function buildDpFibreIntakeSummary(args: {
  incomingCable: SavedMapAsset | null | undefined;
  splitterFibres?: unknown[];
  directFibres?: unknown[];
  spliceFibres?: unknown[];
  passthroughFibres?: unknown[];
  spareFibres?: unknown[];
  fallbackUsedFibres?: unknown;
  hasDownstreamCable?: boolean;
}) {
  const incomingFibreCount = getCableFibreCount(args.incomingCable);
  const localUsedFibres = uniqueSortedNumbers([
    ...(args.splitterFibres || []),
    ...(args.directFibres || []),
    ...(args.spliceFibres || []),
  ]);
  const fallbackUsed = Number(args.fallbackUsedFibres || 0);
  const usedAtThisDp = localUsedFibres.length || (Number.isFinite(fallbackUsed) && fallbackUsed > 0 ? fallbackUsed : 0);
  const safeUsedAtThisDp = incomingFibreCount > 0 ? Math.min(usedAtThisDp, incomingFibreCount) : usedAtThisDp;
  const rawPassthrough = uniqueSortedNumbers(args.passthroughFibres || []);
  const passthroughCount = incomingFibreCount > 0
    ? Math.max(incomingFibreCount - safeUsedAtThisDp, 0)
    : rawPassthrough.length;
  const spareCount = args.hasDownstreamCable
    ? uniqueSortedNumbers(args.spareFibres || []).length
    : incomingFibreCount > 0
      ? Math.max(incomingFibreCount - safeUsedAtThisDp, 0)
      : uniqueSortedNumbers(args.spareFibres || []).length;

  return {
    incomingFibreCount,
    incomingFibreLabel: incomingFibreCount > 0 ? `${incomingFibreCount}F` : "Unknown",
    usedAtThisDp: safeUsedAtThisDp,
    passthroughCount,
    spareCount,
    localUsedFibres,
  };
}
