// =====================================================
// FILE: dpFibreAutoAllocator.ts
// PURPOSE: Automatic AFN / MDU fibre reservation on through-cable runs.
//
// IMPORTANT:
// - Does NOT save to Firestore.
// - Does NOT change drop-cable generation.
// - Does NOT change cable route drawing.
// - Does NOT reserve a full branch cable size automatically.
//   Branches only reserve the fibres actually needed by downstream
//   AFN / MDU / MDU_SPLITTER assets on that branch.
// =====================================================

import type { DpFibrePlan } from "./dpArchitecturePlanner";
import type {
  DistributionArchitecture,
  SavedMapAsset,
} from "../components/map/types";

type LatLng = { lat: number; lng: number };

type CableProjection = {
  distanceToCableMeters: number;
  distanceAlongCableMeters: number;
};

export type DpFibreAllocationTraceRow = {
  assetId?: string;
  assetName: string;
  cableId?: string;
  cableName: string;
  localFibres: number;
  branchFibres: number;
  totalFibres: number;
  note: string;
};

export type DpFibreAllocationExplanationRow = {
  label: string;
  value: string | number;
  help: string;
};

export type DpFibreAutoAllocation = {
  throughCableId?: string;
  throughCableName?: string;
  fibreTotal: number;
  inputFibres: number[];
  localReservedFibres: number;
  branchReservedFibres: number;
  downstreamReservedFibres: number;
  totalReservedFibres: number;
  startFibre: number;
  endFibre: number;
  freeFibresAfterAllocation: number;
  utilisationPercent: number;
  duplicateFibres: number[];
  conflictingReservations: string[];
  explanationRows: DpFibreAllocationExplanationRow[];
  traceRows: DpFibreAllocationTraceRow[];
  branchNotes: string[];
  warnings: string[];
};

type AllocateDpFibresInput = {
  currentDpId?: string | null;
  currentClosureType?: DistributionArchitecture | string | null;
  currentDpDetails?: any;
  connectedHomes: number;
  plan: DpFibrePlan;
  selectedThroughCableId?: string | null;
  availableThroughCables?: SavedMapAsset[];
  allDistributionPoints?: SavedMapAsset[];
  allAssets?: SavedMapAsset[];
  snapToleranceMeters?: number;
};

function normaliseText(value: unknown): string {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[\s_/-]+/g, " ");
}

function normaliseArchitecture(value: unknown): DistributionArchitecture {
  const raw = String(value || "CBT").toUpperCase();
  if (raw === "AFN") return "AFN";
  if (raw === "MDU") return "MDU";
  if (raw === "MDU_SPLITTER") return "MDU_SPLITTER";
  return "CBT";
}

function isPassthroughArchitecture(value: unknown): boolean {
  return normaliseArchitecture(value) !== "CBT";
}

function parseFibreTotal(asset: any, fallback = 48): number {
  const candidates = [
    asset?.fibreCount,
    asset?.fiberCount,
    asset?.size,
    asset?.cableSize,
    asset?.name,
    asset?.label,
  ];
  for (const candidate of candidates) {
    const match = String(candidate ?? "")
      .toUpperCase()
      .match(/(288|144|96|48|36|24|12)\s*F?/);
    if (match) return Number(match[1]);
  }
  return fallback;
}

function getAssetName(asset: any): string {
  return String(
    asset?.name || asset?.cableId || asset?.label || asset?.id || "Asset",
  );
}

function isCableAsset(asset: any): boolean {
  const text = normaliseText(
    asset?.assetType ||
      asset?.type ||
      asset?.jointType ||
      asset?.cableType ||
      asset?.name,
  );
  return (
    asset?.geometry?.type === "LineString" ||
    text.includes("cable") ||
    text.includes("ulw") ||
    text.includes("feeder") ||
    text.includes("link")
  );
}

function isDropCableAsset(asset: any): boolean {
  const text = normaliseText(
    asset?.assetType ||
      asset?.type ||
      asset?.cableType ||
      asset?.name ||
      asset?.generatedBy,
  );
  return (
    text.includes("drop") ||
    asset?.isDropCable === true ||
    asset?.autoGeneratedDrop === true ||
    Boolean(
      asset?.homeId ||
      asset?.connectedHomeId ||
      asset?.toHomeId ||
      asset?.fromHomeId,
    )
  );
}

function getPoint(asset: any): LatLng | null {
  if (typeof asset?.lat === "number" && typeof asset?.lng === "number") {
    return { lat: asset.lat, lng: asset.lng };
  }
  const coords = asset?.geometry?.coordinates;
  if (asset?.geometry?.type === "Point" && Array.isArray(coords)) {
    const lat = Number(coords[0]);
    const lng = Number(coords[1]);
    if (Number.isFinite(lat) && Number.isFinite(lng)) return { lat, lng };
  }
  return null;
}

function getLine(asset: any): LatLng[] {
  const coords = asset?.geometry?.coordinates;
  if (asset?.geometry?.type !== "LineString" || !Array.isArray(coords))
    return [];
  return coords
    .map((coord: any) => ({ lat: Number(coord?.[0]), lng: Number(coord?.[1]) }))
    .filter(
      (point: LatLng) =>
        Number.isFinite(point.lat) && Number.isFinite(point.lng),
    );
}

function toRad(value: number): number {
  return (value * Math.PI) / 180;
}

function distanceMeters(a: LatLng, b: LatLng): number {
  const radius = 6371000;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * radius * Math.asin(Math.sqrt(h));
}

function segmentProjection(
  point: LatLng,
  start: LatLng,
  end: LatLng,
): { distanceMeters: number; ratio: number } {
  const midLat = ((point.lat + start.lat + end.lat) / 3) * (Math.PI / 180);
  const toXY = (p: LatLng) => ({
    x: p.lng * 111320 * Math.cos(midLat),
    y: p.lat * 111320,
  });

  const p = toXY(point);
  const a = toXY(start);
  const b = toXY(end);
  const dx = b.x - a.x;
  const dy = b.y - a.y;
  const lenSq = dx * dx + dy * dy;

  if (lenSq <= 0) {
    return {
      distanceMeters: Math.sqrt((p.x - a.x) ** 2 + (p.y - a.y) ** 2),
      ratio: 0,
    };
  }

  const ratio = Math.max(
    0,
    Math.min(1, ((p.x - a.x) * dx + (p.y - a.y) * dy) / lenSq),
  );
  const projected = { x: a.x + ratio * dx, y: a.y + ratio * dy };
  return {
    distanceMeters: Math.sqrt(
      (p.x - projected.x) ** 2 + (p.y - projected.y) ** 2,
    ),
    ratio,
  };
}

function projectPointOnCable(
  point: LatLng,
  cable: SavedMapAsset,
): CableProjection | null {
  const line = getLine(cable);
  if (line.length < 2) return null;

  let travelled = 0;
  let best: CableProjection | null = null;

  for (let index = 1; index < line.length; index += 1) {
    const start = line[index - 1];
    const end = line[index];
    const segmentLength = distanceMeters(start, end);
    const projection = segmentProjection(point, start, end);
    const candidate: CableProjection = {
      distanceToCableMeters: projection.distanceMeters,
      distanceAlongCableMeters: travelled + segmentLength * projection.ratio,
    };

    if (!best || candidate.distanceToCableMeters < best.distanceToCableMeters) {
      best = candidate;
    }

    travelled += segmentLength;
  }

  return best;
}

function getDpThroughCableId(asset: any): string {
  const details = asset?.dpDetails || {};
  return String(
    details?.afnDetails?.throughCableId ||
      details?.mduDetails?.throughCableId ||
      asset?.parentCableId ||
      "",
  );
}

function getDpArchitecture(asset: any): DistributionArchitecture {
  return normaliseArchitecture(
    asset?.dpDetails?.closureType ||
      asset?.dpDetails?.networkArchitecture ||
      asset?.closureType,
  );
}

function getExplicitMduReservedFibres(details: any, architecture: DistributionArchitecture): number {
  const existing = details?.mduDetails || {};

  const totalReserved = Number(existing?.totalReservedFibres);
  if (Number.isFinite(totalReserved) && totalReserved > 0) {
    return Math.floor(totalReserved);
  }

  const selectedCount = Array.isArray(existing?.inputFibres)
    ? existing.inputFibres.length
    : 0;
  if (selectedCount > 0) return selectedCount;

  const direct = Number(existing?.mduFibres || 0);
  const splitter =
    architecture === "MDU_SPLITTER"
      ? Number(existing?.splitterFibres || 0)
      : 0;

  if (Number.isFinite(direct + splitter) && direct + splitter > 0) {
    return Math.floor(direct + splitter);
  }

  // Safe default: MDU buildings reserve a fixed building feed.
  // Connected flats are internal outputs and must not inflate external fibre demand.
  return architecture === "MDU_SPLITTER" ? 8 : 6;
}

function countConnectedHomesFromDrops(
  dpId: string,
  allAssets: SavedMapAsset[],
): number {
  const seen = new Set<string>();

  allAssets.forEach((asset: any) => {
    if (!isDropCableAsset(asset)) return;
    const linkedDp = String(
      asset?.dpId ||
        asset?.fromAssetId ||
        asset?.toAssetId ||
        asset?.parentDpId ||
        "",
    );
    if (linkedDp !== dpId) return;
    const homeKey = String(
      asset?.homeId ||
        asset?.connectedHomeId ||
        asset?.toHomeId ||
        asset?.uprn ||
        asset?.UPRN ||
        asset?.id ||
        "",
    );
    if (homeKey) seen.add(homeKey);
  });

  return seen.size;
}

function getLocalReservedFibres(
  asset: SavedMapAsset,
  allAssets: SavedMapAsset[],
  currentOverride?: {
    dpId?: string | null;
    connectedHomes: number;
    plan: DpFibrePlan;
  },
): number {
  const dpId = String(asset?.id || "");
  if (currentOverride?.dpId && dpId === String(currentOverride.dpId)) {
    return Math.max(
      0,
      Math.floor(currentOverride.plan.requiredInputFibres || 0),
    );
  }

  const details = (asset as any)?.dpDetails || {};
  const architecture = getDpArchitecture(asset);
  const autoPlanReserved = Number(details?.autoFibrePlan?.requiredInputFibres);
  if (Number.isFinite(autoPlanReserved) && autoPlanReserved > 0)
    return Math.floor(autoPlanReserved);

  if (architecture === "AFN") {
    const existingCount = Array.isArray(details?.afnDetails?.inputFibres)
      ? details.afnDetails.inputFibres.length
      : 0;
    if (existingCount > 0) return existingCount;
    const connectedHomes = Number(
      details?.autoFibrePlan?.connectedHomes ||
        countConnectedHomesFromDrops(dpId, allAssets) ||
        0,
    );
    return connectedHomes > 0 ? Math.ceil(connectedHomes / 8) : 0;
  }

  if (architecture === "MDU" || architecture === "MDU_SPLITTER") {
    return getExplicitMduReservedFibres(details, architecture);
  }

  return 0;
}

function findCandidateThroughCables(
  input: AllocateDpFibresInput,
): SavedMapAsset[] {
  const byId = new Map<string, SavedMapAsset>();
  [...(input.availableThroughCables || []), ...(input.allAssets || [])].forEach(
    (asset) => {
      if (!asset?.id) return;
      if (!isCableAsset(asset)) return;
      if (isDropCableAsset(asset)) return;
      if (getLine(asset).length < 2) return;
      byId.set(String(asset.id), asset);
    },
  );
  return Array.from(byId.values());
}

function findCurrentDp(input: AllocateDpFibresInput): SavedMapAsset | null {
  const currentId = String(input.currentDpId || "");
  if (!currentId) return null;
  return (
    (input.allDistributionPoints || []).find(
      (asset) => String(asset?.id || "") === currentId,
    ) ||
    (input.allAssets || []).find(
      (asset) => String(asset?.id || "") === currentId,
    ) ||
    null
  );
}

function findCableForDp(
  input: AllocateDpFibresInput,
  currentDp: SavedMapAsset | null,
): {
  cable: SavedMapAsset | null;
  projection: CableProjection | null;
  warnings: string[];
} {
  const warnings: string[] = [];
  const candidateCables = findCandidateThroughCables(input);
  const selectedId = String(input.selectedThroughCableId || "");

  if (selectedId) {
    const selected =
      candidateCables.find((cable) => String(cable.id) === selectedId) || null;
    if (selected) {
      const point = currentDp ? getPoint(currentDp) : null;
      return {
        cable: selected,
        projection: point ? projectPointOnCable(point, selected) : null,
        warnings,
      };
    }
    warnings.push(
      "Selected through cable could not be found in the current asset list.",
    );
  }

  const dpPoint = currentDp ? getPoint(currentDp) : null;
  if (!dpPoint) {
    warnings.push(
      "Could not auto-select a through cable because this DP has no map position.",
    );
    return { cable: null, projection: null, warnings };
  }

  const tolerance = input.snapToleranceMeters ?? 18;
  const nearest = candidateCables
    .map((cable) => ({
      cable,
      projection: projectPointOnCable(dpPoint, cable),
    }))
    .filter(
      (entry): entry is { cable: SavedMapAsset; projection: CableProjection } =>
        Boolean(entry.projection),
    )
    .filter((entry) => entry.projection.distanceToCableMeters <= tolerance)
    .sort(
      (a, b) =>
        a.projection.distanceToCableMeters - b.projection.distanceToCableMeters,
    )[0];

  if (!nearest) {
    warnings.push(
      `Could not auto-select a through cable within ${tolerance}m of this DP.`,
    );
    return { cable: null, projection: null, warnings };
  }

  return { cable: nearest.cable, projection: nearest.projection, warnings };
}

function getDpsOnCable(
  cable: SavedMapAsset,
  allDistributionPoints: SavedMapAsset[],
  toleranceMeters: number,
): { asset: SavedMapAsset; projection: CableProjection }[] {
  return allDistributionPoints
    .map((asset) => {
      const point = getPoint(asset);
      const projection = point ? projectPointOnCable(point, cable) : null;
      if (!projection) return null;
      return { asset, projection };
    })
    .filter(
      (entry): entry is { asset: SavedMapAsset; projection: CableProjection } =>
        Boolean(entry),
    )
    .filter(
      (entry) => entry.projection.distanceToCableMeters <= toleranceMeters,
    )
    .sort(
      (a, b) =>
        a.projection.distanceAlongCableMeters -
        b.projection.distanceAlongCableMeters,
    );
}

function getCableEndpointDistanceToDp(
  cable: SavedMapAsset,
  dpPoint: LatLng,
): number {
  const line = getLine(cable);
  if (line.length < 2) return Number.POSITIVE_INFINITY;
  return Math.min(
    distanceMeters(line[0], dpPoint),
    distanceMeters(line[line.length - 1], dpPoint),
  );
}

function getBranchCablesAtDp(
  dp: SavedMapAsset,
  parentCableId: string,
  allAssets: SavedMapAsset[],
  toleranceMeters: number,
): SavedMapAsset[] {
  const point = getPoint(dp);
  if (!point) return [];

  return allAssets.filter((asset) => {
    if (!asset?.id || String(asset.id) === parentCableId) return false;
    if (!isCableAsset(asset) || isDropCableAsset(asset)) return false;

    // Explicit parentCableId wins when older saved cable records have it.
    if (String((asset as any).parentCableId || "") === parentCableId) {
      return getCableEndpointDistanceToDp(asset, point) <= toleranceMeters;
    }

    return getCableEndpointDistanceToDp(asset, point) <= toleranceMeters;
  });
}

function getCableDemand(input: {
  cable: SavedMapAsset;
  originDpId?: string;
  allDistributionPoints: SavedMapAsset[];
  allAssets: SavedMapAsset[];
  toleranceMeters: number;
  currentOverride: {
    dpId?: string | null;
    connectedHomes: number;
    plan: DpFibrePlan;
  };
  visitedCableIds: Set<string>;
  branchNotes: string[];
  traceRows?: DpFibreAllocationTraceRow[];
}): number {
  const cableId = String(input.cable.id || "");
  if (!cableId || input.visitedCableIds.has(cableId)) return 0;
  input.visitedCableIds.add(cableId);

  const dpsOnCable = getDpsOnCable(
    input.cable,
    input.allDistributionPoints,
    input.toleranceMeters,
  )
    .filter(
      (entry) =>
        String(entry.asset.id || "") !== String(input.originDpId || ""),
    )
    .filter((entry) =>
      isPassthroughArchitecture(getDpArchitecture(entry.asset)),
    );

  let total = 0;

  dpsOnCable.forEach(({ asset }) => {
    const local = getLocalReservedFibres(
      asset,
      input.allAssets,
      input.currentOverride,
    );
    const branches = getBranchCablesAtDp(
      asset,
      cableId,
      input.allAssets,
      input.toleranceMeters,
    );
    const branchDemand = branches.reduce(
      (sum, branchCable) =>
        sum +
        getCableDemand({
          ...input,
          cable: branchCable,
          originDpId: String(asset.id || ""),
          visitedCableIds: new Set(input.visitedCableIds),
        }),
      0,
    );
    const demand = local + branchDemand;
    if (demand > 0) {
      const parentDp = input.originDpId
        ? input.allDistributionPoints.find(
            (candidate) => String(candidate.id || "") === String(input.originDpId || ""),
          )
        : null;
      const relationshipLabel = parentDp
        ? `${getAssetName(parentDp)} → ${getAssetName(asset)}`
        : getAssetName(asset);

      input.branchNotes.push(
        `${relationshipLabel}: ${demand} fibre(s) needed${branchDemand ? ` (${branchDemand} from downstream branches)` : ""}.`,
      );
      input.traceRows?.push({
        assetId: String(asset.id || ""),
        assetName: getAssetName(asset),
        cableId,
        cableName: getAssetName(input.cable),
        localFibres: local,
        branchFibres: branchDemand,
        totalFibres: demand,
        note: branchDemand
          ? `${relationshipLabel}: ${branchDemand} downstream branch fibre(s); this does not reserve the full branch cable size.`
          : `${relationshipLabel}: local splitter/building demand only.`,
      });
    }
    total += demand;
  });

  return total;
}

function formatFibreRange(fibres: number[]): string {
  if (!fibres.length) return "none";
  const sorted = [...new Set(fibres)].sort((a, b) => a - b);
  const ranges: string[] = [];
  let start = sorted[0];
  let previous = sorted[0];

  for (let index = 1; index <= sorted.length; index += 1) {
    const current = sorted[index];
    if (current === previous + 1) {
      previous = current;
      continue;
    }
    ranges.push(start === previous ? `F${start}` : `F${start}–F${previous}`);
    start = current;
    previous = current;
  }

  return ranges.join(", ");
}

function getReservedFibresForAsset(asset: any): number[] {
  const details = asset?.dpDetails || {};
  const afnFibres = Array.isArray(details?.afnDetails?.inputFibres)
    ? details.afnDetails.inputFibres
    : [];
  const mduFibres = Array.isArray(details?.mduDetails?.inputFibres)
    ? details.mduDetails.inputFibres
    : [];
  const cableFibres = Array.isArray(asset?.allocatedInputFibres)
    ? asset.allocatedInputFibres
    : [];

  return [...afnFibres, ...mduFibres, ...cableFibres]
    .map((fibre) => Number(fibre))
    .filter((fibre) => Number.isFinite(fibre) && fibre > 0);
}

function getReservationConflicts(input: {
  currentDpId?: string | null;
  throughCableId: string;
  proposedFibres: number[];
  allDistributionPoints: SavedMapAsset[];
  allAssets: SavedMapAsset[];
}): { duplicateFibres: number[]; conflictingReservations: string[] } {
  if (!input.throughCableId || !input.proposedFibres.length) {
    return { duplicateFibres: [], conflictingReservations: [] };
  }

  const proposed = new Set(input.proposedFibres);
  const duplicateFibres = new Set<number>();
  const conflictingReservations: string[] = [];

  input.allDistributionPoints.forEach((asset: any) => {
    if (!asset || String(asset.id || "") === String(input.currentDpId || ""))
      return;
    if (getDpThroughCableId(asset) !== input.throughCableId) return;

    const overlap = getReservedFibresForAsset(asset).filter((fibre) =>
      proposed.has(fibre),
    );
    if (!overlap.length) return;

    overlap.forEach((fibre) => duplicateFibres.add(fibre));
    conflictingReservations.push(
      `${getAssetName(asset)} already reserves ${formatFibreRange(overlap)} on ${input.throughCableId}.`,
    );
  });

  input.allAssets.forEach((asset: any) => {
    if (!asset || String(asset.parentCableId || "") !== input.throughCableId)
      return;
    const overlap = getReservedFibresForAsset(asset).filter((fibre) =>
      proposed.has(fibre),
    );
    if (!overlap.length) return;

    overlap.forEach((fibre) => duplicateFibres.add(fibre));
    conflictingReservations.push(
      `${getAssetName(asset)} branch record already reserves ${formatFibreRange(overlap)}.`,
    );
  });

  return {
    duplicateFibres: Array.from(duplicateFibres).sort((a, b) => a - b),
    conflictingReservations,
  };
}

export function allocateDpFibresForPlan(
  input: AllocateDpFibresInput,
): DpFibreAutoAllocation {
  const currentDp = findCurrentDp(input);
  const toleranceMeters = input.snapToleranceMeters ?? 18;
  const allDistributionPoints = input.allDistributionPoints || [];
  const allAssets = input.allAssets || [];
  const currentOverride = {
    dpId: input.currentDpId,
    connectedHomes: input.connectedHomes,
    plan: input.plan,
  };

  const found = findCableForDp(input, currentDp);
  const warnings = [...found.warnings];

  if (!found.cable) {
    return {
      fibreTotal: 0,
      inputFibres: [],
      localReservedFibres: input.plan.requiredInputFibres,
      branchReservedFibres: 0,
      downstreamReservedFibres: 0,
      totalReservedFibres: input.plan.requiredInputFibres,
      startFibre: 0,
      endFibre: 0,
      freeFibresAfterAllocation: 0,
      utilisationPercent: 0,
      duplicateFibres: [],
      conflictingReservations: [],
      explanationRows: [
        {
          label: "Through cable",
          value: "Not found",
          help: "Select a through cable or move the DP onto the cable route.",
        },
        {
          label: "Local demand",
          value: input.plan.requiredInputFibres,
          help: "Fibres needed for homes directly served by this DP.",
        },
      ],
      traceRows: [],
      branchNotes: [],
      warnings,
    };
  }

  const cable = found.cable;
  const cableId = String(cable.id || "");
  const fibreTotal = parseFibreTotal(cable);
  const branchNotes: string[] = [];
  const traceRows: DpFibreAllocationTraceRow[] = [];
  const currentProjection =
    found.projection ||
    (currentDp && getPoint(currentDp)
      ? projectPointOnCable(getPoint(currentDp)!, cable)
      : null);

  const branchReservedFibres = currentDp
    ? getBranchCablesAtDp(
        currentDp,
        cableId,
        allAssets,
        toleranceMeters,
      ).reduce((sum, branchCable) => {
        const branchDemand = getCableDemand({
          cable: branchCable,
          originDpId: String(currentDp.id || ""),
          allDistributionPoints,
          allAssets,
          toleranceMeters,
          currentOverride,
          visitedCableIds: new Set([cableId]),
          branchNotes,
          traceRows,
        });
        if (branchDemand > 0) {
          branchNotes.push(
            `${getAssetName(branchCable)} branch needs ${branchDemand} fibre(s) downstream, not the full ${parseFibreTotal(branchCable)}F cable size.`,
          );
          traceRows.push({
            assetName: getAssetName(branchCable),
            cableId: String(branchCable.id || ""),
            cableName: getAssetName(branchCable),
            localFibres: 0,
            branchFibres: branchDemand,
            totalFibres: branchDemand,
            note: `Branch cable demand is calculated from downstream AFN/MDU reservations, not from ${parseFibreTotal(branchCable)}F cable capacity.`,
          });
        }
        return sum + branchDemand;
      }, 0)
    : 0;

  const localReservedFibres = Math.max(
    0,
    Math.floor(input.plan.requiredInputFibres || 0),
  );
  const totalReservedFibres = localReservedFibres + branchReservedFibres;

  let downstreamReservedFibres = 0;
  if (currentProjection) {
    const dpsOnCable = getDpsOnCable(
      cable,
      allDistributionPoints,
      toleranceMeters,
    )
      .filter(
        (entry) =>
          String(entry.asset.id || "") !== String(input.currentDpId || ""),
      )
      .filter(
        (entry) =>
          entry.projection.distanceAlongCableMeters >
          currentProjection.distanceAlongCableMeters,
      )
      .filter((entry) =>
        isPassthroughArchitecture(getDpArchitecture(entry.asset)),
      );

    downstreamReservedFibres = dpsOnCable.reduce((sum, entry) => {
      const local = getLocalReservedFibres(
        entry.asset,
        allAssets,
        currentOverride,
      );
      const branches = getBranchCablesAtDp(
        entry.asset,
        cableId,
        allAssets,
        toleranceMeters,
      );
      const branchDemand = branches.reduce(
        (branchSum, branchCable) =>
          branchSum +
          getCableDemand({
            cable: branchCable,
            originDpId: String(entry.asset.id || ""),
            allDistributionPoints,
            allAssets,
            toleranceMeters,
            currentOverride,
            visitedCableIds: new Set([cableId]),
            branchNotes,
          }),
        0,
      );
      return sum + local + branchDemand;
    }, 0);
  }

  const startFibre = downstreamReservedFibres + 1;
  const endFibre = downstreamReservedFibres + totalReservedFibres;
  const inputFibres =
    totalReservedFibres > 0
      ? Array.from(
          { length: totalReservedFibres },
          (_, index) => startFibre + index,
        ).filter((fibre) => fibre <= fibreTotal)
      : [];

  if (totalReservedFibres > 0 && endFibre > fibreTotal) {
    warnings.push(
      `${getAssetName(cable)} is ${fibreTotal}F but this allocation needs up to F${endFibre}. Split the run, reduce downstream demand, or use a larger spine.`,
    );
  }

  if (
    currentProjection &&
    currentProjection.distanceToCableMeters > toleranceMeters
  ) {
    warnings.push(
      `${getAssetName(currentDp)} is ${currentProjection.distanceToCableMeters.toFixed(1)}m from ${getAssetName(cable)}. Check the DP is really on this through cable.`,
    );
  }

  if (totalReservedFibres > 0 && inputFibres.length < totalReservedFibres) {
    warnings.push(
      `Only ${inputFibres.length} fibre(s) could be selected, but this DP needs ${totalReservedFibres}. Check cable capacity and downstream reservations.`,
    );
  }

  const conflicts = getReservationConflicts({
    currentDpId: input.currentDpId,
    throughCableId: cableId,
    proposedFibres: inputFibres,
    allDistributionPoints,
    allAssets,
  });

  if (conflicts.duplicateFibres.length) {
    warnings.push(
      `Duplicate fibre reservation warning: ${formatFibreRange(conflicts.duplicateFibres)} already appears reserved on ${getAssetName(cable)}.`,
    );
  }

  const freeFibresAfterAllocation = Math.max(
    0,
    fibreTotal - Math.max(endFibre, downstreamReservedFibres),
  );
  const utilisationPercent =
    fibreTotal > 0
      ? Math.round(
          (Math.min(fibreTotal, Math.max(endFibre, downstreamReservedFibres)) /
            fibreTotal) *
            100,
        )
      : 0;
  const explanationRows: DpFibreAllocationExplanationRow[] = [
    {
      label: "Through cable",
      value: `${getAssetName(cable)} (${fibreTotal}F)`,
      help: "The parent cable selected automatically from the DP position or chosen manually.",
    },
    {
      label: "Downstream already reserved",
      value: downstreamReservedFibres,
      help: "Fibres consumed by AFN/MDU assets further towards the end of the run. For MDU, this is the fixed building reserve, not one fibre per flat. Fibre 1 starts at the run end.",
    },
    {
      label: "Local demand",
      value: localReservedFibres,
      help: "Fibres needed for homes/building demand at this DP.",
    },
    {
      label: "Branch demand",
      value: branchReservedFibres,
      help: "Fibres needed by downstream AFN/MDU assets on branch cables from this DP. Full branch cable size is not reserved.",
    },
    {
      label: "New reservation",
      value: formatFibreRange(inputFibres),
      help: "The actual fibres this DP should reserve on the parent cable.",
    },
    {
      label: "Free after allocation",
      value: freeFibresAfterAllocation,
      help: "Remaining parent cable fibres after downstream demand and this DP reservation.",
    },
  ];

  return {
    throughCableId: cableId,
    throughCableName: getAssetName(cable),
    fibreTotal,
    inputFibres,
    localReservedFibres,
    branchReservedFibres,
    downstreamReservedFibres,
    totalReservedFibres,
    startFibre,
    endFibre: inputFibres.length ? inputFibres[inputFibres.length - 1] : 0,
    freeFibresAfterAllocation,
    utilisationPercent,
    duplicateFibres: conflicts.duplicateFibres,
    conflictingReservations: conflicts.conflictingReservations,
    explanationRows,
    traceRows,
    branchNotes,
    warnings,
  };
}

// =====================================================
// PHASE 7A.4 — THROUGH-CABLE CHAIN REBUILD
// Recalculates every AFN / MDU / MDU_SPLITTER reservation on one
// selected through cable from the downstream end of the run backwards.
// This fixes duplicate fibre reservations without manually editing
// every DP on the chain.
// =====================================================

export type DpChainReservationUpdate = {
  assetId: string;
  assetName: string;
  architecture: DistributionArchitecture;
  inputFibres: number[];
  localReservedFibres: number;
  branchReservedFibres: number;
  totalReservedFibres: number;
  startFibre: number;
  endFibre: number;
  freeFibresAfterAllocation: number;
  utilisationPercent: number;
  dpDetails: any;
  warnings: string[];
};

export type RebuildThroughCableReservationResult = {
  throughCableId?: string;
  throughCableName?: string;
  fibreTotal: number;
  updates: DpChainReservationUpdate[];
  warnings: string[];
  traceRows: DpFibreAllocationTraceRow[];
};

type RebuildThroughCableReservationsInput = {
  throughCableId?: string | null;
  currentDpId?: string | null;
  currentDpDetails?: any;
  currentPlan?: DpFibrePlan;
  connectedHomes?: number;
  availableThroughCables?: SavedMapAsset[];
  allDistributionPoints?: SavedMapAsset[];
  allAssets?: SavedMapAsset[];
  snapToleranceMeters?: number;
};

function detailsWithChainReservation(input: {
  dp: SavedMapAsset;
  architecture: DistributionArchitecture;
  cableId: string;
  cableName: string;
  fibreTotal: number;
  inputFibres: number[];
  localReservedFibres: number;
  branchReservedFibres: number;
  downstreamReservedFibres: number;
  totalReservedFibres: number;
  freeFibresAfterAllocation: number;
  utilisationPercent: number;
  traceRows: DpFibreAllocationTraceRow[];
}): any {
  const existingDetails = ((input.dp as any).dpDetails || {}) as any;
  const nextDetails: any = {
    ...existingDetails,
    closureType: input.architecture,
    networkArchitecture: input.architecture,
    autoFibrePlan: {
      ...(existingDetails.autoFibrePlan || {}),
      connectedHomes: Number(existingDetails.autoFibrePlan?.connectedHomes || 0),
      requiredInputFibres: input.localReservedFibres,
      branchReservedFibres: input.branchReservedFibres,
      downstreamReservedFibres: input.downstreamReservedFibres,
      reservedFibres: input.totalReservedFibres,
      capacity: existingDetails.connectionsToHomes || existingDetails.autoFibrePlan?.capacity || 0,
      throughCableId: input.cableId,
      throughCableName: input.cableName,
      inputFibres: input.inputFibres,
      freeFibresAfterAllocation: input.freeFibresAfterAllocation,
      utilisationPercent: input.utilisationPercent,
      duplicateFibres: [],
      allocationWarnings: [],
      allocationTrace: input.traceRows,
      updatedAt: new Date().toISOString(),
    },
  };

  if (input.architecture === "AFN") {
    nextDetails.afnDetails = {
      ...(existingDetails.afnDetails || {}),
      enabled: true,
      throughCableId: input.cableId,
      inputFibres: input.inputFibres,
      fibreCountUsed: input.totalReservedFibres,
      splitterRatio: "1:8",
      splitterOutputs: Math.max(8, Number(existingDetails.afnDetails?.splitterOutputs || 8)),
    };
    nextDetails.mduDetails = undefined;
    return nextDetails;
  }

  if (input.architecture === "MDU" || input.architecture === "MDU_SPLITTER") {
    const existingMdu = existingDetails.mduDetails || {};
    nextDetails.afnDetails = undefined;
    nextDetails.mduDetails = {
      ...existingMdu,
      enabled: true,
      throughCableId: input.cableId,
      inputFibres: input.inputFibres,
      totalReservedFibres: input.totalReservedFibres,
      mduFibres: Number(existingMdu.mduFibres || input.localReservedFibres || 0),
      splitterFibres:
        input.architecture === "MDU_SPLITTER"
          ? Number(existingMdu.splitterFibres || 0)
          : 0,
    };
    return nextDetails;
  }

  return nextDetails;
}

export function rebuildThroughCableReservations(
  input: RebuildThroughCableReservationsInput,
): RebuildThroughCableReservationResult {
  const warnings: string[] = [];
  const toleranceMeters = input.snapToleranceMeters ?? 18;
  const allDistributionPoints = input.allDistributionPoints || [];
  const allAssets = input.allAssets || [];
  const throughCableId = String(input.throughCableId || "");

  const cable = findCandidateThroughCables({
    availableThroughCables: input.availableThroughCables,
    allAssets,
    connectedHomes: input.connectedHomes || 0,
    plan:
      input.currentPlan ||
      ({ requiredInputFibres: 0 } as DpFibrePlan),
  } as AllocateDpFibresInput).find(
    (candidate) => String(candidate.id || "") === throughCableId,
  );

  if (!throughCableId || !cable) {
    return {
      throughCableId,
      fibreTotal: 0,
      updates: [],
      warnings: ["Select a through cable before rebuilding this chain."],
      traceRows: [],
    };
  }

  const cableId = String(cable.id || "");
  const cableName = getAssetName(cable);
  const fibreTotal = parseFibreTotal(cable);
  const currentOverride = {
    dpId: input.currentDpId,
    connectedHomes: input.connectedHomes || 0,
    plan:
      input.currentPlan ||
      ({ requiredInputFibres: 0 } as DpFibrePlan),
  };

  const dpsOnCable = getDpsOnCable(cable, allDistributionPoints, toleranceMeters)
    .filter((entry) => isPassthroughArchitecture(getDpArchitecture(entry.asset)))
    .sort(
      (a, b) =>
        b.projection.distanceAlongCableMeters -
        a.projection.distanceAlongCableMeters,
    );

  let nextFibre = 1;
  const traceRows: DpFibreAllocationTraceRow[] = [];
  const updates: DpChainReservationUpdate[] = [];

  for (const entry of dpsOnCable) {
    const asset = entry.asset;
    const assetId = String(asset.id || "");
    const architecture = getDpArchitecture(asset);
    const localReservedFibres = getLocalReservedFibres(asset, allAssets, currentOverride);

    const branchTraceRows: DpFibreAllocationTraceRow[] = [];
    const branchNotes: string[] = [];
    const branches = getBranchCablesAtDp(asset, cableId, allAssets, toleranceMeters);
    const branchReservedFibres = branches.reduce(
      (sum, branchCable) =>
        sum +
        getCableDemand({
          cable: branchCable,
          originDpId: assetId,
          allDistributionPoints,
          allAssets,
          toleranceMeters,
          currentOverride,
          visitedCableIds: new Set([cableId]),
          branchNotes,
          traceRows: branchTraceRows,
        }),
      0,
    );

    const totalReservedFibres = localReservedFibres + branchReservedFibres;
    const inputFibres =
      totalReservedFibres > 0
        ? Array.from(
            { length: totalReservedFibres },
            (_, index) => nextFibre + index,
          ).filter((fibre) => fibre <= fibreTotal)
        : [];

    const startFibre = inputFibres[0] || 0;
    const endFibre = inputFibres[inputFibres.length - 1] || 0;
    const freeFibresAfterAllocation = Math.max(0, fibreTotal - Math.max(endFibre, nextFibre - 1));
    const utilisationPercent =
      fibreTotal > 0
        ? Math.round((Math.min(fibreTotal, Math.max(endFibre, nextFibre - 1)) / fibreTotal) * 100)
        : 0;

    const assetWarnings: string[] = [];
    if (totalReservedFibres > 0 && inputFibres.length < totalReservedFibres) {
      assetWarnings.push(
        `${getAssetName(asset)} needs ${totalReservedFibres} fibre(s), but ${cableName} only has ${fibreTotal}F available at this point in the rebuild.`,
      );
    }

    traceRows.push({
      assetId,
      assetName: getAssetName(asset),
      cableId,
      cableName,
      localFibres: localReservedFibres,
      branchFibres: branchReservedFibres,
      totalFibres: totalReservedFibres,
      note: inputFibres.length
        ? `Rebuilt chain reservation: ${formatFibreRange(inputFibres)}.`
        : "No fibre demand found for this DP on this rebuild.",
    });
    traceRows.push(...branchTraceRows);

    const dpDetails = detailsWithChainReservation({
      dp: asset,
      architecture,
      cableId,
      cableName,
      fibreTotal,
      inputFibres,
      localReservedFibres,
      branchReservedFibres,
      downstreamReservedFibres: nextFibre - 1,
      totalReservedFibres,
      freeFibresAfterAllocation,
      utilisationPercent,
      traceRows: branchTraceRows,
    });

    updates.push({
      assetId,
      assetName: getAssetName(asset),
      architecture,
      inputFibres,
      localReservedFibres,
      branchReservedFibres,
      totalReservedFibres,
      startFibre,
      endFibre,
      freeFibresAfterAllocation,
      utilisationPercent,
      dpDetails,
      warnings: assetWarnings,
    });

    assetWarnings.forEach((warning) => warnings.push(warning));
    nextFibre += totalReservedFibres;
  }

  if (!updates.length) {
    warnings.push("No AFN / MDU / MDU_SPLITTER assets were found on this through-cable chain.");
  }

  return {
    throughCableId: cableId,
    throughCableName: cableName,
    fibreTotal,
    updates,
    warnings,
    traceRows,
  };
}
