// =====================================================
// FILE: dpFibreAutoAllocator.ts
// PURPOSE: Automatic AFN / MDU fibre reservation on through-cable runs.
//
// IMPORTANT:
// - Does NOT save to Firestore.
// - Does NOT change drop-cable generation.
// - Does NOT change cable route drawing.
// - Does NOT reserve a full branch cable size automatically.
//   Branches only reserve the fibres actually needed by downstream
//   AFN / MDU / MDU_SPLITTER assets on that branch.
// =====================================================

import type { DpFibrePlan } from "./dpArchitecturePlanner";
import type { DistributionArchitecture, SavedMapAsset } from "../components/map/types";

type LatLng = { lat: number; lng: number };

type CableProjection = {
  distanceToCableMeters: number;
  distanceAlongCableMeters: number;
};

export type DpFibreAutoAllocation = {
  throughCableId?: string;
  throughCableName?: string;
  fibreTotal: number;
  inputFibres: number[];
  localReservedFibres: number;
  branchReservedFibres: number;
  downstreamReservedFibres: number;
  totalReservedFibres: number;
  startFibre: number;
  endFibre: number;
  branchNotes: string[];
  warnings: string[];
};

type AllocateDpFibresInput = {
  currentDpId?: string | null;
  currentClosureType?: DistributionArchitecture | string | null;
  currentDpDetails?: any;
  connectedHomes: number;
  plan: DpFibrePlan;
  selectedThroughCableId?: string | null;
  availableThroughCables?: SavedMapAsset[];
  allDistributionPoints?: SavedMapAsset[];
  allAssets?: SavedMapAsset[];
  snapToleranceMeters?: number;
};

function normaliseText(value: unknown): string {
  return String(value || "").trim().toLowerCase().replace(/[\s_/-]+/g, " ");
}

function normaliseArchitecture(value: unknown): DistributionArchitecture {
  const raw = String(value || "CBT").toUpperCase();
  if (raw === "AFN") return "AFN";
  if (raw === "MDU") return "MDU";
  if (raw === "MDU_SPLITTER") return "MDU_SPLITTER";
  return "CBT";
}

function isPassthroughArchitecture(value: unknown): boolean {
  return normaliseArchitecture(value) !== "CBT";
}

function parseFibreTotal(asset: any, fallback = 48): number {
  const candidates = [asset?.fibreCount, asset?.fiberCount, asset?.size, asset?.cableSize, asset?.name, asset?.label];
  for (const candidate of candidates) {
    const match = String(candidate ?? "").toUpperCase().match(/(288|144|96|48|36|24|12)\s*F?/);
    if (match) return Number(match[1]);
  }
  return fallback;
}

function getAssetName(asset: any): string {
  return String(asset?.name || asset?.cableId || asset?.label || asset?.id || "Asset");
}

function isCableAsset(asset: any): boolean {
  const text = normaliseText(asset?.assetType || asset?.type || asset?.jointType || asset?.cableType || asset?.name);
  return asset?.geometry?.type === "LineString" || text.includes("cable") || text.includes("ulw") || text.includes("feeder") || text.includes("link");
}

function isDropCableAsset(asset: any): boolean {
  const text = normaliseText(asset?.assetType || asset?.type || asset?.cableType || asset?.name || asset?.generatedBy);
  return (
    text.includes("drop") ||
    asset?.isDropCable === true ||
    asset?.autoGeneratedDrop === true ||
    Boolean(asset?.homeId || asset?.connectedHomeId || asset?.toHomeId || asset?.fromHomeId)
  );
}

function getPoint(asset: any): LatLng | null {
  if (typeof asset?.lat === "number" && typeof asset?.lng === "number") {
    return { lat: asset.lat, lng: asset.lng };
  }
  const coords = asset?.geometry?.coordinates;
  if (asset?.geometry?.type === "Point" && Array.isArray(coords)) {
    const lat = Number(coords[0]);
    const lng = Number(coords[1]);
    if (Number.isFinite(lat) && Number.isFinite(lng)) return { lat, lng };
  }
  return null;
}

function getLine(asset: any): LatLng[] {
  const coords = asset?.geometry?.coordinates;
  if (asset?.geometry?.type !== "LineString" || !Array.isArray(coords)) return [];
  return coords
    .map((coord: any) => ({ lat: Number(coord?.[0]), lng: Number(coord?.[1]) }))
    .filter((point: LatLng) => Number.isFinite(point.lat) && Number.isFinite(point.lng));
}

function toRad(value: number): number {
  return (value * Math.PI) / 180;
}

function distanceMeters(a: LatLng, b: LatLng): number {
  const radius = 6371000;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * radius * Math.asin(Math.sqrt(h));
}

function segmentProjection(point: LatLng, start: LatLng, end: LatLng): { distanceMeters: number; ratio: number } {
  const midLat = ((point.lat + start.lat + end.lat) / 3) * (Math.PI / 180);
  const toXY = (p: LatLng) => ({
    x: p.lng * 111320 * Math.cos(midLat),
    y: p.lat * 111320,
  });

  const p = toXY(point);
  const a = toXY(start);
  const b = toXY(end);
  const dx = b.x - a.x;
  const dy = b.y - a.y;
  const lenSq = dx * dx + dy * dy;

  if (lenSq <= 0) {
    return { distanceMeters: Math.sqrt((p.x - a.x) ** 2 + (p.y - a.y) ** 2), ratio: 0 };
  }

  const ratio = Math.max(0, Math.min(1, ((p.x - a.x) * dx + (p.y - a.y) * dy) / lenSq));
  const projected = { x: a.x + ratio * dx, y: a.y + ratio * dy };
  return {
    distanceMeters: Math.sqrt((p.x - projected.x) ** 2 + (p.y - projected.y) ** 2),
    ratio,
  };
}

function projectPointOnCable(point: LatLng, cable: SavedMapAsset): CableProjection | null {
  const line = getLine(cable);
  if (line.length < 2) return null;

  let travelled = 0;
  let best: CableProjection | null = null;

  for (let index = 1; index < line.length; index += 1) {
    const start = line[index - 1];
    const end = line[index];
    const segmentLength = distanceMeters(start, end);
    const projection = segmentProjection(point, start, end);
    const candidate: CableProjection = {
      distanceToCableMeters: projection.distanceMeters,
      distanceAlongCableMeters: travelled + segmentLength * projection.ratio,
    };

    if (!best || candidate.distanceToCableMeters < best.distanceToCableMeters) {
      best = candidate;
    }

    travelled += segmentLength;
  }

  return best;
}

function getDpThroughCableId(asset: any): string {
  const details = asset?.dpDetails || {};
  return String(
    details?.afnDetails?.throughCableId ||
      details?.mduDetails?.throughCableId ||
      asset?.parentCableId ||
      "",
  );
}

function getDpArchitecture(asset: any): DistributionArchitecture {
  return normaliseArchitecture(asset?.dpDetails?.closureType || asset?.dpDetails?.networkArchitecture || asset?.closureType);
}

function countConnectedHomesFromDrops(dpId: string, allAssets: SavedMapAsset[]): number {
  const seen = new Set<string>();

  allAssets.forEach((asset: any) => {
    if (!isDropCableAsset(asset)) return;
    const linkedDp = String(asset?.dpId || asset?.fromAssetId || asset?.toAssetId || asset?.parentDpId || "");
    if (linkedDp !== dpId) return;
    const homeKey = String(asset?.homeId || asset?.connectedHomeId || asset?.toHomeId || asset?.uprn || asset?.UPRN || asset?.id || "");
    if (homeKey) seen.add(homeKey);
  });

  return seen.size;
}

function getLocalReservedFibres(asset: SavedMapAsset, allAssets: SavedMapAsset[], currentOverride?: { dpId?: string | null; connectedHomes: number; plan: DpFibrePlan }): number {
  const dpId = String(asset?.id || "");
  if (currentOverride?.dpId && dpId === String(currentOverride.dpId)) {
    return Math.max(0, Math.floor(currentOverride.plan.requiredInputFibres || 0));
  }

  const details = (asset as any)?.dpDetails || {};
  const architecture = getDpArchitecture(asset);
  const autoPlanReserved = Number(details?.autoFibrePlan?.requiredInputFibres);
  if (Number.isFinite(autoPlanReserved) && autoPlanReserved > 0) return Math.floor(autoPlanReserved);

  if (architecture === "AFN") {
    const existingCount = Array.isArray(details?.afnDetails?.inputFibres) ? details.afnDetails.inputFibres.length : 0;
    if (existingCount > 0) return existingCount;
    const connectedHomes = Number(details?.autoFibrePlan?.connectedHomes || countConnectedHomesFromDrops(dpId, allAssets) || 0);
    return connectedHomes > 0 ? Math.ceil(connectedHomes / 8) : 0;
  }

  if (architecture === "MDU" || architecture === "MDU_SPLITTER") {
    const existing = details?.mduDetails;
    const existingCount = Array.isArray(existing?.inputFibres) ? existing.inputFibres.length : 0;
    if (existingCount > 0) return existingCount;
    const direct = Number(existing?.mduFibres || 0);
    const splitter = architecture === "MDU_SPLITTER" ? Number(existing?.splitterFibres || 0) : 0;
    if (direct + splitter > 0) return Math.floor(direct + splitter);
    const connectedHomes = Number(details?.autoFibrePlan?.connectedHomes || countConnectedHomesFromDrops(dpId, allAssets) || 0);
    return Math.max(0, connectedHomes);
  }

  return 0;
}

function findCandidateThroughCables(input: AllocateDpFibresInput): SavedMapAsset[] {
  const byId = new Map<string, SavedMapAsset>();
  [...(input.availableThroughCables || []), ...(input.allAssets || [])].forEach((asset) => {
    if (!asset?.id) return;
    if (!isCableAsset(asset)) return;
    if (isDropCableAsset(asset)) return;
    if (getLine(asset).length < 2) return;
    byId.set(String(asset.id), asset);
  });
  return Array.from(byId.values());
}

function findCurrentDp(input: AllocateDpFibresInput): SavedMapAsset | null {
  const currentId = String(input.currentDpId || "");
  if (!currentId) return null;
  return (
    (input.allDistributionPoints || []).find((asset) => String(asset?.id || "") === currentId) ||
    (input.allAssets || []).find((asset) => String(asset?.id || "") === currentId) ||
    null
  );
}

function findCableForDp(input: AllocateDpFibresInput, currentDp: SavedMapAsset | null): { cable: SavedMapAsset | null; projection: CableProjection | null; warnings: string[] } {
  const warnings: string[] = [];
  const candidateCables = findCandidateThroughCables(input);
  const selectedId = String(input.selectedThroughCableId || "");

  if (selectedId) {
    const selected = candidateCables.find((cable) => String(cable.id) === selectedId) || null;
    if (selected) {
      const point = currentDp ? getPoint(currentDp) : null;
      return { cable: selected, projection: point ? projectPointOnCable(point, selected) : null, warnings };
    }
    warnings.push("Selected through cable could not be found in the current asset list.");
  }

  const dpPoint = currentDp ? getPoint(currentDp) : null;
  if (!dpPoint) {
    warnings.push("Could not auto-select a through cable because this DP has no map position.");
    return { cable: null, projection: null, warnings };
  }

  const tolerance = input.snapToleranceMeters ?? 18;
  const nearest = candidateCables
    .map((cable) => ({ cable, projection: projectPointOnCable(dpPoint, cable) }))
    .filter((entry): entry is { cable: SavedMapAsset; projection: CableProjection } => Boolean(entry.projection))
    .filter((entry) => entry.projection.distanceToCableMeters <= tolerance)
    .sort((a, b) => a.projection.distanceToCableMeters - b.projection.distanceToCableMeters)[0];

  if (!nearest) {
    warnings.push(`Could not auto-select a through cable within ${tolerance}m of this DP.`);
    return { cable: null, projection: null, warnings };
  }

  return { cable: nearest.cable, projection: nearest.projection, warnings };
}

function getDpsOnCable(cable: SavedMapAsset, allDistributionPoints: SavedMapAsset[], toleranceMeters: number): { asset: SavedMapAsset; projection: CableProjection }[] {
  return allDistributionPoints
    .map((asset) => {
      const point = getPoint(asset);
      const projection = point ? projectPointOnCable(point, cable) : null;
      if (!projection) return null;
      return { asset, projection };
    })
    .filter((entry): entry is { asset: SavedMapAsset; projection: CableProjection } => Boolean(entry))
    .filter((entry) => entry.projection.distanceToCableMeters <= toleranceMeters)
    .sort((a, b) => a.projection.distanceAlongCableMeters - b.projection.distanceAlongCableMeters);
}

function getCableEndpointDistanceToDp(cable: SavedMapAsset, dpPoint: LatLng): number {
  const line = getLine(cable);
  if (line.length < 2) return Number.POSITIVE_INFINITY;
  return Math.min(distanceMeters(line[0], dpPoint), distanceMeters(line[line.length - 1], dpPoint));
}

function getBranchCablesAtDp(dp: SavedMapAsset, parentCableId: string, allAssets: SavedMapAsset[], toleranceMeters: number): SavedMapAsset[] {
  const point = getPoint(dp);
  if (!point) return [];

  return allAssets.filter((asset) => {
    if (!asset?.id || String(asset.id) === parentCableId) return false;
    if (!isCableAsset(asset) || isDropCableAsset(asset)) return false;

    // Explicit parentCableId wins when older saved cable records have it.
    if (String((asset as any).parentCableId || "") === parentCableId) {
      return getCableEndpointDistanceToDp(asset, point) <= toleranceMeters;
    }

    return getCableEndpointDistanceToDp(asset, point) <= toleranceMeters;
  });
}

function getCableDemand(input: {
  cable: SavedMapAsset;
  originDpId?: string;
  allDistributionPoints: SavedMapAsset[];
  allAssets: SavedMapAsset[];
  toleranceMeters: number;
  currentOverride: { dpId?: string | null; connectedHomes: number; plan: DpFibrePlan };
  visitedCableIds: Set<string>;
  branchNotes: string[];
}): number {
  const cableId = String(input.cable.id || "");
  if (!cableId || input.visitedCableIds.has(cableId)) return 0;
  input.visitedCableIds.add(cableId);

  const dpsOnCable = getDpsOnCable(input.cable, input.allDistributionPoints, input.toleranceMeters)
    .filter((entry) => String(entry.asset.id || "") !== String(input.originDpId || ""))
    .filter((entry) => isPassthroughArchitecture(getDpArchitecture(entry.asset)));

  let total = 0;

  dpsOnCable.forEach(({ asset }) => {
    const local = getLocalReservedFibres(asset, input.allAssets, input.currentOverride);
    const branches = getBranchCablesAtDp(asset, cableId, input.allAssets, input.toleranceMeters);
    const branchDemand = branches.reduce(
      (sum, branchCable) =>
        sum +
        getCableDemand({
          ...input,
          cable: branchCable,
          originDpId: String(asset.id || ""),
          visitedCableIds: new Set(input.visitedCableIds),
        }),
      0,
    );
    const demand = local + branchDemand;
    if (demand > 0) {
      input.branchNotes.push(`${getAssetName(asset)} reserves ${demand} fibre(s) on ${getAssetName(input.cable)}${branchDemand ? ` (${branchDemand} from downstream branches)` : ""}.`);
    }
    total += demand;
  });

  return total;
}

export function allocateDpFibresForPlan(input: AllocateDpFibresInput): DpFibreAutoAllocation {
  const currentDp = findCurrentDp(input);
  const toleranceMeters = input.snapToleranceMeters ?? 18;
  const allDistributionPoints = input.allDistributionPoints || [];
  const allAssets = input.allAssets || [];
  const currentOverride = {
    dpId: input.currentDpId,
    connectedHomes: input.connectedHomes,
    plan: input.plan,
  };

  const found = findCableForDp(input, currentDp);
  const warnings = [...found.warnings];

  if (!found.cable) {
    return {
      fibreTotal: 0,
      inputFibres: [],
      localReservedFibres: input.plan.requiredInputFibres,
      branchReservedFibres: 0,
      downstreamReservedFibres: 0,
      totalReservedFibres: input.plan.requiredInputFibres,
      startFibre: 0,
      endFibre: 0,
      branchNotes: [],
      warnings,
    };
  }

  const cable = found.cable;
  const cableId = String(cable.id || "");
  const fibreTotal = parseFibreTotal(cable);
  const branchNotes: string[] = [];
  const currentProjection = found.projection || (currentDp && getPoint(currentDp) ? projectPointOnCable(getPoint(currentDp)!, cable) : null);

  const branchReservedFibres = currentDp
    ? getBranchCablesAtDp(currentDp, cableId, allAssets, toleranceMeters).reduce(
        (sum, branchCable) => {
          const branchDemand = getCableDemand({
            cable: branchCable,
            originDpId: String(currentDp.id || ""),
            allDistributionPoints,
            allAssets,
            toleranceMeters,
            currentOverride,
            visitedCableIds: new Set([cableId]),
            branchNotes,
          });
          if (branchDemand > 0) {
            branchNotes.push(`${getAssetName(branchCable)} branch needs ${branchDemand} fibre(s) downstream, not the full ${parseFibreTotal(branchCable)}F cable size.`);
          }
          return sum + branchDemand;
        },
        0,
      )
    : 0;

  const localReservedFibres = Math.max(0, Math.floor(input.plan.requiredInputFibres || 0));
  const totalReservedFibres = localReservedFibres + branchReservedFibres;

  let downstreamReservedFibres = 0;
  if (currentProjection) {
    const dpsOnCable = getDpsOnCable(cable, allDistributionPoints, toleranceMeters)
      .filter((entry) => String(entry.asset.id || "") !== String(input.currentDpId || ""))
      .filter((entry) => entry.projection.distanceAlongCableMeters > currentProjection.distanceAlongCableMeters)
      .filter((entry) => isPassthroughArchitecture(getDpArchitecture(entry.asset)));

    downstreamReservedFibres = dpsOnCable.reduce((sum, entry) => {
      const local = getLocalReservedFibres(entry.asset, allAssets, currentOverride);
      const branches = getBranchCablesAtDp(entry.asset, cableId, allAssets, toleranceMeters);
      const branchDemand = branches.reduce(
        (branchSum, branchCable) =>
          branchSum +
          getCableDemand({
            cable: branchCable,
            originDpId: String(entry.asset.id || ""),
            allDistributionPoints,
            allAssets,
            toleranceMeters,
            currentOverride,
            visitedCableIds: new Set([cableId]),
            branchNotes,
          }),
        0,
      );
      return sum + local + branchDemand;
    }, 0);
  }

  const startFibre = downstreamReservedFibres + 1;
  const endFibre = downstreamReservedFibres + totalReservedFibres;
  const inputFibres = totalReservedFibres > 0
    ? Array.from({ length: totalReservedFibres }, (_, index) => startFibre + index).filter((fibre) => fibre <= fibreTotal)
    : [];

  if (totalReservedFibres > 0 && endFibre > fibreTotal) {
    warnings.push(
      `${getAssetName(cable)} is ${fibreTotal}F but this allocation needs up to F${endFibre}. Split the run, reduce downstream demand, or use a larger spine.`,
    );
  }

  if (currentProjection && currentProjection.distanceToCableMeters > toleranceMeters) {
    warnings.push(`${getAssetName(currentDp)} is ${currentProjection.distanceToCableMeters.toFixed(1)}m from ${getAssetName(cable)}. Check the DP is really on this through cable.`);
  }

  return {
    throughCableId: cableId,
    throughCableName: getAssetName(cable),
    fibreTotal,
    inputFibres,
    localReservedFibres,
    branchReservedFibres,
    downstreamReservedFibres,
    totalReservedFibres,
    startFibre,
    endFibre: inputFibres.length ? inputFibres[inputFibres.length - 1] : 0,
    branchNotes,
    warnings,
  };
}
