// =====================================================
// FILE: dpRelationshipRouting.ts
// PURPOSE: DP/SB-first relationship view for AFN/CBT routing.
//          This keeps the operational UI focused on which SB feeds
//          which SB. Cables remain supporting route records only.
//
// IMPORTANT:
// - Does NOT save to Firestore.
// - Does NOT alter cable geometry, drop generation, or chunk storage.
// - Reads existing asset/cable metadata and geometry defensively.
// =====================================================

import type { DistributionPointDetails, SavedMapAsset } from "../components/map/types";

type LatLng = { lat: number; lng: number };

export type DpRelationshipMapping = {
  parentFibre: number;
  localFibre: number;
};

export type DpRelationshipNode = {
  assetId?: string;
  name: string;
  cableId?: string;
  cableName?: string;
  requiredFibres?: number;
  mapping?: DpRelationshipMapping[];
};

export type DpRelationshipRouting = {
  current: DpRelationshipNode;
  fedFrom: DpRelationshipNode[];
  mainDownstream: DpRelationshipNode[];
  branchDownstream: DpRelationshipNode[];
  selectedParent?: DpRelationshipNode;
  selectedBranch?: DpRelationshipNode;
  selectedCableName?: string;
  selectedCableId?: string;
  localFibres: number[];
  parentFibres: number[];
  mapping: DpRelationshipMapping[];
  requiredFibres: number;
  isShootOff: boolean;
};

type BuildInput = {
  currentDpId?: string | null;
  currentDpName?: string | null;
  currentDpDetails?: DistributionPointDetails | any;
  selectedCableId?: string | null;
  localFibres?: number[];
  allDistributionPoints?: SavedMapAsset[];
  allAssets?: SavedMapAsset[];
};

function text(value: unknown): string {
  return String(value ?? "").trim();
}

function normaliseRef(value: unknown): string {
  return text(value)
    .toUpperCase()
    .replace(/[–—]/g, "-")
    .replace(/[^A-Z0-9]/g, "");
}

function refsMatch(a: unknown, b: unknown): boolean {
  const left = normaliseRef(a);
  const right = normaliseRef(b);
  if (!left || !right) return false;
  return left === right || left.includes(right) || right.includes(left);
}

function assetName(asset: any): string {
  return text(
    asset?.name ||
      asset?.jointName ||
      asset?.label ||
      asset?.cableId ||
      asset?.assetId ||
      asset?.id ||
      "Asset",
  );
}

function assetIdentities(asset: any): string[] {
  return [
    asset?.id,
    asset?.assetId,
    asset?.name,
    asset?.jointName,
    asset?.label,
    asset?.dpId,
  ]
    .map(text)
    .filter(Boolean);
}

function isDistributionPoint(asset: any): boolean {
  if (!asset) return false;
  if (asset?.assetType === "distribution-point") return true;
  const haystack = [
    asset?.assetType,
    asset?.type,
    asset?.dpType,
    asset?.distributionPointType,
    asset?.jointType,
    asset?.closureType,
    asset?.name,
    asset?.label,
  ]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return (
    haystack.includes("distribution") ||
    haystack.includes("afn") ||
    haystack.includes("cbt") ||
    /\bsb\s*\d+\b/i.test(haystack) ||
    /sb\d+/i.test(haystack)
  );
}

function isCable(asset: any): boolean {
  if (!asset) return false;
  const haystack = [asset?.assetType, asset?.type, asset?.cableType, asset?.name, asset?.label]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return asset?.geometry?.type === "LineString" || haystack.includes("cable") || haystack.includes("ulw");
}

function isDropCable(asset: any): boolean {
  const haystack = [asset?.assetType, asset?.type, asset?.cableType, asset?.name, asset?.label, asset?.generatedBy]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return (
    haystack.includes("drop") ||
    asset?.isDropCable === true ||
    asset?.isHomeDrop === true ||
    asset?.generatedDrop === true ||
    asset?.autoGeneratedDrop === true ||
    Boolean(asset?.homeId || asset?.connectedHomeId || asset?.toHomeId || asset?.fromHomeId)
  );
}

function getPoint(asset: any): LatLng | null {
  if (!asset) return null;
  if (typeof asset?.lat === "number" && typeof asset?.lng === "number") return { lat: asset.lat, lng: asset.lng };
  const coords = asset?.geometry?.coordinates;
  if (asset?.geometry?.type === "Point" && Array.isArray(coords)) {
    const lat = Number(coords[0]);
    const lng = Number(coords[1]);
    if (Number.isFinite(lat) && Number.isFinite(lng)) return { lat, lng };
  }
  return null;
}

function getLine(asset: any): LatLng[] {
  const coords = asset?.geometry?.coordinates;
  if (asset?.geometry?.type !== "LineString" || !Array.isArray(coords)) return [];
  return coords
    .map((coord: any) => ({ lat: Number(coord?.[0]), lng: Number(coord?.[1]) }))
    .filter((point: LatLng) => Number.isFinite(point.lat) && Number.isFinite(point.lng));
}

function toRad(value: number): number {
  return (value * Math.PI) / 180;
}

function distanceMeters(a: LatLng, b: LatLng): number {
  const radius = 6371000;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * radius * Math.asin(Math.sqrt(h));
}

function parseFibreTotal(asset: any): number {
  const candidates = [asset?.fibreCount, asset?.fiberCount, asset?.size, asset?.cableSize, asset?.name, asset?.label];
  for (const candidate of candidates) {
    const match = text(candidate).toUpperCase().match(/(288|144|96|48|36|24|12)\s*F?/);
    if (match) return Number(match[1]);
  }
  return 0;
}

function parseSbNumber(value: unknown): number | null {
  const match = text(value).match(/\bSB\s*0*(\d+)\b/i) || text(value).match(/SB0*(\d+)/i);
  if (!match) return null;
  const next = Number(match[1]);
  return Number.isFinite(next) ? next : null;
}

function readFibres(values: unknown[]): number[] {
  const fibres: number[] = [];
  values.forEach((value) => {
    if (Array.isArray(value)) {
      value.forEach((entry) => {
        const next = Number(entry);
        if (Number.isFinite(next) && next > 0) fibres.push(Math.floor(next));
      });
      return;
    }
    if (typeof value === "string") {
      value.split(/[,;\s]+/).forEach((entry) => {
        const next = Number(entry.replace(/[^0-9]/g, ""));
        if (Number.isFinite(next) && next > 0) fibres.push(Math.floor(next));
      });
      return;
    }
    const next = Number(value);
    if (Number.isFinite(next) && next > 0) fibres.push(Math.floor(next));
  });
  return Array.from(new Set(fibres)).sort((a, b) => a - b);
}

function findAssetByRefs(assets: SavedMapAsset[], refs: unknown[]): SavedMapAsset | null {
  const wanted = refs.map(normaliseRef).filter(Boolean);
  if (!wanted.length) return null;
  return (
    assets.find((asset) =>
      assetIdentities(asset).some((identity) => wanted.some((wantedRef) => refsMatch(identity, wantedRef))),
    ) || null
  );
}

function getCableEndpointRefs(cable: any): unknown[] {
  return [
    cable?.fromAssetId,
    cable?.fromId,
    cable?.sourceAssetId,
    cable?.sourceId,
    cable?.aEndAssetId,
    cable?.aAssetId,
    cable?.startAssetId,
    cable?.fromDpId,
    cable?.toAssetId,
    cable?.toId,
    cable?.targetAssetId,
    cable?.targetId,
    cable?.zEndAssetId,
    cable?.bAssetId,
    cable?.endAssetId,
    cable?.toDpId,
  ].filter(Boolean);
}

function getCableEndpoints(cable: SavedMapAsset, dps: SavedMapAsset[]): SavedMapAsset[] {
  const refs = getCableEndpointRefs(cable as any);
  const explicit = dps.filter((dp) => assetIdentities(dp).some((identity) => refs.some((ref) => refsMatch(identity, ref))));
  if (explicit.length >= 2) return explicit.slice(0, 2);

  const line = getLine(cable as any);
  if (line.length < 2) return explicit;
  const start = line[0];
  const end = line[line.length - 1];
  const candidates = dps
    .map((dp) => ({ dp, point: getPoint(dp) }))
    .filter((item): item is { dp: SavedMapAsset; point: LatLng } => Boolean(item.point));

  const startDp = candidates
    .map((item) => ({ dp: item.dp, distance: distanceMeters(item.point, start) }))
    .filter((item) => item.distance <= 35)
    .sort((a, b) => a.distance - b.distance)[0]?.dp;

  const endDp = candidates
    .map((item) => ({ dp: item.dp, distance: distanceMeters(item.point, end) }))
    .filter((item) => item.distance <= 35)
    .sort((a, b) => a.distance - b.distance)[0]?.dp;

  return [startDp, endDp].filter((dp, index, arr): dp is SavedMapAsset => Boolean(dp) && arr.findIndex((x) => x?.id === dp?.id) === index);
}

function isBranchCable(cable: any): boolean {
  const total = parseFibreTotal(cable);
  const haystack = [cable?.name, cable?.label, cable?.cableType, cable?.kind, cable?.category]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return Boolean(
    cable?.parentCableId ||
      cable?.parentCableName ||
      cable?.parentDpId ||
      cable?.upstreamDpId ||
      Array.isArray(cable?.allocatedInputFibres) ||
      Array.isArray(cable?.parentInputFibres) ||
      haystack.includes("branch") ||
      haystack.includes("spur") ||
      (total > 0 && total <= 24),
  );
}

function mappingFrom(parentFibres: number[], localFibres: number[]): DpRelationshipMapping[] {
  const length = Math.min(parentFibres.length, localFibres.length);
  return Array.from({ length }, (_, index) => ({ parentFibre: parentFibres[index], localFibre: localFibres[index] }));
}

function requiredFibreCount(dp: any, fallbackFibres: number[]): number {
  const details = dp?.dpDetails || dp?.properties?.dpDetails || {};
  const inputFibres = readFibres([
    details?.afnDetails?.inputFibres,
    details?.mduDetails?.inputFibres,
    details?.autoFibrePlan?.inputFibres,
    dp?.afnDetails?.inputFibres,
  ]);
  if (inputFibres.length) return inputFibres.length;
  if (fallbackFibres.length) return fallbackFibres.length;
  const homes = Number(details?.connectionsToHomes || dp?.connectionsToHomes || dp?.connectedHomes || 0);
  if (Number.isFinite(homes) && homes > 0) return Math.max(1, Math.ceil(homes / 8));
  return 0;
}

function makeNode(dp: SavedMapAsset, cable?: SavedMapAsset, requiredFibres?: number, mapping?: DpRelationshipMapping[]): DpRelationshipNode {
  return {
    assetId: dp.id,
    name: assetName(dp),
    cableId: cable?.id,
    cableName: cable ? assetName(cable) : undefined,
    requiredFibres,
    mapping,
  };
}

export function buildDpRelationshipRouting(input: BuildInput): DpRelationshipRouting | null {
  const allAssets = input.allAssets || [];
  const dps = (input.allDistributionPoints?.length ? input.allDistributionPoints : allAssets.filter(isDistributionPoint)) as SavedMapAsset[];
  const cables = allAssets.filter((asset) => isCable(asset) && !isDropCable(asset));
  const current = findAssetByRefs(dps, [input.currentDpId, input.currentDpName]) || null;
  if (!current) return null;

  const selectedCable = input.selectedCableId
    ? cables.find((cable) => assetIdentities(cable).some((identity) => refsMatch(identity, input.selectedCableId))) || null
    : null;

  const details = input.currentDpDetails || (current as any).dpDetails || (current as any).properties?.dpDetails || {};
  const localFibres = readFibres([
    input.localFibres,
    details?.afnDetails?.splitterFibres,
    details?.afnDetails?.inputFibres,
    details?.mduDetails?.inputFibres,
    details?.autoFibrePlan?.inputFibres,
  ]);

  const fedFrom: DpRelationshipNode[] = [];
  const mainDownstream: DpRelationshipNode[] = [];
  const branchDownstream: DpRelationshipNode[] = [];

  const seen = new Set<string>();
  const currentRefs = assetIdentities(current);

  cables.forEach((cable) => {
    const endpoints = getCableEndpoints(cable, dps);
    if (!endpoints.some((dp) => refsMatch(dp.id, current.id) || assetIdentities(dp).some((identity) => currentRefs.some((ref) => refsMatch(identity, ref))))) return;

    const other = endpoints.find((dp) => !refsMatch(dp.id, current.id) && !assetIdentities(dp).some((identity) => currentRefs.some((ref) => refsMatch(identity, ref))));
    if (!other) return;

    const cableAny = cable as any;
    const explicitParent = findAssetByRefs(dps, [cableAny.parentDpId, cableAny.parentAssetId, cableAny.upstreamDpId, cableAny.upstreamAssetId]);
    const explicitChild = findAssetByRefs(dps, [cableAny.childDpId, cableAny.childAssetId, cableAny.downstreamDpId, cableAny.downstreamAssetId]);

    const currentIsExplicitParent = explicitParent && refsMatch(explicitParent.id, current.id);
    const currentIsExplicitChild = explicitChild && refsMatch(explicitChild.id, current.id);
    const otherIsExplicitParent = explicitParent && refsMatch(explicitParent.id, other.id);

    const currentSb = parseSbNumber(assetName(current));
    const otherSb = parseSbNumber(assetName(other));
    const currentIsParentByOrder = currentSb !== null && otherSb !== null ? currentSb < otherSb : false;
    const branch = isBranchCable(cableAny);

    const parentFibres = readFibres([
      cableAny.allocatedInputFibres,
      cableAny.parentInputFibres,
      cableAny.upstreamInputFibres,
      cableAny.sourceFibres,
      cableAny.sourceFibreNumbers,
      cableAny.parentFibres,
      cableAny.reservationFibres,
      cableAny.reservedFibres,
    ]);
    const otherRequired = requiredFibreCount(other, parentFibres);
    const currentRequired = requiredFibreCount(current, localFibres.length ? localFibres : parentFibres);

    const otherNode = makeNode(other, cable, otherRequired, mappingFrom(parentFibres, readFibres([(other as any).dpDetails?.afnDetails?.inputFibres])));
    const currentNode = makeNode(current, cable, currentRequired, mappingFrom(parentFibres, localFibres));

    const key = `${cable.id}-${other.id}`;
    if (seen.has(key)) return;
    seen.add(key);

    if (currentIsExplicitParent || (!currentIsExplicitChild && !otherIsExplicitParent && currentIsParentByOrder)) {
      if (branch) branchDownstream.push(otherNode);
      else mainDownstream.push(otherNode);
      return;
    }

    if (otherIsExplicitParent || currentIsExplicitChild || !currentIsParentByOrder) {
      fedFrom.push(otherNode);
      return;
    }

    mainDownstream.push(otherNode);
  });

  let selectedParent: DpRelationshipNode | undefined;
  let selectedBranch: DpRelationshipNode | undefined;
  let parentFibres: number[] = [];
  let mapping: DpRelationshipMapping[] = [];
  let isShootOff = false;

  if (selectedCable) {
    const selectedEndpoints = getCableEndpoints(selectedCable, dps);
    const selectedOther = selectedEndpoints.find((dp) => !refsMatch(dp.id, current.id));
    parentFibres = readFibres([
      (selectedCable as any).allocatedInputFibres,
      (selectedCable as any).parentInputFibres,
      (selectedCable as any).upstreamInputFibres,
      (selectedCable as any).sourceFibres,
      (selectedCable as any).sourceFibreNumbers,
      (selectedCable as any).parentFibres,
      (selectedCable as any).reservationFibres,
      (selectedCable as any).reservedFibres,
    ]);
    mapping = mappingFrom(parentFibres, localFibres);
    isShootOff = isBranchCable(selectedCable as any) && Boolean(selectedOther);

    if (selectedOther) {
      const currentSb = parseSbNumber(assetName(current));
      const otherSb = parseSbNumber(assetName(selectedOther));
      const otherIsParent = otherSb !== null && currentSb !== null ? otherSb < currentSb : true;
      if (otherIsParent || isShootOff) selectedParent = makeNode(selectedOther, selectedCable, Math.max(parentFibres.length, localFibres.length), mapping);
      else selectedBranch = makeNode(selectedOther, selectedCable, Math.max(parentFibres.length, localFibres.length), mapping);
    }
  }

  const requiredFibres = Math.max(localFibres.length, parentFibres.length, requiredFibreCount(current, localFibres));

  return {
    current: makeNode(current, undefined, requiredFibres),
    fedFrom,
    mainDownstream,
    branchDownstream,
    selectedParent,
    selectedBranch,
    selectedCableId: selectedCable?.id || text(input.selectedCableId),
    selectedCableName: selectedCable ? assetName(selectedCable) : text(input.selectedCableId),
    localFibres,
    parentFibres,
    mapping,
    requiredFibres,
    isShootOff: isShootOff || Boolean(selectedParent && parentFibres.length),
  };
}
