// =====================================================
// FILE: topologyTraceService.ts
// PURPOSE: Operational trace builder for Project Workspace.
//          Keeps graph/fibre/QA aggregation out of React panels.
//
// IMPORTANT:
// - Does NOT save to Firestore.
// - Does NOT change cable drawing, drop generation or allocation logic.
// - Reads existing networkGraph, DP auto fibre metadata and QA issues only.
// =====================================================

import type { AuditIssue } from "./areaAudit";
import type { NetworkGraph, GraphEdge, GraphNode } from "./networkGraph";
import type { SavedMapAsset } from "../components/map/types";
import { getCableUsedFibres } from "../components/map/cableUsage";

export type TraceDirection = "selected" | "upstream" | "downstream" | "branch" | "home" | "qa";

export type TopologyTraceStep = {
  id: string;
  title: string;
  subtitle: string;
  direction: TraceDirection;
  asset?: SavedMapAsset | any;
  distanceMeters?: number;
  fibreText?: string;
  warning?: string;
};

export type TopologyTraceSummary = {
  selectedName: string;
  selectedType: string;
  upstreamCount: number;
  downstreamCount: number;
  branchCableCount: number;
  connectedHomeCount: number;
  connectedDpCount: number;
  connectedJointCount: number;
  reservedFibres: number;
  capacity: number;
  utilisationPercent: number | null;
  qaHigh: number;
  qaMedium: number;
  qaLow: number;
};

export type TopologyTraceResult = {
  selectedAsset: SavedMapAsset | null;
  summary: TopologyTraceSummary;
  path: TopologyTraceStep[];
  upstream: TopologyTraceStep[];
  downstream: TopologyTraceStep[];
  branches: TopologyTraceStep[];
  homes: TopologyTraceStep[];
  fibre: TopologyTraceStep[];
  qa: TopologyTraceStep[];
  warnings: string[];
};

type BuildTopologyTraceInput = {
  selectedAsset: SavedMapAsset | null;
  assets: SavedMapAsset[];
  graph: NetworkGraph;
  auditIssues?: AuditIssue[];
};

function text(value: unknown): string {
  return String(value ?? "").trim();
}

function norm(value: unknown): string {
  return text(value).toLowerCase().replace(/[\s_/-]+/g, "");
}

function prettyType(asset: any): string {
  const raw = text(asset?.assetType || asset?.type || asset?.jointType || asset?.cableType || "Asset");
  if (!raw) return "Asset";
  return raw.replace(/-/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

function assetTitle(asset: any): string {
  return text(asset?.name || asset?.jointName || asset?.label || asset?.cableId || asset?.cableName || asset?.assetId || asset?.id || "Asset");
}

function candidateKeys(asset: any): string[] {
  return [
    asset?.id,
    asset?.assetId,
    asset?.name,
    asset?.jointName,
    asset?.label,
    asset?.cableId,
    asset?.cableName,
  ]
    .map(norm)
    .filter(Boolean);
}

function matchesAsset(a: any, b: any): boolean {
  const aKeys = new Set(candidateKeys(a));
  return candidateKeys(b).some((key) => aKeys.has(key));
}

function isCable(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.cableType, asset?.name, asset?.label]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return asset?.geometry?.type === "LineString" || joined.includes("cable") || joined.includes("ulw") || joined.includes("feeder") || joined.includes("link");
}

function isDropCable(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.cableType, asset?.name, asset?.label, asset?.generatedBy]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return joined.includes("drop") || joined.includes("uprn") || asset?.isDropCable === true || asset?.autoGeneratedDrop === true || Boolean(asset?.homeId || asset?.connectedHomeId || asset?.toHomeId);
}

function isDesignCable(asset: any): boolean {
  return isCable(asset) && !isDropCable(asset);
}

function isDp(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.jointType, asset?.name, asset?.dpDetails?.closureType]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return joined.includes("distribution") || joined.includes("dp") || joined.includes("afn") || joined.includes("cbt") || joined.includes("mdu");
}

function isJoint(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.jointType, asset?.name]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return joined.includes("joint") || joined.includes("ag") || joined.includes("lmj") || joined.includes("cmj");
}

function isHome(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.name]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return joined.includes("home") || joined.includes("premise") || Boolean(asset?.uprn || asset?.UPRN || asset?.properties?.UPRN);
}

function parseCapacity(asset: any): number {
  const candidates = [asset?.fibreCount, asset?.fiberCount, asset?.size, asset?.cableSize, asset?.name, asset?.label];
  for (const candidate of candidates) {
    const match = text(candidate).match(/(288|144|96|48|36|24|12)\s*F?/i);
    if (match) return Number(match[1]);
  }
  return Number(asset?.capacity || asset?.ports || asset?.dpDetails?.connectionsToHomes || 0) || 0;
}

function parseCount(value: unknown): number {
  const parsed = Number(value);
  return Number.isFinite(parsed) && parsed > 0 ? Math.floor(parsed) : 0;
}

function getCableUsedCount(asset: any, assets: SavedMapAsset[]): number {
  const direct = Math.max(
    parseCount(asset?.usedFibres),
    parseCount(asset?.usedFibers),
    parseCount(asset?.usedCoreCount),
    parseCount(asset?.fibresUsed),
    parseCount(asset?.allocatedFibres),
    parseCount(asset?.properties?.usedFibres),
    parseCount(asset?.properties?.usedFibers),
    parseCount(asset?.properties?.usedCoreCount),
    parseCount(asset?.properties?.fibresUsed),
    parseCount(asset?.properties?.allocatedFibres),
  );

  if (direct > 0) return direct;

  const derived = getCableUsedFibres(asset, assets);
  return Number.isFinite(derived) && derived > 0 ? Math.floor(derived) : 0;
}

function getDpThroughCableId(asset: any): string {
  const details = asset?.dpDetails || {};
  return text(details?.afnDetails?.throughCableId || details?.mduDetails?.throughCableId || asset?.parentCableId || "");
}

function getDpInputFibres(asset: any): number[] {
  const details = asset?.dpDetails || {};
  const fibres = details?.afnDetails?.inputFibres || details?.mduDetails?.inputFibres || details?.autoFibrePlan?.inputFibres || [];
  return Array.isArray(fibres)
    ? fibres.map((fibre) => Number(fibre)).filter((fibre) => Number.isFinite(fibre) && fibre > 0)
    : [];
}

function getReservedFibres(asset: any): number {
  const details = asset?.dpDetails || {};
  const autoPlan = details?.autoFibrePlan || {};
  const explicit = Number(autoPlan.reservedFibres || details?.afnDetails?.fibreCountUsed || details?.mduDetails?.totalReservedFibres || 0);
  if (Number.isFinite(explicit) && explicit > 0) return explicit;
  return getDpInputFibres(asset).length;
}

function issueKey(issue: AuditIssue): string[] {
  return [issue.assetId, issue.assetName, (issue as any).asset?.id, (issue as any).asset?.name].map(norm).filter(Boolean);
}

function issuesForAsset(asset: any, issues: AuditIssue[]): AuditIssue[] {
  const keys = new Set(candidateKeys(asset));
  return issues.filter((issue) => issueKey(issue).some((key) => keys.has(key)));
}

function findSelectedNode(graph: NetworkGraph, selectedAsset: SavedMapAsset): GraphNode | null {
  return Array.from(graph.nodes.values()).find((node) => matchesAsset(node.asset, selectedAsset)) || null;
}

function findSelectedEdge(graph: NetworkGraph, selectedAsset: SavedMapAsset): GraphEdge | null {
  return Array.from(graph.edges.values()).find((edge) => matchesAsset(edge.asset, selectedAsset)) || null;
}

function edgeStep(edge: GraphEdge, direction: TraceDirection, titlePrefix = ""): TopologyTraceStep {
  const name = assetTitle(edge.asset);
  return {
    id: edge.id,
    title: `${titlePrefix}${name}`,
    subtitle: `${prettyType(edge.asset)} • ${Math.round(edge.lengthMeters || 0)}m • ${edge.visualStyle}`,
    direction,
    asset: edge.asset,
    distanceMeters: edge.lengthMeters,
    fibreText: isDropCable(edge.asset) ? "Drop" : `${getReservedFibres(edge.asset) || Number((edge.asset as any)?.usedFibres || 0) || 0}/${parseCapacity(edge.asset) || "?"}F`,
  };
}

function nodeStep(node: GraphNode, direction: TraceDirection, titlePrefix = ""): TopologyTraceStep {
  const reserved = getReservedFibres(node.asset);
  const inputFibres = getDpInputFibres(node.asset);
  return {
    id: node.id,
    title: `${titlePrefix}${assetTitle(node.asset)}`,
    subtitle: prettyType(node.asset),
    direction,
    asset: node.asset,
    fibreText: reserved > 0 ? `${reserved} reserved${inputFibres.length ? ` • F${inputFibres.join("/F")}` : ""}` : undefined,
  };
}

function cableReferenceMatches(cable: any, reference: string): boolean {
  if (!reference) return false;
  const ref = norm(reference);
  return candidateKeys(cable).some((key) => key === ref || key.includes(ref) || ref.includes(key));
}

function cableForDp(dp: any, assets: SavedMapAsset[]): SavedMapAsset | null {
  const throughCableId = getDpThroughCableId(dp);
  if (!throughCableId) return null;
  return assets.find((asset) => isDesignCable(asset) && cableReferenceMatches(asset, throughCableId)) || null;
}

function dpsOnCable(cable: any, assets: SavedMapAsset[]): SavedMapAsset[] {
  return assets.filter((asset) => isDp(asset) && cableReferenceMatches(cable, getDpThroughCableId(asset)));
}

function dropsForDp(dp: any, assets: SavedMapAsset[]): SavedMapAsset[] {
  const dpKeys = new Set(candidateKeys(dp));
  return assets.filter((asset: any) => {
    if (!isDropCable(asset)) return false;
    const linked = [asset?.dpId, asset?.fromAssetId, asset?.connectedDpId, asset?.parentDpId].map(norm).filter(Boolean);
    return linked.some((key) => dpKeys.has(key));
  });
}

function branchCablesForDp(dp: any, assets: SavedMapAsset[]): SavedMapAsset[] {
  const dpKeys = new Set(candidateKeys(dp));
  const parentCable = getDpThroughCableId(dp);
  return assets.filter((asset: any) => {
    if (!isDesignCable(asset)) return false;
    if (parentCable && cableReferenceMatches(asset, parentCable)) return false;
    const references = [asset?.parentDpId, asset?.fromAssetId, asset?.sourceAssetId, asset?.aEndAssetId, asset?.fromJointId].map(norm).filter(Boolean);
    return references.some((key) => dpKeys.has(key));
  });
}

function emptyResult(selectedAsset: SavedMapAsset | null): TopologyTraceResult {
  return {
    selectedAsset,
    summary: {
      selectedName: selectedAsset ? assetTitle(selectedAsset) : "No asset selected",
      selectedType: selectedAsset ? prettyType(selectedAsset) : "Asset",
      upstreamCount: 0,
      downstreamCount: 0,
      branchCableCount: 0,
      connectedHomeCount: 0,
      connectedDpCount: 0,
      connectedJointCount: 0,
      reservedFibres: 0,
      capacity: 0,
      utilisationPercent: null,
      qaHigh: 0,
      qaMedium: 0,
      qaLow: 0,
    },
    path: [],
    upstream: [],
    downstream: [],
    branches: [],
    homes: [],
    fibre: [],
    qa: [],
    warnings: [],
  };
}

function uniqueSteps(steps: TopologyTraceStep[]): TopologyTraceStep[] {
  const seen = new Set<string>();
  return steps.filter((step) => {
    const key = `${step.direction}:${step.id}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function isInfrastructureEdge(edge: GraphEdge): boolean {
  return !isDropCable(edge.asset) && edge.kind !== "drop";
}

function isInfrastructureNode(node: GraphNode): boolean {
  return !isHome(node.asset) && node.kind !== "home";
}

function edgeText(edge: GraphEdge): string {
  return [
    edge.kind,
    edge.asset?.name,
    edge.asset?.label,
    edge.asset?.cableId,
    edge.asset?.cableName,
    edge.asset?.cableType,
    edge.asset?.type,
    edge.asset?.assetType,
  ]
    .map((value) => text(value).toLowerCase())
    .filter(Boolean)
    .join(" ");
}

function edgeBackboneScore(edge: GraphEdge): number {
  const value = edgeText(edge);
  if (value.includes("link cable") || /\blink\b/.test(value)) return 95;
  if (value.includes("feeder") || /\bfc\b/.test(value)) return 90;
  if (/\blc\b/.test(value) || /(?:^|[^a-z0-9])lc\d+/i.test(value)) return 86;
  if (value.includes("96f")) return 42;
  if (value.includes("48f")) return 34;
  if (value.includes("ulw") || value.includes("fulw")) return 20;
  if (edge.kind === "link") return 92;
  if (edge.kind === "feeder") return 88;
  if (edge.kind === "cable") return 30;
  return 10;
}

function pathTargetScore(node: GraphNode): number {
  if (node.kind === "exchange") return 1000;
  if (node.kind === "cabinet") return 850;
  if (node.kind === "joint") return 820;
  if (node.kind === "chamber") return 240;
  if (node.kind === "dp") return 160;
  if (node.kind === "pole") return 60;
  return 100;
}

function isBackboneTransitNode(node: GraphNode): boolean {
  return node.kind === "joint" || node.kind === "cabinet" || node.kind === "exchange";
}

function scoreInfrastructureSteps(steps: TopologyTraceStep[], terminalNode?: GraphNode): number {
  const edgeScore = steps.reduce((sum, step) => {
    const asset = step.asset as any;
    if (!asset || asset.geometry?.type !== "LineString") return sum;
    return sum + edgeBackboneScore({
      id: step.id,
      kind: "cable",
      asset,
      from: [0, 0],
      to: [0, 0],
      connectedNodeIds: [],
      lengthMeters: 0,
      visualStyle: "solid",
    });
  }, 0);

  return (terminalNode ? pathTargetScore(terminalNode) : 0) * 10 + edgeScore * 100 + steps.length;
}

function buildInfrastructurePath(selectedAsset: SavedMapAsset, graph: NetworkGraph): TopologyTraceStep[] {
  const selectedNode = findSelectedNode(graph, selectedAsset);
  const selectedEdge = findSelectedEdge(graph, selectedAsset);
  const maxDepth = 18;

  type QueueItem = {
    node: GraphNode;
    steps: TopologyTraceStep[];
    visitedNodes: Set<string>;
    visitedEdges: Set<string>;
  };

  const queue: QueueItem[] = [];

  if (selectedNode && isInfrastructureNode(selectedNode)) {
    queue.push({
      node: selectedNode,
      steps: [nodeStep(selectedNode, "selected")],
      visitedNodes: new Set([selectedNode.id]),
      visitedEdges: new Set(),
    });
  }

  if (selectedEdge && isInfrastructureEdge(selectedEdge)) {
    selectedEdge.connectedNodeIds
      .map((nodeId) => graph.nodes.get(nodeId))
      .filter((node): node is GraphNode => Boolean(node && isInfrastructureNode(node)))
      .forEach((node) => {
        queue.push({
          node,
          steps: [
            edgeStep(selectedEdge, "selected"),
            nodeStep(node, "upstream"),
          ],
          visitedNodes: new Set([node.id]),
          visitedEdges: new Set([selectedEdge.id]),
        });
      });
  }

  if (!queue.length) return [];

  let best = queue[0].steps;
  let bestScore = -Infinity;

  while (queue.length) {
    const current = queue.shift();
    if (!current) break;

    const score = scoreInfrastructureSteps(current.steps, current.node);
    if (score > bestScore) {
      best = current.steps;
      bestScore = score;
    }

    if (current.steps.length >= maxDepth) continue;

    const availableEdges = current.node.connectedTo
      .map((edgeId) => graph.edges.get(edgeId))
      .filter((edge): edge is GraphEdge => Boolean(edge && isInfrastructureEdge(edge)))
      .filter((edge) => !current.visitedEdges.has(edge.id));
    const backboneEdges = availableEdges.filter((edge) => edgeBackboneScore(edge) >= 80);
    const candidateEdges =
      isBackboneTransitNode(current.node) && backboneEdges.length
        ? backboneEdges
        : availableEdges;

    candidateEdges
      .sort((a, b) => edgeBackboneScore(b) - edgeBackboneScore(a))
      .forEach((edge) => {
        const backboneScore = edgeBackboneScore(edge);

        const allNextNodes = edge.connectedNodeIds
          .map((nodeId) => graph.nodes.get(nodeId))
          .filter((node): node is GraphNode => Boolean(node && isInfrastructureNode(node)))
          .filter((nextNode) => !current.visitedNodes.has(nextNode.id));
        const nextNodes =
          backboneScore >= 80
            ? allNextNodes.filter(isBackboneTransitNode)
            : allNextNodes;

        if (!nextNodes.length && backboneScore >= 80) {
          const terminalSteps = [...current.steps, edgeStep(edge, "upstream")];
          const terminalScore = scoreInfrastructureSteps(terminalSteps, current.node);
          if (terminalScore > bestScore) {
            best = terminalSteps;
            bestScore = terminalScore;
          }
          return;
        }

        nextNodes.forEach((nextNode) => {
            const visitedNodes = new Set(current.visitedNodes);
            const visitedEdges = new Set(current.visitedEdges);
            visitedNodes.add(nextNode.id);
            visitedEdges.add(edge.id);

            queue.push({
              node: nextNode,
              visitedNodes,
              visitedEdges,
              steps: [
                ...current.steps,
                edgeStep(edge, "upstream"),
                nodeStep(nextNode, "upstream"),
              ],
            });
          });
      });
  }

  return uniqueSteps(best).slice(0, maxDepth);
}

export function buildTopologyTrace(input: BuildTopologyTraceInput): TopologyTraceResult {
  const { selectedAsset, assets, graph, auditIssues = [] } = input;
  const result = emptyResult(selectedAsset);
  if (!selectedAsset) return result;

  const selectedNode = findSelectedNode(graph, selectedAsset);
  const selectedEdge = findSelectedEdge(graph, selectedAsset);
  const selectedIssues = issuesForAsset(selectedAsset, auditIssues);

  const addQa = (issues: AuditIssue[]) => {
    issues.forEach((issue, index) => {
      result.qa.push({
        id: `${issue.assetId}-${issue.issue}-${index}`,
        title: issue.issue,
        subtitle: `${issue.severity.toUpperCase()} • ${issue.category}`,
        direction: "qa",
        asset: issue.asset,
        warning: issue.issue,
      });
    });
  };

  addQa(selectedIssues);
  result.path = buildInfrastructurePath(selectedAsset, graph);

  if (selectedNode) {
    selectedNode.connectedTo.forEach((edgeId, index) => {
      const edge = graph.edges.get(edgeId);
      if (!edge) return;
      if (isDropCable(edge.asset)) {
        result.homes.push(edgeStep(edge, "home"));
        return;
      }
      result.upstream.push(edgeStep(edge, index === 0 ? "upstream" : "downstream"));
      const connectedNodes = Array.from(graph.nodes.values()).filter((node) => node.id !== selectedNode.id && node.connectedTo.includes(edge.id));
      connectedNodes.forEach((node) => {
        const step = nodeStep(node, isHome(node.asset) ? "home" : "downstream");
        if (isHome(node.asset)) result.homes.push(step);
        else result.downstream.push(step);
        addQa(issuesForAsset(node.asset, auditIssues));
      });
    });
  }

  if (selectedEdge) {
    const connectedNodes = Array.from(graph.nodes.values()).filter((node) => node.connectedTo.includes(selectedEdge.id));
    connectedNodes.forEach((node, index) => {
      const direction: TraceDirection = index === 0 ? "upstream" : isHome(node.asset) ? "home" : "downstream";
      const step = nodeStep(node, direction);
      if (direction === "home") result.homes.push(step);
      else if (direction === "upstream") result.upstream.push(step);
      else result.downstream.push(step);
      addQa(issuesForAsset(node.asset, auditIssues));
    });

    dpsOnCable(selectedEdge.asset, assets).forEach((dp) => {
      result.fibre.push(nodeStep({ id: dp.id, kind: "dp", asset: dp, position: [0, 0], connectedTo: [], connectedNodeIds: [] }, "selected", "Reservation: "));
      branchCablesForDp(dp, assets).forEach((branch) => result.branches.push(edgeStep({ id: branch.id, kind: "cable", asset: branch, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: 0, visualStyle: "solid" }, "branch")));
      dropsForDp(dp, assets).forEach((drop) => result.homes.push(edgeStep({ id: drop.id, kind: "drop", asset: drop, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: Number((drop as any).distanceM || 0), visualStyle: "dashed" }, "home")));
      addQa(issuesForAsset(dp, auditIssues));
    });
  }

  if (isDp(selectedAsset)) {
    const throughCable = cableForDp(selectedAsset, assets);
    if (throughCable) result.upstream.unshift(edgeStep({ id: throughCable.id, kind: "cable", asset: throughCable, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: Number((throughCable as any).lengthMeters || 0), visualStyle: "solid" }, "upstream", "Through cable: "));
    branchCablesForDp(selectedAsset, assets).forEach((branch) => result.branches.push(edgeStep({ id: branch.id, kind: "cable", asset: branch, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: 0, visualStyle: "solid" }, "branch")));
    dropsForDp(selectedAsset, assets).forEach((drop) => result.homes.push(edgeStep({ id: drop.id, kind: "drop", asset: drop, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: Number((drop as any).distanceM || 0), visualStyle: "dashed" }, "home")));
  }

  const autoPlan = (selectedAsset as any)?.dpDetails?.autoFibrePlan;
  if (autoPlan?.allocationTrace?.length) {
    autoPlan.allocationTrace.forEach((row: any, index: number) => {
      result.fibre.push({
        id: `allocation-${index}-${row.assetId || row.assetName}`,
        title: row.assetName || "Allocation step",
        subtitle: row.note || row.cableName || "Fibre allocation",
        direction: "selected",
        fibreText: `${Number(row.totalFibres || 0)}F total • local ${Number(row.localFibres || 0)}F • branch ${Number(row.branchFibres || 0)}F`,
      });
    });
  }

  const cableReservationFibres = isDesignCable(selectedAsset)
    ? dpsOnCable(selectedAsset, assets).reduce((sum, dp) => sum + getReservedFibres(dp), 0)
    : 0;
  const cableUsedFibres = isDesignCable(selectedAsset)
    ? getCableUsedCount(selectedAsset, assets)
    : 0;
  const reservedFibres = isDesignCable(selectedAsset)
    ? Math.max(cableReservationFibres, cableUsedFibres)
    : getReservedFibres(selectedAsset);
  const capacity = parseCapacity(selectedAsset);
  const utilisationPercent = capacity > 0 ? Math.round((reservedFibres / capacity) * 100) : null;

  if (isDesignCable(selectedAsset) && cableUsedFibres > 0 && result.fibre.length === 0) {
    result.fibre.push({
      id: `${selectedAsset.id || assetTitle(selectedAsset)}-cable-usage`,
      title: "Cable fibre usage",
      subtitle: "Used fibres derived from cable mapping / network state",
      direction: "selected",
      asset: selectedAsset,
      fibreText: `${cableUsedFibres}${capacity ? `/${capacity}` : ""}F used`,
    });
  }

  result.upstream = uniqueSteps(result.upstream).slice(0, 12);
  result.downstream = uniqueSteps(result.downstream).slice(0, 12);
  result.branches = uniqueSteps(result.branches).slice(0, 12);
  result.homes = uniqueSteps(result.homes).slice(0, 20);
  result.fibre = uniqueSteps(result.fibre).slice(0, 16);
  result.qa = uniqueSteps(result.qa).slice(0, 16);

  if (capacity > 0 && reservedFibres > capacity) {
    result.warnings.push(`Reserved fibre demand exceeds capacity (${reservedFibres}/${capacity}F).`);
  }
  if (isDp(selectedAsset) && !getDpThroughCableId(selectedAsset)) {
    result.warnings.push("Selected AFN/MDU/DP has no through cable selected.");
  }
  result.qa.filter((step) => step.subtitle.toLowerCase().startsWith("high")).forEach((step) => result.warnings.push(step.title));

  const allRelatedAssets = [
    ...result.upstream.map((step) => step.asset),
    ...result.downstream.map((step) => step.asset),
    ...result.branches.map((step) => step.asset),
    ...result.homes.map((step) => step.asset),
  ].filter(Boolean);

  result.summary = {
    selectedName: assetTitle(selectedAsset),
    selectedType: prettyType(selectedAsset),
    upstreamCount: result.upstream.length,
    downstreamCount: result.downstream.length,
    branchCableCount: result.branches.length,
    connectedHomeCount: result.homes.length + allRelatedAssets.filter(isHome).length,
    connectedDpCount: allRelatedAssets.filter(isDp).length,
    connectedJointCount: allRelatedAssets.filter(isJoint).length,
    reservedFibres,
    capacity,
    utilisationPercent,
    qaHigh: result.qa.filter((step) => step.subtitle.toLowerCase().startsWith("high")).length,
    qaMedium: result.qa.filter((step) => step.subtitle.toLowerCase().startsWith("medium")).length,
    qaLow: result.qa.filter((step) => step.subtitle.toLowerCase().startsWith("low")).length,
  };

  return result;
}
