// =====================================================
// FILE: topologyTraceService.ts
// PURPOSE: Operational trace builder for Project Workspace.
//          Keeps graph/fibre/QA aggregation out of React panels.
//
// IMPORTANT:
// - Does NOT save to Firestore.
// - Does NOT change cable drawing, drop generation or allocation logic.
// - Reads existing networkGraph, DP auto fibre metadata and QA issues only.
// =====================================================

import type { AuditIssue } from "./areaAudit";
import type { NetworkGraph, GraphEdge, GraphNode } from "./networkGraph";
import type { SavedMapAsset } from "../components/map/types";

export type TraceDirection = "selected" | "upstream" | "downstream" | "branch" | "home" | "qa";

export type TopologyTraceStep = {
  id: string;
  title: string;
  subtitle: string;
  direction: TraceDirection;
  asset?: SavedMapAsset | any;
  distanceMeters?: number;
  fibreText?: string;
  warning?: string;
};

export type TopologyTraceSummary = {
  selectedName: string;
  selectedType: string;
  upstreamCount: number;
  downstreamCount: number;
  branchCableCount: number;
  connectedHomeCount: number;
  connectedDpCount: number;
  connectedJointCount: number;
  reservedFibres: number;
  capacity: number;
  utilisationPercent: number | null;
  qaHigh: number;
  qaMedium: number;
  qaLow: number;
};

export type TopologyTraceResult = {
  selectedAsset: SavedMapAsset | null;
  summary: TopologyTraceSummary;
  upstream: TopologyTraceStep[];
  downstream: TopologyTraceStep[];
  branches: TopologyTraceStep[];
  homes: TopologyTraceStep[];
  fibre: TopologyTraceStep[];
  qa: TopologyTraceStep[];
  warnings: string[];
};

type BuildTopologyTraceInput = {
  selectedAsset: SavedMapAsset | null;
  assets: SavedMapAsset[];
  graph: NetworkGraph;
  auditIssues?: AuditIssue[];
};

function text(value: unknown): string {
  return String(value ?? "").trim();
}

function norm(value: unknown): string {
  return text(value).toLowerCase().replace(/[\s_/-]+/g, "");
}

function prettyType(asset: any): string {
  const raw = text(asset?.assetType || asset?.type || asset?.jointType || asset?.cableType || "Asset");
  if (!raw) return "Asset";
  return raw.replace(/-/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());
}

function assetTitle(asset: any): string {
  return text(asset?.name || asset?.jointName || asset?.label || asset?.cableId || asset?.cableName || asset?.assetId || asset?.id || "Asset");
}

function candidateKeys(asset: any): string[] {
  return [
    asset?.id,
    asset?.assetId,
    asset?.name,
    asset?.jointName,
    asset?.label,
    asset?.cableId,
    asset?.cableName,
  ]
    .map(norm)
    .filter(Boolean);
}

function matchesAsset(a: any, b: any): boolean {
  const aKeys = new Set(candidateKeys(a));
  return candidateKeys(b).some((key) => aKeys.has(key));
}

function isCable(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.cableType, asset?.name, asset?.label]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return asset?.geometry?.type === "LineString" || joined.includes("cable") || joined.includes("ulw") || joined.includes("feeder") || joined.includes("link");
}

function isDropCable(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.cableType, asset?.name, asset?.label, asset?.generatedBy]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return joined.includes("drop") || asset?.isDropCable === true || asset?.autoGeneratedDrop === true || Boolean(asset?.homeId || asset?.connectedHomeId || asset?.toHomeId);
}

function isDp(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.jointType, asset?.name, asset?.dpDetails?.closureType]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return joined.includes("distribution") || joined.includes("dp") || joined.includes("afn") || joined.includes("cbt") || joined.includes("mdu");
}

function isJoint(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.jointType, asset?.name]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return joined.includes("joint") || joined.includes("ag") || joined.includes("lmj") || joined.includes("cmj");
}

function isHome(asset: any): boolean {
  const joined = [asset?.assetType, asset?.type, asset?.name]
    .map((value) => text(value).toLowerCase())
    .join(" ");
  return joined.includes("home") || joined.includes("premise") || Boolean(asset?.uprn || asset?.UPRN || asset?.properties?.UPRN);
}

function parseCapacity(asset: any): number {
  const candidates = [asset?.fibreCount, asset?.fiberCount, asset?.size, asset?.cableSize, asset?.name, asset?.label];
  for (const candidate of candidates) {
    const match = text(candidate).match(/(288|144|96|48|36|24|12)\s*F?/i);
    if (match) return Number(match[1]);
  }
  return Number(asset?.capacity || asset?.ports || asset?.dpDetails?.connectionsToHomes || 0) || 0;
}

function getDpThroughCableId(asset: any): string {
  const details = asset?.dpDetails || {};
  return text(details?.afnDetails?.throughCableId || details?.mduDetails?.throughCableId || asset?.parentCableId || "");
}

function getDpInputFibres(asset: any): number[] {
  const details = asset?.dpDetails || {};
  const fibres = details?.afnDetails?.inputFibres || details?.mduDetails?.inputFibres || details?.autoFibrePlan?.inputFibres || [];
  return Array.isArray(fibres)
    ? fibres.map((fibre) => Number(fibre)).filter((fibre) => Number.isFinite(fibre) && fibre > 0)
    : [];
}

function getReservedFibres(asset: any): number {
  const details = asset?.dpDetails || {};
  const autoPlan = details?.autoFibrePlan || {};
  const explicit = Number(autoPlan.reservedFibres || details?.afnDetails?.fibreCountUsed || details?.mduDetails?.totalReservedFibres || 0);
  if (Number.isFinite(explicit) && explicit > 0) return explicit;
  return getDpInputFibres(asset).length;
}

function issueKey(issue: AuditIssue): string[] {
  return [issue.assetId, issue.assetName, (issue as any).asset?.id, (issue as any).asset?.name].map(norm).filter(Boolean);
}

function issuesForAsset(asset: any, issues: AuditIssue[]): AuditIssue[] {
  const keys = new Set(candidateKeys(asset));
  return issues.filter((issue) => issueKey(issue).some((key) => keys.has(key)));
}

function findSelectedNode(graph: NetworkGraph, selectedAsset: SavedMapAsset): GraphNode | null {
  return Array.from(graph.nodes.values()).find((node) => matchesAsset(node.asset, selectedAsset)) || null;
}

function findSelectedEdge(graph: NetworkGraph, selectedAsset: SavedMapAsset): GraphEdge | null {
  return Array.from(graph.edges.values()).find((edge) => matchesAsset(edge.asset, selectedAsset)) || null;
}

function edgeStep(edge: GraphEdge, direction: TraceDirection, titlePrefix = ""): TopologyTraceStep {
  const name = assetTitle(edge.asset);
  return {
    id: edge.id,
    title: `${titlePrefix}${name}`,
    subtitle: `${prettyType(edge.asset)} • ${Math.round(edge.lengthMeters || 0)}m • ${edge.visualStyle}`,
    direction,
    asset: edge.asset,
    distanceMeters: edge.lengthMeters,
    fibreText: isDropCable(edge.asset) ? "Drop" : `${getReservedFibres(edge.asset) || Number((edge.asset as any)?.usedFibres || 0) || 0}/${parseCapacity(edge.asset) || "?"}F`,
  };
}

function nodeStep(node: GraphNode, direction: TraceDirection, titlePrefix = ""): TopologyTraceStep {
  const reserved = getReservedFibres(node.asset);
  const inputFibres = getDpInputFibres(node.asset);
  return {
    id: node.id,
    title: `${titlePrefix}${assetTitle(node.asset)}`,
    subtitle: prettyType(node.asset),
    direction,
    asset: node.asset,
    fibreText: reserved > 0 ? `${reserved} reserved${inputFibres.length ? ` • F${inputFibres.join("/F")}` : ""}` : undefined,
  };
}

function cableReferenceMatches(cable: any, reference: string): boolean {
  if (!reference) return false;
  const ref = norm(reference);
  return candidateKeys(cable).some((key) => key === ref || key.includes(ref) || ref.includes(key));
}

function cableForDp(dp: any, assets: SavedMapAsset[]): SavedMapAsset | null {
  const throughCableId = getDpThroughCableId(dp);
  if (!throughCableId) return null;
  return assets.find((asset) => isCable(asset) && !isDropCable(asset) && cableReferenceMatches(asset, throughCableId)) || null;
}

function dpsOnCable(cable: any, assets: SavedMapAsset[]): SavedMapAsset[] {
  return assets.filter((asset) => isDp(asset) && cableReferenceMatches(cable, getDpThroughCableId(asset)));
}

function dropsForDp(dp: any, assets: SavedMapAsset[]): SavedMapAsset[] {
  const dpKeys = new Set(candidateKeys(dp));
  return assets.filter((asset: any) => {
    if (!isDropCable(asset)) return false;
    const linked = [asset?.dpId, asset?.fromAssetId, asset?.connectedDpId, asset?.parentDpId].map(norm).filter(Boolean);
    return linked.some((key) => dpKeys.has(key));
  });
}

function branchCablesForDp(dp: any, assets: SavedMapAsset[]): SavedMapAsset[] {
  const dpKeys = new Set(candidateKeys(dp));
  const parentCable = getDpThroughCableId(dp);
  return assets.filter((asset: any) => {
    if (!isCable(asset) || isDropCable(asset)) return false;
    if (parentCable && cableReferenceMatches(asset, parentCable)) return false;
    const references = [asset?.parentDpId, asset?.fromAssetId, asset?.sourceAssetId, asset?.aEndAssetId, asset?.fromJointId].map(norm).filter(Boolean);
    return references.some((key) => dpKeys.has(key));
  });
}

function emptyResult(selectedAsset: SavedMapAsset | null): TopologyTraceResult {
  return {
    selectedAsset,
    summary: {
      selectedName: selectedAsset ? assetTitle(selectedAsset) : "No asset selected",
      selectedType: selectedAsset ? prettyType(selectedAsset) : "Asset",
      upstreamCount: 0,
      downstreamCount: 0,
      branchCableCount: 0,
      connectedHomeCount: 0,
      connectedDpCount: 0,
      connectedJointCount: 0,
      reservedFibres: 0,
      capacity: 0,
      utilisationPercent: null,
      qaHigh: 0,
      qaMedium: 0,
      qaLow: 0,
    },
    upstream: [],
    downstream: [],
    branches: [],
    homes: [],
    fibre: [],
    qa: [],
    warnings: [],
  };
}

function uniqueSteps(steps: TopologyTraceStep[]): TopologyTraceStep[] {
  const seen = new Set<string>();
  return steps.filter((step) => {
    const key = `${step.direction}:${step.id}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

export function buildTopologyTrace(input: BuildTopologyTraceInput): TopologyTraceResult {
  const { selectedAsset, assets, graph, auditIssues = [] } = input;
  const result = emptyResult(selectedAsset);
  if (!selectedAsset) return result;

  const selectedNode = findSelectedNode(graph, selectedAsset);
  const selectedEdge = findSelectedEdge(graph, selectedAsset);
  const selectedIssues = issuesForAsset(selectedAsset, auditIssues);

  const addQa = (issues: AuditIssue[]) => {
    issues.forEach((issue, index) => {
      result.qa.push({
        id: `${issue.assetId}-${issue.issue}-${index}`,
        title: issue.issue,
        subtitle: `${issue.severity.toUpperCase()} • ${issue.category}`,
        direction: "qa",
        asset: issue.asset,
        warning: issue.issue,
      });
    });
  };

  addQa(selectedIssues);

  if (selectedNode) {
    selectedNode.connectedTo.forEach((edgeId, index) => {
      const edge = graph.edges.get(edgeId);
      if (!edge) return;
      result.upstream.push(edgeStep(edge, index === 0 ? "upstream" : "downstream"));
      const connectedNodes = Array.from(graph.nodes.values()).filter((node) => node.id !== selectedNode.id && node.connectedTo.includes(edge.id));
      connectedNodes.forEach((node) => {
        const step = nodeStep(node, isHome(node.asset) ? "home" : "downstream");
        if (isHome(node.asset)) result.homes.push(step);
        else result.downstream.push(step);
        addQa(issuesForAsset(node.asset, auditIssues));
      });
    });
  }

  if (selectedEdge) {
    const connectedNodes = Array.from(graph.nodes.values()).filter((node) => node.connectedTo.includes(selectedEdge.id));
    connectedNodes.forEach((node, index) => {
      const direction: TraceDirection = index === 0 ? "upstream" : isHome(node.asset) ? "home" : "downstream";
      const step = nodeStep(node, direction);
      if (direction === "home") result.homes.push(step);
      else if (direction === "upstream") result.upstream.push(step);
      else result.downstream.push(step);
      addQa(issuesForAsset(node.asset, auditIssues));
    });

    dpsOnCable(selectedEdge.asset, assets).forEach((dp) => {
      result.fibre.push(nodeStep({ id: dp.id, kind: "dp", asset: dp, position: [0, 0], connectedTo: [], connectedNodeIds: [] }, "selected", "Reservation: "));
      branchCablesForDp(dp, assets).forEach((branch) => result.branches.push(edgeStep({ id: branch.id, kind: "cable", asset: branch, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: 0, visualStyle: "solid" }, "branch")));
      dropsForDp(dp, assets).forEach((drop) => result.homes.push(edgeStep({ id: drop.id, kind: "drop", asset: drop, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: Number((drop as any).distanceM || 0), visualStyle: "dashed" }, "home")));
      addQa(issuesForAsset(dp, auditIssues));
    });
  }

  if (isDp(selectedAsset)) {
    const throughCable = cableForDp(selectedAsset, assets);
    if (throughCable) result.upstream.unshift(edgeStep({ id: throughCable.id, kind: "cable", asset: throughCable, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: Number((throughCable as any).lengthMeters || 0), visualStyle: "solid" }, "upstream", "Through cable: "));
    branchCablesForDp(selectedAsset, assets).forEach((branch) => result.branches.push(edgeStep({ id: branch.id, kind: "cable", asset: branch, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: 0, visualStyle: "solid" }, "branch")));
    dropsForDp(selectedAsset, assets).forEach((drop) => result.homes.push(edgeStep({ id: drop.id, kind: "drop", asset: drop, from: [0, 0], to: [0, 0], connectedNodeIds: [], lengthMeters: Number((drop as any).distanceM || 0), visualStyle: "dashed" }, "home")));
  }

  const autoPlan = (selectedAsset as any)?.dpDetails?.autoFibrePlan;
  if (autoPlan?.allocationTrace?.length) {
    autoPlan.allocationTrace.forEach((row: any, index: number) => {
      result.fibre.push({
        id: `allocation-${index}-${row.assetId || row.assetName}`,
        title: row.assetName || "Allocation step",
        subtitle: row.note || row.cableName || "Fibre allocation",
        direction: "selected",
        fibreText: `${Number(row.totalFibres || 0)}F total • local ${Number(row.localFibres || 0)}F • branch ${Number(row.branchFibres || 0)}F`,
      });
    });
  }

  const reservedFibres = isCable(selectedAsset)
    ? dpsOnCable(selectedAsset, assets).reduce((sum, dp) => sum + getReservedFibres(dp), 0)
    : getReservedFibres(selectedAsset);
  const capacity = parseCapacity(selectedAsset);
  const utilisationPercent = capacity > 0 ? Math.round((reservedFibres / capacity) * 100) : null;

  result.upstream = uniqueSteps(result.upstream).slice(0, 12);
  result.downstream = uniqueSteps(result.downstream).slice(0, 12);
  result.branches = uniqueSteps(result.branches).slice(0, 12);
  result.homes = uniqueSteps(result.homes).slice(0, 20);
  result.fibre = uniqueSteps(result.fibre).slice(0, 16);
  result.qa = uniqueSteps(result.qa).slice(0, 16);

  if (capacity > 0 && reservedFibres > capacity) {
    result.warnings.push(`Reserved fibre demand exceeds capacity (${reservedFibres}/${capacity}F).`);
  }
  if (isDp(selectedAsset) && !getDpThroughCableId(selectedAsset)) {
    result.warnings.push("Selected AFN/MDU/DP has no through cable selected.");
  }
  result.qa.filter((step) => step.subtitle.toLowerCase().startsWith("high")).forEach((step) => result.warnings.push(step.title));

  const allRelatedAssets = [
    ...result.upstream.map((step) => step.asset),
    ...result.downstream.map((step) => step.asset),
    ...result.branches.map((step) => step.asset),
    ...result.homes.map((step) => step.asset),
  ].filter(Boolean);

  result.summary = {
    selectedName: assetTitle(selectedAsset),
    selectedType: prettyType(selectedAsset),
    upstreamCount: result.upstream.length,
    downstreamCount: result.downstream.length,
    branchCableCount: result.branches.length,
    connectedHomeCount: result.homes.length + allRelatedAssets.filter(isHome).length,
    connectedDpCount: allRelatedAssets.filter(isDp).length,
    connectedJointCount: allRelatedAssets.filter(isJoint).length,
    reservedFibres,
    capacity,
    utilisationPercent,
    qaHigh: result.qa.filter((step) => step.subtitle.toLowerCase().startsWith("high")).length,
    qaMedium: result.qa.filter((step) => step.subtitle.toLowerCase().startsWith("medium")).length,
    qaLow: result.qa.filter((step) => step.subtitle.toLowerCase().startsWith("low")).length,
  };

  return result;
}
