import React, { useMemo, useState } from "react";
import type { LatLngLiteral } from "leaflet";
import type { SavedMapAsset, DistributionPointDetails } from "../map/types";
import { getPathDistanceMeters } from "../../utils/mapMeasure";

type DistributionChoice = "CBT" | "AFN";
type BuildMethod = "oh" | "ug_preferred" | "mixed";

type AutoNetworkSettings = {
  distribution: DistributionChoice;
  cbtPorts: 8 | 12;
  buildMethod: BuildMethod;
  maxOhSpanSameSide: number;
  maxOhSpanRoadCrossing: number;
  cbtMaxRun: number;
  poleDropRiseAllowance: number;
  allowNewPoles: boolean;
  includeAlreadyConnectedHomes: boolean;
};

type PlannedCluster = {
  id: string;
  name: string;
  dpId: string;
  poleId: string;
  centre: LatLngLiteral;
  homes: SavedMapAsset[];
  longestDropMeters: number;
  totalDropMeters: number;
  warnings: string[];
};

type AutoNetworkPlan = {
  clusters: PlannedCluster[];
  newAssets: SavedMapAsset[];
  warnings: string[];
  summary: {
    homesConsidered: number;
    homesAssigned: number;
    polesCreated: number;
    dpsCreated: number;
    dropsCreated: number;
    warnings: number;
    totalDropMeters: number;
  };
};

type Props = {
  assets: SavedMapAsset[];
  scopeArea?: SavedMapAsset | null;
  onBack: () => void;
  onApply: (assetsToMerge: SavedMapAsset[]) => void;
};

const DEFAULT_SETTINGS: AutoNetworkSettings = {
  distribution: "CBT",
  cbtPorts: 12,
  buildMethod: "mixed",
  maxOhSpanSameSide: 85,
  maxOhSpanRoadCrossing: 75,
  cbtMaxRun: 350,
  poleDropRiseAllowance: 18,
  allowNewPoles: true,
  includeAlreadyConnectedHomes: false,
};

function getAssetPoint(asset: SavedMapAsset): LatLngLiteral | null {
  const flatLat = Number((asset as any).lat);
  const flatLng = Number((asset as any).lng);

  if (Number.isFinite(flatLat) && Number.isFinite(flatLng)) {
    return { lat: flatLat, lng: flatLng };
  }

  if (asset.geometry?.type === "Point" && Array.isArray(asset.geometry.coordinates)) {
    const [lat, lng] = asset.geometry.coordinates as any;
    const nextLat = Number(lat);
    const nextLng = Number(lng);
    if (Number.isFinite(nextLat) && Number.isFinite(nextLng)) {
      return { lat: nextLat, lng: nextLng };
    }
  }

  return null;
}

function getAreaPolygon(areaAsset?: SavedMapAsset | null): [number, number][] {
  if (!areaAsset || areaAsset.geometry?.type !== "Polygon") return [];

  const ring = areaAsset.geometry.coordinates?.[0] || [];

  return ring
    .map((point: unknown) => point as [number, number])
    .filter(
      (point) =>
        Array.isArray(point) &&
        typeof point[0] === "number" &&
        typeof point[1] === "number",
    );
}

function pointInPolygon(point: LatLngLiteral, polygon: [number, number][]): boolean {
  if (polygon.length < 3) return true;

  const lat = point.lat;
  const lng = point.lng;
  let inside = false;

  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const [latI, lngI] = polygon[i];
    const [latJ, lngJ] = polygon[j];

    const intersects =
      lngI > lng !== lngJ > lng &&
      lat <
        ((latJ - latI) * (lng - lngI)) /
          (lngJ - lngI || Number.EPSILON) +
          latI;

    if (intersects) inside = !inside;
  }

  return inside;
}

function assetIsInsideArea(asset: SavedMapAsset, areaAsset?: SavedMapAsset | null): boolean {
  const polygon = getAreaPolygon(areaAsset);
  if (!polygon.length) return true;

  const point = getAssetPoint(asset);
  if (!point) return false;

  return pointInPolygon(point, polygon);
}

function hasExistingHomeConnection(home: SavedMapAsset) {
  return Boolean(
    (home as any).connectedDpId ||
      (home as any).connection === "connected" ||
      (home as any).connectionMode === "manual" ||
      (home as any).connectionMode === "auto-network",
  );
}

function makePointAsset(args: {
  id: string;
  name: string;
  assetType: "pole" | "distribution-point";
  point: LatLngLiteral;
  jointType: string;
  extras?: Record<string, unknown>;
}): SavedMapAsset {
  return {
    id: args.id,
    name: args.name,
    assetType: args.assetType,
    jointType: args.jointType,
    notes: "Generated by Auto Network Designer preview/apply.",
    geometry: {
      type: "Point",
      coordinates: [args.point.lat, args.point.lng],
    },
    lat: args.point.lat,
    lng: args.point.lng,
    ...(args.extras || {}),
  } as SavedMapAsset;
}

function makeLineCableAsset(args: {
  id: string;
  name: string;
  from: LatLngLiteral;
  to: LatLngLiteral;
  fromAssetId: string;
  toAssetId: string;
  dpId: string;
  homeId: string;
  lengthMeters: number;
}): SavedMapAsset {
  return {
    id: args.id,
    name: args.name,
    assetType: "cable",
    jointType: "Drop Cable",
    cableType: "Drop" as any,
    installMethod: "OH" as any,
    notes: "Auto-generated drop from Auto Network Designer.",
    geometry: {
      type: "LineString",
      coordinates: [
        [args.from.lat, args.from.lng],
        [args.to.lat, args.to.lng],
      ],
    },
    fromAssetId: args.fromAssetId,
    toAssetId: args.toAssetId,
    dpId: args.dpId,
    homeId: args.homeId,
    routeLengthMeters: Math.round(args.lengthMeters),
    source: "auto-network",
  } as SavedMapAsset;
}

function centreOfHomes(homes: SavedMapAsset[]): LatLngLiteral {
  const points = homes.map(getAssetPoint).filter(Boolean) as LatLngLiteral[];

  if (!points.length) return { lat: 0, lng: 0 };

  return {
    lat: points.reduce((sum, p) => sum + p.lat, 0) / points.length,
    lng: points.reduce((sum, p) => sum + p.lng, 0) / points.length,
  };
}

function buildAutoNetworkPlan(
  assets: SavedMapAsset[],
  settings: AutoNetworkSettings,
): AutoNetworkPlan {
  const runId = `auto-${Date.now()}`;
  const homes = assets
    .filter((asset) => asset.assetType === "home")
    .filter((home) => Boolean(getAssetPoint(home)))
    .filter((home) => settings.includeAlreadyConnectedHomes || !hasExistingHomeConnection(home));

  const capacity = settings.distribution === "CBT" ? settings.cbtPorts : 8;
  const unassigned = new Set(homes.map((home) => home.id));
  const clusters: PlannedCluster[] = [];
  const warnings: string[] = [];
  const newAssets: SavedMapAsset[] = [];

  let clusterIndex = 0;

  while (unassigned.size > 0) {
    const seed = homes.find((home) => unassigned.has(home.id));
    if (!seed) break;

    const seedPoint = getAssetPoint(seed);
    if (!seedPoint) {
      unassigned.delete(seed.id);
      continue;
    }

    const nearest = homes
      .filter((home) => unassigned.has(home.id))
      .map((home) => {
        const point = getAssetPoint(home)!;
        return {
          home,
          distance: getPathDistanceMeters([seedPoint, point]),
        };
      })
      .sort((a, b) => a.distance - b.distance)
      .slice(0, capacity)
      .map((item) => item.home);

    nearest.forEach((home) => unassigned.delete(home.id));
    clusterIndex += 1;

    const centre = centreOfHomes(nearest);
    const padded = String(clusterIndex).padStart(3, "0");
    const poleId = `${runId}-pole-${padded}`;
    const dpId = `${runId}-dp-${padded}`;
    const dpName = `AUTO-${settings.distribution}-${padded}`;
    const poleName = `AUTO-POLE-${padded}`;

    const dpDetails: DistributionPointDetails = {
      powerReadings: ["", "", "", ""],
      closureType: settings.distribution,
      connectionsToHomes: capacity,
      buildStatus: "Auto Network Preview",
      afnDetails:
        settings.distribution === "AFN"
          ? {
              enabled: true,
              fibreCountUsed: nearest.length,
              inputFibres: Array.from({ length: Math.min(nearest.length, 8) }, (_, i) => i + 1),
              splitterRatio: "1:8",
              splitterOutputs: 8,
            }
          : undefined,
    };

    const poleAsset = makePointAsset({
      id: poleId,
      name: poleName,
      assetType: "pole",
      point: centre,
      jointType: "New Pole",
      extras: {
        poleDetails: {
          poleType: settings.allowNewPoles ? "new" : "or",
          locationType: "House Boundary",
        },
        source: "auto-network",
      },
    });

    const dpAsset = makePointAsset({
      id: dpId,
      name: dpName,
      assetType: "distribution-point",
      point: centre,
      jointType: settings.distribution,
      extras: {
        dpDetails,
        capacity,
        ports: capacity,
        source: "auto-network",
      },
    });

    newAssets.push(poleAsset, dpAsset);

    const clusterWarnings: string[] = [];
    let longestDropMeters = 0;
    let totalDropMeters = 0;

    nearest.forEach((home, homeIndex) => {
      const homePoint = getAssetPoint(home)!;
      const straightLine = getPathDistanceMeters([centre, homePoint]);
      const engineeredLength = straightLine + settings.poleDropRiseAllowance;
      longestDropMeters = Math.max(longestDropMeters, engineeredLength);
      totalDropMeters += engineeredLength;

      if (engineeredLength > settings.maxOhSpanSameSide) {
        clusterWarnings.push(
          `${String(home.name || home.id)} drop is ${Math.round(engineeredLength)}m. Suggest intermediate pole/chamber route.`,
        );
      }

      if (engineeredLength > settings.cbtMaxRun) {
        clusterWarnings.push(
          `${String(home.name || home.id)} exceeds ${settings.cbtMaxRun}m CBT run. Joint required before final drop.`,
        );
      }

      const dropId = `${runId}-drop-${padded}-${String(homeIndex + 1).padStart(2, "0")}`;
      newAssets.push(
        makeLineCableAsset({
          id: dropId,
          name: `${dpName}-DROP-${homeIndex + 1}`,
          from: centre,
          to: homePoint,
          fromAssetId: dpId,
          toAssetId: home.id,
          dpId,
          homeId: home.id,
          lengthMeters: engineeredLength,
        }),
      );

      newAssets.push({
        ...(home as any),
        connectedDpId: dpId,
        connection: "connected",
        connectionMode: "auto-network",
        autoNetworkDpName: dpName,
        updatedAt: new Date().toISOString(),
      } as SavedMapAsset);
    });

    if (!settings.allowNewPoles) {
      clusterWarnings.push("Budget disallows new poles. Treat AUTO-POLE as suggested location only.");
    }

    if (settings.buildMethod === "ug_preferred") {
      clusterWarnings.push("UG preferred: feeder/link route should use chambers/14/10 duct in later phase.");
    }

    warnings.push(...clusterWarnings.map((warning) => `${dpName}: ${warning}`));

    clusters.push({
      id: `${runId}-cluster-${padded}`,
      name: dpName,
      dpId,
      poleId,
      centre,
      homes: nearest,
      longestDropMeters,
      totalDropMeters,
      warnings: clusterWarnings,
    });
  }

  return {
    clusters,
    newAssets,
    warnings,
    summary: {
      homesConsidered: homes.length,
      homesAssigned: clusters.reduce((sum, cluster) => sum + cluster.homes.length, 0),
      polesCreated: clusters.length,
      dpsCreated: clusters.length,
      dropsCreated: clusters.reduce((sum, cluster) => sum + cluster.homes.length, 0),
      warnings: warnings.length,
      totalDropMeters: clusters.reduce((sum, cluster) => sum + cluster.totalDropMeters, 0),
    },
  };
}

function formatMeters(value: number) {
  if (value >= 1000) return `${(value / 1000).toFixed(2)} km`;
  return `${Math.round(value)} m`;
}

function PreviewMap({ assets, plan }: { assets: SavedMapAsset[]; plan: AutoNetworkPlan }) {
  const homes = assets.filter((asset) => asset.assetType === "home").filter((asset) => Boolean(getAssetPoint(asset)));
  const dpPoints = plan.clusters.map((cluster) => cluster.centre);
  const points = [...homes.map((home) => getAssetPoint(home)!), ...dpPoints];

  if (!points.length) {
    return <div style={emptyPreviewStyle}>No homes with coordinates found.</div>;
  }

  const minLat = Math.min(...points.map((p) => p.lat));
  const maxLat = Math.max(...points.map((p) => p.lat));
  const minLng = Math.min(...points.map((p) => p.lng));
  const maxLng = Math.max(...points.map((p) => p.lng));
  const width = 900;
  const height = 520;
  const pad = 36;

  const project = (point: LatLngLiteral) => {
    const x = pad + ((point.lng - minLng) / Math.max(0.000001, maxLng - minLng)) * (width - pad * 2);
    const y = height - pad - ((point.lat - minLat) / Math.max(0.000001, maxLat - minLat)) * (height - pad * 2);
    return { x, y };
  };

  return (
    <svg viewBox={`0 0 ${width} ${height}`} style={{ width: "100%", height: "100%", background: "#020617", borderRadius: 14 }}>
      {plan.clusters.flatMap((cluster) => {
        const start = project(cluster.centre);
        return cluster.homes.map((home) => {
          const point = getAssetPoint(home)!;
          const end = project(point);
          return <line key={`${cluster.id}-${home.id}`} x1={start.x} y1={start.y} x2={end.x} y2={end.y} stroke="#22c55e" strokeWidth={1.4} opacity={0.45} />;
        });
      })}

      {homes.map((home) => {
        const point = project(getAssetPoint(home)!);
        return <circle key={home.id} cx={point.x} cy={point.y} r={3.5} fill="#94a3b8" opacity={0.8} />;
      })}

      {plan.clusters.map((cluster) => {
        const point = project(cluster.centre);
        return (
          <g key={cluster.id}>
            <rect x={point.x - 7} y={point.y - 7} width={14} height={14} rx={3} fill="#2563eb" stroke="#ffffff" strokeWidth={2} />
            <text x={point.x + 10} y={point.y + 4} fill="#e5e7eb" fontSize={11} fontWeight={800}>{cluster.homes.length}</text>
          </g>
        );
      })}
    </svg>
  );
}

export default function AutoNetworkDesigner({ assets, scopeArea, onBack, onApply }: Props) {
  const [settings, setSettings] = useState<AutoNetworkSettings>(DEFAULT_SETTINGS);
  const [plan, setPlan] = useState<AutoNetworkPlan | null>(null);
  const [hasApplied, setHasApplied] = useState(false);

  const scopedAssets = useMemo(
    () => (scopeArea ? assets.filter((asset) => assetIsInsideArea(asset, scopeArea)) : []),
    [assets, scopeArea],
  );

  const scopeName = String((scopeArea as any)?.name || (scopeArea as any)?.label || "No area selected");
  const canPreview = Boolean(scopeArea) && scopedAssets.some((asset) => asset.assetType === "home");

  const homeStats = useMemo(() => {
    const homes = scopedAssets.filter((asset) => asset.assetType === "home");
    const connected = homes.filter(hasExistingHomeConnection).length;
    return { homes: homes.length, connected, unconnected: homes.length - connected };
  }, [scopedAssets]);

  const update = <K extends keyof AutoNetworkSettings>(key: K, value: AutoNetworkSettings[K]) => {
    setSettings((prev) => ({ ...prev, [key]: value }));
    setHasApplied(false);
  };

  const handlePreview = () => {
    if (!canPreview) return;
    setPlan(buildAutoNetworkPlan(scopedAssets, settings));
    setHasApplied(false);
  };

  const handleApply = () => {
    if (!scopeArea || !plan) return;
    onApply(plan.newAssets);
    setHasApplied(true);
  };

  return (
    <div style={screenStyle}>
      <aside style={sideStyle}>
        <button type="button" onClick={onBack} style={secondaryButtonStyle}>← Back to Map</button>

        <div>
          <h1 style={{ margin: "14px 0 4px", fontSize: 24 }}>Auto Network Designer</h1>
          <div style={{ color: "#94a3b8", fontSize: 13 }}>
            Preview-only rules engine for CBT / AFN access design. Apply only when the proposal looks right.
          </div>
        </div>

        <div style={noticeStyle}>
          <strong>V1 safety rules</strong>
          <div>Creates suggested poles, DPs and drops only. Feeder/link routes are not generated yet.</div>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionTitleStyle}>Design Scope</h3>
          <div style={{ fontSize: 13, color: "#cbd5e1", lineHeight: 1.45 }}>
            {scopeArea ? (
              <>
                Auto network is scoped to:
                <br />
                <strong style={{ color: "white" }}>{scopeName}</strong>
              </>
            ) : (
              <>
                No project area selected.
                <br />
                <strong style={{ color: "#fbbf24" }}>Go back and select an area first</strong>
              </>
            )}
          </div>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionTitleStyle}>Distribution</h3>

          <label style={labelStyle}>Closure type</label>
          <select value={settings.distribution} onChange={(e) => update("distribution", e.target.value as DistributionChoice)} style={inputStyle}>
            <option value="CBT">CBT</option>
            <option value="AFN">AFN pass-through</option>
          </select>

          <label style={labelStyle}>CBT ports / capacity</label>
          <select value={settings.cbtPorts} onChange={(e) => update("cbtPorts", Number(e.target.value) as 8 | 12)} style={inputStyle} disabled={settings.distribution === "AFN"}>
            <option value={8}>8 ports</option>
            <option value={12}>12 ports</option>
          </select>

          <label style={labelStyle}>Build method</label>
          <select value={settings.buildMethod} onChange={(e) => update("buildMethod", e.target.value as BuildMethod)} style={inputStyle}>
            <option value="mixed">Mixed build</option>
            <option value="oh">Overhead only</option>
            <option value="ug_preferred">UG preferred for feeder/link</option>
          </select>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionTitleStyle}>Engineering Rules</h3>

          <NumberInput label="OH span same side road max" value={settings.maxOhSpanSameSide} suffix="m" onChange={(value) => update("maxOhSpanSameSide", value)} />
          <NumberInput label="OH road crossing max" value={settings.maxOhSpanRoadCrossing} suffix="m" onChange={(value) => update("maxOhSpanRoadCrossing", value)} />
          <NumberInput label="CBT max run before joint" value={settings.cbtMaxRun} suffix="m" onChange={(value) => update("cbtMaxRun", value)} />
          <NumberInput label="Pole down/up allowance" value={settings.poleDropRiseAllowance} suffix="m" onChange={(value) => update("poleDropRiseAllowance", value)} />

          <label style={checkStyle}>
            <input type="checkbox" checked={settings.allowNewPoles} onChange={(e) => update("allowNewPoles", e.target.checked)} />
            Budget allows suggested new poles
          </label>

          <label style={checkStyle}>
            <input type="checkbox" checked={settings.includeAlreadyConnectedHomes} onChange={(e) => update("includeAlreadyConnectedHomes", e.target.checked)} />
            Include already connected homes
          </label>
        </div>

        <div style={sectionStyle}>
          <h3 style={sectionTitleStyle}>Homes</h3>
          <div style={miniStatGridStyle}>
            <MiniStat label="Total" value={homeStats.homes} />
            <MiniStat label="Connected" value={homeStats.connected} />
            <MiniStat label="Available" value={settings.includeAlreadyConnectedHomes ? homeStats.homes : homeStats.unconnected} />
          </div>
        </div>

        <button
          type="button"
          onClick={handlePreview}
          disabled={!canPreview}
          style={{
            ...primaryButtonStyle,
            background: !canPreview ? "#475569" : primaryButtonStyle.background,
            cursor: !canPreview ? "not-allowed" : "pointer",
          }}
        >
          {scopeArea ? "Preview Design" : "Select Area First"}
        </button>
        <button type="button" onClick={handleApply} disabled={!scopeArea || !plan || hasApplied} style={{ ...primaryButtonStyle, background: !scopeArea || !plan || hasApplied ? "#475569" : "#16a34a" }}>
          {hasApplied ? "Applied to Map" : "Apply to Live Map"}
        </button>
      </aside>

      <main style={mainStyle}>
        <div style={topBarStyle}>
          <div>
            <div style={{ fontSize: 13, color: "#94a3b8" }}>Auto build preview</div>
            <h2 style={{ margin: 0 }}>Suggested {settings.distribution} network</h2>
          </div>
          <div style={{ color: "#94a3b8", fontSize: 13 }}>OH {settings.maxOhSpanSameSide}m · crossing {settings.maxOhSpanRoadCrossing}m · CBT run {settings.cbtMaxRun}m</div>
        </div>

        {plan ? (
          <>
            <div style={kpiGridStyle}>
              <Kpi label="Homes assigned" value={plan.summary.homesAssigned} sub={`${plan.summary.homesConsidered} considered`} />
              <Kpi label="DPs / closures" value={plan.summary.dpsCreated} sub={settings.distribution} />
              <Kpi label="New poles" value={plan.summary.polesCreated} sub={settings.allowNewPoles ? "allowed" : "suggested only"} />
              <Kpi label="Drop route" value={formatMeters(plan.summary.totalDropMeters)} sub={`${plan.summary.dropsCreated} drops`} />
              <Kpi label="Warnings" value={plan.summary.warnings} sub={plan.summary.warnings ? "review required" : "clear"} tone={plan.summary.warnings ? "warn" : "ok"} />
            </div>

            <div style={previewBoxStyle}>
              <PreviewMap assets={scopedAssets} plan={plan} />
            </div>

            <div style={gridTwoStyle}>
              <div style={tableCardStyle}>
                <h3 style={{ marginTop: 0 }}>Closure groups</h3>
                <div style={{ display: "grid", gap: 8 }}>
                  {plan.clusters.map((cluster) => (
                    <div key={cluster.id} style={rowStyle}>
                      <div>
                        <strong>{cluster.name}</strong>
                        <div style={mutedStyle}>{cluster.homes.length} homes · longest drop {formatMeters(cluster.longestDropMeters)}</div>
                      </div>
                      <div style={{ color: cluster.warnings.length ? "#fbbf24" : "#22c55e", fontWeight: 900 }}>
                        {cluster.warnings.length ? `${cluster.warnings.length} warning` : "OK"}
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div style={tableCardStyle}>
                <h3 style={{ marginTop: 0 }}>Warnings</h3>
                {plan.warnings.length ? (
                  <div style={{ display: "grid", gap: 8 }}>
                    {plan.warnings.slice(0, 60).map((warning, index) => (
                      <div key={`${warning}-${index}`} style={warningStyle}>{warning}</div>
                    ))}
                  </div>
                ) : (
                  <div style={mutedStyle}>No warnings on this preview.</div>
                )}
              </div>
            </div>
          </>
        ) : (
          <div style={emptyStateStyle}>
            <h2>Ready to preview</h2>
            <p>Choose CBT/AFN rules on the left, then click Preview Design.</p>
          </div>
        )}
      </main>
    </div>
  );
}

function NumberInput({ label, value, suffix, onChange }: { label: string; value: number; suffix: string; onChange: (value: number) => void }) {
  return (
    <label style={labelStyle}>
      {label}
      <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
        <input type="number" value={value} min={0} onChange={(e) => onChange(Number(e.target.value))} style={inputStyle} />
        <span style={{ color: "#94a3b8", width: 28 }}>{suffix}</span>
      </div>
    </label>
  );
}

function MiniStat({ label, value }: { label: string; value: string | number }) {
  return (
    <div style={miniStatStyle}>
      <div style={{ color: "#94a3b8", fontSize: 11 }}>{label}</div>
      <div style={{ fontWeight: 900, fontSize: 18 }}>{value}</div>
    </div>
  );
}

function Kpi({ label, value, sub, tone }: { label: string; value: string | number; sub: string; tone?: "ok" | "warn" }) {
  return (
    <div style={{ ...kpiStyle, borderColor: tone === "warn" ? "#f59e0b" : tone === "ok" ? "#22c55e" : "#334155" }}>
      <div style={{ color: "#94a3b8", fontSize: 12 }}>{label}</div>
      <div style={{ fontSize: 26, fontWeight: 950 }}>{value}</div>
      <div style={{ color: "#64748b", fontSize: 12 }}>{sub}</div>
    </div>
  );
}

const screenStyle: React.CSSProperties = { height: "100vh", width: "100vw", display: "grid", gridTemplateColumns: "360px 1fr", background: "#020617", color: "white", overflow: "hidden" };
const sideStyle: React.CSSProperties = { borderRight: "1px solid #1e293b", padding: 16, overflowY: "auto", background: "#0f172a", display: "flex", flexDirection: "column", gap: 14 };
const mainStyle: React.CSSProperties = { overflowY: "auto", padding: 18, background: "#020617" };
const topBarStyle: React.CSSProperties = { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "center", marginBottom: 14 };
const sectionStyle: React.CSSProperties = { border: "1px solid #334155", borderRadius: 14, padding: 12, background: "#111827" };
const sectionTitleStyle: React.CSSProperties = { margin: "0 0 10px", fontSize: 14 };
const labelStyle: React.CSSProperties = { display: "block", color: "#cbd5e1", fontSize: 12, fontWeight: 800, marginTop: 8, marginBottom: 5 };
const inputStyle: React.CSSProperties = { width: "100%", boxSizing: "border-box", border: "1px solid #334155", background: "#020617", color: "white", borderRadius: 10, padding: "9px 10px" };
const checkStyle: React.CSSProperties = { display: "flex", gap: 8, alignItems: "center", color: "#cbd5e1", fontSize: 13, marginTop: 10 };
const primaryButtonStyle: React.CSSProperties = { border: "none", background: "#2563eb", color: "white", borderRadius: 12, padding: "11px 14px", cursor: "pointer", fontWeight: 900 };
const secondaryButtonStyle: React.CSSProperties = { border: "1px solid #334155", background: "#1f2937", color: "white", borderRadius: 12, padding: "10px 14px", cursor: "pointer", fontWeight: 900 };
const noticeStyle: React.CSSProperties = { border: "1px solid #0369a1", background: "rgba(14,165,233,0.12)", borderRadius: 12, padding: 10, color: "#bae6fd", fontSize: 12, lineHeight: 1.4 };
const miniStatGridStyle: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 8 };
const miniStatStyle: React.CSSProperties = { background: "#020617", border: "1px solid #334155", borderRadius: 10, padding: 9 };
const kpiGridStyle: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(5, minmax(130px, 1fr))", gap: 12, marginBottom: 14 };
const kpiStyle: React.CSSProperties = { border: "1px solid #334155", borderRadius: 14, background: "#0f172a", padding: 14 };
const previewBoxStyle: React.CSSProperties = { height: 430, border: "1px solid #334155", borderRadius: 16, overflow: "hidden", marginBottom: 14, background: "#020617" };
const emptyPreviewStyle: React.CSSProperties = { display: "grid", placeItems: "center", height: "100%", color: "#94a3b8" };
const gridTwoStyle: React.CSSProperties = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 };
const tableCardStyle: React.CSSProperties = { border: "1px solid #334155", borderRadius: 14, padding: 14, background: "#0f172a" };
const rowStyle: React.CSSProperties = { display: "flex", justifyContent: "space-between", gap: 10, alignItems: "center", border: "1px solid #1e293b", background: "#020617", borderRadius: 10, padding: 10 };
const mutedStyle: React.CSSProperties = { color: "#94a3b8", fontSize: 12 };
const warningStyle: React.CSSProperties = { color: "#fbbf24", background: "rgba(245,158,11,0.10)", border: "1px solid rgba(245,158,11,0.24)", borderRadius: 10, padding: 9, fontSize: 12 };
const emptyStateStyle: React.CSSProperties = { height: "calc(100vh - 80px)", display: "grid", placeItems: "center", textAlign: "center", color: "#94a3b8" };
