import { useMemo } from "react";
import { getPathDistanceMeters } from "../../../utils/mapMeasure";
import type { SavedMapAsset } from "../types";

export type ProjectWorkspaceStats = {
  homesPassed: number;
  homesConnected: number;
  rfsPercent: number;
  issueCount: number;
  topologyLinks: number;
  splicePoints: number;
  joints: number;
  dps: number;
  streetCabs: number;
  poles: number;
  chambers: number;
  cables: number;
  designCables: number;
  dropCables: number;
  routeLengthMeters: number;
};

type Args = {
  visibleProjectAssets: SavedMapAsset[];
  topologyLinks: number;
};

export function useProjectWorkspaceStats({
  visibleProjectAssets,
  topologyLinks,
}: Args): ProjectWorkspaceStats {
  return useMemo(() => {
    const norm = (value: unknown) => String(value ?? "").toLowerCase();

    const isType = (asset: SavedMapAsset, tokens: string[]) => {
      const item = asset as any;
      const haystack = `${norm(item.assetType)} ${norm(item.type)} ${norm(
        item.jointType,
      )} ${norm(item.name)} ${norm(item.dpType)}`;
      return tokens.some((token) => haystack.includes(token));
    };

    const isLineCable = (asset: SavedMapAsset) =>
      asset.assetType === "cable" ||
      asset.geometry?.type === "LineString" ||
      isType(asset, ["cable"]);

    const isDropCableAsset = (asset: SavedMapAsset) => {
      const item = asset as any;
      const haystack = `${norm(item.assetType)} ${norm(item.type)} ${norm(
        item.cableType,
      )} ${norm(item.name)} ${norm(item.label)} ${norm(item.generatedBy)}`;

      return (
        isLineCable(asset) &&
        (haystack.includes("drop") ||
          item.isDropCable === true ||
          item.isHomeDrop === true ||
          item.generatedDrop === true ||
          item.autoGeneratedDrop === true ||
          item.dropCable === true ||
          Boolean(
            item.homeId ||
              item.connectedHomeId ||
              item.toHomeId ||
              item.fromHomeId,
          ))
      );
    };

    const isDpClosureAsset = (asset: SavedMapAsset) => {
      if (isDropCableAsset(asset)) return false;
      const item = asset as any;
      const hasPointGeometry =
        asset.geometry?.type === "Point" ||
        (typeof item.lat === "number" && typeof item.lng === "number");

      if (!hasPointGeometry) return false;

      const haystack = `${norm(item.assetType)} ${norm(item.type)} ${norm(
        item.jointType,
      )} ${norm(item.name)} ${norm(item.dpType)} ${norm(item.closureType)}`;

      return (
        haystack.includes("distribution-point") ||
        haystack.includes("distribution point") ||
        haystack.includes("dp") ||
        haystack.includes("cbt") ||
        haystack.includes("afn")
      );
    };

    const cables = visibleProjectAssets.filter(isLineCable);
    const dropCables = cables.filter(isDropCableAsset);
    const designCables = cables.filter((asset) => !isDropCableAsset(asset));

    const isHomePremiseAsset = (asset: SavedMapAsset) => {
      const item = asset as any;
      const hasPointGeometry =
        asset.geometry?.type === "Point" ||
        (typeof item.lat === "number" && typeof item.lng === "number");

      if (!hasPointGeometry) return false;
      if (isLineCable(asset) || isDropCableAsset(asset) || isDpClosureAsset(asset)) {
        return false;
      }

      const haystack = `${norm(item.assetType)} ${norm(item.type)} ${norm(
        item.homeType,
      )} ${norm(item.name)} ${norm(item.label)}`;
      const hasHomeIdentifier = Boolean(
        item.uprn ||
          item.UPRN ||
          item.homeId ||
          item.properties?.UPRN ||
          item.properties?.uprn,
      );

      return (
        hasHomeIdentifier ||
        haystack.includes("home") ||
        haystack.includes("premise") ||
        haystack.includes("sdu") ||
        haystack.includes("flat")
      );
    };

    const homeKey = (asset: SavedMapAsset) => {
      const item = asset as any;
      const rawKey =
        item.uprn ||
        item.UPRN ||
        item.properties?.UPRN ||
        item.properties?.uprn ||
        item.homeId ||
        item.address ||
        item.label ||
        item.name ||
        item.id;

      if (rawKey) return String(rawKey).trim().toLowerCase();

      if (asset.geometry?.type === "Point") {
        const [lat, lng] = asset.geometry.coordinates as [number, number];
        return `${Number(lat).toFixed(7)},${Number(lng).toFixed(7)}`;
      }

      return "";
    };

    const homesByKey = new Map<string, SavedMapAsset>();
    visibleProjectAssets.filter(isHomePremiseAsset).forEach((asset) => {
      const key = homeKey(asset);
      if (key && !homesByKey.has(key)) homesByKey.set(key, asset);
    });

    const homes = Array.from(homesByKey.values());
    const connectedHomes = homes.filter((asset: any) =>
      Boolean(
        asset.connectedDpId ||
          asset.connectedDP ||
          asset.dpId ||
          asset.connection === "connected" ||
          asset.status === "connected",
      ),
    );

    const routeLengthMeters = cables.reduce((total, asset) => {
      if (asset.geometry?.type !== "LineString") return total;
      const points = asset.geometry.coordinates.map(([lat, lng]) => ({ lat, lng }));
      return total + getPathDistanceMeters(points);
    }, 0);

    const issueCount = visibleProjectAssets.filter((asset: any) => {
      const status = norm(asset.status);
      return Boolean(
        asset.auditIssue ||
          asset.auditFail ||
          asset.missingPia ||
          status.includes("fail") ||
          status.includes("issue"),
      );
    }).length;

    const jointCount = visibleProjectAssets.filter((asset) =>
      isType(asset, ["joint", "cmj", "lmj", "mmj"]),
    ).length;

    return {
      homesPassed: homes.length,
      homesConnected: connectedHomes.length,
      rfsPercent: homes.length
        ? Math.round((connectedHomes.length / homes.length) * 100)
        : 0,
      issueCount,
      topologyLinks,
      splicePoints: jointCount,
      joints: jointCount,
      dps: visibleProjectAssets.filter(isDpClosureAsset).length,
      streetCabs: visibleProjectAssets.filter((asset) =>
        isType(asset, ["street cab", "streetcab", "cabinet"]),
      ).length,
      poles: visibleProjectAssets.filter((asset) => isType(asset, ["pole"]))
        .length,
      chambers: visibleProjectAssets.filter((asset) =>
        isType(asset, ["chamber", "manhole"]),
      ).length,
      cables: designCables.length,
      designCables: designCables.length,
      dropCables: dropCables.length,
      routeLengthMeters,
    };
  }, [visibleProjectAssets, topologyLinks]);
}
