import type { LayerVisibility } from "../../components/map/hooks/useLayerVisibility";
import type { SavedMapAsset } from "../../components/map/types";
import { shouldRequestSpatialAssetType } from "../../config/assetZoomRules";

export type CableLayerKind =
  | "feeder"
  | "link"
  | "drop"
  | "ulw96"
  | "ulw48"
  | "ulw36"
  | "ulw24"
  | "ulw12"
  | "cable";

export function normaliseAssetText(value: unknown): string {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[\s_/-]+/g, " ");
}

export function getAssetClassificationText(asset: SavedMapAsset): string {
  const item = asset as any;

  return [
    item.assetType,
    item.type,
    item.jointType,
    item.cableType,
    item.name,
    item.label,
    item.category,
    item.source,
    item.referenceSubtype,
    item.homeType,
    item.dpType,
    item.closureType,
    item.fibreCount,
    item.fiberCount,
    item.size,
    item.cableSize,
    item.importedProperties?.assetType,
    item.importedProperties?.assetSubtype,
    item.importedProperties?.sourceRevision,
    item.properties?.assetType,
    item.properties?.assetSubtype,
  ]
    .map(normaliseAssetText)
    .filter(Boolean)
    .join(" ");
}

export function hasPointGeometry(asset: SavedMapAsset): boolean {
  const item = asset as any;
  return (
    asset.geometry?.type === "Point" ||
    (typeof item.lat === "number" && typeof item.lng === "number")
  );
}

export function hasLineGeometry(asset: SavedMapAsset): boolean {
  return (
    asset.geometry?.type === "LineString" ||
    asset.geometry?.type === "MultiLineString"
  );
}

export function hasAreaGeometry(asset: SavedMapAsset): boolean {
  return asset.geometry?.type === "Polygon" || asset.geometry?.type === "MultiPolygon";
}

export function isCableAsset(asset: SavedMapAsset): boolean {
  const text = getAssetClassificationText(asset);
  return (
    hasLineGeometry(asset) &&
    (text.includes("cable") ||
      text.includes("feeder") ||
      text.includes("link") ||
      /\b(96|48|36|24|12)\s*f?\b/.test(text))
  );
}

export function isDropCableAsset(asset: SavedMapAsset): boolean {
  const item = asset as any;
  const text = getAssetClassificationText(asset);

  return (
    isCableAsset(asset) &&
    (text.includes("drop") ||
      text.includes("home drop") ||
      text.includes("home tail") ||
      item.isDropCable === true ||
      item.isHomeDrop === true ||
      item.generatedDrop === true ||
      item.autoGeneratedDrop === true ||
      item.dropCable === true ||
      Boolean(item.homeId || item.connectedHomeId || item.toHomeId || item.fromHomeId))
  );
}

export function getCableFibreCountForLayer(asset: SavedMapAsset): number | null {
  const item = asset as any;
  const candidates = [
    item.fibreCount,
    item.fiberCount,
    item.size,
    item.cableSize,
    item.name,
    item.cableId,
    item.label,
    item.cableType,
    item.importedProperties?.assetSubtype,
  ];

  for (const candidate of candidates) {
    const match = String(candidate ?? "").toUpperCase().match(/(288|144|96|48|36|24|12)\s*F?/);
    if (match) return Number(match[1]);
  }

  return null;
}

export function getCableLayerKind(asset: SavedMapAsset): CableLayerKind | null {
  if (!isCableAsset(asset)) return null;
  if (isDropCableAsset(asset)) return "drop";

  const text = getAssetClassificationText(asset);
  if (text.includes("feeder")) return "feeder";
  if (text.includes("link")) return "link";

  switch (getCableFibreCountForLayer(asset)) {
    case 96:
      return "ulw96";
    case 48:
      return "ulw48";
    case 36:
      return "ulw36";
    case 24:
      return "ulw24";
    case 12:
      return "ulw12";
    default:
      return "cable";
  }
}

export function isHomeAsset(asset: SavedMapAsset): boolean {
  const item = asset as any;
  if (!hasPointGeometry(asset) || isCableAsset(asset) || isDistributionPointAsset(asset)) {
    return false;
  }

  const text = getAssetClassificationText(asset);
  return Boolean(
    item.uprn ||
      item.UPRN ||
      item.properties?.UPRN ||
      item.properties?.uprn ||
      item.homeId ||
      text.includes("home") ||
      text.includes("premise") ||
      text.includes("property") ||
      text.includes("sdu") ||
      text.includes("flat")
  );
}

export function isDistributionPointAsset(asset: SavedMapAsset): boolean {
  if (!hasPointGeometry(asset) || isDropCableAsset(asset)) return false;
  const text = getAssetClassificationText(asset);
  return (
    text.includes("distribution point") ||
    text.includes("distribution-point") ||
    text.includes("dp") ||
    text.includes("cbt") ||
    text.includes("afn") ||
    text.includes("mdu")
  );
}

export function isJointAsset(asset: SavedMapAsset): boolean {
  if (!hasPointGeometry(asset) || isDistributionPointAsset(asset)) return false;
  const text = getAssetClassificationText(asset);
  return text.includes("joint") || text.includes("cmj") || text.includes("lmj") || text.includes("mmj");
}

export function isAreaAsset(asset: SavedMapAsset): boolean {
  const text = getAssetClassificationText(asset);
  return (
    hasAreaGeometry(asset) &&
    (text.includes("area") ||
      text.includes("polygon") ||
      text.includes("project area"))
  );
}

export function getSpatialAssetTypesForLayers(
  visibleLayers: LayerVisibility,
  zoom: number,
): string[] {
  const types = new Set<string>();

  if (visibleLayers.agJoints) {
    types.add("ag-joint");
    types.add("joint");
  }

  if (visibleLayers.streetCabs) types.add("street-cab");

  if (visibleLayers.distributionPoints) {
    types.add("distribution-point");
    types.add("dp");
  }

  if (visibleLayers.poles) types.add("pole");
  if (visibleLayers.chambers) types.add("chamber");

  if (visibleLayers.cables) {
    types.add("cable");
    types.add("feederCable");
    types.add("linkCable");
    types.add("drop-cable");
  }

  if (visibleLayers.homes) types.add("home");

  if (visibleLayers.areas) {
    types.add("area");
    types.add("polygon");
    types.add("project-area");
    types.add("ag-polygon");
  }

  return Array.from(types).filter((assetType) =>
    shouldRequestSpatialAssetType(assetType, zoom),
  );
}
