import type { SavedMapAsset } from "../../map/types";

// =====================================================
// FILE: canonicalHomeStatus.ts
// PURPOSE: Shared workspace home/drop/SB counting logic.
//          This is the single source of truth for operational home counts.
//          It never writes to Firestore and never changes chunk storage.
// =====================================================

export type CanonicalHomeStatus = "unconnected" | "connected" | "live";

export type CanonicalHomeRecord = {
  key: string;
  home: SavedMapAsset;
  status: CanonicalHomeStatus;
  linkedDrop?: SavedMapAsset;
  splitterBox?: string;
  connectedDpId?: string;
};

export type CanonicalHomeSummary = {
  homes: SavedMapAsset[];
  records: CanonicalHomeRecord[];
  homesPassed: number;
  homesConnected: number;
  homesLive: number;
  homesNotLive: number;
  drops: SavedMapAsset[];
};

function text(value: unknown): string {
  return String(value ?? "").trim();
}

function norm(value: unknown): string {
  return text(value).toLowerCase();
}

export function getCanonicalHomeKey(asset: SavedMapAsset | null | undefined): string {
  const item = asset as any;
  if (!item) return "";

  const raw =
    item.uprn ||
    item.UPRN ||
    item.properties?.UPRN ||
    item.properties?.uprn ||
    item.homeId ||
    item.addressBaseUprn ||
    item.address ||
    item.fullAddress ||
    item.label ||
    item.name ||
    item.id;

  if (raw) return norm(raw).replace(/^uprn-/, "");

  if (asset?.geometry?.type === "Point" && Array.isArray(asset.geometry.coordinates)) {
    const [lat, lng] = asset.geometry.coordinates as any;
    if (Number.isFinite(Number(lat)) && Number.isFinite(Number(lng))) {
      return `${Number(lat).toFixed(7)},${Number(lng).toFixed(7)}`;
    }
  }

  return "";
}

export function getCanonicalAssetKeys(asset: SavedMapAsset | null | undefined): string[] {
  const item = asset as any;
  if (!item) return [];

  const base = [
    item.id,
    item.assetId,
    item.name,
    item.jointName,
    item.label,
    item.homeId,
    item.uprn,
    item.UPRN,
    item.properties?.UPRN,
    item.properties?.uprn,
    item.connectedHomeId,
    item.toHomeId,
    item.fromHomeId,
  ]
    .map((value) => norm(value).replace(/^uprn-/, ""))
    .filter(Boolean);

  const keys = new Set<string>();
  base.forEach((key) => {
    keys.add(key);
    keys.add(`uprn-${key}`);
  });
  return Array.from(keys);
}

export function isCanonicalHomeDropCable(asset: SavedMapAsset | null | undefined): boolean {
  if (!asset) return false;
  const item = asset as any;
  const hasLineGeometry = asset.geometry?.type === "LineString";
  const typeText = norm(item.assetType || item.type);
  const looksLikeCable = hasLineGeometry || typeText.includes("cable") || text(item.cableType).length > 0;

  if (!looksLikeCable) return false;

  const haystack = [
    item.assetType,
    item.type,
    item.cableType,
    item.name,
    item.label,
    item.category,
    item.kind,
    item.installType,
    item.source,
    item.generatedBy,
    item.generationMode,
  ]
    .map(norm)
    .join(" ");

  return (
    haystack.includes("drop") ||
    haystack.includes("home-drop") ||
    haystack.includes("home drop") ||
    haystack.includes("drop-cable") ||
    haystack.includes("drop cable") ||
    item.isDropCable === true ||
    item.isHomeDrop === true ||
    item.generatedDrop === true ||
    item.autoGeneratedDrop === true ||
    item.dropCable === true ||
    Boolean(item.homeId || item.connectedHomeId || item.toHomeId || item.fromHomeId)
  );
}

export function isCanonicalInfrastructureAsset(asset: SavedMapAsset | null | undefined): boolean {
  if (!asset) return false;
  if (isCanonicalHomeDropCable(asset)) return true;
  const item = asset as any;
  const haystack = [
    item.assetType,
    item.type,
    item.jointType,
    item.cableType,
    item.name,
    item.label,
    item.category,
    item.dpType,
    item.distributionPointType,
    item.closureType,
  ]
    .map(norm)
    .join(" ");

  return (
    asset.geometry?.type === "LineString" ||
    haystack.includes("cable") ||
    haystack.includes("joint") ||
    haystack.includes("pole") ||
    haystack.includes("chamber") ||
    haystack.includes("cabinet") ||
    haystack.includes("street cab") ||
    haystack.includes("streetcab") ||
    haystack.includes("distribution-point") ||
    haystack.includes("distribution point") ||
    haystack.includes("cbt") ||
    haystack.includes("afn")
  );
}

export function isCanonicalHomeAsset(asset: SavedMapAsset | null | undefined): boolean {
  if (!asset) return false;
  const item = asset as any;
  const hasPointGeometry =
    asset.geometry?.type === "Point" ||
    (typeof item.lat === "number" && typeof item.lng === "number");

  if (!hasPointGeometry) return false;
  if (isCanonicalInfrastructureAsset(asset)) return false;

  const haystack = [item.assetType, item.type, item.name, item.label, item.homeType, item.category]
    .map(norm)
    .join(" ");

  return Boolean(
    item.uprn ||
      item.UPRN ||
      item.properties?.UPRN ||
      item.properties?.uprn ||
      item.homeId ||
      haystack.includes("home") ||
      haystack.includes("premise") ||
      haystack.includes("property") ||
      haystack.includes("sdu") ||
      haystack.includes("flat"),
  );
}

export function uniqueCanonicalHomes(assets: SavedMapAsset[]): SavedMapAsset[] {
  const byKey = new Map<string, SavedMapAsset>();
  assets.filter(isCanonicalHomeAsset).forEach((home) => {
    const key = getCanonicalHomeKey(home);
    if (key && !byKey.has(key)) byKey.set(key, home);
  });
  return Array.from(byKey.values());
}

function normaliseHomeStatus(value: unknown): string {
  return text(value).toLowerCase().replace(/\s+/g, "_").replace(/-/g, "_");
}

export function dropLinksToCanonicalHome(drop: SavedMapAsset, home: SavedMapAsset): boolean {
  if (!isCanonicalHomeDropCable(drop)) return false;
  const homeKeys = new Set(getCanonicalAssetKeys(home));
  const dropKeys = getCanonicalAssetKeys(drop);
  return dropKeys.some((key) => homeKeys.has(key));
}

export function getCanonicalHomeConnectionStatus(
  home: SavedMapAsset,
  allAssets: SavedMapAsset[],
): CanonicalHomeStatus {
  const item = home as any;
  const ownStatus = normaliseHomeStatus(
    item.customerStatus ||
      item.homeStatus ||
      item.status ||
      item.buildStatus ||
      item.serviceStatus ||
      item.connectionStatus ||
      item.properties?.status,
  );

  if (ownStatus === "live") return "live";

  const metadataConnection = norm(item.connection || item.properties?.connection);
  if (
    item.connectedDpId ||
    item.properties?.connectedDpId ||
    item.connectedDP ||
    item.dpId ||
    metadataConnection === "connected" ||
    ownStatus === "connected"
  ) {
    return "connected";
  }

  const linkedDrop = allAssets.find((asset) => dropLinksToCanonicalHome(asset, home));
  if (!linkedDrop) return "unconnected";

  const dropItem = linkedDrop as any;
  const dropStatus = normaliseHomeStatus(
    dropItem.customerStatus || dropItem.homeStatus || dropItem.status || dropItem.serviceStatus,
  );

  return dropStatus === "live" ? "live" : "connected";
}

export function buildCanonicalHomeSummary(assets: SavedMapAsset[]): CanonicalHomeSummary {
  const homes = uniqueCanonicalHomes(assets);
  const drops = assets.filter(isCanonicalHomeDropCable);

  const records = homes.map((home) => {
    const item = home as any;
    const linkedDrop = assets.find((asset) => dropLinksToCanonicalHome(asset, home));
    const status = getCanonicalHomeConnectionStatus(home, assets);
    return {
      key: getCanonicalHomeKey(home),
      home,
      status,
      linkedDrop,
      splitterBox: text(item.splitterBox || item.splitter_box || item.sbId || item.assignedSplitterBox),
      connectedDpId: text(item.connectedDpId || item.properties?.connectedDpId || item.connectedDP || item.dpId),
    };
  });

  const homesLive = records.filter((record) => record.status === "live").length;
  const homesConnected = records.filter((record) => record.status !== "unconnected").length;

  return {
    homes,
    records,
    homesPassed: homes.length,
    homesConnected,
    homesLive,
    homesNotLive: Math.max(homes.length - homesLive, 0),
    drops,
  };
}

export function clampCanonicalCount(value: unknown, min: number, max: number, fallback: number): number {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) return fallback;
  return Math.max(min, Math.min(max, numeric));
}
