import React, { useMemo, useState } from "react";
import type { SavedMapAsset, AssetStatus, DistributionArchitecture } from "../../map/types";
import LiveHomesTable from "./LiveHomesTable";

export type LiveHomesDpRow = {
  dp: SavedMapAsset;
  name: string;
  closureType: DistributionArchitecture | "UNKNOWN";
  status: AssetStatus | "Unknown";
  homesServed: number;
  liveHomes: number;
  notLiveHomes: number;
  dropCableCount: number;
  capacity: number;
  capacityUsed: number;
  capacityPercent: number;
  capacityWarning: string;
  operationalRisk: "OK" | "WARN" | "FULL" | "OVER";
};

type Props = {
  projectAssets: SavedMapAsset[];
  onSelectAsset?: (asset: SavedMapAsset) => void;
  onOpenAsset?: (asset: SavedMapAsset) => void;
};

type LiveFilter = "all" | "live" | "notLive" | "bwip" | "unserviceable" | "lnrfs";
type ClosureFilter = "all" | DistributionArchitecture;

const STATUS_LABELS: Record<string, string> = {
  Live: "Live",
  BWIP: "BWIP",
  Unserviceable: "Unserviceable",
  "Live not ready for service": "Live not ready for service",
};

function text(value: unknown): string {
  return String(value ?? "").trim();
}

function norm(value: unknown): string {
  return text(value).toLowerCase();
}

function assetName(asset: SavedMapAsset): string {
  const item = asset as any;
  return text(item.name || item.jointName || item.label || item.assetId || item.id || "Unnamed DP");
}

function assetKeys(asset: any): string[] {
  return [asset?.id, asset?.assetId, asset?.name, asset?.jointName, asset?.label, asset?.dpId]
    .map((value) => text(value).toLowerCase())
    .filter(Boolean);
}

function isDp(asset: SavedMapAsset): boolean {
  const item = asset as any;
  const haystack = [item.assetType, item.type, item.jointType, item.dpType, item.distributionPointType, item.name, item.dpDetails?.closureType]
    .map(norm)
    .join(" ");
  return (
    asset.geometry?.type === "Point" &&
    (haystack.includes("distribution") || haystack.includes("dp") || haystack.includes("cbt") || haystack.includes("afn") || haystack.includes("mdu"))
  );
}

function isHome(asset: SavedMapAsset): boolean {
  const item = asset as any;
  const haystack = [item.assetType, item.type, item.name, item.homeType].map(norm).join(" ");
  return haystack.includes("home") || haystack.includes("premise") || Boolean(item.uprn || item.UPRN || item.properties?.UPRN);
}

function isDropCable(asset: SavedMapAsset): boolean {
  const item = asset as any;
  const haystack = [item.assetType, item.type, item.cableType, item.name, item.label, item.generatedBy]
    .map(norm)
    .join(" ");
  return asset.geometry?.type === "LineString" && (haystack.includes("drop") || item.isDropCable === true || item.autoGeneratedDrop === true || item.generatedDrop === true || Boolean(item.homeId || item.connectedHomeId));
}

function closureType(asset: SavedMapAsset): DistributionArchitecture | "UNKNOWN" {
  const item = asset as any;
  const raw = text(item.dpDetails?.closureType || item.dpDetails?.networkArchitecture || item.closureType || item.networkArchitecture || item.dpType || item.jointType).toUpperCase();
  if (raw.includes("MDU_SPLITTER")) return "MDU_SPLITTER";
  if (raw.includes("MDU")) return "MDU";
  if (raw.includes("AFN")) return "AFN";
  if (raw.includes("CBT")) return "CBT";
  return "UNKNOWN";
}

function dpStatus(asset: SavedMapAsset): AssetStatus | "Unknown" {
  const item = asset as any;
  const raw = text(item.status || item.dpDetails?.buildStatus || item.buildStatus || item.serviceStatus || item.dpStatus);
  if (raw === "Live") return "Live";
  if (raw === "BWIP") return "BWIP";
  if (raw === "Unserviceable") return "Unserviceable";
  if (raw === "Live not ready for service") return "Live not ready for service";
  return raw ? (raw as AssetStatus) : "Unknown";
}

function dpCapacity(asset: SavedMapAsset, servedHomes: number): number {
  const item = asset as any;
  const raw = Number(item.capacity || item.dpCapacity || item.ports || item.dpDetails?.connectionsToHomes || item.dpDetails?.capacity || 0);
  if (Number.isFinite(raw) && raw > 0) return raw;
  const closure = closureType(asset);
  if (closure === "CBT") return 12;
  if (closure === "AFN" || closure === "MDU_SPLITTER") return Math.max(16, servedHomes);
  if (closure === "MDU") return Math.max(servedHomes, 0);
  return Math.max(servedHomes, 0);
}


function getCapacityWarning(capacity: number, capacityUsed: number): { warning: string; risk: "OK" | "WARN" | "FULL" | "OVER" } {
  if (capacity <= 0) return { warning: "No capacity set", risk: "WARN" };
  if (capacityUsed > capacity) return { warning: "Over capacity", risk: "OVER" };
  if (capacityUsed === capacity) return { warning: "Full", risk: "FULL" };
  const percent = (capacityUsed / capacity) * 100;
  if (percent >= 80) return { warning: "Near capacity", risk: "WARN" };
  return { warning: "Capacity OK", risk: "OK" };
}

function valueMatchesAny(value: unknown, lookup: Set<string>): boolean {
  const key = text(value).toLowerCase();
  return Boolean(key && lookup.has(key));
}

function homesForDp(dp: SavedMapAsset, homes: SavedMapAsset[], drops: SavedMapAsset[]): SavedMapAsset[] {
  const dpKeySet = new Set(assetKeys(dp));
  const homeKeysFromDrops = new Set<string>();

  drops.forEach((drop: any) => {
    const dropDpKeys = [drop.dpId, drop.fromAssetId, drop.connectedDpId, drop.parentDpId, drop.sourceAssetId].map((value) => text(value).toLowerCase()).filter(Boolean);
    if (!dropDpKeys.some((key) => dpKeySet.has(key))) return;
    [drop.homeId, drop.toAssetId, drop.connectedHomeId, drop.uprn, drop.UPRN].forEach((value) => {
      const key = text(value).toLowerCase();
      if (key) homeKeysFromDrops.add(key);
    });
  });

  return homes.filter((home: any) => {
    const directDp = [home.connectedDpId, home.dpId, home.parentDpId, home.properties?.connectedDpId, home.properties?.dpId]
      .some((value) => valueMatchesAny(value, dpKeySet));
    if (directDp) return true;

    const homeKeySet = new Set(assetKeys(home));
    [home.homeId, home.uprn, home.UPRN, home.properties?.UPRN, home.properties?.uprn].forEach((value) => {
      const key = text(value).toLowerCase();
      if (key) {
        homeKeySet.add(key);
        homeKeySet.add(key.replace(/^uprn-/, ""));
        homeKeySet.add(`uprn-${key.replace(/^uprn-/, "")}`);
      }
    });

    return Array.from(homeKeySet).some((key) => homeKeysFromDrops.has(key) || homeKeysFromDrops.has(key.replace(/^uprn-/, "")) || homeKeysFromDrops.has(`uprn-${key.replace(/^uprn-/, "")}`));
  });
}

function dropsForDp(dp: SavedMapAsset, drops: SavedMapAsset[]): SavedMapAsset[] {
  const dpKeySet = new Set(assetKeys(dp));
  return drops.filter((drop: any) => [drop.dpId, drop.fromAssetId, drop.connectedDpId, drop.parentDpId, drop.sourceAssetId].some((value) => valueMatchesAny(value, dpKeySet)));
}

function buildRows(projectAssets: SavedMapAsset[]): LiveHomesDpRow[] {
  const dps = projectAssets.filter(isDp);
  const homes = projectAssets.filter(isHome);
  const drops = projectAssets.filter(isDropCable);

  return dps.map((dp) => {
    const servedHomes = homesForDp(dp, homes, drops);
    const dpDrops = dropsForDp(dp, drops);
    const status = dpStatus(dp);
    const isLive = status === "Live";
    const capacity = dpCapacity(dp, servedHomes.length);
    const capacityUsed = Math.max(servedHomes.length, dpDrops.length);
    const capacityPercent = capacity > 0 ? (capacityUsed / capacity) * 100 : 0;
    const capacityState = getCapacityWarning(capacity, capacityUsed);

    return {
      dp,
      name: assetName(dp),
      closureType: closureType(dp),
      status,
      homesServed: servedHomes.length,
      liveHomes: isLive ? servedHomes.length : 0,
      notLiveHomes: isLive ? 0 : servedHomes.length,
      dropCableCount: dpDrops.length,
      capacity,
      capacityUsed,
      capacityPercent,
      capacityWarning: capacityState.warning,
      operationalRisk: capacityState.risk,
    };
  }).sort((a, b) => a.name.localeCompare(b.name, undefined, { numeric: true }));
}

export default function LiveHomesControl({ projectAssets, onSelectAsset, onOpenAsset }: Props) {
  const [search, setSearch] = useState("");
  const [liveFilter, setLiveFilter] = useState<LiveFilter>("all");
  const [closureFilter, setClosureFilter] = useState<ClosureFilter>("all");
  const [selectedDpId, setSelectedDpId] = useState("");

  const rows = useMemo(() => buildRows(projectAssets), [projectAssets]);

  const filteredRows = useMemo(() => {
    const query = search.trim().toLowerCase();
    return rows.filter((row) => {
      if (closureFilter !== "all" && row.closureType !== closureFilter) return false;
      if (liveFilter === "live" && row.status !== "Live") return false;
      if (liveFilter === "notLive" && row.status === "Live") return false;
      if (liveFilter === "bwip" && row.status !== "BWIP") return false;
      if (liveFilter === "unserviceable" && row.status !== "Unserviceable") return false;
      if (liveFilter === "lnrfs" && row.status !== "Live not ready for service") return false;
      if (!query) return true;
      return `${row.name} ${row.dp.id} ${row.closureType} ${row.status}`.toLowerCase().includes(query);
    });
  }, [rows, search, liveFilter, closureFilter]);

  const selectedRow = useMemo(
    () => rows.find((row) => row.dp.id === selectedDpId) || filteredRows[0] || null,
    [rows, filteredRows, selectedDpId],
  );

  const summary = useMemo(() => {
    const totalHomes = filteredRows.reduce((sum, row) => sum + row.homesServed, 0);
    const liveHomes = filteredRows.reduce((sum, row) => sum + row.liveHomes, 0);
    const drops = filteredRows.reduce((sum, row) => sum + row.dropCableCount, 0);
    const nearCapacity = filteredRows.filter((row) => row.operationalRisk === "WARN" || row.operationalRisk === "FULL").length;
    const overCapacity = filteredRows.filter((row) => row.operationalRisk === "OVER").length;
    return {
      dps: filteredRows.length,
      totalHomes,
      liveHomes,
      notLiveHomes: Math.max(totalHomes - liveHomes, 0),
      drops,
      nearCapacity,
      overCapacity,
      livePercent: totalHomes ? Math.round((liveHomes / totalHomes) * 100) : 0,
    };
  }, [filteredRows]);

  return (
    <section style={widePanel}>
      <div style={headerRow}>
        <div>
          <div style={kicker}>LIVE HOMES / RFS CONTROL</div>
          <h3 style={title}>DP Live Homes Control</h3>
          <p style={muted}>Manager view of which DPs are live and how many homes they release.</p>
        </div>
        <select
          value={selectedRow?.dp.id || ""}
          onChange={(event) => {
            setSelectedDpId(event.target.value);
            const next = rows.find((row) => row.dp.id === event.target.value);
            if (next) onSelectAsset?.(next.dp);
          }}
          style={select}
        >
          {rows.map((row) => <option key={row.dp.id} value={row.dp.id}>{row.name} — {row.status}</option>)}
        </select>
      </div>

      <div style={metricGrid}>
        <Metric label="DPs" value={summary.dps} />
        <Metric label="Homes" value={summary.totalHomes} />
        <Metric label="Live Homes" value={summary.liveHomes} good />
        <Metric label="Not Live" value={summary.notLiveHomes} warn={summary.notLiveHomes > 0} />
        <Metric label="Drops" value={summary.drops} />
        <Metric label="Near Cap" value={summary.nearCapacity} warn={summary.nearCapacity > 0} />
        <Metric label="Over Cap" value={summary.overCapacity} warn={summary.overCapacity > 0} />
        <Metric label="Live %" value={`${summary.livePercent}%`} good={summary.livePercent === 100} />
      </div>

      <div style={filterGrid}>
        <input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search DP, status, closure..." style={input} />
        <select value={liveFilter} onChange={(event) => setLiveFilter(event.target.value as LiveFilter)} style={select}>
          <option value="all">All live states</option>
          <option value="live">Live DPs</option>
          <option value="notLive">Not live DPs</option>
          <option value="bwip">BWIP</option>
          <option value="unserviceable">Unserviceable</option>
          <option value="lnrfs">Live not ready for service</option>
        </select>
        <select value={closureFilter} onChange={(event) => setClosureFilter(event.target.value as ClosureFilter)} style={select}>
          <option value="all">All closure types</option>
          <option value="CBT">CBT</option>
          <option value="AFN">AFN</option>
          <option value="MDU">MDU</option>
          <option value="MDU_SPLITTER">MDU_SPLITTER</option>
        </select>
      </div>

      {selectedRow ? (
        <div style={selectedCard}>
          <div>
            <div style={kicker}>SELECTED DP</div>
            <strong>{selectedRow.name}</strong>
            <span>{selectedRow.closureType} • {selectedRow.status}</span>
          </div>
          <div style={selectedStats}>
            <span>{selectedRow.liveHomes}/{selectedRow.homesServed} homes live</span>
            <span>{selectedRow.dropCableCount} drops</span>
            <span>{selectedRow.capacityUsed}/{selectedRow.capacity || "—"} capacity</span>
            <span style={{ color: selectedRow.operationalRisk === "OK" ? "#4ade80" : selectedRow.operationalRisk === "OVER" ? "#fb7185" : "#fbbf24" }}>{selectedRow.capacityWarning}</span>
          </div>
          <div style={{ display: "flex", gap: 8 }}>
            <button type="button" style={button} onClick={() => onSelectAsset?.(selectedRow.dp)}>Focus DP</button>
            <button type="button" style={button} onClick={() => onOpenAsset?.(selectedRow.dp)}>Open Details</button>
          </div>
        </div>
      ) : null}

      <LiveHomesTable
        rows={filteredRows}
        selectedDpId={selectedRow?.dp.id}
        onSelectDp={(dpId) => {
          setSelectedDpId(dpId);
          const row = rows.find((item) => item.dp.id === dpId);
          if (row) onSelectAsset?.(row.dp);
        }}
        onFocusDp={onSelectAsset}
        onOpenDp={onOpenAsset}
      />
    </section>
  );
}

function Metric({ label, value, good = false, warn = false }: { label: string; value: React.ReactNode; good?: boolean; warn?: boolean }) {
  return <div style={metricCard}><span>{label}</span><strong style={{ color: good ? "#4ade80" : warn ? "#fbbf24" : "#f8fafc" }}>{value}</strong></div>;
}

const widePanel: React.CSSProperties = { background: "#0f1b2d", border: "1px solid rgba(96,165,250,0.28)", borderRadius: 12, padding: 16, gridColumn: "span 2", display: "grid", gap: 13 };
const headerRow: React.CSSProperties = { display: "flex", justifyContent: "space-between", gap: 16, alignItems: "flex-start" };
const kicker: React.CSSProperties = { color: "#93c5fd", fontSize: 11, fontWeight: 900, letterSpacing: 0.5 };
const title: React.CSSProperties = { margin: "4px 0 2px", fontSize: 18, color: "#e5e7eb" };
const muted: React.CSSProperties = { margin: 0, color: "#94a3b8", fontSize: 12 };
const metricGrid: React.CSSProperties = { display: "grid", gridTemplateColumns: "repeat(8, minmax(95px, 1fr))", gap: 9 };
const metricCard: React.CSSProperties = { background: "#0b1424", border: "1px solid rgba(148,163,184,0.14)", borderRadius: 10, padding: 11, display: "grid", gap: 5, color: "#94a3b8", fontSize: 11 };
const filterGrid: React.CSSProperties = { display: "grid", gridTemplateColumns: "minmax(220px, 1fr) 180px 180px", gap: 9 };
const input: React.CSSProperties = { background: "#081225", color: "#e5e7eb", border: "1px solid #334155", borderRadius: 9, padding: "10px 11px", outline: "none" };
const select: React.CSSProperties = { ...input };
const selectedCard: React.CSSProperties = { display: "grid", gridTemplateColumns: "1fr auto auto", gap: 14, alignItems: "center", background: "rgba(15,23,42,0.84)", border: "1px solid rgba(148,163,184,0.16)", borderRadius: 12, padding: 12, color: "#e5e7eb" };
const selectedStats: React.CSSProperties = { display: "flex", gap: 8, flexWrap: "wrap", color: "#cbd5e1", fontSize: 12 };
const button: React.CSSProperties = { border: "1px solid rgba(96,165,250,0.28)", background: "#10203a", color: "#e5e7eb", borderRadius: 8, padding: "8px 10px", fontWeight: 850, cursor: "pointer" };
