import type { SavedMapAsset } from "../components/map/types";

export const ASSET_MIN_ZOOM = {
  exchange: 8,
  fibrehood: 10,
  agPolygon: 11,
  feederCable: 11,
  linkCable: 11,
  joint: 13,
  streetCab: 13,
  pole: 15,
  chamber: 15,
  distributionCable: 15,
  distributionPoint: 16,
  home: 17,
  dropCable: 18,
  openreachRoute: 15,
  openreachPoint: 16,
} as const;

export type ZoomAssetKind = keyof typeof ASSET_MIN_ZOOM;

export const SPATIAL_ASSET_TYPE_ZOOM_KIND: Record<string, ZoomAssetKind> = {
  exchange: "exchange",
  fibrehood: "fibrehood",
  "ag-polygon": "agPolygon",
  area: "agPolygon",
  polygon: "agPolygon",
  "project-area": "agPolygon",
  "feeder-cable": "feederCable",
  feederCable: "feederCable",
  linkCable: "linkCable",
  "link-cable": "linkCable",
  joint: "joint",
  "ag-joint": "joint",
  "street-cab": "streetCab",
  pole: "pole",
  chamber: "chamber",
  cable: "distributionCable",
  "distribution-cable": "distributionCable",
  "distribution-point": "distributionPoint",
  dp: "distributionPoint",
  home: "home",
  "drop-cable": "dropCable",
};

export function shouldShowZoomKind(kind: ZoomAssetKind, zoom: number): boolean {
  return zoom >= ASSET_MIN_ZOOM[kind];
}

export function shouldRequestSpatialAssetType(assetType: string, zoom: number): boolean {
  const kind = SPATIAL_ASSET_TYPE_ZOOM_KIND[assetType];
  return !kind || shouldShowZoomKind(kind, zoom);
}

export function getAssetZoomKind(asset: SavedMapAsset): ZoomAssetKind {
  const item = asset as any;
  const typeText = normaliseText(item.assetType || item.type);
  const jointText = normaliseText(item.jointType);
  const cableText = normaliseText(item.cableType || item.name);
  const geometryType = normaliseText(asset.geometry?.type);

  if (typeText.includes("exchange")) return "exchange";
  if (typeText.includes("fibrehood")) return "fibrehood";

  if (
    (geometryType === "polygon" || geometryType === "multipolygon") &&
    (typeText.includes("area") ||
      typeText.includes("polygon") ||
      jointText.includes("polygon-area"))
  ) {
    return "agPolygon";
  }

  if (isDropCableAsset(asset)) return "dropCable";
  if (isHomeAsset(asset)) return "home";

  if (geometryType === "linestring" || geometryType === "multilinestring" || typeText.includes("cable")) {
    if (cableText.includes("feeder")) return "feederCable";
    if (cableText.includes("link")) return "linkCable";
    return "distributionCable";
  }

  if (typeText === "distribution-point" || typeText === "dp") return "distributionPoint";
  if (typeText.includes("pole")) return "pole";
  if (typeText.includes("chamber")) return "chamber";
  if (typeText.includes("street") || typeText.includes("cab")) return "streetCab";
  if (typeText.includes("joint") || jointText.includes("joint")) return "joint";

  return geometryType === "polygon" || geometryType === "multipolygon" ? "agPolygon" : "joint";
}

export function shouldRenderOperationalAssetAtZoomLevel(
  asset: SavedMapAsset,
  zoom: number,
): boolean {
  return shouldShowZoomKind(getAssetZoomKind(asset), zoom);
}

export function shouldRenderOpenreachAssetAtZoomLevel(
  asset: SavedMapAsset,
  zoom: number,
): boolean {
  return shouldShowZoomKind(
    asset.geometry?.type === "LineString" || asset.geometry?.type === "MultiLineString" ? "openreachRoute" : "openreachPoint",
    zoom,
  );
}

function isHomeAsset(asset: SavedMapAsset): boolean {
  const item = asset as any;
  const text = [item.assetType, item.type, item.jointType, item.name, item.homeType, item.uprn]
    .map(normaliseText)
    .join(" ");

  return (
    text.includes("home") ||
    text.includes("uprn") ||
    text.includes("premise") ||
    text.includes("property")
  );
}

function isDropCableAsset(asset: SavedMapAsset): boolean {
  const item = asset as any;
  const text = [item.assetType, item.type, item.cableType, item.name, item.generatedBy]
    .map(normaliseText)
    .join(" ");

  return (
    text.includes("drop") ||
    item.isDropCable === true ||
    item.isHomeDrop === true ||
    item.generatedDrop === true ||
    item.autoGeneratedDrop === true ||
    Boolean(item.homeId || item.connectedHomeId)
  );
}

function normaliseText(value: unknown): string {
  return String(value ?? "").trim().toLowerCase().replace(/[\s_/-]+/g, "-");
}
