import type { LatLngLiteral } from "leaflet";
import type { FibreCount, InstallMethod, SavedMapAsset } from "../types";
import { getAssetLatLng } from "../utils/generateDrops";
import { getHomeConnectionKey } from "./homeConnectionKeys";

function getDistanceMeters(a: { lat: number; lng: number }, b: { lat: number; lng: number }): number {
  const R = 6371000;
  const toRad = (deg: number) => (deg * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const lat1 = toRad(a.lat);
  const lat2 = toRad(b.lat);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(h));
}

export function createManualDropCable(dp: SavedMapAsset, home: SavedMapAsset): SavedMapAsset | null {
  const dpCoord = getAssetLatLng(dp as any);
  const homeCoord = getAssetLatLng(home as any);
  if (!dpCoord || !homeCoord) return null;

  const homeId = getHomeConnectionKey(home);
  const dpId = String(dp.id || "");
  if (!homeId || !dpId) return null;

  const lineCoords: [number, number][] = [
    [dpCoord.lat, dpCoord.lng],
    [homeCoord.lat, homeCoord.lng],
  ];

  return {
    id: `drop_${dpId}_${homeId}`,
    name: `Drop ${dp.name || dpId} → ${home.name || homeId}`,
    assetType: "cable",
    cableType: "Drop",
    type: "cable",
    fibreCount: "1F" as FibreCount,
    installMethod: "Overhead" as InstallMethod,
    fromAssetId: dpId,
    toAssetId: homeId,
    fromType: "distribution-point",
    toType: "home",
    dpId,
    homeId,
    uprn: (home as any).properties?.UPRN ?? (home as any).UPRN ?? (home as any).uprn,
    distanceM: Math.round(getDistanceMeters(dpCoord, homeCoord) * 10) / 10,
    coordinates: lineCoords,
    route: lineCoords,
    path: lineCoords,
    points: lineCoords,
    geometry: {
      type: "LineString",
      coordinates: lineCoords,
    },
    generated: true,
    autoGenerated: true,
    generationMode: "manual-home-move",
    connectionMode: "manual",
    status: "planned",
  } as SavedMapAsset;
}

export function isDropCable(asset: SavedMapAsset): boolean {
  return (
    asset.assetType === "cable" &&
    String((asset as any).cableType || "")
      .trim()
      .toLowerCase() === "drop"
  );
}
