import type { SavedMapAsset } from "../types";
import { createManualDropCable, isDropCable } from "./homeDropFactory";
import { getDropHomeKeys, getHomeDropKeys } from "./homeConnectionKeys";

export function getAssignedDpId(home: SavedMapAsset | any): string {
  return String(
    home?.connectedDpId ??
      home?.properties?.connectedDpId ??
      home?.dpId ??
      home?.properties?.dpId ??
      home?.parentDpId ??
      home?.properties?.parentDpId ??
      home?.connectedDP ??
      home?.properties?.connectedDP ??
      home?.servedByDp ??
      home?.properties?.servedByDp ??
      "",
  ).trim();
}

export function getSelectedHomeAssets(
  assets: SavedMapAsset[],
  selectedHomeIds: string[],
): SavedMapAsset[] {
  const selectedIdSet = new Set(selectedHomeIds.map(String));
  return assets.filter(
    (asset) => asset.assetType === "home" && selectedIdSet.has(String(asset.id)),
  );
}

export function getHomeKeySet(homes: SavedMapAsset[]): Set<string> {
  const keys = new Set<string>();
  homes.forEach((home) => {
    getHomeDropKeys(home).forEach((key) => keys.add(key));
  });
  return keys;
}

export function isDropCableRelatedToHomeKeys(
  asset: SavedMapAsset,
  homeKeys: Set<string>,
): boolean {
  if (!isDropCable(asset)) return false;
  return getDropHomeKeys(asset).some((key) => homeKeys.has(key));
}

export function withHomeAssignedToDp(
  home: SavedMapAsset,
  targetDpId: string,
): SavedMapAsset {
  return {
    ...home,
    connectedDpId: targetDpId,
    dpId: targetDpId,
    parentDpId: targetDpId,
    connectedDP: targetDpId,
    servedByDp: targetDpId,
    connection: "connected",
    connectionMode: "manual",
    port: undefined,
    splitterPort: undefined,
    properties: {
      ...((home as any).properties || {}),
      connectedDpId: targetDpId,
      dpId: targetDpId,
      parentDpId: targetDpId,
      connectedDP: targetDpId,
      servedByDp: targetDpId,
      connection: "connected",
      connectionMode: "manual",
      port: undefined,
      splitterPort: undefined,
    },
  } as SavedMapAsset;
}

export function buildManualDropCablesForHomes(
  targetDp: SavedMapAsset,
  homes: SavedMapAsset[],
): SavedMapAsset[] {
  return homes
    .map((home) => createManualDropCable(targetDp, home))
    .filter(Boolean) as SavedMapAsset[];
}

export function withManualDropFlags(drop: SavedMapAsset): SavedMapAsset {
  return {
    ...(drop as any),
    isDropCable: true,
    isHomeDrop: true,
    autoGeneratedDrop: true,
    generatedDrop: true,
    properties: {
      ...((drop as any).properties || {}),
      isDropCable: true,
      isHomeDrop: true,
      autoGeneratedDrop: true,
      generatedDrop: true,
    },
  } as SavedMapAsset;
}
