import { useState } from "react";
import type { AssetChangeAction } from "../audit/types";
import type { SavedMapAsset } from "../types";
import { withAssetEditedMetadata } from "../../../services/assetActivityService";
import { saveProjectHomes } from "../projects/projectHomesStorage";
import { withAreaAssetIndex } from "../../../services/areaAssetIndex";
import { getDropHomeKeys, getHomeDropKeys } from "./homeDropHelpers";
import {
  buildManualDropCablesForHomes,
  getHomeKeySet,
  getSelectedHomeAssets,
  isDropCableRelatedToHomeKeys,
  withHomeAssignedToDp,
  withManualDropFlags,
} from "./homeReassignment";

type MapModeLike =
  | "pick"
  | "measure"
  | "draw-cable"
  | "draw-area"
  | "drive-to-location"
  | "move-homes"
  | "survey-delete-homes";

type ContextMenuUpdater = React.Dispatch<
  React.SetStateAction<{
    visible: boolean;
    position: { x: number; y: number };
    latlng: { lat: number; lng: number } | null;
  }>
>;

type UseHomeWorkflowControllersArgs = {
  mapMode: MapModeLike;
  setMapMode: React.Dispatch<React.SetStateAction<MapModeLike>>;
  setIsPanelOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setContextMenu: ContextMenuUpdater;
  allMapAssets: SavedMapAsset[];
  selectedProjectHomes: SavedMapAsset[];
  setProjectHomes: React.Dispatch<React.SetStateAction<SavedMapAsset[]>>;
  setSavedJoints: React.Dispatch<React.SetStateAction<SavedMapAsset[]>>;
  activeProjectId: string | null;
  activeProjectAreaName: string | undefined;
  stampHomesForActiveArea: (homes: SavedMapAsset[]) => SavedMapAsset[];
  getChangeReasonForCurrentMode: (
    action: AssetChangeAction,
    assetName?: string,
  ) => string | null;
  markAssetForLiveSync: (asset: SavedMapAsset, isNew?: boolean) => SavedMapAsset;
  writeAssetAuditLog: (args: {
    asset: SavedMapAsset;
    action: AssetChangeAction;
    reason?: string;
    comment?: string;
    before?: unknown;
    after?: unknown;
  }) => void;
};

export function useHomeWorkflowControllers({
  mapMode,
  setMapMode,
  setIsPanelOpen,
  setContextMenu,
  allMapAssets,
  selectedProjectHomes,
  setProjectHomes,
  setSavedJoints,
  activeProjectId,
  activeProjectAreaName,
  stampHomesForActiveArea,
  getChangeReasonForCurrentMode,
  markAssetForLiveSync,
  writeAssetAuditLog,
}: UseHomeWorkflowControllersArgs) {
  const [selectedMoveHomeIds, setSelectedMoveHomeIds] = useState<string[]>([]);
  const [selectedSurveyDeleteHomeIds, setSelectedSurveyDeleteHomeIds] =
    useState<string[]>([]);

  const handleToggleSurveyDeleteHomesMode = () => {
    setMapMode((prev) =>
      prev === "survey-delete-homes" ? "pick" : "survey-delete-homes",
    );
    setIsPanelOpen(true);
    setContextMenu((prev) => ({ ...prev, visible: false }));
  };

  const handleToggleSurveyDeleteHomeSelection = (home: SavedMapAsset) => {
    if (mapMode !== "survey-delete-homes") return;
    if (home.assetType !== "home") return;

    const homeId = String(home.id || "");
    if (!homeId) return;

    setSelectedSurveyDeleteHomeIds((prev) =>
      prev.includes(homeId)
        ? prev.filter((id) => id !== homeId)
        : [...prev, homeId],
    );
  };

  const handleClearSurveyDeleteHomeSelection = () => {
    setSelectedSurveyDeleteHomeIds([]);
  };

  const handleDeleteSelectedSurveyHomes = async () => {
    if (selectedSurveyDeleteHomeIds.length === 0) {
      alert("Select one or more wrong homes first.");
      return;
    }

    const selectedHomeIds = new Set(selectedSurveyDeleteHomeIds.map(String));
    const selectedHomeKeySet = new Set<string>();

    allMapAssets.forEach((asset: any) => {
      if (asset?.assetType !== "home") return;
      const assetId = String(asset.id || "");
      if (!selectedHomeIds.has(assetId)) return;
      selectedHomeKeySet.add(assetId);
      getHomeDropKeys(asset).forEach((key) => selectedHomeKeySet.add(key));
    });

    selectedHomeIds.forEach((id) => selectedHomeKeySet.add(id));

    const ok = window.confirm(
      `Delete ${selectedSurveyDeleteHomeIds.length} selected home${selectedSurveyDeleteHomeIds.length === 1 ? "" : "s"} and any related drop cables?\n\nThis will not delete DPs, joints, feeder cables, link cables, PIA/Openreach overlay or project areas.`,
    );

    if (!ok) return;

    const shouldRemoveAsset = (asset: SavedMapAsset) => {
      const assetId = String(asset.id || "");

      if (asset.assetType === "home" && selectedHomeIds.has(assetId)) {
        return true;
      }

      const cableType = String((asset as any).cableType || "").toLowerCase();
      const isRelatedDropCable =
        asset.assetType === "cable" &&
        (cableType.includes("drop") ||
          String((asset as any).isDropCable || "").toLowerCase() === "true" ||
          String((asset as any).autoGeneratedDrop || "").toLowerCase() ===
            "true" ||
          String((asset as any).autoGenerated || "").toLowerCase() ===
            "true" ||
          String((asset as any).generated || "").toLowerCase() === "true") &&
        getDropHomeKeys(asset).some((key) => selectedHomeKeySet.has(key));

      return isRelatedDropCable;
    };

    setSavedJoints((prev) =>
      (prev ?? []).filter((asset) => !shouldRemoveAsset(asset)),
    );

    if (activeProjectId) {
      const updatedProjectHomes = (selectedProjectHomes ?? []).filter((home) => {
        const homeId = String(home.id || "");
        return !selectedHomeIds.has(homeId);
      });

      setProjectHomes(updatedProjectHomes);

      try {
        await saveProjectHomes(
          activeProjectId,
          stampHomesForActiveArea(updatedProjectHomes),
          activeProjectAreaName,
        );
      } catch (err) {
        console.error(
          "Failed to save project homes after survey cleanup delete",
          err,
        );
        alert(
          "Homes were removed from the map view, but saving project homes failed. Check the console before refreshing.",
        );
      }
    }

    setSelectedSurveyDeleteHomeIds([]);
    setMapMode("pick");
  };

  const handleToggleMoveHomesMode = () => {
    setMapMode((prev) => (prev === "move-homes" ? "pick" : "move-homes"));
    setIsPanelOpen(true);
    setContextMenu((prev) => ({ ...prev, visible: false }));
  };

  const handleToggleMoveHomeSelection = (home: SavedMapAsset) => {
    const homeId = String(home.id || "");
    if (!homeId) return;

    setSelectedMoveHomeIds((prev) =>
      prev.includes(homeId)
        ? prev.filter((id) => id !== homeId)
        : [...prev, homeId],
    );
  };

  const handleClearMoveHomeSelection = () => {
    setSelectedMoveHomeIds([]);
  };

  const handleMoveSelectedHomesToDp = async (targetDp: SavedMapAsset) => {
    if (mapMode !== "move-homes") return;
    if (targetDp.assetType !== "distribution-point") return;

    const selectedHomes = getSelectedHomeAssets(
      allMapAssets,
      selectedMoveHomeIds,
    );

    if (selectedHomes.length === 0) {
      alert("Select one or more UPRNs/homes first, then click the target DP.");
      return;
    }

    const reason = getChangeReasonForCurrentMode(
      "updated",
      `Move ${selectedHomes.length} home${selectedHomes.length === 1 ? "" : "s"} to ${targetDp.name || targetDp.id}`,
    );
    if (!reason) return;

    const selectedHomeKeySet = getHomeKeySet(selectedHomes);
    const newDrops = buildManualDropCablesForHomes(targetDp, selectedHomes);

    if (newDrops.length !== selectedHomes.length) {
      alert(
        "Some selected homes could not be moved because coordinates were missing.",
      );
      return;
    }

    const targetDpId = String(targetDp.id);

    const stampHome = (home: SavedMapAsset): SavedMapAsset =>
      markAssetForLiveSync(
        withAssetEditedMetadata(
          {
            ...withHomeAssignedToDp(home, targetDpId),
          } as SavedMapAsset,
          "updated",
          reason,
        ),
        false,
      );

    setSavedJoints((prev) => {
      const withoutOldDrops = (prev ?? []).filter((asset: any) => {
        return !isDropCableRelatedToHomeKeys(asset, selectedHomeKeySet);
      });

      const updatedAssets = withoutOldDrops.map((asset) => {
        if (asset.assetType !== "home") return asset;
        if (!selectedMoveHomeIds.includes(asset.id)) return asset;
        return stampHome(asset);
      });

      const markedDrops = newDrops.map((drop) =>
        markAssetForLiveSync(
          withAreaAssetIndex(
            withManualDropFlags(drop),
            activeProjectId,
            activeProjectAreaName,
          ),
          true,
        ),
      );

      return [...updatedAssets, ...markedDrops];
    });

    if (activeProjectId) {
      const updatedProjectHomes = selectedProjectHomes.map((home) => {
        if (!selectedMoveHomeIds.includes(home.id)) return home;
        return stampHome(home);
      });

      setProjectHomes(updatedProjectHomes);
      await saveProjectHomes(
        activeProjectId,
        stampHomesForActiveArea(updatedProjectHomes),
        activeProjectAreaName,
      );
    }

    writeAssetAuditLog({
      asset: targetDp,
      action: "updated",
      reason,
      comment: `Moved ${selectedHomes.length} home${selectedHomes.length === 1 ? "" : "s"} to this DP and regenerated manual drop cables.`,
      before: selectedHomes,
      after: newDrops,
    });

    setSelectedMoveHomeIds([]);
    setMapMode("pick");
    alert(
      `Moved ${selectedHomes.length} home${selectedHomes.length === 1 ? "" : "s"} to ${targetDp.name || "selected DP"}.`,
    );
  };

  return {
    selectedMoveHomeIds,
    selectedSurveyDeleteHomeIds,
    handleToggleSurveyDeleteHomesMode,
    handleToggleSurveyDeleteHomeSelection,
    handleClearSurveyDeleteHomeSelection,
    handleDeleteSelectedSurveyHomes,
    handleToggleMoveHomesMode,
    handleToggleMoveHomeSelection,
    handleClearMoveHomeSelection,
    handleMoveSelectedHomesToDp,
  };
}
