import { getTupleDistanceMeters as getDistanceMeters, getTuplePathDistanceMeters } from "../../../utils/mapMeasure";
import React, { useEffect, useMemo, useState } from "react";
import L from "leaflet";
import {
  CircleMarker,
  Marker,
  Polyline,
  Popup,
  Tooltip,
  useMap,
  useMapEvents,
} from "react-leaflet";
import type { SavedMapAsset } from "../../JointMapManager";
import {
  loadJointMappingRowsFromFirestore,
  type MappingRowsByAssetId,
} from "./cableMappingRows";
import {
  getCableDistanceLabelIcon,
  getCableSpanAngleDegrees,
  getMidpoint,
  getOffsetCableLabelPosition,
  getRouteEditHandleIndexes,
  getRouteEditInsertSegmentIndexes,
  ROUTE_EDIT_MIN_INSERT_SPAN_METERS,
  sanitizeCableCoordinates,
} from "./cableRouteGeometry";
import { getCableUsedFibres } from "../cableUsage";
import { buildNetworkState } from "../../../services/network";
import { isOpenreachReferenceAsset } from "../../../services/orAssetStorage";
import { getPaddedRenderBounds, isLineStringInsideRenderBounds } from "../utils/renderBounds";
import { useDeviceLayout } from "../responsive/useDeviceLayout";
import {
  getDailyProgressTeamColour,
  getDailyProgressTotals,
} from "../../Project/workspace/workspaceOperations";
type Props = {
  assets: SavedMapAsset[];
  cablesVisible: boolean;
  visibleLayers?: Record<string, boolean>;
  showCableDistances?: boolean;
  cableDrawingMode?: boolean;
  endpointAssetOptions?: SavedMapAsset[];
  onDeleteAsset: (id: string) => void;
  onEditAsset: (asset: SavedMapAsset) => void;
  onUpdateAsset?: (asset: SavedMapAsset) => void;
  canEditCables?: boolean;
  canDeleteCables?: boolean;
};

function formatCableLength(length: number): string {
  if (length < 1000) return `${length.toFixed(1)} m`;
  return `${(length / 1000).toFixed(3)} km`;
}

const LONG_CABLE_CLICK_ZOOM = 17;

function focusCableClick(map: L.Map, point: L.LatLng) {
  map.setView(point, Math.max(map.getZoom(), LONG_CABLE_CLICK_ZOOM), {
    animate: false,
  });
}

function isDropCableAsset(asset: SavedMapAsset): boolean {
  const cableType = String((asset as any).cableType || "").toLowerCase();
  const assetType = String((asset as any).assetType || "").toLowerCase();
  const name = String((asset as any).name || "").toLowerCase();

  return (
    assetType === "drop-cable" ||
    cableType.includes("drop") ||
    name.includes("drop") ||
    String((asset as any).isDropCable || "").toLowerCase() === "true" ||
    String((asset as any).autoGeneratedDrop || "").toLowerCase() === "true" ||
    Boolean((asset as any).homeId || (asset as any).connectedHomeId || (asset as any).toHomeId || (asset as any).fromHomeId)
  );
}

function getCableFibreCount(asset: SavedMapAsset): number | null {
  const item = asset as any;

  const candidates = [
    item.fibreCount,
    item.fiberCount,
    item.size,
    item.cableSize,
    item.name,
    item.cableId,
    item.label,
  ];

  for (const candidate of candidates) {
    const text = String(candidate ?? "").toUpperCase();
    const match = text.match(/(288|144|96|48|36|24|12)\s*F?/);
    if (match) return Number(match[1]);
  }

  return null;
}

function isEngineeringDrawingTrunkCable(asset: SavedMapAsset): boolean {
  if (isDropCableAsset(asset)) return false;

  const fibreCount = getCableFibreCount(asset);
  return fibreCount === 96 || fibreCount === 144 || fibreCount === 288;
}

function isCoreNetworkCable(asset: SavedMapAsset): boolean {
  if (isDropCableAsset(asset)) return false;

  const cableType = normaliseCableText((asset as any).cableType || (asset as any).type || (asset as any).assetType);
  const fibreCount = getCableFibreCount(asset) || 0;

  // Core network is role-led, not size-led. 48F/96F can be distribution,
  // so only Feeder/Link cables are allowed into the global core system.
  return fibreCount >= 48 && (cableType.includes("feeder") || cableType.includes("link"));
}


function getCableCapacityWarning(asset: SavedMapAsset, usedFibres: number | null): string {
  const fibreCount = getCableFibreCount(asset);
  if (!fibreCount || usedFibres === null) return "";
  if (usedFibres > fibreCount) return `Over capacity: ${usedFibres}/${fibreCount}F`;
  if (usedFibres === fibreCount) return `Full: ${usedFibres}/${fibreCount}F`;
  if ((usedFibres / fibreCount) >= 0.8) return `Near capacity: ${usedFibres}/${fibreCount}F`;
  return `Fibres: ${usedFibres}/${fibreCount}F`;
}

function getDropCableDistanceColour(lengthMeters: number): string {
  // Blue = shortest tails, red = top end of acceptable drop length.
  // 68m is the existing design target used elsewhere in the app.
  const maxDropMeters = 68;
  const ratio = Math.max(0, Math.min(1, lengthMeters / maxDropMeters));

  if (ratio < 0.5) {
    const local = ratio / 0.5;
    const r = Math.round(37 + (34 - 37) * local);
    const g = Math.round(99 + (197 - 99) * local);
    const b = Math.round(235 + (94 - 235) * local);
    return `rgb(${r}, ${g}, ${b})`;
  }

  const local = (ratio - 0.5) / 0.5;
  const r = Math.round(34 + (239 - 34) * local);
  const g = Math.round(197 + (68 - 197) * local);
  const b = Math.round(94 + (68 - 94) * local);
  return `rgb(${r}, ${g}, ${b})`;
}

function getCableColor(asset: SavedMapAsset, lengthMeters = 0): string {
  if (isDuctAsset(asset)) return "#7c3aed";
  if (isDropCableAsset(asset)) return getDropCableDistanceColour(lengthMeters);

  const fibreCount = getCableFibreCount(asset);
  if (fibreCount === 96) return "#2563eb"; // blue
  if (fibreCount === 48) return "#01fff2"; // red
  if (fibreCount === 12) return "#ff9500"; // green

  if (asset.cableType === "ULW Cable") return "#22c55e";
  if (asset.cableType === "Link Cable") return "#3b82f6";
  return "#f59e0b";
}

/* =========================================================
   CABLE STYLE HELPERS
   Visual rule requested:
   - Drop cables = dashed, like OH tails
   - OH / Overhead spans to DPs = dashed
   - UG / Underground cables = solid
========================================================= */
function normaliseCableText(value: unknown): string {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[\s_/-]+/g, " ");
}

function isUndergroundInstall(asset: SavedMapAsset): boolean {
  const install = normaliseCableText((asset as any).installMethod);
  const cableType = normaliseCableText((asset as any).cableType);
  const name = normaliseCableText((asset as any).name);

  return (
    install === "ug" ||
    install.includes("underground") ||
    install.includes("duct") ||
    cableType.includes("duct") ||
    name.includes(" ug ") ||
    name.startsWith("ug ") ||
    name.endsWith(" ug")
  );
}

function isOverheadInstall(asset: SavedMapAsset): boolean {
  const install = normaliseCableText((asset as any).installMethod);
  const cableType = normaliseCableText((asset as any).cableType);
  const name = normaliseCableText((asset as any).name);

  return (
    install === "oh" ||
    install.includes("overhead") ||
    install.includes("aerial") ||
    install.includes("span") ||
    cableType.includes("overhead") ||
    cableType.includes("span") ||
    name.includes(" oh ") ||
    name.startsWith("oh ") ||
    name.endsWith(" oh") ||
    name.includes("span")
  );
}

function isDistributionPointAsset(asset?: SavedMapAsset | null): boolean {
  if (!asset) return false;

  const assetType = normaliseCableText((asset as any).assetType);
  const type = normaliseCableText((asset as any).type);
  const name = normaliseCableText((asset as any).name);

  return (
    assetType === "distribution point" ||
    assetType === "distribution point afn" ||
    assetType === "dp" ||
    assetType.includes("distribution") ||
    assetType.includes("afn") ||
    assetType.includes("cbt") ||
    type.includes("distribution") ||
    type.includes("afn") ||
    type.includes("cbt") ||
    name.includes("dp") ||
    name.includes("afn") ||
    name.includes("cbt")
  );
}

function getDashArray(
  asset: SavedMapAsset,
  startAsset?: SavedMapAsset | null,
  endAsset?: SavedMapAsset | null
): string | undefined {
  // UG always stays solid, even if another field has confusing wording.
  if (isDuctAsset(asset)) return undefined;
  if (isUndergroundInstall(asset)) return undefined;

  // All drops are dashed because they are house tails / OH-style tails on the map.
  if (isDropCableAsset(asset)) return "6, 7";

  // OH spans are dashed. If the span touches a DP/CBT/AFN, make sure it follows the DP visual rule.
  if (isOverheadInstall(asset)) return isDistributionPointAsset(startAsset) || isDistributionPointAsset(endAsset) ? "10, 8" : "10, 8";

  return undefined;
}

function getDailyRouteProgress(asset: SavedMapAsset) {
  const totals = getDailyProgressTotals(asset as any);
  const meters = totals.civilsMeters + totals.cablingMeters;
  const team =
    totals.cablingMeters >= totals.civilsMeters && totals.cablingMeters > 0
      ? "cabling"
      : totals.civilsMeters > 0
        ? "civils"
        : null;

  return { ...totals, meters, team };
}

function getSegmentInstallMethod(asset: SavedMapAsset, index: number): "OH" | "Underground" | null {
  const methods = (asset as any).cableSegmentInstallMethods;
  if (!Array.isArray(methods) || !methods.length) return null;
  const text = normaliseCableText(methods[index]);
  return text === "oh" || text.includes("overhead") ? "OH" : "Underground";
}

function hasMixedSegmentInstallMethods(asset: SavedMapAsset): boolean {
  const methods = (asset as any).cableSegmentInstallMethods;
  if (!Array.isArray(methods) || methods.length < 1) return false;
  return new Set(methods.map((method: unknown) => getSegmentInstallMethod({ ...(asset as any), cableSegmentInstallMethods: [method] }, 0))).size > 1;
}

function getCableInstallSummary(asset: SavedMapAsset): string {
  const methods = (asset as any).cableSegmentInstallMethods;
  if (Array.isArray(methods) && methods.length > 0) {
    const normalised = methods
      .map((_: unknown, index: number) => getSegmentInstallMethod(asset, index))
      .filter(Boolean);
    const ugCount = normalised.filter((method) => method === "Underground").length;
    const ohCount = normalised.filter((method) => method === "OH").length;

    if (ugCount > 0 && ohCount > 0) {
      return `Mixed · ${ugCount} UG / ${ohCount} OH`;
    }

    if (ohCount > 0) return `Overhead · ${ohCount} span${ohCount === 1 ? "" : "s"}`;
    if (ugCount > 0) return `Underground · ${ugCount} span${ugCount === 1 ? "" : "s"}`;
  }

  return isOverheadInstall(asset) ? "Overhead" : "Underground";
}
/* ======================= END CABLE STYLE HELPERS ======================= */

function getAssetPoint(asset: SavedMapAsset): [number, number] | null {
  if (asset.geometry?.type === "Point" && Array.isArray(asset.geometry.coordinates)) {
    const [lat, lng] = asset.geometry.coordinates;
    if (typeof lat === "number" && typeof lng === "number") return [lat, lng];
  }

  const lat = Number((asset as any).lat);
  const lng = Number((asset as any).lng);
  if (Number.isFinite(lat) && Number.isFinite(lng)) return [lat, lng];

  return null;
}

function findConnectedAssetAtCableEnd(
  assets: SavedMapAsset[],
  point: [number, number]
): SavedMapAsset | null {
  const candidates = assets
    .filter((asset) => {
      if (asset.assetType === "area") return false;
      if (asset.assetType === "cable") return false;

      const assetPoint = getAssetPoint(asset);
      if (!assetPoint) return false;

      return getDistanceMeters(assetPoint, point) <= 10;
    })
    .sort((a, b) => {
      const pointA = getAssetPoint(a);
      const pointB = getAssetPoint(b);
      if (!pointA || !pointB) return 0;

      return getDistanceMeters(pointA, point) - getDistanceMeters(pointB, point);
    });

  return candidates[0] || null;
}

function getAssetDisplayName(asset?: SavedMapAsset | null): string {
  if (!asset) return "Not connected";
  const item = asset as any;
  return String(item.name || item.jointName || item.label || item.assetId || item.id || "Connected asset");
}

function getAssetTypeLabel(asset?: SavedMapAsset | null): string {
  if (!asset) return "asset";
  const item = asset as any;
  const raw = String(item.assetType || item.jointType || "asset")
    .replace(/-/g, " ")
    .trim();
  return raw || "asset";
}

function getEndpointOptionLabel(asset: SavedMapAsset): string {
  return `${getAssetDisplayName(asset)} · ${getAssetTypeLabel(asset)}`;
}

function isCableEndpointSelectableAsset(asset: SavedMapAsset): boolean {
  if (asset.assetType === "area") return false;
  if (asset.assetType === "cable") return false;
  if (asset.assetType === "home") return false;

  // DPs/SBs are valid endpoints for distribution cables. Do not filter them out.
  // The old logic removed distribution-point/dp here, which is why the cable
  // popup dropdown showed poles/chambers/joints but not the DPs in the area.
  if (isOpenreachReferenceAsset(asset)) return false;
  return Boolean(getAssetPoint(asset));
}

function getEndpointOptionPriority(asset: SavedMapAsset): number {
  const text = normaliseCableText(
    `${(asset as any).assetType || ""} ${(asset as any).jointType || ""} ${(asset as any).name || ""}`,
  );

  if (text.includes("distribution point") || text.includes("distribution-point") || text.includes(" dp") || text.includes("sb")) return 0;
  if (text.includes("joint") || text.includes("cmj") || text.includes("mmj") || text.includes("lmj") || text.includes("midj")) return 1;
  if (text.includes("chamber") || text.includes("fw")) return 2;
  if (text.includes("pole")) return 3;
  if (text.includes("street") || text.includes("cab")) return 4;
  if (text.includes("exchange")) return 5;
  return 9;
}

function buildCableWithEndpoint(
  cable: SavedMapAsset,
  side: "from" | "to",
  endpointAsset: SavedMapAsset | null,
): SavedMapAsset {
  const endpointId = endpointAsset?.id ? String(endpointAsset.id) : "";
  const endpointName = endpointAsset ? getAssetDisplayName(endpointAsset) : "";
  const endpointType = endpointAsset ? String((endpointAsset as any).assetType || "") : "";

  const next: any = { ...cable };
  const endpointPoint = endpointAsset ? getAssetPoint(endpointAsset) : null;

  if (endpointPoint && next.geometry?.type === "LineString" && Array.isArray(next.geometry.coordinates)) {
    const coordinates = [...next.geometry.coordinates];

    if (coordinates.length > 0) {
      if (side === "from") {
        coordinates[0] = endpointPoint;
      } else {
        coordinates[coordinates.length - 1] = endpointPoint;
      }

      next.geometry = {
        ...next.geometry,
        coordinates,
      };
    }
  }

  if (side === "from") {
    next.fromAssetId = endpointId || undefined;
    next.startAssetId = endpointId || undefined;
    next.fromAssetName = endpointName || undefined;
    next.fromAssetType = endpointType || undefined;
    next.fromJointId = endpointId || undefined;
    next.fromJoint = endpointName || undefined;
    next.startJoint = endpointName || undefined;
  } else {
    next.toAssetId = endpointId || undefined;
    next.endAssetId = endpointId || undefined;
    next.toAssetName = endpointName || undefined;
    next.toAssetType = endpointType || undefined;
    next.toJointId = endpointId || undefined;
    next.toJoint = endpointName || undefined;
    next.endJoint = endpointName || undefined;
  }

  return next as SavedMapAsset;
}

function normaliseAssetLookupKey(value: unknown): string {
  return String(value ?? "")
    .trim()
    .toLowerCase()
    .replace(/[–—]/g, "-")
    .replace(/\s+/g, "")
    .replace(/[^a-z0-9-]/g, "");
}

function getAssetLookupKeysForConnection(asset: SavedMapAsset): string[] {
  const item = asset as any;
  const raw = [
    item.id,
    item.assetId,
    item.name,
    item.jointName,
    item.label,
    item.nodeId,
    item.cableId,
    item.cableName,
  ];

  const keys = new Set<string>();

  raw.forEach((value) => {
    const normalised = normaliseAssetLookupKey(value);
    if (!normalised) return;

    keys.add(normalised);

    const withoutJointSuffix = normalised.replace(/-(cmj|midj|mmj|lmj)\d{1,4}$/i, "");
    if (withoutJointSuffix) keys.add(withoutJointSuffix);

    const nodeMatches = normalised.match(/(?:ag|lmj|mmj|cmj|lc|sb|midj|sc)\d{1,4}/gi);
    nodeMatches?.forEach((match) => keys.add(normaliseAssetLookupKey(match)));
  });

  return Array.from(keys).filter((key) => key.length >= 2);
}

function findAssetByStoredReference(
  assets: SavedMapAsset[],
  reference: unknown
): SavedMapAsset | null {
  const lookup = normaliseAssetLookupKey(reference);
  if (!lookup) return null;

  return (
    assets.find((candidate) =>
      getAssetLookupKeysForConnection(candidate).some(
        (key) => key === lookup || key.includes(lookup) || lookup.includes(key),
      ),
    ) || null
  );
}

function getCableEndpointReferences(
  cable: SavedMapAsset,
  side: "from" | "to"
): unknown[] {
  const item = cable as any;

  if (side === "from") {
    return [
      item.fromAssetId,
      item.fromId,
      item.fromJointId,
      item.fromJoint,
      item.fromName,
      item.fromAssetName,
      item.sourceAssetId,
      item.sourceJointId,
      item.sourceJoint,
      item.sourceName,
      item.upstreamAssetId,
      item.upstreamJoint,
      item.aEnd,
      item.aEndAssetId,
      item.startAssetId,
      item.startJoint,
    ];
  }

  return [
    item.toAssetId,
    item.toId,
    item.toJointId,
    item.toJoint,
    item.toName,
    item.toAssetName,
    item.targetAssetId,
    item.targetJointId,
    item.targetJoint,
    item.targetName,
    item.downstreamAssetId,
    item.downstreamJoint,
    item.zEnd,
    item.zEndAssetId,
    item.endAssetId,
    item.endJoint,
  ];
}

function findNearestConnectedAssetAtCableEnd(
  assets: SavedMapAsset[],
  point: [number, number],
  maxDistanceMeters = 35
): SavedMapAsset | null {
  const candidates = assets
    .filter((asset) => {
      if (asset.assetType === "area") return false;
      if (asset.assetType === "cable") return false;
      if (asset.assetType === "home") return false;
      return Boolean(getAssetPoint(asset));
    })
    .map((asset) => {
      const assetPoint = getAssetPoint(asset)!;
      return { asset, distance: getDistanceMeters(assetPoint, point) };
    })
    .filter(({ distance }) => distance <= maxDistanceMeters)
    .sort((a, b) => a.distance - b.distance);

  return candidates[0]?.asset || null;
}

function getAssetKindPriority(asset: SavedMapAsset): number {
  const text = normaliseCableText(
    `${(asset as any).assetType || ""} ${(asset as any).jointType || ""} ${(asset as any).name || ""}`,
  );

  if (text.includes("joint") || text.includes("cmj") || text.includes("mmj") || text.includes("lmj") || text.includes("midj")) return 0;
  if (text.includes("exchange")) return 1;
  if (text.includes("street") || text.includes("cab")) return 2;
  if (text.includes("chamber") || text.includes("fw")) return 3;
  if (text.includes("pole")) return 4;
  return 9;
}

function findBestAssetNearCableSide(
  cable: SavedMapAsset,
  assets: SavedMapAsset[],
  side: "from" | "to",
  maxDistanceMeters = 55,
): SavedMapAsset | null {
  const points = getCableLinePoints(cable);
  if (points.length < 2) return null;

  const sidePoints = side === "from"
    ? points.slice(0, Math.max(2, Math.ceil(points.length * 0.25)))
    : points.slice(Math.max(0, points.length - Math.max(2, Math.ceil(points.length * 0.25))));

  const endpoint = side === "from" ? points[0] : points[points.length - 1];

  const candidates = assets
    .filter((asset) => {
      if (asset.assetType === "area") return false;
      if (asset.assetType === "cable") return false;
      if (asset.assetType === "home") return false;
      return Boolean(getAssetPoint(asset));
    })
    .map((asset) => {
      const assetPoint = getAssetPoint(asset)!;
      const routeDistance = distancePointToRouteMeters(assetPoint, sidePoints);
      const endpointDistance = getDistanceMeters(endpoint, assetPoint);
      return { asset, routeDistance, endpointDistance, priority: getAssetKindPriority(asset) };
    })
    .filter(({ routeDistance, endpointDistance }) => routeDistance <= maxDistanceMeters || endpointDistance <= maxDistanceMeters)
    .sort((a, b) =>
      a.priority - b.priority ||
      a.routeDistance - b.routeDistance ||
      a.endpointDistance - b.endpointDistance,
    );

  return candidates[0]?.asset || null;
}

function resolveCableEndpointAsset(
  cable: SavedMapAsset,
  assets: SavedMapAsset[],
  side: "from" | "to",
  point?: [number, number]
): SavedMapAsset | null {
  for (const reference of getCableEndpointReferences(cable, side)) {
    const matched = findAssetByStoredReference(assets, reference);
    if (matched) return matched;
  }

  if (point) {
    return (
      findConnectedAssetAtCableEnd(assets, point) ||
      findNearestConnectedAssetAtCableEnd(assets, point) ||
      findBestAssetNearCableSide(cable, assets, side)
    );
  }

  return findBestAssetNearCableSide(cable, assets, side);
}

function normaliseCableRef(value: unknown): string {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/[–—]/g, "-");
}

function getNumberFromFibreCount(value: unknown): number {
  const match = String(value || "").match(/\d+/);
  return match ? Number(match[0]) : 0;
}

function getRowText(row: any[]): string {
  return row.map((cell) => String(cell || "").trim()).join(" ");
}

function getCableAliases(cable: SavedMapAsset): string[] {
  const values = [cable.name, cable.id, (cable as any).label, (cable as any).cableId]
    .map(normaliseCableRef)
    .filter(Boolean);

  const aliases = new Set<string>();

  values.forEach((value) => {
    aliases.add(value);

    const parts = value.split("-").filter(Boolean);
    const last = parts[parts.length - 1];
    if (last) aliases.add(last);

    const lcMatch = value.match(/lc\d{1,4}/i);
    if (lcMatch) aliases.add(normaliseCableRef(lcMatch[0]));
  });

  return Array.from(aliases).filter((alias) => alias.length >= 3);
}

function rowMentionsCable(row: any[], cable: SavedMapAsset): boolean {
  const aliases = getCableAliases(cable);
  if (!aliases.length) return false;

  const rowText = normaliseCableRef(getRowText(row));

  return aliases.some((alias) => rowText.includes(alias));
}

function getAssetAliases(asset?: SavedMapAsset | null): string[] {
  if (!asset) return [];

  const rawValues = [asset.name, asset.id, (asset as any).label, (asset as any).nodeId]
    .map((value) => String(value || '').trim())
    .filter(Boolean);

  const aliases = new Set<string>();

  rawValues.forEach((raw) => {
    const value = normaliseCableRef(raw);
    if (!value) return;

    aliases.add(value);

    // BD-BAW-AG11-CMJ01 should also match BD-BAW-AG11.
    const withoutJointSuffix = value.replace(/-(cmj|midj|mmj|lmj)\d{1,4}$/i, '');
    if (withoutJointSuffix && withoutJointSuffix !== value) {
      aliases.add(withoutJointSuffix);
    }

    // Add compact node tokens such as AG11, LMJ01, LC011, SB35.
    const nodeMatches = value.match(/(?:ag|lmj|mmj|cmj|lc|sb|midj|sc)\d{1,4}/gi);
    nodeMatches?.forEach((match) => aliases.add(normaliseCableRef(match)));
  });

  return Array.from(aliases).filter((alias) => alias.length >= 3);
}

function rowMentionsAsset(row: any[], asset?: SavedMapAsset | null): boolean {
  const aliases = getAssetAliases(asset);
  if (!aliases.length) return false;

  const rowText = normaliseCableRef(getRowText(row));
  return aliases.some((alias) => rowText.includes(alias));
}

function countRowsMatching(
  allAssets: SavedMapAsset[],
  mappingRowsByAssetId: MappingRowsByAssetId,
  predicate: (row: any[], sourceAsset: SavedMapAsset, rowIndex: number) => boolean
): number {
  const keys = new Set<string>();

  allAssets.forEach((asset) => {
    const localRows = Array.isArray(asset.mappingRows) ? asset.mappingRows : [];
    const sharedRows = mappingRowsByAssetId[asset.id] || [];
    const rows = sharedRows.length ? sharedRows : localRows;

    rows.forEach((row: any[], rowIndex: number) => {
      if (!Array.isArray(row)) return;
      if (!predicate(row, asset, rowIndex)) return;

      const rowText = getRowText(row).trim();
      if (!rowText) return;

      keys.add(`${asset.id}:${rowIndex}:${normaliseCableRef(rowText)}`);
    });
  });

  return keys.size;
}

function getValidFibreNumber(value: unknown): number | null {
  const direct = Number(value);
  if (Number.isFinite(direct) && direct > 0 && direct <= 432) return direct;

  const match = String(value ?? "").match(/\b(\d{1,3})\b/);
  if (!match) return null;

  const parsed = Number(match[1]);
  return Number.isFinite(parsed) && parsed > 0 && parsed <= 432 ? parsed : null;
}

function getCableMentionCellIndex(row: any[], cable: SavedMapAsset): number | null {
  const aliases = getCableAliases(cable).sort((a, b) => b.length - a.length);
  if (!aliases.length) return null;

  for (let index = 0; index < row.length; index += 1) {
    const cellText = normaliseCableRef(String(row[index] ?? ""));
    if (!cellText) continue;
    if (aliases.some((alias) => cellText.includes(alias))) return index;
  }

  return null;
}

function getFibreNumberFromMappingRow(row: any[], cable?: SavedMapAsset): number | null {
  if (cable) {
    const cableCellIndex = getCableMentionCellIndex(row, cable);

    if (cableCellIndex !== null) {
      // Meet-me imports are normally: input cable, input fibre, output cable, output fibre.
      // Prefer the fibre number next to the cable name so tray numbers are not counted as fibres.
      for (const offset of [1, 2, -1, -2]) {
        const candidate = getValidFibreNumber(row[cableCellIndex + offset]);
        if (candidate !== null) return candidate;
      }
    }
  }

  // Generic LMJ/meet-me rows often store the usable fibre number in output/input
  // columns later in the row. Keep tray number (index 1) as the last fallback.
  for (const index of [8, 6, 4, 2, 1]) {
    const candidate = getValidFibreNumber(row?.[index]);
    if (candidate !== null) return candidate;
  }

  for (const cell of row || []) {
    const candidate = getValidFibreNumber(cell);
    if (candidate !== null) return candidate;
  }

  return null;
}


function expandMeetMeTrayEndMarkers(fibres: number[], cable?: SavedMapAsset): number[] {
  const unique = Array.from(new Set((fibres || []).filter((f) => Number.isFinite(f) && f > 0))).sort((a, b) => a - b);
  if (unique.length < 2) return unique;

  // Meet-me chamber uploads can be stored as one rendered splice row per tray.
  // In that case the saved row carries the last fibre on each 12F tray
  // (12, 24, 36 ... 240), not every live fibre.  For cable utilisation and
  // popup display this must be treated as the continuous range F1-F240.
  const looksLikeTrayEndMarkers = unique.every((f, index) => f === (index + 1) * 12);
  if (!looksLikeTrayEndMarkers) return unique;

  const capacity = getNumberFromFibreCount((cable as any)?.fibreCount || (cable as any)?.size || (cable as any)?.capacity);
  const maxFibre = unique[unique.length - 1];
  if (capacity > 0 && maxFibre > capacity) return unique;

  return Array.from({ length: maxFibre }, (_, index) => index + 1);
}

function collectUsedFibreNumbersForCable(
  allAssets: SavedMapAsset[],
  mappingRowsByAssetId: MappingRowsByAssetId,
  cable: SavedMapAsset
): number[] {
  const fibreNumbers = new Set<number>();

  allAssets.forEach((asset) => {
    const localRows = Array.isArray(asset.mappingRows) ? asset.mappingRows : [];
    const sharedRows = mappingRowsByAssetId[asset.id] || [];
    const rows = sharedRows.length ? sharedRows : localRows;

    rows.forEach((row: any[]) => {
      if (!Array.isArray(row)) return;
      if (!rowMentionsCable(row, cable)) return;

      const fibreNumber = getFibreNumberFromMappingRow(row, cable);
      if (fibreNumber !== null) fibreNumbers.add(fibreNumber);
    });
  });

  return expandMeetMeTrayEndMarkers(Array.from(fibreNumbers), cable);
}

function formatFibreRanges(fibres: number[]): string {
  if (!fibres.length) return "None found";

  const ranges: string[] = [];
  let start = fibres[0];
  let previous = fibres[0];

  for (let i = 1; i <= fibres.length; i += 1) {
    const current = fibres[i];

    if (current === previous + 1) {
      previous = current;
      continue;
    }

    ranges.push(start === previous ? String(start) : `${start}-${previous}`);
    start = current;
    previous = current;
  }

  return ranges.join(", ");
}

function getCableLinePoints(asset: SavedMapAsset): [number, number][] {
  return asset.geometry?.type === "LineString" && Array.isArray(asset.geometry.coordinates)
    ? (asset.geometry.coordinates as [number, number][]).filter(
        (point) =>
          Array.isArray(point) &&
          point.length >= 2 &&
          Number.isFinite(Number(point[0])) &&
          Number.isFinite(Number(point[1])),
      )
    : [];
}

function getCableTypeKey(asset: SavedMapAsset): string {
  const cableType = normaliseCableText((asset as any).cableType || "cable");
  if (cableType.includes("feeder")) return "feeder";
  if (cableType.includes("link")) return "link";
  if (cableType.includes("ulw")) return "ulw";
  return cableType || "cable";
}

function distancePointToSegmentMeters(
  point: [number, number],
  a: [number, number],
  b: [number, number],
): number {
  const meanLat = ((point[0] + a[0] + b[0]) / 3) * (Math.PI / 180);
  const toXY = (coord: [number, number]) => ({
    x: coord[1] * 111320 * Math.cos(meanLat),
    y: coord[0] * 111320,
  });

  const p = toXY(point);
  const start = toXY(a);
  const end = toXY(b);
  const dx = end.x - start.x;
  const dy = end.y - start.y;
  const lengthSquared = dx * dx + dy * dy;

  if (!lengthSquared) return getDistanceMeters(point, a);

  const t = Math.max(0, Math.min(1, ((p.x - start.x) * dx + (p.y - start.y) * dy) / lengthSquared));
  const projected = {
    x: start.x + t * dx,
    y: start.y + t * dy,
  };

  return Math.sqrt((p.x - projected.x) ** 2 + (p.y - projected.y) ** 2);
}

function distancePointToRouteMeters(point: [number, number], route: [number, number][]): number {
  if (!route.length) return Number.POSITIVE_INFINITY;
  if (route.length === 1) return getDistanceMeters(point, route[0]);

  let best = Number.POSITIVE_INFINITY;
  for (let index = 0; index < route.length - 1; index += 1) {
    best = Math.min(best, distancePointToSegmentMeters(point, route[index], route[index + 1]));
  }
  return best;
}

function minDistanceBetweenCableRoutes(a: SavedMapAsset, b: SavedMapAsset): number {
  const aPoints = getCableLinePoints(a);
  const bPoints = getCableLinePoints(b);
  if (!aPoints.length || !bPoints.length) return Number.POSITIVE_INFINITY;

  let best = Number.POSITIVE_INFINITY;

  aPoints.forEach((point) => {
    best = Math.min(best, distancePointToRouteMeters(point, bPoints));
  });

  bPoints.forEach((point) => {
    best = Math.min(best, distancePointToRouteMeters(point, aPoints));
  });

  return best;
}

function findPhysicalTrunkCableGroup(
  allAssets: SavedMapAsset[],
  selectedCable: SavedMapAsset,
  maxJoinMeters = 24,
): SavedMapAsset[] {
  const selectedFibreCount = getCableFibreCount(selectedCable);
  const selectedIsCore = isCoreNetworkCable(selectedCable);

  if (!selectedFibreCount || !selectedIsCore) return [selectedCable];

  const selectedCableType = getCableTypeKey(selectedCable);
  const trunkCables = allAssets.filter((candidate) => {
    if (candidate.id === selectedCable.id) return true;
    if (candidate.assetType !== "cable") return false;
    if (!isCoreNetworkCable(candidate)) return false;
    if (getCableFibreCount(candidate) !== selectedFibreCount) return false;

    const candidateType = getCableTypeKey(candidate);
    return candidateType === selectedCableType;
  });

  const byId = new Map(trunkCables.map((candidate) => [candidate.id, candidate]));
  const connectedIds = new Set<string>([selectedCable.id]);
  const queue: SavedMapAsset[] = [selectedCable];

  while (queue.length && connectedIds.size < 40) {
    const current = queue.shift()!;

    trunkCables.forEach((candidate) => {
      if (connectedIds.has(candidate.id)) return;
      if (minDistanceBetweenCableRoutes(current, candidate) > maxJoinMeters) return;

      connectedIds.add(candidate.id);
      queue.push(candidate);
    });
  }

  return Array.from(connectedIds)
    .map((id) => byId.get(id))
    .filter((asset): asset is SavedMapAsset => Boolean(asset));
}

function getCableAreaLabel(cable: SavedMapAsset): string {
  const raw = String((cable as any).name || cable.id || "Cable").trim();
  const match = raw.match(/^([A-Z]{1,4}-[A-Z0-9]{2,5})(?:-|$)/i);
  return match ? match[1].toUpperCase() : raw;
}

type RouteGroupUsage = {
  totalUsed: number;
  usedFibreNumbers: number[];
  source: string;
  breakdown: { label: string; cableName: string; count: number; ranges: string }[];
};

function countRowsForCable(
  allAssets: SavedMapAsset[],
  mappingRowsByAssetId: MappingRowsByAssetId,
  cable: SavedMapAsset,
): { count: number; fibres: number[] } {
  const rowKeys = new Set<string>();
  const fibres = new Set<number>();

  allAssets.forEach((asset) => {
    const localRows = Array.isArray(asset.mappingRows) ? asset.mappingRows : [];
    const sharedRows = mappingRowsByAssetId[asset.id] || [];
    const rows = sharedRows.length ? sharedRows : localRows;

    rows.forEach((row: any[], rowIndex: number) => {
      if (!Array.isArray(row)) return;
      if (!rowMentionsCable(row, cable)) return;

      const rowText = getRowText(row).trim();
      if (!rowText) return;

      rowKeys.add(`${asset.id}:${rowIndex}:${normaliseCableRef(rowText)}`);

      const fibreNumber = getFibreNumberFromMappingRow(row, cable);
      if (fibreNumber !== null) fibres.add(fibreNumber);
    });
  });

  const expandedFibres = expandMeetMeTrayEndMarkers(Array.from(fibres), cable);

  return {
    count: expandedFibres.length || fibres.size || rowKeys.size,
    fibres: expandedFibres,
  };
}

function getRouteGroupUsage(
  allAssets: SavedMapAsset[],
  mappingRowsByAssetId: MappingRowsByAssetId,
  selectedCable: SavedMapAsset,
): RouteGroupUsage {
  const group = findPhysicalTrunkCableGroup(allAssets, selectedCable);
  const breakdown = group
    .map((cable) => {
      const usage = countRowsForCable(allAssets, mappingRowsByAssetId, cable);
      return {
        label: getCableAreaLabel(cable),
        cableName: String((cable as any).name || cable.id || "Cable"),
        count: usage.count,
        ranges: formatFibreRanges(usage.fibres),
        fibres: usage.fibres,
      };
    })
    .filter((entry) => entry.count > 0);

  const routeFibreNumbers = Array.from(
    new Set(breakdown.flatMap((entry) => entry.fibres))
  ).sort((a, b) => a - b);
  const totalUsed = routeFibreNumbers.length || breakdown.reduce((sum, entry) => sum + entry.count, 0);
  const selectedUsage = countRowsForCable(allAssets, mappingRowsByAssetId, selectedCable);

  return {
    totalUsed,
    usedFibreNumbers: routeFibreNumbers.length ? routeFibreNumbers : selectedUsage.fibres,
    source:
      group.length > 1 && totalUsed > 0
        ? "physical-route-joint-mapping-engine"
        : selectedUsage.count > 0
          ? "joint-mapping-engine"
          : "network-state",
    breakdown: breakdown.map(({ fibres, ...entry }) => entry),
  };
}


export default function CableLinesLayer({
  assets,
  cablesVisible,
  visibleLayers = {},
  showCableDistances,
  cableDrawingMode = false,
  endpointAssetOptions,
  onDeleteAsset,
  onEditAsset,
  onUpdateAsset,
  canEditCables = true,
  canDeleteCables = true,
}: Props) {
  const map = useMap();
  const { isMobile, isTablet } = useDeviceLayout();
  const usesTouchCableSheet = isMobile || isTablet;
  const [selectedCableId, setSelectedCableId] = useState<string | null>(null);
  const [editingCableId, setEditingCableId] = useState<string | null>(null);
  const [hoveredCableId, setHoveredCableId] = useState<string | null>(null);
  const [mappingRowsByAssetId, setMappingRowsByAssetId] = useState<MappingRowsByAssetId>({});
  const [mapViewBounds, setMapViewBounds] = useState(() => map.getBounds());
  const [mapViewZoom, setMapViewZoom] = useState(() => map.getZoom());
  const cableCanvasRenderer = useMemo(() => L.canvas({ padding: 0.5 }), []);
  const shouldRunCableIntelligence = Boolean(selectedCableId || editingCableId);

  const networkAnalysisAssets = useMemo(() => {
    const sourceAssets = endpointAssetOptions?.length ? endpointAssetOptions : assets;
    const byId = new Map<string, SavedMapAsset>();

    sourceAssets.forEach((asset) => {
      const id = String(asset.id || "").trim();
      if (!id) return;
      byId.set(id, asset);
    });

    // Ensure the visible/editing cable is always present even if the global
    // option set is still loading or filtered by the workspace.
    assets.forEach((asset) => {
      const id = String(asset.id || "").trim();
      if (!id || byId.has(id)) return;
      byId.set(id, asset);
    });

    return Array.from(byId.values());
  }, [assets, endpointAssetOptions]);

  const mappingAssetKey = useMemo(
    () =>
      shouldRunCableIntelligence
        ? networkAnalysisAssets
            .filter((asset) => Boolean((asset as any).mappingRowsRef || (asset as any).mappingRowsCount))
            .map((asset) => `${asset.id}:${(asset as any).mappingRowsCount || 0}:${(asset as any).updatedAt || ""}`)
            .sort()
            .join("|")
        : "",
    [networkAnalysisAssets, shouldRunCableIntelligence]
  );

  const mappingSourceAssets = useMemo(
    () =>
      shouldRunCableIntelligence
        ? networkAnalysisAssets.filter((asset) =>
            Boolean((asset as any).mappingRowsRef || (asset as any).mappingRowsCount)
          )
        : [],
    [networkAnalysisAssets, shouldRunCableIntelligence],
  );

  const networkState = useMemo(
    () =>
      shouldRunCableIntelligence
        ? buildNetworkState(networkAnalysisAssets as any)
        : null,
    [networkAnalysisAssets, shouldRunCableIntelligence],
  );

  const connectionAssets = useMemo(() => {
    const sourceAssets = endpointAssetOptions?.length ? endpointAssetOptions : assets;
    const byId = new Map<string, SavedMapAsset>();

    sourceAssets.forEach((asset) => {
      if (!isCableEndpointSelectableAsset(asset)) return;
      const id = String(asset.id || "").trim();
      if (!id) return;
      byId.set(id, asset);
    });

    return Array.from(byId.values()).sort(
      (a, b) =>
        getEndpointOptionPriority(a) - getEndpointOptionPriority(b) ||
        getAssetDisplayName(a).localeCompare(getAssetDisplayName(b)),
    );
  }, [assets, endpointAssetOptions]);

  useEffect(() => {
    let cancelled = false;

    if (!mappingSourceAssets.length) {
      setMappingRowsByAssetId({});
      return;
    }

    Promise.all(
      mappingSourceAssets.map(async (asset) => {
        try {
          const rows = await loadJointMappingRowsFromFirestore(asset.id);
          return [asset.id, rows] as const;
        } catch (err) {
          console.error(`Failed to load mapping rows for ${asset.name || asset.id}`, err);
          return [asset.id, []] as const;
        }
      })
    ).then((entries) => {
      if (cancelled) return;
      setMappingRowsByAssetId(Object.fromEntries(entries));
    });

    return () => {
      cancelled = true;
    };
  }, [mappingAssetKey, mappingSourceAssets]);

  useMapEvents({
    click: () => {
      setSelectedCableId(null);
    },
    moveend: () => {
      setMapViewBounds(map.getBounds());
      setMapViewZoom(map.getZoom());
    },
    zoomend: () => {
      setMapViewBounds(map.getBounds());
      setMapViewZoom(map.getZoom());
    },
  });

  const renderBounds = useMemo(() => getPaddedRenderBounds(mapViewBounds), [mapViewBounds]);

  const allCableLayersVisible = cablesVisible || visibleLayers?.cables !== false;

  const isLayerOn = (key: string) => visibleLayers?.[key] !== false;

  const hasAnyIndividualCableLayerOn =
    isLayerOn("feeders") ||
    isLayerOn("ducts") ||
    isLayerOn("links") ||
    isLayerOn("dropCables") ||
    isLayerOn("ulw96") ||
    isLayerOn("ulw48") ||
    isLayerOn("ulw36") ||
    isLayerOn("ulw24") ||
    isLayerOn("ulw12");

  const cableAssets = useMemo(
    () =>
      assets.filter((asset) => {
        if (isOpenreachReferenceAsset(asset)) return false;
        const isDuct = isDuctAsset(asset);

        if (
          (!isDuct && asset.assetType !== "cable") ||
          asset.geometry?.type !== "LineString" ||
          !Array.isArray(asset.geometry.coordinates)
        ) {
          return false;
        }

        const points = asset.geometry.coordinates as [number, number][];
        if (!isLineStringInsideRenderBounds(points, renderBounds)) return false;

        if (isDuct) return !cableDrawingMode && isLayerOn("ducts");

        if (cableDrawingMode) return isEngineeringDrawingTrunkCable(asset);

        const cableType = String(asset.cableType || "").toLowerCase();
        const fibreCount = String(asset.fibreCount || "").toLowerCase();
        const isDropCable = isDropCableAsset(asset);

        if (isDropCable) return isLayerOn("dropCables");

        const matchesFeeder = cableType.includes("feeder");
        const matchesLink = cableType.includes("link");
        const matches96 = fibreCount.includes("96");
        const matches48 = fibreCount.includes("48");
        const matches36 = fibreCount.includes("36");
        const matches24 = fibreCount.includes("24");
        const matches12 = fibreCount.includes("12");

        if (
          (matchesFeeder && !isLayerOn("feeders")) ||
          (matchesLink && !isLayerOn("links")) ||
          (matches96 && !isLayerOn("ulw96")) ||
          (matches48 && !isLayerOn("ulw48")) ||
          (matches36 && !isLayerOn("ulw36")) ||
          (matches24 && !isLayerOn("ulw24")) ||
          (matches12 && !isLayerOn("ulw12"))
        ) {
          return false;
        }

        if (allCableLayersVisible) return true;

        return (
          (matchesFeeder && isLayerOn("feeders")) ||
          (matchesLink && isLayerOn("links")) ||
          (matches96 && isLayerOn("ulw96")) ||
          (matches48 && isLayerOn("ulw48")) ||
          (matches36 && isLayerOn("ulw36")) ||
          (matches24 && isLayerOn("ulw24")) ||
          (matches12 && isLayerOn("ulw12"))
        );
      }),
    [assets, allCableLayersVisible, renderBounds, visibleLayers, cableDrawingMode],
  );

  if (!cableDrawingMode && !allCableLayersVisible && !hasAnyIndividualCableLayerOn) return null;

  const updateCableCoordinates = (
    asset: SavedMapAsset,
    coordinates: [number, number][]
  ) => {
    const cleanedCoordinates = sanitizeCableCoordinates(coordinates);

    onEditAsset({
      ...asset,
      geometry: {
        ...asset.geometry,
        type: "LineString",
        coordinates: cleanedCoordinates,
      },
    });
  };

  const handleMovePoint = (
    asset: SavedMapAsset,
    index: number,
    lat: number,
    lng: number
  ) => {
    if (asset.geometry?.type !== "LineString") return;

    const updated = [...asset.geometry.coordinates];
    updated[index] = [lat, lng];

    // Dragging a route handle must move one existing vertex only.
    // It must never append or duplicate geometry points.
    updateCableCoordinates(asset, updated);
  };

  const handleInsertMidpoint = (asset: SavedMapAsset, i: number) => {
    if (asset.geometry?.type !== "LineString") return;

    const coords = asset.geometry.coordinates;
    const start = coords[i];
    const end = coords[i + 1];

    if (!start || !end) return;

    if (getDistanceMeters(start, end) < ROUTE_EDIT_MIN_INSERT_SPAN_METERS) return;

    const updated = [...coords];
    updated.splice(i + 1, 0, getMidpoint(start, end));

    updateCableCoordinates(asset, updated);
  };

  return (
    <>
      {cableAssets.map((asset) => {
        const points =
          asset.geometry?.type === "LineString"
            ? asset.geometry.coordinates
            : [];

        const length = getTuplePathDistanceMeters(points);
        const isDuct = isDuctAsset(asset);
        const parentDuct =
          !isDuct && (asset as any).ductId
            ? networkAnalysisAssets.find(
                (candidate) => candidate.id === (asset as any).ductId && isDuctAsset(candidate),
              ) || null
            : null;
        const linkedCableIds = Array.isArray((asset as any).linkedCableIds)
          ? ((asset as any).linkedCableIds as string[])
          : [];
        const isHovered = hoveredCableId === asset.id;
        const isSelected = selectedCableId === asset.id;
        const isEditing = editingCableId === asset.id;
        const shouldCalculateCableDetails = !isDuct && (isSelected || isEditing);
        const baseColor = getCableColor(asset, length);
        const cableColor = isSelected ? "#f59e0b" : baseColor;
        const ductLinePositions = isDuct
          ? getDuctParallelLinePositions(asset, points, map)
          : [];
        const displayPoints = parentDuct
          ? getDuctSlotCablePositions(parentDuct, asset, points, map)
          : points;
        const routeEditHandleIndexes = isEditing ? getRouteEditHandleIndexes(points) : [];
        const routeEditInsertSegmentIndexes = isEditing
          ? new Set(getRouteEditInsertSegmentIndexes(points, routeEditHandleIndexes))
          : new Set<number>();
        const rendersMixedInstallSegments = hasMixedSegmentInstallMethods(asset);
        const dailyProgress = getDailyRouteProgress(asset);

        const startAsset = shouldCalculateCableDetails
          ? points.length >= 2
            ? resolveCableEndpointAsset(asset, connectionAssets, "from", points[0])
            : resolveCableEndpointAsset(asset, connectionAssets, "from")
          : null;

        const endAsset = shouldCalculateCableDetails
          ? points.length >= 2
            ? resolveCableEndpointAsset(asset, connectionAssets, "to", points[points.length - 1])
            : resolveCableEndpointAsset(asset, connectionAssets, "to")
          : null;

        

        const routeGroupUsage: RouteGroupUsage = shouldCalculateCableDetails
          ? getRouteGroupUsage(networkAnalysisAssets, mappingRowsByAssetId, asset)
          : {
              totalUsed: 0,
              usedFibreNumbers: [],
              source: "deferred",
              breakdown: [],
            };

        const usedFibreNumbersFromMappings = shouldCalculateCableDetails
          ? collectUsedFibreNumbersForCable(
              networkAnalysisAssets,
              mappingRowsByAssetId,
              asset,
            )
          : [];

        const usedFibresFromSharedMappings = shouldCalculateCableDetails
          ? usedFibreNumbersFromMappings.length
            ? usedFibreNumbersFromMappings.length
            : countRowsMatching(
                networkAnalysisAssets,
                mappingRowsByAssetId,
                (row) => rowMentionsCable(row, asset),
              )
          : 0;

        const cableState = shouldCalculateCableDetails
          ? networkState?.cableStates?.[asset.id]
          : undefined;

        const usedFibreNumbers = usedFibreNumbersFromMappings.length
          ? usedFibreNumbersFromMappings
          : routeGroupUsage.usedFibreNumbers.length
            ? routeGroupUsage.usedFibreNumbers
            : cableState?.usedFibreNumbers || [];

        const localLegacyUsedFibres = shouldCalculateCableDetails
          ? getCableUsedFibres(asset, networkAnalysisAssets)
          : 0;
        const usedFibres = usedFibreNumbers.length
          ? usedFibreNumbers.length
          : usedFibresFromSharedMappings > 0
            ? usedFibresFromSharedMappings
            : routeGroupUsage.totalUsed > 0
              ? routeGroupUsage.totalUsed
              : Math.max(cableState?.usedFibres ?? 0, localLegacyUsedFibres);

        const networkStateSource = routeGroupUsage.totalUsed > usedFibresFromSharedMappings
          ? routeGroupUsage.source
          : usedFibreNumbersFromMappings.length || usedFibresFromSharedMappings > 0
            ? "joint-mapping-engine"
            : cableState?.source || (localLegacyUsedFibres > 0 ? "network-state-cable-usage" : "network-state");

        const usedFibreRangeLabel = shouldCalculateCableDetails
          ? formatFibreRanges(usedFibreNumbers)
          : "Select cable to calculate";
        const capacityWarning = cableState?.warnings?.length
          ? cableState.warnings.join(" • ")
          : getCableCapacityWarning(asset, usedFibres);

        const selectedFromId = String((asset as any).fromAssetId || (asset as any).startAssetId || startAsset?.id || "");
        const selectedToId = String((asset as any).toAssetId || (asset as any).endAssetId || endAsset?.id || "");

        const handleEndpointChange = (side: "from" | "to", endpointId: string) => {
          const cleanEndpointId = String(endpointId || "").trim();
          const otherEndpointId = side === "from" ? selectedToId : selectedFromId;

          if (cleanEndpointId && otherEndpointId && cleanEndpointId === otherEndpointId) {
            alert("Start and end asset cannot be the same.");
            return;
          }

          const endpointAsset = cleanEndpointId
            ? connectionAssets.find((candidate) => String(candidate.id) === cleanEndpointId) || null
            : null;

          const updatedCable = buildCableWithEndpoint(asset, side, endpointAsset);

          if (onUpdateAsset) {
            onUpdateAsset(updatedCable);
            return;
          }

          onEditAsset(updatedCable);
        };

        return (
          <React.Fragment key={asset.id}>
            {rendersMixedInstallSegments
              ? points.slice(0, -1).map((point, index) => {
                  const nextPoint = points[index + 1];
                  if (!nextPoint) return null;
                  const segmentMethod = getSegmentInstallMethod(asset, index);

                  return (
                    <Polyline
                      key={`${asset.id}-install-segment-${index}`}
                      renderer={cableCanvasRenderer}
                      positions={[point, nextPoint]}
                      interactive={false}
                      pathOptions={{
                        color: cableColor,
                        weight: isSelected ? 9 : isHovered || isEditing ? 7 : 4,
                        opacity: isSelected || isHovered || isEditing ? 1 : 0.85,
                        dashArray: segmentMethod === "OH" ? "10, 8" : undefined,
                      }}
                    />
                  );
                })
              : null}
            {isDuct
              ? ductLinePositions.map((positions, index) => (
                  <Polyline
                    key={`${asset.id}-duct-line-${index}`}
                    renderer={cableCanvasRenderer}
                    positions={positions}
                    interactive={false}
                    pathOptions={{
                      color: cableColor,
                      weight: isSelected ? 4 : isHovered || isEditing ? 3.5 : 3,
                      opacity: isSelected || isHovered || isEditing ? 1 : 0.95,
                      dashArray: undefined,
                    }}
                  />
                ))
              : null}
            <Polyline
              renderer={cableCanvasRenderer}
              positions={displayPoints}
              pathOptions={{
                color: cableColor,
                weight: isDuct ? 18 : isSelected ? 9 : isHovered || isEditing ? 7 : 4,
                opacity: isDuct
                  ? 0.01
                  : rendersMixedInstallSegments
                  ? 0.02
                  : isSelected || isHovered || isEditing
                    ? 1
                    : 0.85,
                dashArray: isDuct ? undefined : getDashArray(asset),
                className: isSelected && !isDuct ? "selected-cable-glow" : "",
              }}
              eventHandlers={{
                click: (e) => {
                  L.DomEvent.stopPropagation(e);
                  if (cableDrawingMode) return;
                  setSelectedCableId(asset.id);
                  focusCableClick(map, e.latlng);
                },
                mouseover: () => setHoveredCableId(asset.id),
                mouseout: () => setHoveredCableId(null),
              }}
            >
              {!cableDrawingMode && !isMobile ? (
              <Popup>
                <div style={{ minWidth: 240 }}>
                  <div style={{ fontWeight: 700, fontSize: "1rem" }}>
                    {isDuct
                      ? getDuctBundleTitle(asset)
                      : asset.name || "Unnamed Cable"}
                  </div>

                  {isDuct ? (
                    <>
                      <div style={{ marginTop: 6 }}>
                        <b>Spec:</b> {getDuctLabel(asset)}
                      </div>

                      <div>
                        <b>Use:</b> {(asset as any).ductUse || "Main route"}
                      </div>

                      <div>
                        <b>Linked cables:</b> {linkedCableIds.length}
                      </div>

                      <div style={{ marginTop: 6 }}>
                        <b>Ducts:</b> {getDuctNumberLabels(asset).join(", ")}
                      </div>
                    </>
                  ) : (
                    <div style={{ marginTop: 6 }}>
                      <b>Size:</b> {asset.fibreCount || "N/A"}
                    </div>
                  )}

                  {!isDuct ? (
                    <div>
                      <b>Type:</b> {asset.cableType || "Cable"}
                    </div>
                  ) : null}

                  {!isDuct && (asset as any).subDuctDiameterMm ? (
                    <div>
                      <b>Sub duct:</b> {(asset as any).subDuctDiameterMm}mm
                      {(asset as any).ductNumber ? ` in Duct ${(asset as any).ductNumber}` : ""}
                    </div>
                  ) : null}

                  <div>
                    <b>Install:</b> {asset.installMethod || "Underground"}
                  </div>

                  <div>
                    <b>Length:</b> {formatCableLength(length)}
                  </div>

                  {!isDuct ? (
                    <div>
                      <b>Used fibres:</b> {usedFibres} /{" "}
                      {asset.fibreCount || "N/A"}
                    </div>
                  ) : null}

                  {!isDuct ? (
                    <div>
                      <b>Fibre numbers:</b> {usedFibreRangeLabel}
                    </div>
                  ) : null}

                  {!isDuct && routeGroupUsage.breakdown.length > 1 ? (
                    <div style={{ marginTop: 6, fontSize: 12 }}>
                      <b>Route breakdown:</b>
                      <div style={{ marginTop: 2 }}>
                        {routeGroupUsage.breakdown.map((entry) => (
                          <div key={`${asset.id}-${entry.cableName}`}>
                            {entry.label}: {entry.count}F
                            {entry.ranges !== "None found" ? ` (${entry.ranges})` : ""}
                          </div>
                        ))}
                      </div>
                    </div>
                  ) : null}

                  {!isDuct ? (
                  <div style={{ marginTop: 4, color: "#64748b", fontSize: 12 }}>
                    <b>Network state:</b> {networkStateSource}
                  </div>
                  ) : null}

                  {!isDuct && capacityWarning ? (
                    <div style={{ marginTop: 4, color: cableState?.warnings?.length ? "#dc2626" : "#475569", fontSize: 12 }}>
                      {capacityWarning}
                    </div>
                  ) : null}

                  <div>
                    <b>From:</b> {getAssetDisplayName(startAsset)}
                  </div>

                  <div>
                    <b>To:</b> {getAssetDisplayName(endAsset)}
                  </div>

                  {!isDuct ? (
                  <div style={{ marginTop: 8, paddingTop: 8, borderTop: "1px solid #e5e7eb" }}>
                    <div style={{ fontWeight: 700, marginBottom: 4 }}>Connections</div>
                    <label style={{ display: "block", fontSize: 12, fontWeight: 700, marginBottom: 2 }}>
                      From
                    </label>
                    <select
                      value={selectedFromId}
                      onChange={(e) => handleEndpointChange("from", e.target.value)}
                      style={{ width: "100%", marginBottom: 6 }}
                    >
                      <option value="">Auto / not set</option>
                      {connectionAssets.map((candidate) => (
                        <option key={`from-${asset.id}-${candidate.id}`} value={candidate.id}>
                          {getEndpointOptionLabel(candidate)}
                        </option>
                      ))}
                    </select>

                    <label style={{ display: "block", fontSize: 12, fontWeight: 700, marginBottom: 2 }}>
                      To
                    </label>
                    <select
                      value={selectedToId}
                      onChange={(e) => handleEndpointChange("to", e.target.value)}
                      style={{ width: "100%" }}
                    >
                      <option value="">Auto / not set</option>
                      {connectionAssets.map((candidate) => (
                        <option key={`to-${asset.id}-${candidate.id}`} value={candidate.id}>
                          {getEndpointOptionLabel(candidate)}
                        </option>
                      ))}
                    </select>
                  </div>
                  ) : null}

                  {asset.notes ? (
                    <div style={{ marginTop: 8 }}>{asset.notes}</div>
                  ) : null}

                  <div
                    style={{
                      marginTop: 10,
                      display: "flex",
                      gap: 8,
                      flexWrap: "wrap",
                    }}
                  >
                    <button
                      onClick={(event) => {
                        event.stopPropagation();
                        onEditAsset(asset);
                      }}
                    >
                      Edit details
                    </button>

                    {canEditCables ? (
                      <button
                        onClick={(event) => {
                          event.stopPropagation();
                          setSelectedCableId(asset.id);
                          setEditingCableId(asset.id);
                        }}
                      >
                        Edit route
                      </button>
                    ) : null}

                    <button
                      onClick={(event) => {
                        event.stopPropagation();
                        setEditingCableId(null);
                      }}
                    >
                      Done
                    </button>

                    {canDeleteCables ? (
                      <button
                        onClick={(event) => {
                          event.stopPropagation();
                          setSelectedCableId(null);
                          setEditingCableId(null);
                          map.closePopup();
                          onDeleteAsset(asset.id);
                        }}
                      >
                        Delete
                      </button>
                    ) : null}
                  </div>
                </div>
              </Popup>
              ) : null}

              {!cableDrawingMode ? (
              <Tooltip sticky>
                {isDuct ? getDuctBundleTitle(asset) : asset.name || "Cable"} - {isDuct ? getDuctLabel(asset) : asset.fibreCount || "N/A"} - {formatCableLength(length)}
              </Tooltip>
              ) : null}
            </Polyline>

            {!cableDrawingMode && dailyProgress.team ? (
              <Polyline
                renderer={cableCanvasRenderer}
                positions={displayPoints}
                interactive={false}
                pathOptions={{
                  color: getDailyProgressTeamColour(dailyProgress.team),
                  weight: isDuct ? 10 : isSelected ? 11 : 8,
                  opacity: 0.96,
                  dashArray: "14, 8",
                }}
              >
                {!isMobile ? (
                  <Tooltip sticky>
                    {isDuct ? getDuctBundleTitle(asset) : asset.name || "Cable"} - today {dailyProgress.team}: {dailyProgress.meters.toFixed(1)}m
                  </Tooltip>
                ) : null}
              </Polyline>
            ) : null}

            {!cableDrawingMode && usesTouchCableSheet && isSelected ? (
              <div
                style={getTouchCableSheetStyle(isTablet)}
                onClick={(event) => event.stopPropagation()}
              >
                {!isTablet ? <div style={mobileSheetHandleStyle} /> : null}
                <div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}>
                  <div style={{ minWidth: 0 }}>
                    <div style={mobileSheetKickerStyle}>{isDuct ? "Duct asset" : "Cable asset"}</div>
                    <div style={mobileSheetTitleStyle}>
                      {isDuct ? getDuctBundleTitle(asset) : asset.name || "Unnamed Cable"}
                    </div>
                    <div style={mobileSheetMetaStyle}>
                      {isDuct
                        ? getDuctLabel(asset)
                        : (asset as any).subDuctDiameterMm
                          ? `${(asset as any).subDuctDiameterMm}mm sub duct`
                          : asset.cableType || "Cable"} - {isDuct ? (asset as any).ductUse || "Main route" : asset.fibreCount || "N/A"} - {formatCableLength(length)}
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={() => {
                      setSelectedCableId(null);
                      setEditingCableId(null);
                    }}
                    aria-label="Close selected cable panel"
                    style={mobileSheetCloseButtonStyle}
                  >
                    x
                  </button>
                </div>

                <div style={mobileCableSummaryStyle}>
                  <span>Install</span>
                  <strong>{getCableInstallSummary(asset)}</strong>
                </div>

                {isDuct ? (
                  <div style={mobileCableSummaryStyle}>
                    <span>Linked cables</span>
                    <strong>{linkedCableIds.length}</strong>
                  </div>
                ) : (
                  <div style={mobileCableSummaryStyle}>
                    <span>Used fibres</span>
                    <strong>{usedFibres} / {asset.fibreCount || "N/A"}</strong>
                  </div>
                )}

                {!isDuct && capacityWarning ? (
                  <div style={mobileCableWarningStyle}>{capacityWarning}</div>
                ) : null}

                <div style={mobileCableButtonGridStyle}>
                  <button type="button" style={mobilePrimaryButtonStyle} onClick={() => onEditAsset(asset)}>
                    {isDuct ? "Open Duct Editor" : "View / Edit"}
                  </button>
                  {canEditCables ? (
                    <button
                      type="button"
                      style={mobileSecondaryButtonStyle}
                      onClick={() => {
                        setSelectedCableId(asset.id);
                        setEditingCableId(asset.id);
                      }}
                    >
                      Edit Route
                    </button>
                  ) : null}
                  <button
                    type="button"
                    style={mobileSecondaryButtonStyle}
                    onClick={() => {
                      const point = points[0];
                      if (!point) return;
                      window.open(
                        `https://www.google.com/maps/dir/?api=1&destination=${point[0]},${point[1]}&travelmode=driving`,
                        "_blank",
                        "noopener,noreferrer",
                      );
                    }}
                  >
                    Navigate
                  </button>
                  {canDeleteCables ? (
                    <button
                      type="button"
                      style={mobileDangerButtonStyle}
                      onClick={() => {
                        setSelectedCableId(null);
                        setEditingCableId(null);
                        onDeleteAsset(asset.id);
                      }}
                    >
                      Delete
                    </button>
                  ) : null}
                </div>
              </div>
            ) : null}

            {showCableDistances === true && mapViewZoom >= 17 &&
              points.slice(0, -1).map((coord, i) => {
                const next = points[i + 1];
                if (!next) return null;

                const spanLength = getDistanceMeters(coord, next);

                return (
                  <Marker
                    key={`${asset.id}-distance-${i}`}
                    position={getOffsetCableLabelPosition(coord, next)}
                    interactive={false}
                    icon={getCableDistanceLabelIcon(
                      formatCableLength(spanLength),
                      getCableSpanAngleDegrees(coord, next)
                    )}
                  />
                );
              })}

            {isEditing &&
              routeEditHandleIndexes.map((i) => {
                const coord = points[i];
                if (!coord) return null;

                return (
                  <Marker
                    key={`${asset.id}-drag-${i}`}
                    position={coord}
                    draggable
                    eventHandlers={{
                      dragend: (e) => {
                        const p = e.target.getLatLng();
                        handleMovePoint(asset, i, p.lat, p.lng);
                      },
                    }}
                  />
                );
              })}

            {isEditing &&
              points.slice(0, -1).map((coord, i) => {
                if (!routeEditInsertSegmentIndexes.has(i)) return null;

                const next = points[i + 1];
                if (!next) return null;

                return (
                  <CircleMarker
                    renderer={cableCanvasRenderer}
                    key={`${asset.id}-mid-${i}`}
                    center={getMidpoint(coord, next)}
                    radius={5}
                    pathOptions={{
                      color: getCableColor(asset),
                      weight: 2,
                      fillOpacity: 0.85,
                    }}
                    eventHandlers={{
                      click: () => handleInsertMidpoint(asset, i),
                    }}
                  />
                );
              })}
          </React.Fragment>
        );
      })}
    </>
  );
}

function isDuctAsset(asset: SavedMapAsset): boolean {
  return String((asset as any).assetType || "").toLowerCase() === "duct";
}

function getDuctLabel(asset: SavedMapAsset): string {
  const count = Math.max(1, Math.round(Number((asset as any).ductCount || 1)));
  const diameter = Math.max(1, Math.round(Number((asset as any).ductDiameterMm || 96)));
  return `${count} x ${diameter}mm`;
}

function getDuctCount(asset: SavedMapAsset): number {
  return Math.max(1, Math.min(12, Math.round(Number((asset as any).ductCount || 1))));
}

function getDuctStartNumber(asset: SavedMapAsset): number {
  const storedStart = Number((asset as any).ductStartNumber);
  if (Number.isFinite(storedStart) && storedStart > 0) return Math.round(storedStart);

  const match = String(asset.name || "").trim().match(/^duct\s+(\d+)/i);
  return match ? Number(match[1]) : 1;
}

function getDuctNumberLabels(asset: SavedMapAsset): string[] {
  const start = getDuctStartNumber(asset);
  return Array.from({ length: getDuctCount(asset) }, (_, index) => `Duct ${start + index}`);
}

function getDuctBundleTitle(asset: SavedMapAsset): string {
  const labels = getDuctNumberLabels(asset);
  if (labels.length === 1) return labels[0];
  return `${labels[0]}-${labels[labels.length - 1].replace("Duct ", "")}`;
}

function getDuctLineOffsets(asset: SavedMapAsset): number[] {
  const count = getDuctCount(asset);
  const spacingPx = 5;
  const middle = (count - 1) / 2;
  return Array.from({ length: count }, (_, index) => (index - middle) * spacingPx);
}

function getOffsetRoutePoints(
  points: [number, number][],
  map: L.Map,
  offsetPx: number,
): [number, number][] {
  if (!offsetPx || points.length < 2) return points;

  return points.map((point, index) => {
    const previous = points[Math.max(0, index - 1)];
    const next = points[Math.min(points.length - 1, index + 1)];
    const previousLayerPoint = map.latLngToLayerPoint(L.latLng(previous[0], previous[1]));
    const nextLayerPoint = map.latLngToLayerPoint(L.latLng(next[0], next[1]));
    const currentLayerPoint = map.latLngToLayerPoint(L.latLng(point[0], point[1]));
    const dx = nextLayerPoint.x - previousLayerPoint.x;
    const dy = nextLayerPoint.y - previousLayerPoint.y;
    const length = Math.sqrt(dx * dx + dy * dy) || 1;
    const offsetLayerPoint = L.point(
      currentLayerPoint.x + (-dy / length) * offsetPx,
      currentLayerPoint.y + (dx / length) * offsetPx,
    );
    const offsetLatLng = map.layerPointToLatLng(offsetLayerPoint);
    return [offsetLatLng.lat, offsetLatLng.lng];
  });
}

function getDuctParallelLinePositions(
  asset: SavedMapAsset,
  points: [number, number][],
  map: L.Map,
): [number, number][][] {
  return getDuctLineOffsets(asset).map((offsetPx) =>
    getOffsetRoutePoints(points, map, offsetPx),
  );
}

function getDuctSlotCablePositions(
  duct: SavedMapAsset,
  cable: SavedMapAsset,
  points: [number, number][],
  map: L.Map,
): [number, number][] {
  const ductNumber = Number((cable as any).ductNumber || (cable as any).ductSlotNumber);
  if (!Number.isFinite(ductNumber)) return points;

  const startNumber = getDuctStartNumber(duct);
  const index = Math.max(0, Math.min(getDuctCount(duct) - 1, Math.round(ductNumber) - startNumber));
  const offset = getDuctLineOffsets(duct)[index] || 0;
  return getOffsetRoutePoints(points, map, offset);
}

const mobileCableSheetStyle: React.CSSProperties = {
  position: "absolute",
  left: 10,
  right: 10,
  bottom: 14,
  zIndex: 2450,
  borderRadius: 22,
  border: "1px solid rgba(148,163,184,0.35)",
  background: "rgba(15,23,42,0.96)",
  color: "white",
  boxShadow: "0 18px 42px rgba(0,0,0,0.45)",
  padding: 14,
  backdropFilter: "blur(12px)",
  pointerEvents: "auto",
};

function getTouchCableSheetStyle(isTablet: boolean): React.CSSProperties {
  if (!isTablet) return mobileCableSheetStyle;

  return {
    ...mobileCableSheetStyle,
    left: "auto",
    right: 14,
    bottom: 88,
    width: 340,
    maxWidth: "calc(100% - 28px)",
    borderRadius: 18,
  };
}

const mobileSheetHandleStyle: React.CSSProperties = {
  width: 46,
  height: 5,
  borderRadius: 999,
  background: "rgba(148,163,184,0.55)",
  margin: "0 auto 12px",
};

const mobileSheetKickerStyle: React.CSSProperties = {
  color: "#93c5fd",
  fontSize: 11,
  fontWeight: 900,
  letterSpacing: 0.8,
  textTransform: "uppercase",
};

const mobileSheetTitleStyle: React.CSSProperties = {
  marginTop: 3,
  fontSize: 18,
  fontWeight: 900,
  overflow: "hidden",
  textOverflow: "ellipsis",
  whiteSpace: "nowrap",
};

const mobileSheetMetaStyle: React.CSSProperties = {
  marginTop: 4,
  color: "#cbd5e1",
  fontSize: 12,
};

const mobileSheetCloseButtonStyle: React.CSSProperties = {
  width: 34,
  height: 34,
  borderRadius: 999,
  border: "1px solid rgba(148,163,184,0.35)",
  background: "rgba(30,41,59,0.9)",
  color: "white",
  fontWeight: 900,
  flex: "0 0 auto",
};

const mobileCableSummaryStyle: React.CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  gap: 10,
  marginTop: 12,
  padding: "9px 10px",
  borderRadius: 12,
  background: "rgba(30,41,59,0.78)",
  border: "1px solid rgba(148,163,184,0.22)",
  color: "#cbd5e1",
  fontSize: 12,
};

const mobileCableWarningStyle: React.CSSProperties = {
  marginTop: 10,
  padding: "8px 10px",
  borderRadius: 12,
  background: "rgba(127,29,29,0.35)",
  border: "1px solid rgba(248,113,113,0.45)",
  color: "#fecaca",
  fontSize: 12,
  fontWeight: 800,
};

const mobileCableButtonGridStyle: React.CSSProperties = {
  display: "grid",
  gridTemplateColumns: "1fr 1fr",
  gap: 8,
  marginTop: 12,
};

const mobilePrimaryButtonStyle: React.CSSProperties = {
  minHeight: 44,
  borderRadius: 14,
  border: "none",
  background: "#2563eb",
  color: "white",
  fontWeight: 900,
  fontSize: 13,
};

const mobileSecondaryButtonStyle: React.CSSProperties = {
  ...mobilePrimaryButtonStyle,
  border: "1px solid rgba(148,163,184,0.35)",
  background: "rgba(30,41,59,0.92)",
};

const mobileDangerButtonStyle: React.CSSProperties = {
  ...mobilePrimaryButtonStyle,
  border: "1px solid rgba(248,113,113,0.55)",
  background: "#991b1b",
};

