import type { LatLngLiteral } from "leaflet";
import type { OsmBounds } from "./loadOsmBuildings";
import type { SavedMapAsset } from "../types";

// =====================================================
// VIEWPORT RENDER FILTERING
// Render-only optimisation: keep data loaded in memory, but only pass
// assets inside the current Leaflet screen bounds into heavy Leaflet layers.
// This does NOT write visibility flags and does NOT change Firestore reads.
// =====================================================
const VIEWPORT_PADDING_DEGREES = 0.0025;
const MIN_ZOOM_MARKERS = 13;
const MIN_ZOOM_CABLES = 14;
const MIN_ZOOM_OR_ROUTES = 15;
const MIN_ZOOM_OR_POINTS = 16;
const MIN_ZOOM_HOMES = 17;
const MIN_ZOOM_DROP_CABLES = 18;

function boundsWithPadding(bounds: OsmBounds | null, padding = VIEWPORT_PADDING_DEGREES): OsmBounds | null {
  if (!bounds) return null;
  return {
    south: bounds.south - padding,
    west: bounds.west - padding,
    north: bounds.north + padding,
    east: bounds.east + padding,
  };
}

function pointInsideBounds(point: LatLngLiteral, bounds: OsmBounds | null): boolean {
  if (!bounds) return true;
  return (
    point.lat >= bounds.south &&
    point.lat <= bounds.north &&
    point.lng >= bounds.west &&
    point.lng <= bounds.east
  );
}

function assetRenderPoints(asset: SavedMapAsset): LatLngLiteral[] {
  const item = asset as any;

  if (typeof item.lat === "number" && typeof item.lng === "number") {
    return [{ lat: item.lat, lng: item.lng }];
  }

  const geometry = asset.geometry;
  if (!geometry) return [];

  if (geometry.type === "Point") {
    const [lat, lng] = geometry.coordinates as any;
    return Number.isFinite(Number(lat)) && Number.isFinite(Number(lng))
      ? [{ lat: Number(lat), lng: Number(lng) }]
      : [];
  }

  if (geometry.type === "LineString") {
    return ((geometry.coordinates || []) as any[])
      .map(([lat, lng]) => ({ lat: Number(lat), lng: Number(lng) }))
      .filter((point) => Number.isFinite(point.lat) && Number.isFinite(point.lng));
  }

  if (geometry.type === "Polygon") {
    return (((geometry.coordinates || [])[0] || []) as any[])
      .map(([lat, lng]) => ({ lat: Number(lat), lng: Number(lng) }))
      .filter((point) => Number.isFinite(point.lat) && Number.isFinite(point.lng));
  }

  return [];
}

export function assetTouchesViewport(asset: SavedMapAsset, bounds: OsmBounds | null): boolean {
  const padded = boundsWithPadding(bounds);
  if (!padded) return true;
  const points = assetRenderPoints(asset);
  if (!points.length) return true;
  return points.some((point) => pointInsideBounds(point, padded));
}

function isHomeRenderAsset(asset: SavedMapAsset): boolean {
  const item = asset as any;
  const text = [item.assetType, item.type, item.jointType, item.name, item.homeType, item.uprn]
    .map((value) => String(value ?? "").toLowerCase())
    .join(" ");

  return text.includes("home") || text.includes("uprn") || text.includes("premise") || text.includes("property");
}

function isDropCableRenderAsset(asset: SavedMapAsset): boolean {
  const item = asset as any;
  const text = [item.assetType, item.type, item.cableType, item.name, item.generatedBy]
    .map((value) => String(value ?? "").toLowerCase())
    .join(" ");

  return (
    text.includes("drop") ||
    item.isDropCable === true ||
    item.isHomeDrop === true ||
    item.generatedDrop === true ||
    item.autoGeneratedDrop === true ||
    Boolean(item.homeId || item.connectedHomeId)
  );
}

function isCableRenderAsset(asset: SavedMapAsset): boolean {
  const item = asset as any;
  const type = String(item.assetType || item.type || "").toLowerCase();
  return type.includes("cable") || asset.geometry?.type === "LineString";
}

export function shouldRenderOperationalAssetAtZoom(asset: SavedMapAsset, zoom: number): boolean {
  if (isDropCableRenderAsset(asset)) return zoom >= MIN_ZOOM_DROP_CABLES;
  if (isHomeRenderAsset(asset)) return zoom >= MIN_ZOOM_HOMES;
  if (isCableRenderAsset(asset)) return zoom >= MIN_ZOOM_CABLES;
  return zoom >= MIN_ZOOM_MARKERS || asset.geometry?.type === "Polygon";
}

export function shouldRenderOpenreachAssetAtZoom(asset: SavedMapAsset, zoom: number): boolean {
  if (asset.geometry?.type === "LineString") return zoom >= MIN_ZOOM_OR_ROUTES;
  return zoom >= MIN_ZOOM_OR_POINTS;
}
