import type { JobPackAssetRecord, JobPackDocumentModel, JobPackRisk, JobPackSection } from './jobPackTypes';
import { buildJobPackMapPdfHtml } from './jobPackMapPdfEngine';

export type JobPackDownloadFormat = 'zip' | 'html' | 'json';

export interface JobPackDownloadFile {
  path: string;
  mimeType: string;
  content: string;
}

export interface JobPackDownloadBundle {
  fileName: string;
  files: JobPackDownloadFile[];
}

const textEncoder = new TextEncoder();

function safeFileName(value: string): string {
  return (value || 'job-pack')
    .replace(/[\\/:*?"<>|]+/g, '-')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .toUpperCase();
}

function csvCell(value: unknown): string {
  const text = value === null || value === undefined ? '' : String(value);
  return `"${text.replace(/"/g, '""')}"`;
}

function csvRow(values: unknown[]): string {
  return values.map(csvCell).join(',');
}

function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function sectionToMarkdown(section: JobPackSection): string {
  return [`## ${section.title}`, '', ...section.lines.map((line) => `- ${line}`), ''].join('\n');
}

function assetRegisterCsv(assets: JobPackAssetRecord[]): string {
  const rows = [
    csvRow(['Asset ID', 'Name', 'Type', 'Status', 'Install Method', 'Fibre Count', 'Cable Type', 'Geometry', 'Work Instruction', 'Validation Notes']),
    ...assets.map((asset) => csvRow([
      asset.id,
      asset.name,
      asset.type,
      asset.status || '',
      asset.installMethod || '',
      asset.fibreCount || '',
      asset.cableType || '',
      asset.geometrySummary,
      asset.workInstruction,
      asset.validationNotes.join(' | '),
    ])),
  ];
  return rows.join('\n');
}

function riskRegisterCsv(risks: JobPackRisk[]): string {
  const rows = [
    csvRow(['Risk ID', 'Level', 'Title', 'Asset ID', 'Asset Name', 'Message', 'Recommended Action']),
    ...risks.map((risk) => csvRow([
      risk.id,
      risk.level,
      risk.title,
      risk.assetId || '',
      risk.assetName || '',
      risk.message,
      risk.recommendedAction,
    ])),
  ];
  return rows.join('\n');
}

function jobPackMarkdown(jobPack: JobPackDocumentModel): string {
  return [
    `# ${jobPack.jobPackNumber}`,
    '',
    `Area: ${jobPack.areaName || jobPack.areaId}`,
    `Revision: ${jobPack.revisionNumber || 'Live Draft'}`,
    `Status: ${jobPack.status.replace(/_/g, ' ')}`,
    `Generated: ${jobPack.generatedAt}`,
    `Generated By: ${jobPack.generatedBy || 'Unknown'}`,
    `Issued: ${jobPack.issuedAt || 'Not issued'}`,
    `Reason: ${jobPack.reason}`,
    '',
    '## Summary',
    '',
    `- Total assets: ${jobPack.summary.totalAssets}`,
    `- Poles: ${jobPack.summary.poles}`,
    `- Chambers: ${jobPack.summary.chambers}`,
    `- DPs: ${jobPack.summary.distributionPoints}`,
    `- Joints: ${jobPack.summary.joints}`,
    `- Cables: ${jobPack.summary.cables}`,
    `- Homes: ${jobPack.summary.homes}`,
    `- Warnings: ${jobPack.summary.warnings}`,
    `- Blockers: ${jobPack.summary.blockers}`,
    '',
    ...jobPack.sections.map(sectionToMarkdown),
  ].join('\n');
}

export function buildJobPackHtml(jobPack: JobPackDocumentModel): string {
  const riskRows = jobPack.risks.length
    ? jobPack.risks.map((risk) => `
      <tr>
        <td>${escapeHtml(risk.level.toUpperCase())}</td>
        <td>${escapeHtml(risk.assetName || 'Area')}</td>
        <td>${escapeHtml(risk.message)}</td>
        <td>${escapeHtml(risk.recommendedAction)}</td>
      </tr>`).join('')
    : '<tr><td colspan="4">No issue checks raised.</td></tr>';

  const assetRows = jobPack.assets.map((asset) => `
      <tr>
        <td>${escapeHtml(asset.name)}</td>
        <td>${escapeHtml(asset.type)}</td>
        <td>${escapeHtml(asset.status || 'No status')}</td>
        <td>${escapeHtml(asset.geometrySummary)}</td>
        <td>${escapeHtml(asset.workInstruction)}</td>
      </tr>`).join('');

  const sectionBlocks = jobPack.sections.map((section) => `
    <section>
      <h2>${escapeHtml(section.title)}</h2>
      <ul>${section.lines.map((line) => `<li>${escapeHtml(line)}</li>`).join('')}</ul>
    </section>`).join('');

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${escapeHtml(jobPack.jobPackNumber)}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 32px; color: #111827; }
  h1 { margin-bottom: 4px; }
  .meta { color: #4b5563; margin-bottom: 24px; }
  .grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 12px; margin: 20px 0; }
  .card { border: 1px solid #d1d5db; border-radius: 10px; padding: 12px; background: #f9fafb; }
  .label { font-size: 11px; text-transform: uppercase; color: #6b7280; letter-spacing: .06em; }
  .value { font-weight: 700; font-size: 18px; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0 28px; }
  th, td { border: 1px solid #d1d5db; padding: 8px; vertical-align: top; text-align: left; font-size: 12px; }
  th { background: #e5e7eb; }
  section { break-inside: avoid; margin-top: 24px; }
  @media print { body { margin: 16mm; } button { display: none; } }
</style>
</head>
<body>
<button onclick="window.print()">Print / Save PDF</button>
<h1>${escapeHtml(jobPack.jobPackNumber)}</h1>
<div class="meta">
  Area: ${escapeHtml(jobPack.areaName || jobPack.areaId)} · Revision: ${escapeHtml(jobPack.revisionNumber || 'Live Draft')} · Status: ${escapeHtml(jobPack.status.replace(/_/g, ' '))}<br />
  Generated: ${escapeHtml(jobPack.generatedAt)} · Generated By: ${escapeHtml(jobPack.generatedBy || 'Unknown')} · Issued: ${escapeHtml(jobPack.issuedAt || 'Not issued')}<br />
  Reason: ${escapeHtml(jobPack.reason)}
</div>
<div class="grid">
  <div class="card"><div class="label">Assets</div><div class="value">${jobPack.summary.totalAssets}</div></div>
  <div class="card"><div class="label">Poles</div><div class="value">${jobPack.summary.poles}</div></div>
  <div class="card"><div class="label">DPs</div><div class="value">${jobPack.summary.distributionPoints}</div></div>
  <div class="card"><div class="label">Cables</div><div class="value">${jobPack.summary.cables}</div></div>
  <div class="card"><div class="label">Warnings</div><div class="value">${jobPack.summary.warnings}</div></div>
  <div class="card"><div class="label">Blockers</div><div class="value">${jobPack.summary.blockers}</div></div>
</div>
<h2>Asset Register</h2>
<table>
<thead><tr><th>Name</th><th>Type</th><th>Status</th><th>Geometry</th><th>Work Instruction</th></tr></thead>
<tbody>${assetRows || '<tr><td colspan="5">No assets included.</td></tr>'}</tbody>
</table>
<h2>Issue Checks</h2>
<table>
<thead><tr><th>Level</th><th>Asset</th><th>Message</th><th>Action</th></tr></thead>
<tbody>${riskRows}</tbody>
</table>
${sectionBlocks}
</body>
</html>`;
}

export function buildJobPackDownloadBundle(jobPack: JobPackDocumentModel): JobPackDownloadBundle {
  const base = safeFileName(jobPack.jobPackNumber);
  return {
    fileName: `${base}.zip`,
    files: [
      { path: `${base}/README.md`, mimeType: 'text/markdown', content: jobPackMarkdown(jobPack) },
      { path: `${base}/Job-Pack-Map-Print.html`, mimeType: 'text/html', content: buildJobPackMapPdfHtml(jobPack) },
      { path: `${base}/Job-Pack-Register.html`, mimeType: 'text/html', content: buildJobPackHtml(jobPack) },
      { path: `${base}/registers/Asset-Register.csv`, mimeType: 'text/csv', content: assetRegisterCsv(jobPack.assets) },
      { path: `${base}/registers/Issue-Checks.csv`, mimeType: 'text/csv', content: riskRegisterCsv(jobPack.risks) },
      { path: `${base}/data/Job-Pack.json`, mimeType: 'application/json', content: JSON.stringify(jobPack, null, 2) },
    ],
  };
}

function makeCrcTable(): Uint32Array {
  const table = new Uint32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c >>> 0;
  }
  return table;
}

const crcTable = makeCrcTable();

function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i += 1) crc = crcTable[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function dosDateTime(date = new Date()): { time: number; date: number } {
  const time = (date.getHours() << 11) | (date.getMinutes() << 5) | Math.floor(date.getSeconds() / 2);
  const dosDate = ((date.getFullYear() - 1980) << 9) | ((date.getMonth() + 1) << 5) | date.getDate();
  return { time, date: dosDate };
}

function u16(value: number): Uint8Array {
  return new Uint8Array([value & 0xff, (value >>> 8) & 0xff]);
}

function u32(value: number): Uint8Array {
  return new Uint8Array([value & 0xff, (value >>> 8) & 0xff, (value >>> 16) & 0xff, (value >>> 24) & 0xff]);
}

function concatBytes(chunks: Uint8Array[]): Uint8Array {
  const length = chunks.reduce((total, chunk) => total + chunk.length, 0);
  const output = new Uint8Array(length);
  let offset = 0;
  chunks.forEach((chunk) => {
    output.set(chunk, offset);
    offset += chunk.length;
  });
  return output;
}

export function createZipBlob(files: JobPackDownloadFile[]): Blob {
  const localChunks: Uint8Array[] = [];
  const centralChunks: Uint8Array[] = [];
  let offset = 0;
  const stamp = dosDateTime();

  files.forEach((file) => {
    const fileNameBytes = textEncoder.encode(file.path);
    const contentBytes = textEncoder.encode(file.content);
    const checksum = crc32(contentBytes);
    const localHeader = concatBytes([
      u32(0x04034b50),
      u16(20),
      u16(0x0800),
      u16(0),
      u16(stamp.time),
      u16(stamp.date),
      u32(checksum),
      u32(contentBytes.length),
      u32(contentBytes.length),
      u16(fileNameBytes.length),
      u16(0),
      fileNameBytes,
    ]);

    localChunks.push(localHeader, contentBytes);

    const centralHeader = concatBytes([
      u32(0x02014b50),
      u16(20),
      u16(20),
      u16(0x0800),
      u16(0),
      u16(stamp.time),
      u16(stamp.date),
      u32(checksum),
      u32(contentBytes.length),
      u32(contentBytes.length),
      u16(fileNameBytes.length),
      u16(0),
      u16(0),
      u16(0),
      u16(0),
      u32(0),
      u32(offset),
      fileNameBytes,
    ]);
    centralChunks.push(centralHeader);
    offset += localHeader.length + contentBytes.length;
  });

  const centralDirectory = concatBytes(centralChunks);
  const endRecord = concatBytes([
    u32(0x06054b50),
    u16(0),
    u16(0),
    u16(files.length),
    u16(files.length),
    u32(centralDirectory.length),
    u32(offset),
    u16(0),
  ]);

  return new Blob([concatBytes([...localChunks, centralDirectory, endRecord])], { type: 'application/zip' });
}

function triggerDownload(blob: Blob, fileName: string): void {
  if (typeof document === 'undefined') return;
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = fileName;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.setTimeout(() => URL.revokeObjectURL(url), 500);
}

export function downloadJobPackZip(jobPack: JobPackDocumentModel): void {
  const bundle = buildJobPackDownloadBundle(jobPack);
  triggerDownload(createZipBlob(bundle.files), bundle.fileName);
}

export function downloadJobPackHtml(jobPack: JobPackDocumentModel): void {
  const base = safeFileName(jobPack.jobPackNumber);
  triggerDownload(new Blob([buildJobPackMapPdfHtml(jobPack)], { type: 'text/html' }), `${base}-MAP-PDF.html`);
}

export function downloadJobPackJson(jobPack: JobPackDocumentModel): void {
  const base = safeFileName(jobPack.jobPackNumber);
  triggerDownload(new Blob([JSON.stringify(jobPack, null, 2)], { type: 'application/json' }), `${base}.json`);
}
