import React, { useEffect, useMemo, useState } from "react";
import L from "leaflet";
import {
  CircleMarker,
  Marker,
  Polyline,
  Popup,
  Tooltip,
  useMap,
  useMapEvents,
} from "react-leaflet";
import type { SavedMapAsset } from "../JointMapManager";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../../firebase";
import { getCableUsedFibres } from "./cableUsage";
type Props = {
  assets: SavedMapAsset[];
  cablesVisible: boolean;
  visibleLayers?: Record<string, boolean>;
  showCableDistances?: boolean;
  onDeleteAsset: (id: string) => void;
  onEditAsset: (asset: SavedMapAsset) => void;
};

type MappingRowsByAssetId = Record<string, any[][]>;

type MappingChunkDoc = {
  rowsJson?: string;
  rows?: any[];
  chunkIndex?: number;
};

function safeJsonParse(value: unknown, fallback: any) {
  if (typeof value !== "string") return fallback;
  try {
    return JSON.parse(value);
  } catch {
    return fallback;
  }
}

async function loadJointMappingRowsFromFirestore(jointId: string): Promise<any[][]> {
  const chunksRef = collection(
    db,
    "businesses",
    "fibre-gis-v2",
    "jointMappings",
    jointId,
    "chunks"
  );

  const snapshot = await getDocs(chunksRef);

  return snapshot.docs
    .map((chunkDoc) => {
      const data = chunkDoc.data() as MappingChunkDoc;

      let rows: any[] = [];

      // Current shared format: JSON string, avoids Firestore nested-array errors.
      if (typeof data.rowsJson === "string") {
        rows = safeJsonParse(data.rowsJson, []);
      }

      // Backwards compatibility with earlier test formats.
      if (!rows.length && Array.isArray(data.rows)) {
        rows = data.rows.map((row: any) =>
          Array.isArray(row) ? row : Array.isArray(row?.values) ? row.values : row
        );
      }

      return {
        id: chunkDoc.id,
        index:
          typeof data.chunkIndex === "number"
            ? data.chunkIndex
            : Number(chunkDoc.id.replace("chunk_", "")),
        rows: Array.isArray(rows) ? rows : [],
      };
    })
    .sort((a, b) => a.index - b.index || a.id.localeCompare(b.id))
    .flatMap((chunk) => chunk.rows)
    .filter((row) => Array.isArray(row));
}


function getCableLengthMeters(points: [number, number][]): number {
  if (points.length < 2) return 0;

  let total = 0;

  for (let i = 1; i < points.length; i++) {
    const [lat1, lng1] = points[i - 1];
    const [lat2, lng2] = points[i];

    const toRad = (v: number) => (v * Math.PI) / 180;
    const R = 6371000;

    const dLat = toRad(lat2 - lat1);
    const dLng = toRad(lng2 - lng1);

    const a =
      Math.sin(dLat / 2) ** 2 +
      Math.cos(toRad(lat1)) *
        Math.cos(toRad(lat2)) *
        Math.sin(dLng / 2) ** 2;

    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    total += R * c;
  }

  return total;
}

function formatCableLength(length: number): string {
  if (length < 1000) return `${length.toFixed(1)} m`;
  return `${(length / 1000).toFixed(3)} km`;
}


function isDropCableAsset(asset: SavedMapAsset): boolean {
  const cableType = String((asset as any).cableType || "").toLowerCase();
  const assetType = String((asset as any).assetType || "").toLowerCase();
  const name = String((asset as any).name || "").toLowerCase();

  return (
    assetType === "drop-cable" ||
    cableType.includes("drop") ||
    name.includes("drop") ||
    String((asset as any).isDropCable || "").toLowerCase() === "true" ||
    String((asset as any).autoGeneratedDrop || "").toLowerCase() === "true" ||
    Boolean((asset as any).homeId || (asset as any).connectedHomeId || (asset as any).toHomeId || (asset as any).fromHomeId)
  );
}

function getCableColor(asset: SavedMapAsset): string {
  if (asset.cableType === "ULW Cable") return "#22c55e";
  if (asset.cableType === "Link Cable") return "#3b82f6";
  if (isDropCableAsset(asset)) return "#a855f7";
  return "#f59e0b";
}

/* =========================================================
   CABLE STYLE HELPERS
   Keeps install method visuals consistent across normal map render.
   OH / Overhead cables are dashed. UG cables stay solid.
========================================================= */
function getDashArray(asset: SavedMapAsset): string | undefined {
  const method = String(asset.installMethod || "").toLowerCase();
  return method === "oh" || method === "overhead" ? "10, 8" : undefined;
}
/* ======================= END CABLE STYLE HELPERS ======================= */

function getMidpoint(a: [number, number], b: [number, number]): [number, number] {
  return [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2];
}

const ROUTE_EDIT_HANDLE_MIN_SPACING_METERS = 60;
const ROUTE_EDIT_MAX_HANDLES = 28;
const ROUTE_EDIT_MIN_INSERT_SPAN_METERS = 20;
const ROUTE_COORDINATE_DEDUPE_METERS = 0.35;

function getDistanceMeters(a: [number, number], b: [number, number]): number {
  return getCableLengthMeters([a, b]);
}

function sanitizeCableCoordinates(coordinates: [number, number][]): [number, number][] {
  if (!Array.isArray(coordinates)) return [];

  const cleaned: [number, number][] = [];

  coordinates.forEach((coord) => {
    if (!Array.isArray(coord) || coord.length < 2) return;

    const lat = Number(coord[0]);
    const lng = Number(coord[1]);

    if (!Number.isFinite(lat) || !Number.isFinite(lng)) return;

    const next: [number, number] = [lat, lng];
    const previous = cleaned[cleaned.length - 1];

    // Route edit must not multiply identical / near-identical vertices.
    if (previous && getDistanceMeters(previous, next) <= ROUTE_COORDINATE_DEDUPE_METERS) {
      return;
    }

    cleaned.push(next);
  });

  return cleaned;
}

function getRouteEditHandleIndexes(points: [number, number][]): number[] {
  if (points.length <= 2) return points.map((_, index) => index);

  const indexes = new Set<number>([0, points.length - 1]);
  let distanceSinceLastHandle = 0;

  for (let i = 1; i < points.length - 1; i++) {
    distanceSinceLastHandle += getDistanceMeters(points[i - 1], points[i]);

    if (distanceSinceLastHandle >= ROUTE_EDIT_HANDLE_MIN_SPACING_METERS) {
      indexes.add(i);
      distanceSinceLastHandle = 0;
    }
  }

  const sorted = Array.from(indexes).sort((a, b) => a - b);

  if (sorted.length <= ROUTE_EDIT_MAX_HANDLES) return sorted;

  const sampled = new Set<number>([0, points.length - 1]);
  const step = Math.ceil((sorted.length - 2) / Math.max(1, ROUTE_EDIT_MAX_HANDLES - 2));

  sorted.slice(1, -1).forEach((index, sampleIndex) => {
    if (sampleIndex % step === 0) sampled.add(index);
  });

  return Array.from(sampled).sort((a, b) => a - b);
}

function shouldShowMidpointInsertHandle(
  points: [number, number][],
  segmentIndex: number,
  visibleHandleIndexes: Set<number>
): boolean {
  const start = points[segmentIndex];
  const end = points[segmentIndex + 1];

  if (!start || !end) return false;
  if (getDistanceMeters(start, end) < ROUTE_EDIT_MIN_INSERT_SPAN_METERS) return false;

  return visibleHandleIndexes.has(segmentIndex) || visibleHandleIndexes.has(segmentIndex + 1);
}

function getCableSpanAngleDegrees(a: [number, number], b: [number, number]): number {
  const midLat = ((a[0] + b[0]) / 2) * (Math.PI / 180);
  const dx = (b[1] - a[1]) * Math.cos(midLat);
  const dy = b[0] - a[0];

  return (Math.atan2(dy, dx) * 180) / Math.PI;
}

function getOffsetCableLabelPosition(
  a: [number, number],
  b: [number, number],
  offsetMeters = 7
): [number, number] {
  const midpoint = getMidpoint(a, b);
  const midLatRad = midpoint[0] * (Math.PI / 180);

  const eastMeters = (b[1] - a[1]) * 111320 * Math.cos(midLatRad);
  const northMeters = (b[0] - a[0]) * 111320;
  const lengthMeters = Math.sqrt(eastMeters ** 2 + northMeters ** 2);

  if (!lengthMeters) return midpoint;

  const offsetEastMeters = (-northMeters / lengthMeters) * offsetMeters;
  const offsetNorthMeters = (eastMeters / lengthMeters) * offsetMeters;

  return [
    midpoint[0] + offsetNorthMeters / 111320,
    midpoint[1] + offsetEastMeters / (111320 * Math.cos(midLatRad)),
  ];
}

function getCableDistanceLabelIcon(label: string, angleDegrees: number) {
  return L.divIcon({
    className: "",
    html: `
      <div style="
        pointer-events: none;
        background: transparent;
        border: none;
        padding: 0;
        font-size: 11px;
        font-weight: 800;
        line-height: 1;
        color: rgba(147, 51, 234, 0.72);
        white-space: nowrap;
        text-shadow:
          0 1px 2px rgba(255,255,255,0.9),
          0 -1px 2px rgba(255,255,255,0.9),
          1px 0 2px rgba(255,255,255,0.9),
          -1px 0 2px rgba(255,255,255,0.9);
        transform: translate(-50%, -50%) rotate(${angleDegrees}deg);
        transform-origin: center;
      ">${label}</div>
    `,
    iconSize: [0, 0],
    iconAnchor: [0, 0],
  });
}

function getAssetPoint(asset: SavedMapAsset): [number, number] | null {
  if (asset.geometry?.type !== "Point") return null;

  const [lat, lng] = asset.geometry.coordinates;
  if (typeof lat !== "number" || typeof lng !== "number") return null;

  return [lat, lng];
}

function findConnectedAssetAtCableEnd(
  assets: SavedMapAsset[],
  point: [number, number]
): SavedMapAsset | null {
  const candidates = assets
    .filter((asset) => {
      if (asset.assetType === "area") return false;
      if (asset.assetType === "cable") return false;

      const assetPoint = getAssetPoint(asset);
      if (!assetPoint) return false;

      return getDistanceMeters(assetPoint, point) <= 10;
    })
    .sort((a, b) => {
      const pointA = getAssetPoint(a);
      const pointB = getAssetPoint(b);
      if (!pointA || !pointB) return 0;

      return getDistanceMeters(pointA, point) - getDistanceMeters(pointB, point);
    });

  return candidates[0] || null;
}

function normaliseCableRef(value: unknown): string {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/[–—]/g, "-");
}

function getNumberFromFibreCount(value: unknown): number {
  const match = String(value || "").match(/\d+/);
  return match ? Number(match[0]) : 0;
}

function getRowText(row: any[]): string {
  return row.map((cell) => String(cell || "").trim()).join(" ");
}

function getCableAliases(cable: SavedMapAsset): string[] {
  const values = [cable.name, cable.id, (cable as any).label, (cable as any).cableId]
    .map(normaliseCableRef)
    .filter(Boolean);

  const aliases = new Set<string>();

  values.forEach((value) => {
    aliases.add(value);

    const parts = value.split("-").filter(Boolean);
    const last = parts[parts.length - 1];
    if (last) aliases.add(last);

    const lcMatch = value.match(/lc\d{1,4}/i);
    if (lcMatch) aliases.add(normaliseCableRef(lcMatch[0]));
  });

  return Array.from(aliases).filter((alias) => alias.length >= 3);
}

function rowMentionsCable(row: any[], cable: SavedMapAsset): boolean {
  const aliases = getCableAliases(cable);
  if (!aliases.length) return false;

  const rowText = normaliseCableRef(getRowText(row));

  return aliases.some((alias) => rowText.includes(alias));
}

function getAssetAliases(asset?: SavedMapAsset | null): string[] {
  if (!asset) return [];

  const rawValues = [asset.name, asset.id, (asset as any).label, (asset as any).nodeId]
    .map((value) => String(value || '').trim())
    .filter(Boolean);

  const aliases = new Set<string>();

  rawValues.forEach((raw) => {
    const value = normaliseCableRef(raw);
    if (!value) return;

    aliases.add(value);

    // BD-BAW-AG11-CMJ01 should also match BD-BAW-AG11.
    const withoutJointSuffix = value.replace(/-(cmj|mmj|lmj)\d{1,4}$/i, '');
    if (withoutJointSuffix && withoutJointSuffix !== value) {
      aliases.add(withoutJointSuffix);
    }

    // Add compact node tokens such as AG11, LMJ01, LC011, SB35.
    const nodeMatches = value.match(/(?:ag|lmj|mmj|cmj|lc|sb|midj|sc)\d{1,4}/gi);
    nodeMatches?.forEach((match) => aliases.add(normaliseCableRef(match)));
  });

  return Array.from(aliases).filter((alias) => alias.length >= 3);
}

function rowMentionsAsset(row: any[], asset?: SavedMapAsset | null): boolean {
  const aliases = getAssetAliases(asset);
  if (!aliases.length) return false;

  const rowText = normaliseCableRef(getRowText(row));
  return aliases.some((alias) => rowText.includes(alias));
}

function countRowsMatching(
  allAssets: SavedMapAsset[],
  mappingRowsByAssetId: MappingRowsByAssetId,
  predicate: (row: any[], sourceAsset: SavedMapAsset, rowIndex: number) => boolean
): number {
  const keys = new Set<string>();

  allAssets.forEach((asset) => {
    const localRows = Array.isArray(asset.mappingRows) ? asset.mappingRows : [];
    const sharedRows = mappingRowsByAssetId[asset.id] || [];
    const rows = sharedRows.length ? sharedRows : localRows;

    rows.forEach((row: any[], rowIndex: number) => {
      if (!Array.isArray(row)) return;
      if (!predicate(row, asset, rowIndex)) return;

      const rowText = getRowText(row).trim();
      if (!rowText) return;

      keys.add(`${asset.id}:${rowIndex}:${normaliseCableRef(rowText)}`);
    });
  });

  return keys.size;
}

function clampToCableCapacity(cable: SavedMapAsset, value: number): number {
  const capacity = getNumberFromFibreCount(cable.fibreCount);
  if (!capacity) return value;
  return Math.min(value, capacity);
}


export default function CableLinesLayer({
  assets,
  cablesVisible,
  visibleLayers = {},
  showCableDistances,
  onDeleteAsset,
  onEditAsset,
}: Props) {
  const map = useMap();
  const [selectedCableId, setSelectedCableId] = useState<string | null>(null);
  const [editingCableId, setEditingCableId] = useState<string | null>(null);
  const [hoveredCableId, setHoveredCableId] = useState<string | null>(null);
  const [mappingRowsByAssetId, setMappingRowsByAssetId] = useState<MappingRowsByAssetId>({});

  const mappingAssetKey = useMemo(
    () =>
      assets
        .filter((asset) => Boolean((asset as any).mappingRowsRef || (asset as any).mappingRowsCount))
        .map((asset) => `${asset.id}:${(asset as any).mappingRowsCount || 0}:${(asset as any).updatedAt || ""}`)
        .sort()
        .join("|"),
    [assets]
  );

  useEffect(() => {
    let cancelled = false;

    const assetsWithSharedMappings = assets.filter((asset) =>
      Boolean((asset as any).mappingRowsRef || (asset as any).mappingRowsCount)
    );

    if (!assetsWithSharedMappings.length) {
      setMappingRowsByAssetId({});
      return;
    }

    Promise.all(
      assetsWithSharedMappings.map(async (asset) => {
        try {
          const rows = await loadJointMappingRowsFromFirestore(asset.id);
          return [asset.id, rows] as const;
        } catch (err) {
          console.error(`Failed to load mapping rows for ${asset.name || asset.id}`, err);
          return [asset.id, []] as const;
        }
      })
    ).then((entries) => {
      if (cancelled) return;
      setMappingRowsByAssetId(Object.fromEntries(entries));
    });

    return () => {
      cancelled = true;
    };
  }, [mappingAssetKey]);

  useMapEvents({
    click: () => {
      setSelectedCableId(null);
    },
  });

  if (!cablesVisible) return null;

  const isLayerOn = (key: string) => visibleLayers[key] !== false;

  const cableAssets = assets.filter((asset) => {
    if (
      asset.assetType !== "cable" ||
      asset.geometry?.type !== "LineString" ||
      !Array.isArray(asset.geometry.coordinates)
    ) {
      return false;
    }

    const cableType = String(asset.cableType || "").toLowerCase();
    const fibreCount = String(asset.fibreCount || "").toLowerCase();
    const isDropCable = isDropCableAsset(asset);

    if (isDropCable && !isLayerOn("dropCables")) return false;
    if (isDropCable) return true;

    if (cableType.includes("feeder") && !isLayerOn("feeders")) return false;
    if (cableType.includes("link") && !isLayerOn("links")) return false;

    if (cableType.includes("ulw")) {
      if (fibreCount.includes("48") && !isLayerOn("ulw48")) return false;
      if (fibreCount.includes("36") && !isLayerOn("ulw36")) return false;
      if (fibreCount.includes("24") && !isLayerOn("ulw24")) return false;
      if (fibreCount.includes("12") && !isLayerOn("ulw12")) return false;
    }

    return true;
  });

  const zoomToCable = (points: [number, number][]) => {
    if (points.length < 2) return;

    const bounds = L.latLngBounds(points);
    map.fitBounds(bounds, {
      padding: [80, 80],
      maxZoom: 19,
    });
  };

  const updateCableCoordinates = (
    asset: SavedMapAsset,
    coordinates: [number, number][]
  ) => {
    const cleanedCoordinates = sanitizeCableCoordinates(coordinates);

    onEditAsset({
      ...asset,
      geometry: {
        ...asset.geometry,
        type: "LineString",
        coordinates: cleanedCoordinates,
      },
    });
  };

  const handleMovePoint = (
    asset: SavedMapAsset,
    index: number,
    lat: number,
    lng: number
  ) => {
    if (asset.geometry?.type !== "LineString") return;

    const updated = [...asset.geometry.coordinates];
    updated[index] = [lat, lng];

    // Dragging a route handle must move one existing vertex only.
    // It must never append or duplicate geometry points.
    updateCableCoordinates(asset, updated);
  };

  const handleInsertMidpoint = (asset: SavedMapAsset, i: number) => {
    if (asset.geometry?.type !== "LineString") return;

    const coords = asset.geometry.coordinates;
    const start = coords[i];
    const end = coords[i + 1];

    if (!start || !end) return;

    if (getDistanceMeters(start, end) < ROUTE_EDIT_MIN_INSERT_SPAN_METERS) return;

    const updated = [...coords];
    updated.splice(i + 1, 0, getMidpoint(start, end));

    updateCableCoordinates(asset, updated);
  };

  return (
    <>
      {cableAssets.map((asset) => {
        const points =
          asset.geometry?.type === "LineString"
            ? asset.geometry.coordinates
            : [];

        const length = getCableLengthMeters(points);
        const isHovered = hoveredCableId === asset.id;
        const isSelected = selectedCableId === asset.id;
        const isEditing = editingCableId === asset.id;
        const baseColor = getCableColor(asset);
        const cableColor = isSelected ? "#f59e0b" : baseColor;
        const routeEditHandleIndexes = isEditing ? getRouteEditHandleIndexes(points) : [];
        const routeEditHandleIndexSet = new Set(routeEditHandleIndexes);

        const startAsset =
          points.length >= 2
            ? findConnectedAssetAtCableEnd(assets, points[0])
            : null;

        const endAsset =
          points.length >= 2
            ? findConnectedAssetAtCableEnd(assets, points[points.length - 1])
            : null;

        

        const usedFibres = clampToCableCapacity(
  asset,
  getCableUsedFibres(asset, assets)
);

        return (
          <React.Fragment key={asset.id}>
            <Polyline
              positions={points}
              pathOptions={{
                color: cableColor,
                weight: isSelected ? 9 : isHovered || isEditing ? 7 : 4,
                opacity: isSelected || isHovered || isEditing ? 1 : 0.85,
                dashArray: getDashArray(asset),
                className: isSelected ? "selected-cable-glow" : "",
              }}
              eventHandlers={{
                click: (e) => {
                  L.DomEvent.stopPropagation(e);
                  setSelectedCableId(asset.id);
                  zoomToCable(points);
                },
                mouseover: () => setHoveredCableId(asset.id),
                mouseout: () => setHoveredCableId(null),
              }}
            >
              <Popup>
                <div style={{ minWidth: 240 }}>
                  <div style={{ fontWeight: 700, fontSize: "1rem" }}>
                    {asset.name || "Unnamed Cable"}
                  </div>

                  <div style={{ marginTop: 6 }}>
                    <b>Size:</b> {asset.fibreCount || "N/A"}
                  </div>

                  <div>
                    <b>Type:</b> {asset.cableType || "Cable"}
                  </div>

                  <div>
                    <b>Install:</b> {asset.installMethod || "Underground"}
                  </div>

                  <div>
                    <b>Length:</b> {formatCableLength(length)}
                  </div>

                  <div>
                    <b>Used fibres:</b> {usedFibres} /{" "}
                    {asset.fibreCount || "N/A"}
                  </div>

                  <div>
                    <b>From:</b> {startAsset?.name || "Not connected"}
                  </div>

                  <div>
                    <b>To:</b> {endAsset?.name || "Not connected"}
                  </div>

                  {asset.notes ? (
                    <div style={{ marginTop: 8 }}>{asset.notes}</div>
                  ) : null}

                  <div
                    style={{
                      marginTop: 10,
                      display: "flex",
                      gap: 8,
                      flexWrap: "wrap",
                    }}
                  >
                    <button onClick={() => onEditAsset(asset)}>
                      Edit details
                    </button>

                    <button
                      onClick={() => {
                        setSelectedCableId(asset.id);
                        setEditingCableId(asset.id);
                      }}
                    >
                      Edit route
                    </button>

                    <button onClick={() => setEditingCableId(null)}>
                      Done
                    </button>

                    <button onClick={() => onDeleteAsset(asset.id)}>
                      Delete
                    </button>
                  </div>
                </div>
              </Popup>

              <Tooltip sticky>
                {asset.name || "Cable"} · {asset.fibreCount || "N/A"} ·{" "}
                {formatCableLength(length)}
              </Tooltip>
            </Polyline>

            {showCableDistances === true &&
              points.slice(0, -1).map((coord, i) => {
                const next = points[i + 1];
                if (!next) return null;

                const spanLength = getDistanceMeters(coord, next);

                return (
                  <Marker
                    key={`${asset.id}-distance-${i}`}
                    position={getOffsetCableLabelPosition(coord, next)}
                    interactive={false}
                    icon={getCableDistanceLabelIcon(
                      formatCableLength(spanLength),
                      getCableSpanAngleDegrees(coord, next)
                    )}
                  />
                );
              })}

            {isEditing &&
              routeEditHandleIndexes.map((i) => {
                const coord = points[i];
                if (!coord) return null;

                return (
                  <Marker
                    key={`${asset.id}-drag-${i}`}
                    position={coord}
                    draggable
                    eventHandlers={{
                      dragend: (e) => {
                        const p = e.target.getLatLng();
                        handleMovePoint(asset, i, p.lat, p.lng);
                      },
                    }}
                  />
                );
              })}

            {isEditing &&
              points.slice(0, -1).map((coord, i) => {
                if (!shouldShowMidpointInsertHandle(points, i, routeEditHandleIndexSet)) return null;

                const next = points[i + 1];
                if (!next) return null;

                return (
                  <CircleMarker
                    key={`${asset.id}-mid-${i}`}
                    center={getMidpoint(coord, next)}
                    radius={5}
                    pathOptions={{
                      color: getCableColor(asset),
                      weight: 2,
                      fillOpacity: 0.85,
                    }}
                    eventHandlers={{
                      click: () => handleInsertMidpoint(asset, i),
                    }}
                  />
                );
              })}
          </React.Fragment>
        );
      })}
    </>
  );
}