import { getTupleDistanceMeters as getDistanceMeters, getTuplePathDistanceMeters } from "../../utils/mapMeasure";
import React, { useEffect, useMemo, useState } from "react";
import L from "leaflet";
import {
  CircleMarker,
  Marker,
  Polyline,
  Popup,
  Tooltip,
  useMap,
  useMapEvents,
} from "react-leaflet";
import type { SavedMapAsset } from "../JointMapManager";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../../firebase";
import { getCableUsedFibres } from "./cableUsage";
import { buildNetworkState } from "../../services/network";
import { isOpenreachReferenceAsset } from "../../services/orAssetStorage";
import { getPaddedRenderBounds, isLineStringInsideRenderBounds } from "./utils/renderBounds";
type Props = {
  assets: SavedMapAsset[];
  cablesVisible: boolean;
  visibleLayers?: Record<string, boolean>;
  showCableDistances?: boolean;
  onDeleteAsset: (id: string) => void;
  onEditAsset: (asset: SavedMapAsset) => void;
};

type MappingRowsByAssetId = Record<string, any[][]>;

type MappingChunkDoc = {
  rowsJson?: string;
  rows?: any[];
  chunkIndex?: number;
};

function safeJsonParse(value: unknown, fallback: any) {
  if (typeof value !== "string") return fallback;
  try {
    return JSON.parse(value);
  } catch {
    return fallback;
  }
}

async function loadJointMappingRowsFromFirestore(jointId: string): Promise<any[][]> {
  const chunksRef = collection(
    db,
    "businesses",
    "fibre-gis-v2",
    "jointMappings",
    jointId,
    "chunks"
  );

  const snapshot = await getDocs(chunksRef);

  return snapshot.docs
    .map((chunkDoc) => {
      const data = chunkDoc.data() as MappingChunkDoc;

      let rows: any[] = [];

      // Current shared format: JSON string, avoids Firestore nested-array errors.
      if (typeof data.rowsJson === "string") {
        rows = safeJsonParse(data.rowsJson, []);
      }

      // Backwards compatibility with earlier test formats.
      if (!rows.length && Array.isArray(data.rows)) {
        rows = data.rows.map((row: any) =>
          Array.isArray(row) ? row : Array.isArray(row?.values) ? row.values : row
        );
      }

      return {
        id: chunkDoc.id,
        index:
          typeof data.chunkIndex === "number"
            ? data.chunkIndex
            : Number(chunkDoc.id.replace("chunk_", "")),
        rows: Array.isArray(rows) ? rows : [],
      };
    })
    .sort((a, b) => a.index - b.index || a.id.localeCompare(b.id))
    .flatMap((chunk) => chunk.rows)
    .filter((row) => Array.isArray(row));
}


function formatCableLength(length: number): string {
  if (length < 1000) return `${length.toFixed(1)} m`;
  return `${(length / 1000).toFixed(3)} km`;
}


function isDropCableAsset(asset: SavedMapAsset): boolean {
  const cableType = String((asset as any).cableType || "").toLowerCase();
  const assetType = String((asset as any).assetType || "").toLowerCase();
  const name = String((asset as any).name || "").toLowerCase();

  return (
    assetType === "drop-cable" ||
    cableType.includes("drop") ||
    name.includes("drop") ||
    String((asset as any).isDropCable || "").toLowerCase() === "true" ||
    String((asset as any).autoGeneratedDrop || "").toLowerCase() === "true" ||
    Boolean((asset as any).homeId || (asset as any).connectedHomeId || (asset as any).toHomeId || (asset as any).fromHomeId)
  );
}

function getCableFibreCount(asset: SavedMapAsset): number | null {
  const item = asset as any;

  const candidates = [
    item.fibreCount,
    item.fiberCount,
    item.size,
    item.cableSize,
    item.name,
    item.cableId,
    item.label,
  ];

  for (const candidate of candidates) {
    const text = String(candidate ?? "").toUpperCase();
    const match = text.match(/(288|144|96|48|36|24|12)\s*F?/);
    if (match) return Number(match[1]);
  }

  return null;
}


function getCableCapacityWarning(asset: SavedMapAsset, usedFibres: number | null): string {
  const fibreCount = getCableFibreCount(asset);
  if (!fibreCount || usedFibres === null) return "";
  if (usedFibres > fibreCount) return `Over capacity: ${usedFibres}/${fibreCount}F`;
  if (usedFibres === fibreCount) return `Full: ${usedFibres}/${fibreCount}F`;
  if ((usedFibres / fibreCount) >= 0.8) return `Near capacity: ${usedFibres}/${fibreCount}F`;
  return `Fibres: ${usedFibres}/${fibreCount}F`;
}

function getDropCableDistanceColour(lengthMeters: number): string {
  // Blue = shortest tails, red = top end of acceptable drop length.
  // 68m is the existing design target used elsewhere in the app.
  const maxDropMeters = 68;
  const ratio = Math.max(0, Math.min(1, lengthMeters / maxDropMeters));

  if (ratio < 0.5) {
    const local = ratio / 0.5;
    const r = Math.round(37 + (34 - 37) * local);
    const g = Math.round(99 + (197 - 99) * local);
    const b = Math.round(235 + (94 - 235) * local);
    return `rgb(${r}, ${g}, ${b})`;
  }

  const local = (ratio - 0.5) / 0.5;
  const r = Math.round(34 + (239 - 34) * local);
  const g = Math.round(197 + (68 - 197) * local);
  const b = Math.round(94 + (68 - 94) * local);
  return `rgb(${r}, ${g}, ${b})`;
}

function getCableColor(asset: SavedMapAsset, lengthMeters = 0): string {
  if (isDropCableAsset(asset)) return getDropCableDistanceColour(lengthMeters);

  const fibreCount = getCableFibreCount(asset);
  if (fibreCount === 96) return "#2563eb"; // blue
  if (fibreCount === 48) return "#01fff2"; // red
  if (fibreCount === 12) return "#ff9500"; // green

  if (asset.cableType === "ULW Cable") return "#22c55e";
  if (asset.cableType === "Link Cable") return "#3b82f6";
  return "#f59e0b";
}

/* =========================================================
   CABLE STYLE HELPERS
   Visual rule requested:
   - Drop cables = dashed, like OH tails
   - OH / Overhead spans to DPs = dashed
   - UG / Underground cables = solid
========================================================= */
function normaliseCableText(value: unknown): string {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[\s_/-]+/g, " ");
}

function isUndergroundInstall(asset: SavedMapAsset): boolean {
  const install = normaliseCableText((asset as any).installMethod);
  const cableType = normaliseCableText((asset as any).cableType);
  const name = normaliseCableText((asset as any).name);

  return (
    install === "ug" ||
    install.includes("underground") ||
    install.includes("duct") ||
    cableType.includes("duct") ||
    name.includes(" ug ") ||
    name.startsWith("ug ") ||
    name.endsWith(" ug")
  );
}

function isOverheadInstall(asset: SavedMapAsset): boolean {
  const install = normaliseCableText((asset as any).installMethod);
  const cableType = normaliseCableText((asset as any).cableType);
  const name = normaliseCableText((asset as any).name);

  return (
    install === "oh" ||
    install.includes("overhead") ||
    install.includes("aerial") ||
    install.includes("span") ||
    cableType.includes("overhead") ||
    cableType.includes("span") ||
    name.includes(" oh ") ||
    name.startsWith("oh ") ||
    name.endsWith(" oh") ||
    name.includes("span")
  );
}

function isDistributionPointAsset(asset?: SavedMapAsset | null): boolean {
  if (!asset) return false;

  const assetType = normaliseCableText((asset as any).assetType);
  const type = normaliseCableText((asset as any).type);
  const name = normaliseCableText((asset as any).name);

  return (
    assetType === "distribution point" ||
    assetType === "distribution point afn" ||
    assetType === "dp" ||
    assetType.includes("distribution") ||
    assetType.includes("afn") ||
    assetType.includes("cbt") ||
    type.includes("distribution") ||
    type.includes("afn") ||
    type.includes("cbt") ||
    name.includes("dp") ||
    name.includes("afn") ||
    name.includes("cbt")
  );
}

function getDashArray(
  asset: SavedMapAsset,
  startAsset?: SavedMapAsset | null,
  endAsset?: SavedMapAsset | null
): string | undefined {
  // UG always stays solid, even if another field has confusing wording.
  if (isUndergroundInstall(asset)) return undefined;

  // All drops are dashed because they are house tails / OH-style tails on the map.
  if (isDropCableAsset(asset)) return "6, 7";

  // OH spans are dashed. If the span touches a DP/CBT/AFN, make sure it follows the DP visual rule.
  if (isOverheadInstall(asset)) return isDistributionPointAsset(startAsset) || isDistributionPointAsset(endAsset) ? "10, 8" : "10, 8";

  return undefined;
}
/* ======================= END CABLE STYLE HELPERS ======================= */

function getMidpoint(a: [number, number], b: [number, number]): [number, number] {
  return [(a[0] + b[0]) / 2, (a[1] + b[1]) / 2];
}

const ROUTE_EDIT_MIN_INSERT_SPAN_METERS = 20;
const ROUTE_COORDINATE_DEDUPE_METERS = 0.35;

function sanitizeCableCoordinates(coordinates: [number, number][]): [number, number][] {
  if (!Array.isArray(coordinates)) return [];

  const cleaned: [number, number][] = [];

  coordinates.forEach((coord) => {
    if (!Array.isArray(coord) || coord.length < 2) return;

    const lat = Number(coord[0]);
    const lng = Number(coord[1]);

    if (!Number.isFinite(lat) || !Number.isFinite(lng)) return;

    const next: [number, number] = [lat, lng];
    const previous = cleaned[cleaned.length - 1];

    // Route edit must not multiply identical / near-identical vertices.
    if (previous && getDistanceMeters(previous, next) <= ROUTE_COORDINATE_DEDUPE_METERS) {
      return;
    }

    cleaned.push(next);
  });

  return cleaned;
}

function getRouteEditHandleIndexes(points: [number, number][]): number[] {
  // Keep route editing simple and readable:
  // only show Start, Middle, End handles.
  // Extra vertices stay in the saved geometry but do not create marker clutter.
  if (points.length <= 3) return points.map((_, index) => index);

  const totalLength = getTuplePathDistanceMeters(points);
  const targetMiddleDistance = totalLength / 2;

  let walked = 0;
  let middleIndex = 1;

  for (let i = 1; i < points.length; i += 1) {
    const spanLength = getDistanceMeters(points[i - 1], points[i]);
    walked += spanLength;

    if (walked >= targetMiddleDistance) {
      middleIndex = i;
      break;
    }
  }

  middleIndex = Math.max(1, Math.min(points.length - 2, middleIndex));

  return Array.from(new Set([0, middleIndex, points.length - 1])).sort(
    (a, b) => a - b,
  );
}

function getRouteEditInsertSegmentIndexes(
  points: [number, number][],
  visibleHandleIndexes: number[]
): number[] {
  // Show one add-point control between Start -> Middle and one between
  // Middle -> End. This keeps the edit UI clean while still letting the
  // engineer add extra shaping points when needed.
  if (points.length < 2 || visibleHandleIndexes.length < 2) return [];

  const insertSegments = new Set<number>();
  const sortedHandles = [...visibleHandleIndexes].sort((a, b) => a - b);

  for (let pairIndex = 0; pairIndex < sortedHandles.length - 1; pairIndex += 1) {
    const startIndex = sortedHandles[pairIndex];
    const endIndex = sortedHandles[pairIndex + 1];

    if (endIndex <= startIndex) continue;

    let sectionLength = 0;
    for (let i = startIndex; i < endIndex; i += 1) {
      sectionLength += getDistanceMeters(points[i], points[i + 1]);
    }

    if (sectionLength < ROUTE_EDIT_MIN_INSERT_SPAN_METERS) continue;

    const targetDistance = sectionLength / 2;
    let walked = 0;

    for (let i = startIndex; i < endIndex; i += 1) {
      const spanLength = getDistanceMeters(points[i], points[i + 1]);
      walked += spanLength;

      if (walked >= targetDistance) {
        insertSegments.add(i);
        break;
      }
    }
  }

  return Array.from(insertSegments).sort((a, b) => a - b);
}

function getCableSpanAngleDegrees(a: [number, number], b: [number, number]): number {
  const midLat = ((a[0] + b[0]) / 2) * (Math.PI / 180);
  const dx = (b[1] - a[1]) * Math.cos(midLat);
  const dy = b[0] - a[0];

  return (Math.atan2(dy, dx) * 180) / Math.PI;
}

function getOffsetCableLabelPosition(
  a: [number, number],
  b: [number, number],
  offsetMeters = 7
): [number, number] {
  const midpoint = getMidpoint(a, b);
  const midLatRad = midpoint[0] * (Math.PI / 180);

  const eastMeters = (b[1] - a[1]) * 111320 * Math.cos(midLatRad);
  const northMeters = (b[0] - a[0]) * 111320;
  const lengthMeters = Math.sqrt(eastMeters ** 2 + northMeters ** 2);

  if (!lengthMeters) return midpoint;

  const offsetEastMeters = (-northMeters / lengthMeters) * offsetMeters;
  const offsetNorthMeters = (eastMeters / lengthMeters) * offsetMeters;

  return [
    midpoint[0] + offsetNorthMeters / 111320,
    midpoint[1] + offsetEastMeters / (111320 * Math.cos(midLatRad)),
  ];
}

function getCableDistanceLabelIcon(label: string, angleDegrees: number) {
  return L.divIcon({
    className: "",
    html: `
      <div style="
        pointer-events: none;
        background: transparent;
        border: none;
        padding: 0;
        font-size: 11px;
        font-weight: 800;
        line-height: 1;
        color: rgba(147, 51, 234, 0.72);
        white-space: nowrap;
        text-shadow:
          0 1px 2px rgba(255,255,255,0.9),
          0 -1px 2px rgba(255,255,255,0.9),
          1px 0 2px rgba(255,255,255,0.9),
          -1px 0 2px rgba(255,255,255,0.9);
        transform: translate(-50%, -50%) rotate(${angleDegrees}deg);
        transform-origin: center;
      ">${label}</div>
    `,
    iconSize: [0, 0],
    iconAnchor: [0, 0],
  });
}

function getAssetPoint(asset: SavedMapAsset): [number, number] | null {
  if (asset.geometry?.type !== "Point") return null;

  const [lat, lng] = asset.geometry.coordinates;
  if (typeof lat !== "number" || typeof lng !== "number") return null;

  return [lat, lng];
}

function findConnectedAssetAtCableEnd(
  assets: SavedMapAsset[],
  point: [number, number]
): SavedMapAsset | null {
  const candidates = assets
    .filter((asset) => {
      if (asset.assetType === "area") return false;
      if (asset.assetType === "cable") return false;

      const assetPoint = getAssetPoint(asset);
      if (!assetPoint) return false;

      return getDistanceMeters(assetPoint, point) <= 10;
    })
    .sort((a, b) => {
      const pointA = getAssetPoint(a);
      const pointB = getAssetPoint(b);
      if (!pointA || !pointB) return 0;

      return getDistanceMeters(pointA, point) - getDistanceMeters(pointB, point);
    });

  return candidates[0] || null;
}

function getAssetDisplayName(asset?: SavedMapAsset | null): string {
  if (!asset) return "Not connected";
  const item = asset as any;
  return String(item.name || item.jointName || item.label || item.assetId || item.id || "Connected asset");
}

function normaliseAssetLookupKey(value: unknown): string {
  return String(value ?? "")
    .trim()
    .toLowerCase()
    .replace(/[–—]/g, "-")
    .replace(/\s+/g, "")
    .replace(/[^a-z0-9-]/g, "");
}

function getAssetLookupKeysForConnection(asset: SavedMapAsset): string[] {
  const item = asset as any;
  const raw = [
    item.id,
    item.assetId,
    item.name,
    item.jointName,
    item.label,
    item.nodeId,
    item.cableId,
    item.cableName,
  ];

  const keys = new Set<string>();

  raw.forEach((value) => {
    const normalised = normaliseAssetLookupKey(value);
    if (!normalised) return;

    keys.add(normalised);

    const withoutJointSuffix = normalised.replace(/-(cmj|mmj|lmj)\d{1,4}$/i, "");
    if (withoutJointSuffix) keys.add(withoutJointSuffix);

    const nodeMatches = normalised.match(/(?:ag|lmj|mmj|cmj|lc|sb|midj|sc)\d{1,4}/gi);
    nodeMatches?.forEach((match) => keys.add(normaliseAssetLookupKey(match)));
  });

  return Array.from(keys).filter((key) => key.length >= 2);
}

function findAssetByStoredReference(
  assets: SavedMapAsset[],
  reference: unknown
): SavedMapAsset | null {
  const lookup = normaliseAssetLookupKey(reference);
  if (!lookup) return null;

  return (
    assets.find((candidate) =>
      getAssetLookupKeysForConnection(candidate).some(
        (key) => key === lookup || key.includes(lookup) || lookup.includes(key),
      ),
    ) || null
  );
}

function getCableEndpointReferences(
  cable: SavedMapAsset,
  side: "from" | "to"
): unknown[] {
  const item = cable as any;

  if (side === "from") {
    return [
      item.fromAssetId,
      item.fromId,
      item.fromJointId,
      item.fromJoint,
      item.fromName,
      item.fromAssetName,
      item.sourceAssetId,
      item.sourceJointId,
      item.sourceJoint,
      item.sourceName,
      item.upstreamAssetId,
      item.upstreamJoint,
      item.aEnd,
      item.aEndAssetId,
      item.startAssetId,
      item.startJoint,
    ];
  }

  return [
    item.toAssetId,
    item.toId,
    item.toJointId,
    item.toJoint,
    item.toName,
    item.toAssetName,
    item.targetAssetId,
    item.targetJointId,
    item.targetJoint,
    item.targetName,
    item.downstreamAssetId,
    item.downstreamJoint,
    item.zEnd,
    item.zEndAssetId,
    item.endAssetId,
    item.endJoint,
  ];
}

function findNearestConnectedAssetAtCableEnd(
  assets: SavedMapAsset[],
  point: [number, number],
  maxDistanceMeters = 35
): SavedMapAsset | null {
  const candidates = assets
    .filter((asset) => {
      if (asset.assetType === "area") return false;
      if (asset.assetType === "cable") return false;
      if (asset.assetType === "home") return false;
      return Boolean(getAssetPoint(asset));
    })
    .map((asset) => {
      const assetPoint = getAssetPoint(asset)!;
      return { asset, distance: getDistanceMeters(assetPoint, point) };
    })
    .filter(({ distance }) => distance <= maxDistanceMeters)
    .sort((a, b) => a.distance - b.distance);

  return candidates[0]?.asset || null;
}

function resolveCableEndpointAsset(
  cable: SavedMapAsset,
  assets: SavedMapAsset[],
  side: "from" | "to",
  point?: [number, number]
): SavedMapAsset | null {
  for (const reference of getCableEndpointReferences(cable, side)) {
    const matched = findAssetByStoredReference(assets, reference);
    if (matched) return matched;
  }

  if (point) {
    return (
      findConnectedAssetAtCableEnd(assets, point) ||
      findNearestConnectedAssetAtCableEnd(assets, point)
    );
  }

  return null;
}

function normaliseCableRef(value: unknown): string {
  return String(value || "")
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "")
    .replace(/[–—]/g, "-");
}

function getNumberFromFibreCount(value: unknown): number {
  const match = String(value || "").match(/\d+/);
  return match ? Number(match[0]) : 0;
}

function getRowText(row: any[]): string {
  return row.map((cell) => String(cell || "").trim()).join(" ");
}

function getCableAliases(cable: SavedMapAsset): string[] {
  const values = [cable.name, cable.id, (cable as any).label, (cable as any).cableId]
    .map(normaliseCableRef)
    .filter(Boolean);

  const aliases = new Set<string>();

  values.forEach((value) => {
    aliases.add(value);

    const parts = value.split("-").filter(Boolean);
    const last = parts[parts.length - 1];
    if (last) aliases.add(last);

    const lcMatch = value.match(/lc\d{1,4}/i);
    if (lcMatch) aliases.add(normaliseCableRef(lcMatch[0]));
  });

  return Array.from(aliases).filter((alias) => alias.length >= 3);
}

function rowMentionsCable(row: any[], cable: SavedMapAsset): boolean {
  const aliases = getCableAliases(cable);
  if (!aliases.length) return false;

  const rowText = normaliseCableRef(getRowText(row));

  return aliases.some((alias) => rowText.includes(alias));
}

function getAssetAliases(asset?: SavedMapAsset | null): string[] {
  if (!asset) return [];

  const rawValues = [asset.name, asset.id, (asset as any).label, (asset as any).nodeId]
    .map((value) => String(value || '').trim())
    .filter(Boolean);

  const aliases = new Set<string>();

  rawValues.forEach((raw) => {
    const value = normaliseCableRef(raw);
    if (!value) return;

    aliases.add(value);

    // BD-BAW-AG11-CMJ01 should also match BD-BAW-AG11.
    const withoutJointSuffix = value.replace(/-(cmj|mmj|lmj)\d{1,4}$/i, '');
    if (withoutJointSuffix && withoutJointSuffix !== value) {
      aliases.add(withoutJointSuffix);
    }

    // Add compact node tokens such as AG11, LMJ01, LC011, SB35.
    const nodeMatches = value.match(/(?:ag|lmj|mmj|cmj|lc|sb|midj|sc)\d{1,4}/gi);
    nodeMatches?.forEach((match) => aliases.add(normaliseCableRef(match)));
  });

  return Array.from(aliases).filter((alias) => alias.length >= 3);
}

function rowMentionsAsset(row: any[], asset?: SavedMapAsset | null): boolean {
  const aliases = getAssetAliases(asset);
  if (!aliases.length) return false;

  const rowText = normaliseCableRef(getRowText(row));
  return aliases.some((alias) => rowText.includes(alias));
}

function countRowsMatching(
  allAssets: SavedMapAsset[],
  mappingRowsByAssetId: MappingRowsByAssetId,
  predicate: (row: any[], sourceAsset: SavedMapAsset, rowIndex: number) => boolean
): number {
  const keys = new Set<string>();

  allAssets.forEach((asset) => {
    const localRows = Array.isArray(asset.mappingRows) ? asset.mappingRows : [];
    const sharedRows = mappingRowsByAssetId[asset.id] || [];
    const rows = sharedRows.length ? sharedRows : localRows;

    rows.forEach((row: any[], rowIndex: number) => {
      if (!Array.isArray(row)) return;
      if (!predicate(row, asset, rowIndex)) return;

      const rowText = getRowText(row).trim();
      if (!rowText) return;

      keys.add(`${asset.id}:${rowIndex}:${normaliseCableRef(rowText)}`);
    });
  });

  return keys.size;
}

function clampToCableCapacity(cable: SavedMapAsset, value: number): number {
  const capacity = getNumberFromFibreCount(cable.fibreCount);
  if (!capacity) return value;
  return Math.min(value, capacity);
}

function getFibreNumberFromMappingRow(row: any[]): number | null {
  const preferred = Number(row?.[1]);
  if (Number.isFinite(preferred) && preferred > 0) return preferred;

  for (const cell of row || []) {
    const match = String(cell ?? "").match(/\b(\d{1,3})\b/);
    if (!match) continue;
    const fibreNumber = Number(match[1]);
    if (Number.isFinite(fibreNumber) && fibreNumber > 0 && fibreNumber <= 288) {
      return fibreNumber;
    }
  }

  return null;
}

function collectUsedFibreNumbersForCable(
  allAssets: SavedMapAsset[],
  mappingRowsByAssetId: MappingRowsByAssetId,
  cable: SavedMapAsset
): number[] {
  const fibreNumbers = new Set<number>();

  allAssets.forEach((asset) => {
    const localRows = Array.isArray(asset.mappingRows) ? asset.mappingRows : [];
    const sharedRows = mappingRowsByAssetId[asset.id] || [];
    const rows = sharedRows.length ? sharedRows : localRows;

    rows.forEach((row: any[]) => {
      if (!Array.isArray(row)) return;
      if (!rowMentionsCable(row, cable)) return;

      const fibreNumber = getFibreNumberFromMappingRow(row);
      if (fibreNumber !== null) fibreNumbers.add(fibreNumber);
    });
  });

  return Array.from(fibreNumbers).sort((a, b) => a - b);
}

function formatFibreRanges(fibres: number[]): string {
  if (!fibres.length) return "None found";

  const ranges: string[] = [];
  let start = fibres[0];
  let previous = fibres[0];

  for (let i = 1; i <= fibres.length; i += 1) {
    const current = fibres[i];

    if (current === previous + 1) {
      previous = current;
      continue;
    }

    ranges.push(start === previous ? String(start) : `${start}-${previous}`);
    start = current;
    previous = current;
  }

  return ranges.join(", ");
}


export default function CableLinesLayer({
  assets,
  cablesVisible,
  visibleLayers = {},
  showCableDistances,
  onDeleteAsset,
  onEditAsset,
}: Props) {
  const map = useMap();
  const [selectedCableId, setSelectedCableId] = useState<string | null>(null);
  const [editingCableId, setEditingCableId] = useState<string | null>(null);
  const [hoveredCableId, setHoveredCableId] = useState<string | null>(null);
  const [mappingRowsByAssetId, setMappingRowsByAssetId] = useState<MappingRowsByAssetId>({});
  const [mapViewBounds, setMapViewBounds] = useState(() => map.getBounds());
  const [mapViewZoom, setMapViewZoom] = useState(() => map.getZoom());
  const cableCanvasRenderer = useMemo(() => L.canvas({ padding: 0.5 }), []);

  const mappingAssetKey = useMemo(
    () =>
      assets
        .filter((asset) => Boolean((asset as any).mappingRowsRef || (asset as any).mappingRowsCount))
        .map((asset) => `${asset.id}:${(asset as any).mappingRowsCount || 0}:${(asset as any).updatedAt || ""}`)
        .sort()
        .join("|"),
    [assets]
  );

  useEffect(() => {
    let cancelled = false;

    const assetsWithSharedMappings = assets.filter((asset) =>
      Boolean((asset as any).mappingRowsRef || (asset as any).mappingRowsCount)
    );

    if (!assetsWithSharedMappings.length) {
      setMappingRowsByAssetId({});
      return;
    }

    Promise.all(
      assetsWithSharedMappings.map(async (asset) => {
        try {
          const rows = await loadJointMappingRowsFromFirestore(asset.id);
          return [asset.id, rows] as const;
        } catch (err) {
          console.error(`Failed to load mapping rows for ${asset.name || asset.id}`, err);
          return [asset.id, []] as const;
        }
      })
    ).then((entries) => {
      if (cancelled) return;
      setMappingRowsByAssetId(Object.fromEntries(entries));
    });

    return () => {
      cancelled = true;
    };
  }, [mappingAssetKey]);

  useMapEvents({
    click: () => {
      setSelectedCableId(null);
    },
    moveend: () => {
      setMapViewBounds(map.getBounds());
      setMapViewZoom(map.getZoom());
    },
    zoomend: () => {
      setMapViewBounds(map.getBounds());
      setMapViewZoom(map.getZoom());
    },
  });

  const renderBounds = useMemo(() => getPaddedRenderBounds(mapViewBounds), [mapViewBounds]);

  const networkState = useMemo(() => buildNetworkState(assets as any), [assets]);

  const connectionAssets = useMemo(
    () =>
      assets.filter((asset) => {
        if (asset.assetType === "area") return false;
        if (asset.assetType === "cable") return false;
        if (isOpenreachReferenceAsset(asset)) return false;
        return Boolean(getAssetPoint(asset));
      }),
    [assets],
  );

  const allCableLayersVisible = cablesVisible || visibleLayers?.cables !== false;

  const isLayerOn = (key: string) => visibleLayers?.[key] !== false;

  const hasAnyIndividualCableLayerOn =
    isLayerOn("feeders") ||
    isLayerOn("links") ||
    isLayerOn("dropCables") ||
    isLayerOn("ulw96") ||
    isLayerOn("ulw48") ||
    isLayerOn("ulw36") ||
    isLayerOn("ulw24") ||
    isLayerOn("ulw12");

  const cableAssets = useMemo(
    () =>
      assets.filter((asset) => {
        if (isOpenreachReferenceAsset(asset)) return false;

        if (
          asset.assetType !== "cable" ||
          asset.geometry?.type !== "LineString" ||
          !Array.isArray(asset.geometry.coordinates)
        ) {
          return false;
        }

        const points = asset.geometry.coordinates as [number, number][];
        if (!isLineStringInsideRenderBounds(points, renderBounds)) return false;

        if (allCableLayersVisible) return true;

        const cableType = String(asset.cableType || "").toLowerCase();
        const fibreCount = String(asset.fibreCount || "").toLowerCase();
        const isDropCable = isDropCableAsset(asset);

        if (isDropCable) return isLayerOn("dropCables");

        const matchesFeeder = cableType.includes("feeder");
        const matchesLink = cableType.includes("link");
        const matches96 = fibreCount.includes("96");
        const matches48 = fibreCount.includes("48");
        const matches36 = fibreCount.includes("36");
        const matches24 = fibreCount.includes("24");
        const matches12 = fibreCount.includes("12");

        return (
          (matchesFeeder && isLayerOn("feeders")) ||
          (matchesLink && isLayerOn("links")) ||
          (matches96 && isLayerOn("ulw96")) ||
          (matches48 && isLayerOn("ulw48")) ||
          (matches36 && isLayerOn("ulw36")) ||
          (matches24 && isLayerOn("ulw24")) ||
          (matches12 && isLayerOn("ulw12"))
        );
      }),
    [assets, allCableLayersVisible, renderBounds, visibleLayers],
  );

  if (!allCableLayersVisible && !hasAnyIndividualCableLayerOn) return null;

  const zoomToCable = (points: [number, number][]) => {
    if (points.length < 2) return;

    const bounds = L.latLngBounds(points);
    map.fitBounds(bounds, {
      padding: [80, 80],
      maxZoom: 19,
    });
  };

  const updateCableCoordinates = (
    asset: SavedMapAsset,
    coordinates: [number, number][]
  ) => {
    const cleanedCoordinates = sanitizeCableCoordinates(coordinates);

    onEditAsset({
      ...asset,
      geometry: {
        ...asset.geometry,
        type: "LineString",
        coordinates: cleanedCoordinates,
      },
    });
  };

  const handleMovePoint = (
    asset: SavedMapAsset,
    index: number,
    lat: number,
    lng: number
  ) => {
    if (asset.geometry?.type !== "LineString") return;

    const updated = [...asset.geometry.coordinates];
    updated[index] = [lat, lng];

    // Dragging a route handle must move one existing vertex only.
    // It must never append or duplicate geometry points.
    updateCableCoordinates(asset, updated);
  };

  const handleInsertMidpoint = (asset: SavedMapAsset, i: number) => {
    if (asset.geometry?.type !== "LineString") return;

    const coords = asset.geometry.coordinates;
    const start = coords[i];
    const end = coords[i + 1];

    if (!start || !end) return;

    if (getDistanceMeters(start, end) < ROUTE_EDIT_MIN_INSERT_SPAN_METERS) return;

    const updated = [...coords];
    updated.splice(i + 1, 0, getMidpoint(start, end));

    updateCableCoordinates(asset, updated);
  };

  return (
    <>
      {cableAssets.map((asset) => {
        const points =
          asset.geometry?.type === "LineString"
            ? asset.geometry.coordinates
            : [];

        const length = getTuplePathDistanceMeters(points);
        const isHovered = hoveredCableId === asset.id;
        const isSelected = selectedCableId === asset.id;
        const isEditing = editingCableId === asset.id;
        const baseColor = getCableColor(asset, length);
        const cableColor = isSelected ? "#f59e0b" : baseColor;
        const routeEditHandleIndexes = isEditing ? getRouteEditHandleIndexes(points) : [];
        const routeEditInsertSegmentIndexes = isEditing
          ? new Set(getRouteEditInsertSegmentIndexes(points, routeEditHandleIndexes))
          : new Set<number>();

        const startAsset =
          points.length >= 2
            ? resolveCableEndpointAsset(asset, connectionAssets, "from", points[0])
            : resolveCableEndpointAsset(asset, connectionAssets, "from");

        const endAsset =
          points.length >= 2
            ? resolveCableEndpointAsset(asset, connectionAssets, "to", points[points.length - 1])
            : resolveCableEndpointAsset(asset, connectionAssets, "to");

        

        const usedFibreNumbersFromMappings = collectUsedFibreNumbersForCable(
          assets,
          mappingRowsByAssetId,
          asset,
        );

        const usedFibresFromSharedMappings = usedFibreNumbersFromMappings.length
          ? usedFibreNumbersFromMappings.length
          : countRowsMatching(
              assets,
              mappingRowsByAssetId,
              (row) => rowMentionsCable(row, asset),
            );

        const cableState = networkState.cableStates[asset.id];

        const localLegacyUsedFibres = getCableUsedFibres(asset, assets);
        const usedFibres = clampToCableCapacity(
          asset,
          Math.max(
            cableState?.usedFibres ?? 0,
            localLegacyUsedFibres,
            usedFibresFromSharedMappings,
          ),
        );

        const usedFibreNumbers = usedFibreNumbersFromMappings.length
          ? usedFibreNumbersFromMappings
          : cableState?.usedFibreNumbers || [];

        const networkStateSource = usedFibreNumbersFromMappings.length || usedFibresFromSharedMappings > 0
          ? "joint-mapping-engine"
          : cableState?.source || (localLegacyUsedFibres > 0 ? "network-state-cable-usage" : "network-state");

        const usedFibreRangeLabel = formatFibreRanges(usedFibreNumbers);
        const capacityWarning = cableState?.warnings?.length
          ? cableState.warnings.join(" • ")
          : getCableCapacityWarning(asset, usedFibres);

        return (
          <React.Fragment key={asset.id}>
            <Polyline
              renderer={cableCanvasRenderer}
              positions={points}
              pathOptions={{
                color: cableColor,
                weight: isSelected ? 9 : isHovered || isEditing ? 7 : 4,
                opacity: isSelected || isHovered || isEditing ? 1 : 0.85,
                dashArray: getDashArray(asset, startAsset, endAsset),
                className: isSelected ? "selected-cable-glow" : "",
              }}
              eventHandlers={{
                click: (e) => {
                  L.DomEvent.stopPropagation(e);
                  setSelectedCableId(asset.id);
                  zoomToCable(points);
                },
                mouseover: () => setHoveredCableId(asset.id),
                mouseout: () => setHoveredCableId(null),
              }}
            >
              <Popup>
                <div style={{ minWidth: 240 }}>
                  <div style={{ fontWeight: 700, fontSize: "1rem" }}>
                    {asset.name || "Unnamed Cable"}
                  </div>

                  <div style={{ marginTop: 6 }}>
                    <b>Size:</b> {asset.fibreCount || "N/A"}
                  </div>

                  <div>
                    <b>Type:</b> {asset.cableType || "Cable"}
                  </div>

                  <div>
                    <b>Install:</b> {asset.installMethod || "Underground"}
                  </div>

                  <div>
                    <b>Length:</b> {formatCableLength(length)}
                  </div>

                  <div>
                    <b>Used fibres:</b> {usedFibres} /{" "}
                    {asset.fibreCount || "N/A"}
                  </div>

                  <div>
                    <b>Fibre numbers:</b> {usedFibreRangeLabel}
                  </div>

                  <div style={{ marginTop: 4, color: "#64748b", fontSize: 12 }}>
                    <b>Network state:</b> {networkStateSource}
                  </div>

                  {capacityWarning ? (
                    <div style={{ marginTop: 4, color: cableState?.warnings?.length ? "#dc2626" : "#475569", fontSize: 12 }}>
                      {capacityWarning}
                    </div>
                  ) : null}

                  <div>
                    <b>From:</b> {getAssetDisplayName(startAsset)}
                  </div>

                  <div>
                    <b>To:</b> {getAssetDisplayName(endAsset)}
                  </div>

                  {asset.notes ? (
                    <div style={{ marginTop: 8 }}>{asset.notes}</div>
                  ) : null}

                  <div
                    style={{
                      marginTop: 10,
                      display: "flex",
                      gap: 8,
                      flexWrap: "wrap",
                    }}
                  >
                    <button onClick={() => onEditAsset(asset)}>
                      Edit details
                    </button>

                    <button
                      onClick={() => {
                        setSelectedCableId(asset.id);
                        setEditingCableId(asset.id);
                      }}
                    >
                      Edit route
                    </button>

                    <button onClick={() => setEditingCableId(null)}>
                      Done
                    </button>

                    <button onClick={() => onDeleteAsset(asset.id)}>
                      Delete
                    </button>
                  </div>
                </div>
              </Popup>

              <Tooltip sticky>
                {asset.name || "Cable"} · {asset.fibreCount || "N/A"} ·{" "}
                {formatCableLength(length)}
              </Tooltip>
            </Polyline>

            {showCableDistances === true && mapViewZoom >= 17 &&
              points.slice(0, -1).map((coord, i) => {
                const next = points[i + 1];
                if (!next) return null;

                const spanLength = getDistanceMeters(coord, next);

                return (
                  <Marker
                    key={`${asset.id}-distance-${i}`}
                    position={getOffsetCableLabelPosition(coord, next)}
                    interactive={false}
                    icon={getCableDistanceLabelIcon(
                      formatCableLength(spanLength),
                      getCableSpanAngleDegrees(coord, next)
                    )}
                  />
                );
              })}

            {isEditing &&
              routeEditHandleIndexes.map((i) => {
                const coord = points[i];
                if (!coord) return null;

                return (
                  <Marker
                    key={`${asset.id}-drag-${i}`}
                    position={coord}
                    draggable
                    eventHandlers={{
                      dragend: (e) => {
                        const p = e.target.getLatLng();
                        handleMovePoint(asset, i, p.lat, p.lng);
                      },
                    }}
                  />
                );
              })}

            {isEditing &&
              points.slice(0, -1).map((coord, i) => {
                if (!routeEditInsertSegmentIndexes.has(i)) return null;

                const next = points[i + 1];
                if (!next) return null;

                return (
                  <CircleMarker
                    renderer={cableCanvasRenderer}
                    key={`${asset.id}-mid-${i}`}
                    center={getMidpoint(coord, next)}
                    radius={5}
                    pathOptions={{
                      color: getCableColor(asset),
                      weight: 2,
                      fillOpacity: 0.85,
                    }}
                    eventHandlers={{
                      click: () => handleInsertMidpoint(asset, i),
                    }}
                  />
                );
              })}
          </React.Fragment>
        );
      })}
    </>
  );
}