import type { SavedMapAsset } from "../../components/map/types";
import { buildJobPackRoutes, isJobPackRouteFibreCount } from "./jobPackRouteBuilder";
import type {
  BuildJobPackDraftInput,
  JobPackAssetGroup,
  JobPackDraft,
  JobPackDraftAsset,
  JobPackRiskDraft,
  JobPackScheduleRow,
} from "./jobPackTypes";

const normalize = (value?: string) => (value || "").toLowerCase().replace(/[\s_-]/g, "");

function assetText(asset: SavedMapAsset): string {
  const anyAsset = asset as any;
  return normalize(
    [
      asset.assetType,
      anyAsset.type,
      asset.jointType,
      asset.cableType,
      anyAsset.assetSubtype,
      anyAsset.asset_subtype,
      asset.name,
      anyAsset.label,
      anyAsset.homeType,
      anyAsset.category,
      anyAsset.uprn,
      anyAsset.UPRN,
      anyAsset.homeId,
      anyAsset.connectedHomeId,
      anyAsset.toHomeId,
      anyAsset.fromHomeId,
      anyAsset.fromAssetId,
      anyAsset.toAssetId,
      anyAsset.fromType,
      anyAsset.toType,
      anyAsset.generatedBy,
      anyAsset.generationMode,
      anyAsset.connectionMode,
      anyAsset.properties?.assetSubtype,
      anyAsset.properties?.asset_subtype,
      anyAsset.properties?.assetType,
      anyAsset.properties?.type,
      anyAsset.properties?.uprn,
      anyAsset.properties?.UPRN,
      anyAsset.properties?.homeId,
      anyAsset.properties?.connectedHomeId,
      anyAsset.properties?.toHomeId,
      anyAsset.properties?.fromHomeId,
      anyAsset.properties?.fromAssetId,
      anyAsset.properties?.toAssetId,
      anyAsset.properties?.fromType,
      anyAsset.properties?.toType,
      anyAsset.properties?.generatedBy,
      anyAsset.properties?.generationMode,
      anyAsset.properties?.connectionMode,
    ]
      .filter(Boolean)
      .join(" "),
  );
}

function isHomeAsset(asset: SavedMapAsset): boolean {
  const anyAsset = asset as any;
  const type = assetText(asset);
  const hasPointGeometry =
    asset.geometry?.type === "Point" ||
    (typeof anyAsset.lat === "number" && typeof anyAsset.lng === "number");

  return (
    hasPointGeometry &&
    Boolean(
      anyAsset.uprn ||
        anyAsset.UPRN ||
        anyAsset.properties?.uprn ||
        anyAsset.properties?.UPRN ||
        anyAsset.homeId ||
        type.includes("home") ||
        type.includes("premise") ||
        type.includes("property") ||
        type.includes("sdu") ||
        type.includes("flat"),
    )
  );
}

function isDropCableAsset(asset: SavedMapAsset): boolean {
  const anyAsset = asset as any;
  const type = assetText(asset);
  const isCable =
    asset.geometry?.type === "LineString" ||
    type.includes("cable") ||
    Boolean(asset.cableType);

  return (
    isCable &&
    Boolean(
      type.includes("drop") ||
        type.includes("homedrop") ||
        type.includes("dropcable") ||
        anyAsset.isDropCable === true ||
        anyAsset.isHomeDrop === true ||
        anyAsset.generatedDrop === true ||
        anyAsset.autoGeneratedDrop === true ||
        anyAsset.dropCable === true ||
        anyAsset.properties?.isDropCable === true ||
        anyAsset.properties?.isHomeDrop === true ||
        anyAsset.properties?.generatedDrop === true ||
        anyAsset.properties?.autoGeneratedDrop === true ||
        anyAsset.properties?.dropCable === true ||
        anyAsset.homeId ||
        anyAsset.connectedHomeId ||
        anyAsset.toHomeId ||
        anyAsset.fromHomeId ||
        anyAsset.properties?.homeId ||
        anyAsset.properties?.connectedHomeId ||
        anyAsset.properties?.toHomeId ||
        anyAsset.properties?.fromHomeId,
    )
  );
}

function isJointAsset(asset: SavedMapAsset): boolean {
  const type = assetText(asset);
  return (
    type.includes("agjoint") ||
    type.includes("joint") ||
    type.includes("cmj") ||
    type.includes("lmj") ||
    type.includes("mmj") ||
    type.includes("midj")
  );
}

function assetGroup(asset: SavedMapAsset): JobPackAssetGroup {
  const type = assetText(asset);
  if (type === "area") return "boundary";
  if (isHomeAsset(asset)) return "home";
  if (isJointAsset(asset)) return "joint";
  if (
    type.includes("cable") ||
    type.includes("route") ||
    type.includes("feeder") ||
    type.includes("link") ||
    type.includes("ulw") ||
    type.includes("fulw") ||
    isDropCableAsset(asset) ||
    asset.geometry?.type === "LineString"
  )
    return "route";
  if (
    type.includes("distributionpoint") ||
    type.includes("dp") ||
    type.includes("sb") ||
    type.includes("cbt") ||
    type.includes("afn")
  )
    return "distributionPoint";
  if (type === "streetcab") return "streetCab";
  if (type === "chamber") return "chamber";
  if (type === "pole") return "pole";
  return "other";
}

function assetName(asset: SavedMapAsset): string {
  const anyAsset = asset as any;
  return anyAsset.name || anyAsset.label || anyAsset.properties?.name || asset.id;
}

function formatFibres(fibres?: number[]): string {
  if (!fibres?.length) return "";
  const sorted = [...fibres].sort((a, b) => a - b);
  const ranges: string[] = [];
  let start = sorted[0];
  let previous = sorted[0];
  for (let index = 1; index <= sorted.length; index += 1) {
    const current = sorted[index];
    if (current === previous + 1) {
      previous = current;
      continue;
    }
    ranges.push(start === previous ? String(start) : `${start}-${previous}`);
    start = current;
    previous = current;
  }
  return ranges.join(", ");
}

function detailFor(asset: SavedMapAsset): string {
  if (assetGroup(asset) === "distributionPoint") {
    const homes = asset.dpDetails?.connectionsToHomes ?? 0;
    const architecture = asset.dpDetails?.closureType || asset.dpDetails?.networkArchitecture || "DP";
    const fibres = formatFibres(
      asset.dpDetails?.autoFibrePlan?.inputFibres ||
      asset.dpDetails?.afnDetails?.inputFibres ||
      asset.dpDetails?.mduDetails?.inputFibres ||
      asset.allocatedInputFibres,
    );
    return `${architecture}, ${homes} connected homes${fibres ? `, fibres ${fibres}` : ""}`;
  }
  if (assetGroup(asset) === "route") {
    return [asset.fibreCount, asset.installMethod, asset.cableType].filter(Boolean).join(" / ") || "Route";
  }
  if (asset.assetType === "home") return asset.homeType || "Premises";
  if (asset.assetType === "chamber") return asset.chamberDetails?.size || asset.chamberDetails?.chamberType || "Chamber";
  if (asset.assetType === "pole") return asset.poleDetails?.poleType || "Pole";
  return asset.notes || asset.assetType || "Asset";
}

function toDraftAsset(asset: SavedMapAsset): JobPackDraftAsset {
  const anyAsset = asset as any;
  return {
    id: asset.id,
    name: assetName(asset),
    group: assetGroup(asset),
    assetType: asset.assetType || anyAsset.type || asset.jointType || "unknown",
    status: asset.status || undefined,
    fibreCount: normaliseRouteFibreCount([
      asset.fibreCount,
      anyAsset.fiberCount,
      anyAsset.coreCount,
      anyAsset.size,
      anyAsset.cableSize,
      anyAsset.properties?.fibreCount,
      anyAsset.properties?.fiberCount,
      anyAsset.properties?.coreCount,
      anyAsset.properties?.size,
      anyAsset.properties?.cableSize,
      asset.name,
      anyAsset.label,
      asset.cableType,
      asset.notes,
    ]),
    installMethod: asset.installMethod,
    cableType: asset.cableType,
    notes: asset.notes,
    geometry: asset.geometry,
    sourceAsset: asset,
  };
}

function normaliseRouteFibreCount(value: unknown): string | undefined {
  const raw = Array.isArray(value)
    ? value.map((item) => String(item ?? "").trim()).filter(Boolean).join(" ")
    : String(value ?? "").trim();
  if (!raw) return undefined;
  for (const count of ["96", "48", "36", "24", "12"]) {
    const match = new RegExp(`(?:^|[^0-9])${count}\\s*(?:f|fibre|fiber|core|c|fulw|fu|ulw)(?:\\b|\\d|_)`, "i").test(raw);
    if (match) {
      const next = `${count}F`;
      return isJobPackRouteFibreCount(next) ? next : raw;
    }
  }
  const standalone = raw.match(/\b(12|24|36|48|96)\b/i);
  if (!standalone) return raw;
  const next = `${standalone[1]}F`;
  return isJobPackRouteFibreCount(next) ? next : raw;
}

function scheduleRow(asset: JobPackDraftAsset): JobPackScheduleRow {
  return {
    id: asset.id,
    asset: asset.name,
    type: asset.assetType,
    detail: detailFor(asset.sourceAsset),
    status: asset.status || "Review",
    reviewNote: asset.notes || "Check against live design before issue.",
  };
}

function buildRisks(assets: JobPackDraftAsset[]): JobPackRiskDraft[] {
  const risks: JobPackRiskDraft[] = [];
  assets.forEach((asset) => {
    if (asset.group === "route" && !asset.fibreCount) {
      risks.push({
        id: `risk-fibre-${asset.id}`,
        level: "warning",
        title: "Route missing fibre count",
        assetId: asset.id,
        assetName: asset.name,
        action: "Confirm whether route belongs on a 96F, 48F, 36F, 24F or 12F page.",
      });
    }
    if ((asset.group === "distributionPoint" || asset.group === "home") && !asset.status) {
      risks.push({
        id: `risk-status-${asset.id}`,
        level: "info",
        title: "Status not set",
        assetId: asset.id,
        assetName: asset.name,
        action: "Review status before issuing the contractor pack.",
      });
    }
  });
  return risks;
}

export function buildJobPackDraftFromLiveMap(input: BuildJobPackDraftInput): JobPackDraft {
  const assets = input.assets.map(toDraftAsset);
  const routes = buildJobPackRoutes(assets);
  const risks = buildRisks(assets);
  const count = (group: JobPackDraftAsset["group"]) => assets.filter((asset) => asset.group === group).length;
  const generatedAt = new Date().toISOString();
  const revision = input.revision || "DRAFT-01";

  return {
    id: `job-pack-draft-${input.areaId}-${Date.now()}`,
    areaId: input.areaId,
    areaName: input.areaName,
    packNumber: `AL-${input.areaName.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toUpperCase()}-${revision}`,
    revision,
    status: "draft",
    generatedAt,
    source: "live_map",
    assets,
    routes,
    dpSchedule: assets.filter((asset) => asset.group === "distributionPoint").map(scheduleRow),
    homesSchedule: assets.filter((asset) => asset.group === "home").map(scheduleRow),
    fasRows: assets
      .filter((asset) => asset.group === "route" || asset.group === "distributionPoint")
      .map(scheduleRow),
    buildNotes: [
      "Draft generated directly from the live map.",
      "Review FAS rows, route sheets, UPRNs, build notes and risks before export.",
      "Draft edits are isolated from the live map until explicitly pushed back in a later controlled workflow.",
    ],
    risks,
    summary: {
      totalAssets: assets.length,
      boundaries: count("boundary"),
      routes: count("route"),
      distributionPoints: count("distributionPoint"),
      joints: count("joint"),
      chambers: count("chamber"),
      poles: count("pole"),
      homes: count("home"),
      risks: risks.length,
      blockers: risks.filter((risk) => risk.level === "blocker").length,
    },
  };
}
